### ISSUE TITLE
Feed The Beast Mindcrack Modpack

### ISSUE THREAD

**Issue by TheDigitaldumpKing** [keepcalm/BukkitForge#100]
I have searched the internet for 2 days to get a worldedit version for forge and i only found ForgeEssentials and it doesn't include brushes so i tried bukkit forge, but i got this crash log. I know that there is one issue with the mod xycraft ( don't know what the mod does but it is in the pack) but there are some more, maybe you can look into it.

Sorry if my English is bad

---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/3/13 8:38 PM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at soaryn.xycraft.core.XycraftRegistry.registerItem(XycraftRegistry.java:161)
    at soaryn.xycraft.world.WorldItems.register(WorldItems.java:67)
    at soaryn.xycraft.world.XyCraftWorld.register(XyCraftWorld.java:67)
    at soaryn.xycraft.XyExpansion.register(XyExpansion.java:37)
    at soaryn.xycraft.XyCraft.preInit(XyCraft.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:483)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:485)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:345)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at soaryn.xycraft.core.XycraftRegistry.registerItem(XycraftRegistry.java:152)
    ... 34 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 24256
    at org.bukkit.Material.addMaterial(Material.java:942)
    at org.bukkit.Material.addMaterial(Material.java:933)
    at keepcalm.mods.bukkit.BukkitHelpers.addMaterial(BukkitHelpers.java:17)
    at up.<init>(Item.java)
    at soaryn.xycraft.core.XyItem.<init>(XyItem.java:8)
    at soaryn.xycraft.world.item.ItemWorld.<init>(ItemWorld.java:26)
    ... 39 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.6
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_10, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 460412024 bytes (439 MB) / 578945024 bytes (552 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -Xms512M -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.25 FML v4.6.17.515 Minecraft Forge 6.5.0.489 58 mods loaded, 58 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized
    BlockBreak [Block Break Event](BukkitForge-1.4.6-43.jar) Unloaded->Constructed->Pre-initialized
    BukkitForge [BukkitForge](BukkitForge-1.4.6-43.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core [BuildCraft](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Errored
    BuildCraft|Energy [BC Energy](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Errored
    ExtrabiomesXL [ExtrabiomesXL](ExtrabiomesXL-universal-1.4.6-3.7.0.jar) Unloaded->Constructed->Errored
    Forestry [Forestry for Minecraft](forestry-A-1.6.4.1.jar) Unloaded->Constructed->Pre-initialized
    IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Errored
    drceph.petrogen [Petroleum Generator]([1.4.6]PetroGen-1.1.zip) Unloaded->Constructed->Pre-initialized
    AdvancedMachines [IC2 Advanced Machines Addon](AdvancedMachines_4.7a.zip) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders [BC Builders](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Errored
    BuildCraft|Factory [BC Factory](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport [BC Transport](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Errored
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Errored
    ChickenChunks [ChickenChunks](ChickenChunks 1.2.1.1.jar) Unloaded->Constructed->Pre-initialized
    ComputerCraft [ComputerCraft](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized
    CCTurtle [ComputerCraft Turtles](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized
    EnderStorage [EnderStorage](EnderStorage 1.3.1.1.jar) Unloaded->Constructed->Pre-initialized
    BinnieCore [Binnie Core](extrabees-1.4.9.6-prerelease.zip) Unloaded->Constructed->Pre-initialized
    ExtraBees [Extra Bees](extrabees-1.4.9.6-prerelease.zip) Unloaded->Constructed->Pre-initialized
    factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Errored
    Railcraft [Railcraft](Railcraft_1.4.6-6.12.2.0.zip) Unloaded->Constructed->Errored
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized
    ThermalExpansion [Thermal Expansion](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized
    ThermalExpansion|Factory [Factory](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized
    ThermalExpansion|Energy [Energy](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized
    ThermalExpansion|Transport [Transport](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized
    TwilightForest [The Twilight Forest](twilightforest-1.14.0.zip) Unloaded->Constructed->Errored
    XyCraft [XyCraft](xycraft-universal-1.4.6-0.9.44.zip) Unloaded->Constructed->Errored
    GregTech_Addon [GregTech-Addon](GregTechMod_2.73c.zip) Unloaded->Constructed->Pre-initialized
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.5.zip) Unloaded->Constructed->Pre-initialized
    IronChest [Iron Chest](ironchest-universal-1.4.6-4.5.1.203.zip) Unloaded->Constructed->Pre-initialized
    MiscPeripherals [MiscPeripherals](miscperipherals-2.3.zip) Unloaded->Constructed->Errored
    AdvancedSolarPanel [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_2.zip) Unloaded->Constructed->Pre-initialized
    GraviSuite [Gravitation Suite](mod_zGraviSuite_1_6.zip) Unloaded->Constructed->Pre-initialized
    ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.2.8.2.14.zip) Unloaded->Constructed->Pre-initialized
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates-universal-1.2.0.3.zip) Unloaded->Constructed->Pre-initialized
    OmniTools [OmniTools](OmniTools-2.2.5.zip) Unloaded->Constructed->Errored
    PortalGun [Portal Gun](portalgun1.4.6v2.zip) Unloaded->Constructed->Pre-initialized
    SoulShards [SoulShards](SoulShards-v1.21-universal.zip) Unloaded->Constructed->Pre-initialized
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a41.zip) Unloaded->Constructed->Errored
    Thaumcraft [Thaumcraft](Thaumcraft3.0.1c.zip) Unloaded->Constructed->Pre-initialized
    TC [Traincraft](Traincraft-3.1.13_010.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Core [WR-CBE Core](WR-CBE Core 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Addons [WR-CBE Addons](WR-CBE Addons 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|RedPower [WR-CBE RedPower](WR-CBE RedPower 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by shakey2** [comment]
This is the same problem I'm having(I'm using mindcrack as well). The array out of bounds thing in your log keepcalm has said is a quick fix, so I assume he is gonna fix it in build 44.

**Comment by lisim** [comment]
We run the mindcrack pack with our forge bukkit test server without a hitch

**Comment by TheDigitaldumpKing** [comment]
wich build are you using than i get an error when i try it with build 43

**Comment by keepcalm** [comment]
Did you unzip it?

**Comment by TheDigitaldumpKing** [comment]
yeah i already saw it -_- it is 0:00 here getting tired and I deleted my poste out of shame

**Comment by shakey2** [comment]
Unzip it? Isn't Bukkitforge a Jar file?

**Comment by keepcalm** [comment]
No worldedit-5.4.5.zip :P
