### ISSUE TITLE
[WorldBorder] Exception on generating world

### ISSUE THREAD

**Issue by Feldspaten** [keepcalm/BukkitForge#101]
WorldBorder loads, and the border works well to, but when i want it to fill the missing chunks this happens:

2013-01-03 21:25:59 [WARNING] [com.wimbli.WorldBorder.WorldBorder] [WorldBorder] Task #3 for WorldBorder v1.6.1 generated an exception
java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.isChunkInUse(BukkitWorld.java:367)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunkRequest(BukkitWorld.java:292)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunkRequest(BukkitWorld.java:288)
    at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:205)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:345)
    at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:23)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

**Comment by Feldspaten** [comment]
Tested with 45 and 50, almost same error, some numbers changed.
[com.wimbli.WorldBorder.WorldBorder] [WorldBorder] Task #3 for WorldBorder v1.6.1 generated an exception
java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.isChunkInUse(BukkitWorld.java:408)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunkRequest(BukkitWorld.java:295)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunkRequest(BukkitWorld.java:291)
    at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:205)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:345)
    at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:23)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

**Comment by keepcalm** [comment]
Hmm... What could be null there? Working on it...

**Comment by Nonsanity** [comment]
Just tested this with #77 and get the following less-than-helpful error:

02:20:21 WorldBorder: Filling out world to border at the command of player "Nonsanity".
02:20:21 CONSOLE: [WARNING] Task #17 for WorldBorder v1.6.1 generated an exception

I get more details when I try (and break) the "/wb fill cancel" command:

org.bukkit.command.CommandException: Unhandled exception executing command 'wborder' in plugin WorldBorder v1.6.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
at x.a(CommandHandler.java:82)
at iv.d(NetServerHandler.java:768)
at iv.a(NetServerHandler.java:734)
at cu.a(SourceFile:44)
at cg.b(TcpConnection.java:458)
at iv.d(NetServerHandler.java:136)
at iw.b(NetworkListenThread.java:57)
at ht.b(SourceFile:30)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
at ho.r(DedicatedServer.java:270)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.isChunkInUse(BukkitWorld.java:408)
at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunkRequest(BukkitWorld.java:295)
at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunkRequest(BukkitWorld.java:291)
at com.wimbli.WorldBorder.WorldFillTask.stop(WorldFillTask.java:323)
at com.wimbli.WorldBorder.WorldFillTask.cancel(WorldFillTask.java:304)
at com.wimbli.WorldBorder.Config.StopFillTask(Config.java:270)
at com.wimbli.WorldBorder.WBCommand.cmdFill(WBCommand.java:749)
at com.wimbli.WorldBorder.WBCommand.onCommand(WBCommand.java:503)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
... 14 more

The plugin WorldGenerationControl also threw exceptions when I tried to use it, but that would be a separate report.

**Comment by recon88** [comment]
This bug still exists and I really need to fill the chunks. Are you still working on it?

**Comment by mrdeadlocked** [comment]
Same as recon88. Waiting and anxious. terrain generation is something that's been missing!

**Comment by JohnPark234** [comment]
Three Months since the last comment :/
It seems like this isn't going to work for a long time...
Just to clarify WB still doesn't work in version 283

2013-05-06 03:03:35 [WARNING] [BukkitForge] Task #52 for WorldBorder v1.6.1 generated an exception
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_5_R2.CraftWorld.isChunkInUse(CraftWorld.java:381)
    at org.bukkit.craftbukkit.v1_5_R2.CraftWorld.unloadChunkRequest(CraftWorld.java:303)
    at org.bukkit.craftbukkit.v1_5_R2.CraftWorld.unloadChunkRequest(CraftWorld.java:299)
    at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:205)
    at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftTask.run(CraftTask.java:52)
    at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
    at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:559)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:468)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
