### ISSUE TITLE
NullPointerException on world load

### ISSUE THREAD

**Issue by cking** [keepcalm/BukkitForge#110]
I have a problem using bukkitforge with my (heavily modded) minecraft.
This is the exception thrown:

```
java.lang.NullPointerException
        at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java:46)
        at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
        at org.bukkit.event.world.ChunkLoadEvent.<init>(ChunkLoadEvent.java:14)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkLoadEvent(ForgeEventHandler.java:434)
        at net.minecraftforge.event.ASMEventHandler_102_ForgeEventHandler_chunkLoadEvent_Load.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at zz.c(Chunk.java:1086)
        at im.c(ChunkProviderServer.java:150)
        at il.<init>(PlayerInstance.java:44)
        at ik.getOrCreateChunkWatcher(PlayerManager.java:167)
        at ik.a(PlayerManager.java:157)
        at ik.a(PlayerManager.java:206)
        at gm.a(ServerConfigurationManager.java:163)
        at gm.c(ServerConfigurationManager.java:206)
        at gm.a(ServerConfigurationManager.java:123)
        at bec.b(IntegratedServerListenThread.java:96)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at bdz.q(IntegratedServer.java:159)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
```

You can find the complete crash report here: http://pastebin.com/t5nJkMsf
Also the ForgeModLoader log is here: http://pastebin.com/1XnHzxBW

**Comment by Erycus** [comment]
Are you trying to use this for your server?  Or for your client?

**Comment by cking** [comment]
I tried it on the client for now, planned is usage on a server. I thought it would work on client as well. Not the case?

**Comment by keepcalm** [comment]
No, it will. I test on singleplayer most of the time... And I think I know what the bug is...
