### ISSUE TITLE
bukkitforge not loading build 50

### ISSUE THREAD

**Issue by shakey2** [keepcalm/BukkitForge#112]
2013-01-04 17:24:00 [INFO] [BukkitForge] Going to load perms file: permissions.yml
2013-01-04 17:24:00 [SEVERE] [BukkitForge] Permission node 'groups' in permissions.yml is invalid
java.lang.IllegalArgumentException: 'default' key contained unknown value
    at org.bukkit.permissions.Permission.loadPermission(Permission.java:269)
    at org.bukkit.permissions.Permission.loadPermissions(Permission.java:218)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadCustomPermissions(BukkitServer.java:954)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:892)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:255)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
    at java.lang.Thread.run(Unknown Source)
2013-01-04 17:24:00 [INFO] [BukkitForge] Loaded plugins: 
2013-01-04 17:24:00 [INFO] [BukkitForge] GroupManager- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] WorldEdit- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] LogBlock- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] WorldGuard- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] Permissions- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] Essentials- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] EssentialsXMPP- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] EssentialsChat- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] EssentialsProtect- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] EssentialsSpawn- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] EssentialsAntiBuild- Enabled: true
2013-01-04 17:24:00 [INFO] [BukkitForge] EssentialsGeoIP- Enabled: true
2013-01-04 17:24:00 [SEVERE] [ForgeModLoader] Something real bad happened! The BukkitAPI will not be running for this Minecraft session.
You should _probably_ report this bug to the developer(s) at https://github.com/keepcalm/BukkitForge/issues
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
    at java.util.HashMap$ValueIterator.next(Unknown Source)
    at keepcalm.mods.bukkit.bukkitAPI.command.BukkitCommandMap.doneLoadingPlugins(BukkitCommandMap.java:250)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:261)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
    at java.lang.Thread.run(Unknown Source)
2013-01-04 17:24:01 [WARNING] [BukkitForge] Method "public Class<?> getClassByName(String)" is Deprecated, and may be removed in a future version of Bukkit
org.bukkit.plugin.AuthorNagException: 
    at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:284)
    at com.earth2me.essentials.storage.BukkitConstructor.getClassForNode(BukkitConstructor.java:418)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:321)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:183)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:142)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:128)
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:423)
    at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:47)
    at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:37)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VAsyncTask.run(B4VAsyncTask.java:54)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by shakey2** [comment]
Oh and I figure my permissions.yml might be relevant, I just modified an example permissions.yml:

users:
    shakey2:
        permissions:
            permissions.example: true
        groups:
        - admin
groups:
    default:
        permissions:
            permissions.build: true
    admin:
        permissions:
            permissions.*: true
        inheritance:
        - user
    user:
        permissions:
            permissions.build: true
        inheritance:
        - default
messages:
    build: '&cYou do not have permission to build here.'

**Comment by keepcalm** [comment]
Ouch. Nasty ConcurrentModificationException. Nothing to do with permissions, but weird...

**Comment by shakey2** [comment]
Permissions.build is used in all the example permissions.yml I've looked at. Is there an alternative? Its supposed to give/take users' build rights.

**Comment by minecrafter** [comment]
That, I believe is meant for PermissionsBukkit.

**Comment by shakey2** [comment]
My bad then.
