### ISSUE TITLE
mod compatibility

### ISSUE THREAD

**Issue by shakey2** [keepcalm/BukkitForge#115]
Ok so with essentials controlling permissions for interacting/placing/destroying certain blocks doesn't work yet so I tried installing a forge mod that I know I can control that stuff with and this is the error I'm getting:

2013-01-05 05:19:30 [SEVERE] [ForgeModLoader] Caught exception from MCPermissions
java.lang.NoSuchMethodError: org.yaml.snakeyaml.introspector.PropertyUtils.setSkipMissingProperties(Z)V
at noppes.permissions.PermissionsController.loadPermissions(PermissionsController.java:190)
at noppes.permissions.MCPermissions.loadPermissions(MCPermissions.java:112)
at noppes.permissions.MCPermissions.load(MCPermissions.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:483)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
at com.google.common.eventbus.EventBus.post(EventBus.java:268)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
at com.google.common.eventbus.EventBus.post(EventBus.java:268)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:485)
at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:345)
at ho.c(DedicatedServer.java:64)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
at fy.run(SourceFile:849)
2013-01-05 05:19:30 [INFO] [STDERR] cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: org.yaml.snakeyaml.introspector.PropertyUtils.setSkipMissingProperties(Z)V
2013-01-05 05:19:30 [INFO] [STDERR] at cpw.mods.fml.common.LoadController.transition(LoadController.java:117)
2013-01-05 05:19:30 [INFO] [STDERR] at cpw.mods.fml.common.Loader.loadMods(Loader.java:486)
2013-01-05 05:19:30 [INFO] [STDERR] at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
2013-01-05 05:19:30 [INFO] [STDERR] at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:345)
2013-01-05 05:19:30 [INFO] [STDERR] at ho.c(DedicatedServer.java:64)
2013-01-05 05:19:30 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
2013-01-05 05:19:30 [INFO] [STDERR] at fy.run(SourceFile:849)
2013-01-05 05:19:30 [INFO] [STDERR] Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.introspector.PropertyUtils.setSkipMissingProperties(Z)V
2013-01-05 05:19:30 [INFO] [STDERR] at noppes.permissions.PermissionsController.loadPermissions(PermissionsController.java:190)
2013-01-05 05:19:30 [INFO] [STDERR] at noppes.permissions.MCPermissions.loadPermissions(MCPermissions.java:112)
2013-01-05 05:19:30 [INFO] [STDERR] at noppes.permissions.MCPermissions.load(MCPermissions.java:54)
2013-01-05 05:19:30 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-05 05:19:30 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2013-01-05 05:19:30 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-01-05 05:19:30 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Method.java:616)
2013-01-05 05:19:30 [INFO] [STDERR] at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:483)
2013-01-05 05:19:30 [INFO] [STDERR] at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
2013-01-05 05:19:30 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-01-05 05:19:30 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Method.java:616)
2013-01-05 05:19:30 [INFO] [STDERR] at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2013-01-05 05:19:30 [INFO] [STDERR] at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-01-05 05:19:30 [INFO] [STDERR] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2013-01-05 05:19:30 [INFO] [STDERR] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2013-01-05 05:19:30 [INFO] [STDERR] at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2013-01-05 05:19:30 [INFO] [STDERR] at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
2013-01-05 05:19:30 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-05 05:19:30 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2013-01-05 05:19:30 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-01-05 05:19:30 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Method.java:616)
2013-01-05 05:19:30 [INFO] [STDERR] at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2013-01-05 05:19:30 [INFO] [STDERR] at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-01-05 05:19:30 [INFO] [STDERR] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2013-01-05 05:19:30 [INFO] [STDERR] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2013-01-05 05:19:30 [INFO] [STDERR] at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2013-01-05 05:19:30 [INFO] [STDERR] at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
2013-01-05 05:19:30 [INFO] [STDERR] at cpw.mods.fml.common.Loader.loadMods(Loader.java:485)
2013-01-05 05:19:30 [INFO] [STDERR] ... 5 more
2013-01-05 05:19:30 [SEVERE] [Minecraft] Encountered an unexpected exception LoaderException
cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: org.yaml.snakeyaml.introspector.PropertyUtils.setSkipMissingProperties(Z)V
at cpw.mods.fml.common.LoadController.transition(LoadController.java:117)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:486)
at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:345)
at ho.c(DedicatedServer.java:64)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
at fy.run(SourceFile:849)
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.introspector.PropertyUtils.setSkipMissingProperties(Z)V
at noppes.permissions.PermissionsController.loadPermissions(PermissionsController.java:190)
at noppes.permissions.MCPermissions.loadPermissions(MCPermissions.java:112)
at noppes.permissions.MCPermissions.load(MCPermissions.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:483)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
at com.google.common.eventbus.EventBus.post(EventBus.java:268)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
at com.google.common.eventbus.EventBus.post(EventBus.java:268)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:485)
... 5 more

**Comment by keepcalm** [comment]
It uses a conflicting version of snakeyaml. Not much I can do about this, sorry.
