### ISSUE TITLE
[Heroes] Errors

### ISSUE THREAD

**Issue by rlagur55** [keepcalm/BukkitForge#120]
Heroes Plugin doesn't work with this

2013-01-05 22:52:40 [SEVERE] [BukkitForge] Could not pass event PlayerQuitEvent to Heroes v1.5.1-dev-b1646
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:470)
    at keepcalm.mods.bukkit.forgeHandler.PlayerTracker.onPlayerLogout(PlayerTracker.java:52)
    at cpw.mods.fml.common.registry.GameRegistry.onPlayerLogout(GameRegistry.java:348)
    at gm.e(ServerConfigurationManager.java:228)
    at iv.c(NetServerHandler.java:169)
    at gm.r(ServerConfigurationManager.java:910)
    at net.minecraft.server.MinecraftServer.k(MinecraftServer.java:402)
    at fx.run(SourceFile:837)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/Packet
    at com.herocraftonline.heroes.characters.Hero.<init>(Hero.java:79)
    at com.herocraftonline.heroes.persistence.HeroStorage.createNewHero(HeroStorage.java:17)
    at com.herocraftonline.heroes.persistence.YMLHeroStorage.loadHero(YMLHeroStorage.java:102)
    at com.herocraftonline.heroes.characters.CharacterManager.getHero(CharacterManager.java:162)
    at com.herocraftonline.heroes.listeners.HPlayerListener.onPlayerQuit(HPlayerListener.java:316)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 20 more

**Comment by keepcalm** [comment]
It uses NMS classes

**Comment by SpoonsJTD** [comment]
Heroes switched over to using Libigot which uses an old version of the BukkitAPI. They don't provide a CraftBukkit compatible build, so there is little chance this will run using BukkitForge.
