### ISSUE TITLE
chairs issues

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#121]
2013-01-05 18:18:54 [SEVERE] [BukkitForge] Could not pass event PlayerInteractEvent to Chairs v1.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:470)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:413)
    at net.minecraftforge.event.ASMEventHandler_11_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:28)
    at ir.a(ItemInWorldManager.java:389)
    at iv.a(NetServerHandler.java:578)
    at fk.a(SourceFile:58)
    at cg.b(TcpConnection.java:454)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/Block
    at net.spoothie.chairs.EventListener.onPlayerInteract(EventListener.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 20 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Block
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 26 more

**Comment by keepcalm** [comment]
It uses vanilla classes

**Comment by Thornas88** [comment]
what do you mean?

**Comment by keepcalm** [comment]
CraftBukkit has all of its classes in the net.minecraft.server package, whereas vanilla MC uses obfuscated class names (eg iq) - so these two are incompatible. Sorry.

**Comment by Thornas88** [comment]
its okay
