### ISSUE TITLE
Error saving players / world data when stopping the server + GroupManager Issue

### ISSUE THREAD

**Issue by charlieTheBotDev** [keepcalm/BukkitForge#123]
I installed BukkitForge and all the essentials plugins as well as worldedit to my direwolf FTB server.

Now, whenever I stop the server, it forgets where all the players are and treats them as new, giving them the basic tools kit and moving them to the newbie spawn. 

I looked at the log when saving and it seems that there's an error but I dont know what it is. 

Logs:
2013-01-06 02:37:27 [INFO] [BukkitForge] Stopping the Bukkit API 1.4.6
2013-01-06 02:37:27 [INFO] [Minecraft] Stopping the server
2013-01-06 02:37:27 [INFO] [Minecraft] Stopping server
2013-01-06 02:37:27 [INFO] [Minecraft] Saving players
2013-01-06 02:37:27 [INFO] [Minecraft] Saving worlds
2013-01-06 02:37:27 [INFO] [STDERR] java.net.SocketException: Socket closed
2013-01-06 02:37:27 [INFO] [Minecraft] Saving chunks for level 'SpeexWolf20'/Overworld
2013-01-06 02:37:27 [INFO] [STDERR]     at java.net.PlainSocketImpl.socketAccept(Native Method)
2013-01-06 02:37:27 [INFO] [STDERR]     at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
2013-01-06 02:37:27 [INFO] [STDERR]     at java.net.ServerSocket.implAccept(ServerSocket.java:522)
2013-01-06 02:37:27 [INFO] [STDERR]     at java.net.ServerSocket.accept(ServerSocket.java:490)
2013-01-06 02:37:27 [INFO] [STDERR]     at hu.run(ServerListenThread.java:81)
2013-01-06 02:37:27 [INFO] [STDOUT] Closing listening thread
2013-01-06 02:37:27 [INFO] [Minecraft] Saving chunks for level 'SpeexWolf20'/Nether
2013-01-06 02:37:27 [INFO] [ForgeModLoader] [Thaumcraft] Removed 12 aura nodes when world 0 unloaded.
2013-01-06 02:37:28 [INFO] [ForgeModLoader] [Thaumcraft] Removed 0 aura nodes when world -1 unloaded.
2013-01-06 02:37:28 [INFO] [ForgeModLoader] Unloading dimension 0
2013-01-06 02:37:28 [INFO] [ForgeModLoader] Unloading dimension -1
2013-01-06 02:37:28 [INFO] [Minecraft] Stopping server

The only thing I've done to the server is install the bukkit compatibilty, I havent added any other mods or modified configs. I did try using a different world name from default but that didnt seem to work.

The other issue I'm having is with GroupManager. I don't know what it's supposed to do in this respect but it isn't adding players to the users.yml for the world, even if I change their group.

Build Info:

BukkitForge build 53
Worldedit build 5.4.5
Essentials build 2.9.5 (ported for forge)

Downloaded from here (http://www.minecraftforge.net/forum/index.php/topic,3254.0.html)

**Comment by delsolsi213** [comment]
do what i did, in essentials config disable starter kits for new players and disable the newbie spawn.

**Comment by charlieTheBotDev** [comment]
I don't see this as a fix, more of a workaround but yes, that seemed to work. 

The first issue is caused by essentials spawn not being able to differentiate between new player / existing players. It teleports the player to the spawn every time they join as a result.

The only combination of the settings for essentialsSpawn I found that works (at the bottom of the global essentials config) is this:

newbies:
  announce-format: ''

  spawnpoint: none

respawn-listener-priority: lowest

respawn-at-home: true

I am also still experiencing the issue with groupmanager not adding players to the users.yml - I don't want to have to do this manually as I hope to have a high number of players (50 slot server)

**Comment by charlieTheBotDev** [comment]
Looks like I was being a noob. My worldname wasn't set to 'world' so the config was wrong and it looks like when users are in the default group they don't get added to the users file for the world.

I'm still not sure about the world perms, I have two folders for each world, one with the normal name, and one with @0 on the end. Not sure if this intentional but it hasn't caused any issues so far so I'll live with it. I got around having two sets of files by setting a link to the normal folder with the @0 name and it seems to have stopped duplicates.

**Comment by keepcalm** [comment]
It should be fixed as of the last few builds. The reason I have the @ number naming is that Bukkit separates worlds by name (so you have world and world_nether and world_the_end), whereas vanilla MC separates by dimension (so 0, -1 and 1).
