### ISSUE TITLE
isPlayerOp broken (beta #29)

### ISSUE THREAD

**Issue by dwi** [keepcalm/BukkitForge#124]
When trying to perform op command from game (/stop for example), this is thrown to server console:

``````
2013-01-05 21:58:13 [INFO] [STDERR] java.lang.NoClassDefFoundError: bdz
2013-01-05 21:58:13 [INFO] [STDERR]     at com.ForgeEssentials.util.FunctionHelper.isPlayerOp(FunctionHelper.java:180)
2013-01-05 21:58:13 [INFO] [STDERR]     at com.ForgeEssentials.permission.PermissionsHandler.doOpCheck(PermissionsHandler.java:34)
2013-01-05 21:58:13 [INFO] [STDERR]     at com.ForgeEssentials.permission.query.ASMQueryHandler_0_PermissionsHandler_doOpCheck_PermQueryPlayer.invoke(.dynamic)
2013-01-05 21:58:13 [INFO] [STDERR]     at com.ForgeEssentials.permission.query.ASMQueryHandler.invoke(ASMQueryHandler.java:47)
2013-01-05 21:58:13 [INFO] [STDERR]     at com.ForgeEssentials.permission.query.PermissionQueryBus.post(PermissionQueryBus.java:87)
2013-01-05 21:58:13 [INFO] [STDERR]     at com.ForgeEssentials.permission.PermissionsAPI.checkPermAllowed(PermissionsAPI.java:39)
2013-01-05 21:58:13 [INFO] [STDERR]     at com.ForgeEssentials.commands.vanilla.CommandStop.b(CommandStop.java:17)
2013-01-05 21:58:13 [INFO] [STDERR]     at x.a(CommandHandler.java:44)
2013-01-05 21:58:13 [INFO] [STDERR]     at iv.d(NetServerHandler.java:768)
2013-01-05 21:58:13 [INFO] [STDERR]     at iv.a(NetServerHandler.java:734)
2013-01-05 21:58:13 [INFO] [STDERR]     at cu.a(SourceFile:44)
2013-01-05 21:58:13 [INFO] [STDERR]     at cg.b(TcpConnection.java:458)
2013-01-05 21:58:13 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2013-01-05 21:58:13 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-01-05 21:58:13 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-01-05 21:58:13 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
2013-01-05 21:58:13 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-05 21:58:13 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-01-05 21:58:13 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-05 21:58:13 [INFO] [STDERR]     at fy.run(SourceFile:849)```
``````

**Comment by Erycus** [comment]
You are using build 29?  If so, you need to use the most recent one, not outdated ones.

**Comment by dwi** [comment]
Fixed with build 31
