### ISSUE TITLE
Almost nothing is working

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#13]
2012-12-10 13:49:24 [INFO] [STDERR] java.lang.NoClassDefFoundError: Could not initialize class keepcalm.mods.bukkit.bukkitAPI.block.BukkitBlock
2012-12-10 13:49:24 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getBlock(BukkitChunk.java:90)
2012-12-10 13:49:24 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.getBlockAt(BukkitWorld.java:195)
2012-12-10 13:49:24 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:196)
2012-12-10 13:49:24 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:186)
2012-12-10 13:49:24 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:279)
2012-12-10 13:49:24 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_44_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
2012-12-10 13:49:24 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2012-12-10 13:49:24 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2012-12-10 13:49:24 [INFO] [STDERR]     at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
2012-12-10 13:49:24 [INFO] [STDERR]     at iv.a(NetServerHandler.java:499)
2012-12-10 13:49:24 [INFO] [STDERR]     at net.smart.moving.playerapi.NetServerHandler.a(NetServerHandler.java:34)
2012-12-10 13:49:24 [INFO] [STDERR]     at fl.a(SourceFile:58)
2012-12-10 13:49:24 [INFO] [STDERR]     at cg.b(TcpConnection.java:451)
2012-12-10 13:49:24 [INFO] [STDERR]     at iv.d(NetServerHandler.java:82)
2012-12-10 13:49:24 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:55)
2012-12-10 13:49:24 [INFO] [STDERR]     at ht.b(SourceFile:30)
2012-12-10 13:49:24 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
2012-12-10 13:49:24 [INFO] [STDERR]     at ho.r(DedicatedServer.java:252)
2012-12-10 13:49:24 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
2012-12-10 13:49:24 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
2012-12-10 13:49:24 [INFO] [STDERR]     at fy.run(SourceFile:856)
2012-12-10 13:49:24 [SEVERE] [Minecraft] Encountered an unexpected exception NoClassDefFoundError
java.lang.NoClassDefFoundError: Could not initialize class keepcalm.mods.bukkit.bukkitAPI.block.BukkitBlock
        at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getBlock(BukkitChunk.java:90)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.getBlockAt(BukkitWorld.java:195)
        at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:196)
        at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callPlayerInteractEvent(BukkitEventFactory.java:186)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:279)
        at net.minecraftforge.event.ASMEventHandler_44_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
        at iv.a(NetServerHandler.java:499)
        at net.smart.moving.playerapi.NetServerHandler.a(NetServerHandler.java:34)
        at fl.a(SourceFile:58)
        at cg.b(TcpConnection.java:451)
        at iv.d(NetServerHandler.java:82)
        at iw.b(NetworkListenThread.java:55)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
        at ho.r(DedicatedServer.java:252)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
        at fy.run(SourceFile:856)

**Comment by keepcalm** [comment]
Which release?

**Comment by Wolftein** [comment]
Lastest bukkit4vanilla jar and Forge 1.4.5-6.4.1.411

**Comment by keepcalm** [comment]
Well, something's misbehaving. Which mods do you have installed? I will investigate further.

**Comment by koala1207** [comment]
I met a problem. Use latest bukkit4vanilla and forge 1.4.5-6.4.1.430
I just try to test it. So, the only plugin I used is the essential you post.
java.lang.NoSuchMethodError: iq.h(F)Laob;
    at keepcalm.mods.bukkit.forgeHandler.PlayerUtilities.getTargetBlock(PlayerUtilities.java:17)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:205)
    at net.minecraftforge.event.ASMEventHandler_9_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
    at ir.a(ItemInWorldManager.java:147)
    at iv.a(NetServerHandler.java:445)
    at ej.a(SourceFile:46)
    at cg.b(TcpConnection.java:451)
    at iv.d(NetServerHandler.java:82)
    at iw.b(NetworkListenThread.java:55)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
    at ho.r(DedicatedServer.java:252)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
    at fy.run(SourceFile:856)

**Comment by Wolftein** [comment]
is when i use a essentials command then start to happend that like /sethome

**Comment by keepcalm** [comment]
@koala1207, please use a separate issue in the future. But I've already fixed that. 

Your issue is in no way related to this one.

Oh, and fixing now...

**Comment by keepcalm** [comment]
Fixed in commit 5bdfe6, I think.
