### ISSUE TITLE
Essentials YAML Issue

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#132]
Essentials isn't saving the User Data YAML's and Is causing players to come back with the Welcome message and the default tool pack
[WARNING] [BukkitForge] Method "public Class<?> getClassByName(String)" is Deprecated, and may be removed in a future version of Bukkit
org.bukkit.plugin.AuthorNagException: 
    at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:284)
    at com.earth2me.essentials.storage.BukkitConstructor.getClassForNode(BukkitConstructor.java:418)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:321)
    at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:183)
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:142)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:128)
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:423)
    at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:47)
    at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:37)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VAsyncTask.run(B4VAsyncTask.java:54)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

**Comment by keepcalm** [comment]
Try the latest build

**Comment by ghost** [comment]
Still doing it :/

**Comment by keepcalm** [comment]
Oh, wait, THAT  message is normal. It's just a warning.
