### ISSUE TITLE
[LWC] Error

### ISSUE THREAD

**Issue by Pepejson** [keepcalm/BukkitForge#134]
I've got LWC error.

2013-01-06 16:32:21 [SEVERE] [BukkitForge] Error occurred while enabling LWC v4.3.1 (b767-git-MANUAL) (November 15, 2012) (Is it up to date?)
java.lang.NoClassDefFoundError: org/json/simple/parser/JSONParser
    at com.griefcraft.sql.PhysDB.<init>(PhysDB.java:59)
    at com.griefcraft.lwc.LWC.load(LWC.java:1367)
    at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:224)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:925)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:909)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:256)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: org.json.simple.parser.JSONParser
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 11 more

**Comment by Victor9401** [comment]
ok, just copy org folder from working copy of the craftbukkit

**Comment by cartmen180** [comment]
I have the same issue, copying the lwc folder from a craftbukkitserver does not solve the problem

**Comment by kopylov** [comment]
2013-01-25 10:50:40 [SEVERE] [BukkitForge] Could not pass event BlockPlaceEvent to LWC v4.3.1 (b767-git-MANUAL) (November 15, 2012)
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:397)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteraction(ForgeEventHandler.java:354)
    at net.minecraftforge.event.ASMEventHandler_102_ForgeEventHandler_onPlayerInteraction_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
    at ir.a(ItemInWorldManager.java:389)
    at iv.a(NetServerHandler.java:617)
    at fk.a(SourceFile:58)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:141)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at com.griefcraft.util.ProtectionFinder.tryLoadProtection(ProtectionFinder.java:274)
    at com.griefcraft.util.ProtectionFinder.matchBlocks(ProtectionFinder.java:105)
    at com.griefcraft.lwc.LWC.findProtection(LWC.java:1161)
    at com.griefcraft.listeners.LWCBlockListener.onBlockPlace(LWCBlockListener.java:324)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:395)
    ... 20 more
2013-01-25 10:50:42 [INFO] [STDERR] java.lang.NullPointerException
2013-01-25 10:50:42 [INFO] [STDERR]     at com.griefcraft.util.ProtectionFinder.tryLoadProtection(ProtectionFinder.java:274)
2013-01-25 10:50:42 [INFO] [STDERR]     at com.griefcraft.util.ProtectionFinder.matchBlocks(ProtectionFinder.java:105)
2013-01-25 10:50:42 [INFO] [STDERR]     at com.griefcraft.lwc.LWC.findProtection(LWC.java:1161)
2013-01-25 10:50:42 [INFO] [STDERR]     at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:135)
2013-01-25 10:50:42 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-25 10:50:42 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-01-25 10:50:42 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-01-25 10:50:42 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-01-25 10:50:42 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:395)
2013-01-25 10:50:42 [INFO] [STDERR]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
2013-01-25 10:50:42 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-01-25 10:50:42 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2013-01-25 10:50:42 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:461)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_105_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
2013-01-25 10:50:42 [INFO] [STDERR]     at ir.a(ItemInWorldManager.java:389)
2013-01-25 10:50:42 [INFO] [STDERR]     at iv.a(NetServerHandler.java:617)
2013-01-25 10:50:42 [INFO] [STDERR]     at fk.a(SourceFile:58)
2013-01-25 10:50:42 [INFO] [STDERR]     at cg.b(TcpConnection.java:458)
2013-01-25 10:50:42 [INFO] [STDERR]     at iv.d(NetServerHandler.java:141)
2013-01-25 10:50:42 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-01-25 10:50:42 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
2013-01-25 10:50:42 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-25 10:50:42 [INFO] [STDERR]     at fy.run(SourceFile:849)

**Comment by Sageavatar** [comment]
Status Update anyone? Does LWC work? 

Thanks.

**Comment by SpoonsJTD** [comment]
Can someone retest and report?

**Comment by Sageavatar** [comment]
Hey @SpoonsJTD , #529 . They don't state their build version of either, but it looks like it loads? I can try to test it as well tonight or tomorrow.

**Comment by SpoonsJTD** [comment]
Did someone say something about a custom build for MCPC? Something about hardcoded ID's?

**Comment by alexbegt** [comment]
Fixed
