### ISSUE TITLE
[JSONApi] Exception while starting JSONApi

### ISSUE THREAD

**Issue by Manawyrm** [keepcalm/BukkitForge#135]
http://ci.alecgorge.com/job/JSONAPI/133/artifact/target/JSONAPI.jar

´´´
2013-01-06 18:51:25 [SEVERE] [BukkitForge] Could not load './plugins/JSONApi.jar' in folder './plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_6/World
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:184)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:313)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:238)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:881)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:255)
        at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_6/World
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:173)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_6.World
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 9 more

```
```

**Comment by keepcalm** [comment]
It's accessing MC classes. So it won't work.

**Comment by keplersj** [comment]
I logged my own experience with this on the the repository for it: https://github.com/alecgorge/jsonapi/issues/218

**Comment by SpoonsJTD** [comment]
Doesn't look like this can happen anytime soon.

**Comment by Manawyrm** [comment]
Problem fixed with custom build of JSONApi:
https://github.com/Manawyrm/jsonapi
