### ISSUE TITLE
Block Type error

### ISSUE THREAD

**Issue by TempestCraft** [keepcalm/BukkitForge#139]
I got this error when starting up my server today (This might of happened from changing the ram amount but I don't really think its that)

2013-01-23 14:00:04 [SEVERE] [Minecraft] Encountered an unexpected exception t
t: Exception getting block type in world
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:674)
at ho.r(DedicatedServer.java:270)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java:54)
at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
at org.bukkit.event.world.ChunkLoadEvent.<init>(ChunkLoadEvent.java:14)
at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkLoadEvent(ForgeEventHandler.java:492)
at net.minecraftforge.event.ASMEventHandler_106_ForgeEventHandler_chunkLoadEvent_Load.invoke(.dynamic)
at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
at net.minecraftforge.event.EventBus.post(EventBus.java:103)
at zz.c(Chunk.java:1086)
at im.c(ChunkProviderServer.java:150)
at im.d(ChunkProviderServer.java:166)
at yc.e(World.java:524)
at yc.a(World.java:407)
at yc.c(World.java:436)
at akz.b(SourceFile:63)
at in.g(WorldServer.java:420)
at in.b(WorldServer.java:180)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:668)
... 4 more

**Comment by SpoonsJTD** [comment]
Are you still getting this error with the current build?

**Comment by TempestCraft** [comment]
yes, mainly when restarting my server but its only once in a while.

**Comment by SpoonsJTD** [comment]
Closing. Re-open if it prevents your server from starting.
