### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by ToddVee** [keepcalm/BukkitForge#14]
2012-12-11 03:08:27 [INFO] [STDERR] t: Exception ticking world
2012-12-11 03:08:27 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:668)
2012-12-11 03:08:27 [INFO] [STDERR]     at ho.r(DedicatedServer.java:252)
2012-12-11 03:08:27 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
2012-12-11 03:08:27 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
2012-12-11 03:08:27 [INFO] [STDERR]     at fy.run(SourceFile:856)
2012-12-11 03:08:27 [INFO] [STDERR] Caused by: java.lang.NoSuchMethodError: in.w()Ljava/lang/String;
2012-12-11 03:08:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.getWorld(BukkitServer.java:650)
2012-12-11 03:08:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java:47)
2012-12-11 03:08:27 [INFO] [STDERR]     at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
2012-12-11 03:08:27 [INFO] [STDERR]     at org.bukkit.event.world.ChunkLoadEvent.<init>(ChunkLoadEvent.java:14)
2012-12-11 03:08:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkLoadEvent(ForgeEventHandler.java:206)
2012-12-11 03:08:27 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_47_ForgeEventHandler_chunkLoadEvent_Load.invoke(.dynamic)
2012-12-11 03:08:27 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2012-12-11 03:08:27 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2012-12-11 03:08:27 [INFO] [STDERR]     at zs.c(Chunk.java:1067)
2012-12-11 03:08:27 [INFO] [STDERR]     at im.c(ChunkProviderServer.java:134)
2012-12-11 03:08:27 [INFO] [STDERR]     at im.d(ChunkProviderServer.java:150)
2012-12-11 03:08:27 [INFO] [STDERR]     at xv.e(World.java:496)
2012-12-11 03:08:27 [INFO] [STDERR]     at in.g(WorldServer.java:289)
2012-12-11 03:08:27 [INFO] [STDERR]     at in.b(WorldServer.java:138)
2012-12-11 03:08:27 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:662)
2012-12-11 03:08:27 [INFO] [STDERR]     ... 4 more
2012-12-11 03:08:27 [SEVERE] [Minecraft] Encountered an unexpected exception t
t: Exception ticking world
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:668)
    at ho.r(DedicatedServer.java:252)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
    at fy.run(SourceFile:856)
Caused by: java.lang.NoSuchMethodError: in.w()Ljava/lang/String;
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.getWorld(BukkitServer.java:650)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java:47)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkLoadEvent.<init>(ChunkLoadEvent.java:14)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkLoadEvent(ForgeEventHandler.java:206)
    at net.minecraftforge.event.ASMEventHandler_47_ForgeEventHandler_chunkLoadEvent_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at zs.c(Chunk.java:1067)
    at im.c(ChunkProviderServer.java:134)
    at im.d(ChunkProviderServer.java:150)
    at xv.e(World.java:496)
    at in.g(WorldServer.java:289)
    at in.b(WorldServer.java:138)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:662)
    ... 4 more

**Comment by keepcalm** [comment]
Update

**Comment by ToddVee** [comment]
sry, but I don't get it. I use the latest release of your bukkit4vanilla and forge 1.4.5-6.4.1.425
so "update" what?
