### ISSUE TITLE
[Logblock]

### ISSUE THREAD

**Issue by HypnoTherapist** [keepcalm/BukkitForge#140]
[BukkitForge] Exception in commands handler: 
java.lang.NullPointerException

> ```
>   at de.diddiz.LogBlock.CommandsHandler.onCommand(CommandsHandler.java:144)
>   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
>   at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
>   at x.a(CommandHandler.java:82)
>   at iv.d(NetServerHandler.java:768)
>   at iv.a(NetServerHandler.java:734)
>   at cu.a(SourceFile:44)
>   at cg.b(TcpConnection.java:454)
>   at iv.d(NetServerHandler.java:136)
>   at iw.b(NetworkListenThread.java:57)
>   at ht.b(SourceFile:30)
>   at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
>   at ho.r(DedicatedServer.java:270)
>   at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
>   at fy.run(SourceFile:849)
> ```
> 
> when I give myself the Lb tool it gives me the tool and thriws this error. and it inst recorded in the server.log. not sure whats going on.

**Comment by ghost** [comment]
Logblock is IMHO very close to work. Many thanks. Block place/breaks events works fine - database have rows. But when use ingame tool, throw exeption:

2013-01-24 12:05:17 [SEVERE] [BukkitForge] Could not pass event PlayerInteractEvent to LogBlock v1.61
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:397)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:464)
        at net.minecraftforge.event.ASMEventHandler_50_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:28)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:617)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:454)
        at iv.d(NetServerHandler.java:141)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at de.diddiz.LogBlock.listeners.ToolListener.onPlayerInteract(ToolListener.java:49)
        at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:395)
        ... 20 more

Another cosmetic problem is naming of worlds. Many plugins use default name of world "world", "world_the_nether" and "world_the_end". In the Bukkitforge is default worl named "Overworld". Is possible to make aliases for worlds to compatibility please?
