### ISSUE TITLE
[FirstJoinPlus] FirstJoinEvent Issues

### ISSUE THREAD

**Issue by SpiritedDusty** [keepcalm/BukkitForge#151]
I'm having issues with a plugin, FirstJoinPlus.
`2013-01-06 19:47:06 [SEVERE] [BukkitForge] Could not pass event FirstJoinEvent to FirstJoinPlus v1.7.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471)
    at me.chaseoes.firstjoinplus.PlayerListeners.firstJoinDetection(PlayerListeners.java:32)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471)
    at keepcalm.mods.bukkit.forgeHandler.PlayerTracker$1.run(PlayerTracker.java:38)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
    at me.chaseoes.firstjoinplus.Utilities.getUniquePlayerCount(Utilities.java:89)
    at me.chaseoes.firstjoinplus.Utilities.format(Utilities.java:83)
    at me.chaseoes.firstjoinplus.FirstJoinListener.onFirstJoin(FirstJoinListener.java:91)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 14 more`

**Comment by keepcalm** [comment]
In your configuration, change 'worldname' to world/DIM0, where world is the name of your world on the server.

**Comment by SpiritedDusty** [comment]
Well that stopped the erros but I keep being counted as a new player that never joined before even if I have my player data file in the world's folder. Is there anyway to fix that?

**Comment by keepcalm** [comment]
Did you try logging in twice? I fixed that as of recent builds, just one more login and then it won't happen.

**Comment by SpoonsJTD** [comment]
lieudustry, please check or issue will be closed.

**Comment by SpiritedDusty** [comment]
Its working now, sorry for not replying.
