### ISSUE TITLE
Factions not working Edit:Posted new error, gson download is working

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#153]
Im still getting the gson issue with factions, I have the latest build and it still shows the error and it wont enable factions.

**Comment by keepcalm** [comment]
Delete the existing gson jar in your lib folder.

**Comment by ghost** [comment]
Im getting this error now
2013-01-07 04:07:56 [INFO] [BukkitForge] [Factions v1.6.9.4] Creating default: ./plugins/Factions/conf.json
2013-01-07 04:07:56 [SEVERE] [BukkitForge] Error occurred while enabling Factions v1.6.9.4 (Is it up to date?)
java.lang.AssertionError
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:686)
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.TypeAdapters$24.create(TypeAdapters.java:715)
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.getAdapter(Gson.java:353)
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.getAdapter(Gson.java:353)
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.getAdapter(Gson.java:353)
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.toJson(Gson.java:538)
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.toJson(Gson.java:525)
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.toJson(Gson.java:480)
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.toJson(Gson.java:460)
    at com.massivecraft.factions.zcore.util.Persist.save(Persist.java:116)
    at com.massivecraft.factions.zcore.util.Persist.loadOrSaveDefault(Persist.java:80)
    at com.massivecraft.factions.zcore.util.Persist.loadOrSaveDefault(Persist.java:72)
    at com.massivecraft.factions.Conf.load(Conf.java:369)
    at com.massivecraft.factions.P.onEnable(P.java:99)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:390)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:931)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:915)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:265)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
    at java.lang.Thread.run(Thread.java:722)

**Comment by ghost** [comment]
Im still getting that error above.

**Comment by keepcalm** [comment]
Is that the latest? I see people talking about Factions 1.8...

**Comment by ghost** [comment]
1.8 is the Dev Build, Want me to try that and see if it works?

**Comment by keepcalm** [comment]
Yes, that shouldn't happen.

**Comment by ghost** [comment]
It's working now Thanks
