### ISSUE TITLE
World location

### ISSUE THREAD

**Issue by clienthax** [keepcalm/BukkitForge#158]
2013-01-07 17:40:52 [INFO] [STDOUT] CONSOLE: Disabled level saving..←[m
2013-01-07 17:40:52 [INFO] [BukkitForge.BukkitForge] [Backup] Failed to backup worlds: Exception in BackupWorlds.
2013-01-07 17:40:52 [INFO] [BukkitForge.BukkitForge] [Backup] Please provide following error with support request:
2013-01-07 17:40:52 [INFO] [STDOUT] java.io.FileNotFoundException: Source 'world\0' does not exist
2013-01-07 17:40:52 [INFO] [STDOUT]     at com.bukkitbackup.full.utils.FileUtils.copyDirectory(FileUtils.java:204)
2013-01-07 17:40:52 [INFO] [STDOUT]     at com.bukkitbackup.full.utils.FileUtils.copyDirectory(FileUtils.java:145)
2013-01-07 17:40:52 [INFO] [STDOUT]     at com.bukkitbackup.full.utils.FileUtils.copyDirectory(FileUtils.java:114)
2013-01-07 17:40:52 [INFO] [STDOUT]     at com.bukkitbackup.full.threading.tasks.BackupWorlds.doWorlds(BackupWorlds.java:139)
2013-01-07 17:40:52 [INFO] [STDOUT]     at com.bukkitbackup.full.threading.BackupTask.run(BackupTask.java:109)
2013-01-07 17:40:52 [INFO] [STDOUT]     at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
2013-01-07 17:40:52 [INFO] [STDOUT]     at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VAsyncTask.run(B4VAsyncTask.java:54)
2013-01-07 17:40:52 [INFO] [STDOUT]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
2013-01-07 17:40:52 [INFO] [STDOUT]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
2013-01-07 17:40:52 [INFO] [STDOUT]     at java.lang.Thread.run(Thread.java:722)
2013-01-07 17:40:53 [INFO] [STDOUT] [Backup] Finished Backup!←[m

**Comment by keepcalm** [comment]
<clienthax> C:\voltz1.0.6\world\0>mklink /J players C:\voltz1.0.6\world\players
<clienthax> Junction created for players <<===>> C:\voltz1.0.6\world\players
<clienthax> C:\voltz1.0.6\world\0>mklink /J region C:\voltz1.0.6\world\region
<clienthax> Junction created for region <<===>> C:\voltz1.0.6\world\region
<clienthax> thatl work for now
