### ISSUE TITLE
[WorldEdit] World Edit Error

### ISSUE THREAD

**Issue by UGLHong** [keepcalm/BukkitForge#169]
Worldedit seems to be unable to modify area i select with the block i specify with //set or //replace or any other modifying command. 

Example : //set glass or //set 2 will return java.lang.NoClassDefFoundError: net/minecraf
t/server/Block.

Please look into it as worldedit is really important for a server thanks alot =D

2013-01-09 02:11:23 [INFO] [STDERR] java.lang.NoClassDefFoundError: net/minecraf
t/server/Block
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.worldedit.bukkit.BukkitWorl
d.isValidBlockType(BukkitWorld.java:872)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.worldedit.WorldEdit.getBloc
k(WorldEdit.java:413)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.worldedit.WorldEdit.getBloc
k(WorldEdit.java:354)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.worldedit.WorldEdit.getBloc
k(WorldEdit.java:548)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.worldedit.WorldEdit.getBloc
kPattern(WorldEdit.java:607)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.worldedit.commands.RegionCo
mmands.set(RegionCommands.java:74)
2013-01-09 02:11:23 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.
invoke0(Native Method)
2013-01-09 02:11:23 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.
invoke(Unknown Source)
2013-01-09 02:11:23 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorI
mpl.invoke(Unknown Source)
2013-01-09 02:11:23 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unkno
wn Source)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.minecraft.util.commands.Com
mandsManager.invokeMethod(CommandsManager.java:522)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.worldedit.WorldEdit$1.invok
eMethod(WorldEdit.java:240)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.worldedit.WorldEdit$1.invok
eMethod(WorldEdit.java:171)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.minecraft.util.commands.Com
mandsManager.executeMethod(CommandsManager.java:509)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.minecraft.util.commands.Com
mandsManager.execute(CommandsManager.java:425)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.worldedit.WorldEdit.handleC
ommand(WorldEdit.java:1338)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.worldedit.bukkit.WorldEditP
lugin.onCommand(WorldEditPlugin.java:197)
2013-01-09 02:11:23 [INFO] [STDERR]     at com.sk89q.bukkit.util.DynamicPluginCo
mmand.execute(DynamicPluginCommand.java:52)
2013-01-09 02:11:23 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.com
mands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2013-01-09 02:11:23 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2013-01-09 02:11:23 [INFO] [STDERR]     at iv.d(NetServerHandler.java:768)
2013-01-09 02:11:23 [INFO] [STDERR]     at iv.a(NetServerHandler.java:734)
2013-01-09 02:11:23 [INFO] [STDERR]     at cu.a(SourceFile:44)
2013-01-09 02:11:23 [INFO] [STDERR]     at cg.b(TcpConnection.java:454)
2013-01-09 02:11:23 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2013-01-09 02:11:23 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-01-09 02:11:23 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-01-09 02:11:23 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
r(MinecraftServer.java:702)
2013-01-09 02:11:23 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-09 02:11:23 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
q(MinecraftServer.java:598)
2013-01-09 02:11:23 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
run(MinecraftServer.java:497)
2013-01-09 02:11:23 [INFO] [STDERR]     at fy.run(SourceFile:849)

**Comment by Chasgasm** [comment]
Are you using the custom build of WorldEdit?
If you aren't, use it: https://github.com/keepcalm/BukkitForge/blob/master/dist/plugins/worldedit-5.4.5.zip

**Comment by lohtonghong** [comment]
Yes i'm using custom build of the worldedit
![Untitled](https://f.cloud.github.com/assets/3218341/52155/ec151184-59ee-11e2-8018-3931af819aac.png)

**Comment by alexbegt** [comment]
Well you have forge essentials installed. thats one

**Comment by lohtonghong** [comment]
alexbegt i dont get what you mean, more details please?

**Comment by lohtonghong** [comment]
Well its solved but now a new error occured, i can't spawn tools using //wand and //hpos1 //hpos2 or //pos1 or //pos2 select Null as its corner instead of specified corner
![error](https://f.cloud.github.com/assets/3218341/54076/f69a442a-5a80-11e2-9387-b3b378a1a36c.png)

i tried it with of the latest version of forgebukkit. same thing happen !

**Comment by keepcalm** [comment]
Update. Use the worldedit from [here](https://github.com/keepcalm/BukkitForge/tree/master/dist/plugins), remove any forgeessentials things from .minecraft (look in mods and coremods).
