### ISSUE TITLE
[EntityDamageByEntityEvent] Event issue

### ISSUE THREAD

**Issue by clienthax** [keepcalm/BukkitForge#171]
2013-01-08 19:23:52 [SEVERE] [BukkitForge] Could not pass event EntityDamageByEntityEvent
to xClans v1.2.4 Release
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471)
        at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callEvent(BukkitEventFactory.java:119)
        at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callEntityDamageEvent(BukkitEventFactory.java:414)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingDamage(ForgeEventHandler.java:222)
        at net.minecraftforge.event.ASMEventHandler_15_ForgeEventHandler_onLivingDamage_Li
vingHurtEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:348)
        at qx.d(EntityPlayer.java:1137)
        at md.a(EntityLiving.java:1045)
        at qx.a(EntityPlayer.java:1014)
        at iq.a(EntityPlayerMP.java:388)
        at qz.j_(SourceFile:258)
        at yc.a(World.java:2295)
        at in.a(WorldServer.java:647)
        at yc.g(World.java:2257)
        at yc.h(World.java:2103)
        at in.h(WorldServer.java:516)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at net.planetofgames.xclans.Listeners.onEntityDamage(Listeners.java:285)
        at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja
va:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 25 more

**Comment by SpoonsJTD** [comment]
Plugin?
