### ISSUE TITLE
[FillBucketEvent] Crash on startup

### ISSUE THREAD

**Issue by Dethy** [keepcalm/BukkitForge#174]
Im using the direwolf20 modpack and getting this:
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/8/13 9:11 PM
Description: Exception while updating neighbours

java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.getName(BukkitPlayer.java:119)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.hashCode(BukkitPlayer.java:749)
    at java.util.WeakHashMap.remove(Unknown Source)
    at org.bukkit.plugin.SimplePluginManager.unsubscribeFromDefaultPerms(SimplePluginManager.java:680)
    at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:179)
    at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:153)
    at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:31)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:51)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:109)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:114)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.fillBukkit(ForgeEventHandler.java:378)
    at net.minecraftforge.event.ASMEventHandler_113_ForgeEventHandler_fillBukkit_FillBucketEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at td.a(ItemBucket.java:48)
    at ur.a(SourceFile:98)
    at com.eloraam.redpower.machine.TileDeployBase.tryUseItemStack(TileDeployBase.java:159)
    at com.eloraam.redpower.machine.TileDeploy.enableTowards(TileDeploy.java:78)
    at com.eloraam.redpower.machine.TileDeployBase.onBlockNeighborChange(TileDeployBase.java:197)
    at com.eloraam.redpower.core.BlockExtended.a(BlockExtended.java:94)
    at yc.m(World.java:822)
    at yc.h(World.java:800)
    at alv.l(BlockRedstoneWire.java:106)
    at alv.a(BlockRedstoneWire.java:421)
    at yc.m(World.java:822)
    at yc.h(World.java:805)
    at alv.l(BlockRedstoneWire.java:106)
    at alv.a(BlockRedstoneWire.java:421)
    at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
    at com.eloraam.redpower.core.RedPowerLib.updateIndirectNeighbors(RedPowerLib.java:53)
    at com.eloraam.redpower.core.TileExtended.updateBlockChange(TileExtended.java:86)
    at com.eloraam.redpower.logic.TileLogicPointer.timerUpdate(TileLogicPointer.java:140)
    at com.eloraam.redpower.logic.TileLogicPointer.g(TileLogicPointer.java:274)
    at yc.h(World.java:2164)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.getName(BukkitPlayer.java:119)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.hashCode(BukkitPlayer.java:749)
    at java.util.WeakHashMap.remove(Unknown Source)
    at org.bukkit.plugin.SimplePluginManager.unsubscribeFromDefaultPerms(SimplePluginManager.java:680)
    at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:179)
    at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:153)
    at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:31)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:51)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:109)
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:114)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.fillBukkit(ForgeEventHandler.java:378)
    at net.minecraftforge.event.ASMEventHandler_113_ForgeEventHandler_fillBukkit_FillBucketEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at td.a(ItemBucket.java:48)
    at ur.a(SourceFile:98)
    at com.eloraam.redpower.machine.TileDeployBase.tryUseItemStack(TileDeployBase.java:159)
    at com.eloraam.redpower.machine.TileDeploy.enableTowards(TileDeploy.java:78)
    at com.eloraam.redpower.machine.TileDeployBase.onBlockNeighborChange(TileDeployBase.java:197)
    at com.eloraam.redpower.core.BlockExtended.a(BlockExtended.java:94)

-- Block being updated --
Details:
    Source block type: ID #55 (tile.redstoneDust // alv)
    Block type: ID #763 (tile.rpmachine2 // com.eloraam.redpower.machine.BlockMachine)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (112,122,-256), Chunk: (at 0,7,0 in 7,-16; contains blocks 112,0,-256 to 127,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
    at yc.m(World.java:822)
    at yc.h(World.java:800)
    at alv.l(BlockRedstoneWire.java:106)
    at alv.a(BlockRedstoneWire.java:421)

-- Block being updated --
Details:
    Source block type: ID #55 (tile.redstoneDust // alv)
    Block type: ID #55 (tile.redstoneDust // alv)
    Block data value: 14 / 0xE / 0b1110
    Block location: World: (113,123,-256), Chunk: (at 1,7,0 in 7,-16; contains blocks 112,0,-256 to 127,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
    at yc.m(World.java:822)
    at yc.h(World.java:805)
    at alv.l(BlockRedstoneWire.java:106)
    at alv.a(BlockRedstoneWire.java:421)
    at com.eloraam.redpower.core.RedPowerLib.notifyBlock(RedPowerLib.java:40)
    at com.eloraam.redpower.core.RedPowerLib.updateIndirectNeighbors(RedPowerLib.java:53)
    at com.eloraam.redpower.core.TileExtended.updateBlockChange(TileExtended.java:86)
    at com.eloraam.redpower.logic.TileLogicPointer.timerUpdate(TileLogicPointer.java:140)
    at com.eloraam.redpower.logic.TileLogicPointer.g(TileLogicPointer.java:274)

-- Tile entity being ticked --
Details:
    Name: RPLgPtr // com.eloraam.redpower.logic.TileLogicPointer
    Block type: ID #0
    Block data value: Unknown? (Got -1)
    Block location: World: (113,122,-258), Chunk: (at 1,7,14 in 7,-17; contains blocks 112,0,-272 to 127,255,-257), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
    at yc.h(World.java:2164)
    at in.h(WorldServer.java:516)

-- Affected level --
Details:
    Level name: world
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 378 Drop: 0
    Level seed: 1778618757
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

-- System Details --
Details:
    Minecraft Version: 1.4.6
    Operating System: Windows Server 2008 R2 (amd64) version 6.1
    Java Version: 1.7.0-ea, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 740333032 bytes (706 MB) / 1142554624 bytes (1089 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 1 total; -Xmx2048M
    AABB Pool Size: 8068 (451808 bytes; 0 MB) allocated, 1573 (88088 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 71
    FML: MCP v7.25 FML v4.6.17.515 Minecraft Forge 6.5.0.489 56 mods loaded, 56 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-74.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BechillTPS [Bechill TPS](BechillTPS-universal-v0.4.1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChargePads [Charge Pads](chargepads-universal-2.3.0.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChickenChunks [ChickenChunks](ChickenChunks 1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CompactSolars [Compact Solar Arrays](compactsolars-universal-1.4.6-3.2.0.21.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ComputerCraft [ComputerCraft](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CCTurtle [ComputerCraft Turtles](ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EE3 [Equivalent Exchange 3](ee3-universal-pre1f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EnderStorage [EnderStorage](EnderStorage 1.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](ExtrabiomesXL-universal-1.4.7-3.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forestry [Forestry for Minecraft](forestry-A-1.7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GraviGun [GraviGun](GravityGun1.4.6v1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.7-4.5.2.213.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals-2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    GraviSuite [Gravitation Suite](mod_zGraviSuite_1_6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](ModularForceFieldSystemV2.2.8.2.14.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Mystcraft [Mystcraft](mystcraft-uni-1.4.6-0.9.5.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates-universal-1.2.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    OmniTools [OmniTools](OmniTools-2.2.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PortalGun [Portal Gun](PortalGun1.4.7v2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Railcraft [Railcraft](Railcraft_1.4.6-6.13.1.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    SoulShards [SoulShards](SoulShards-v1.26-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a42.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft3.0.1c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion [Thermal Expansion](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Factory [Factory](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Energy [Energy](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ThermalExpansion|Transport [Transport](ThermalExpansion-2.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Core [WR-CBE Core](WR-CBE Core 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|Addons [WR-CBE Addons](WR-CBE Addons 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](WR-CBE RedPower 1.3.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    XyCraft [XyCraft](xycraft-universal-1.4.6-0.9.44.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:[No plugins loaded]
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1758 (98448 bytes; 0 MB) allocated, 1724 (96544 bytes; 0 MB) used
    Player Count: 0 / 45; []
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by keepcalm** [comment]
Try updating. I seem to recall fixing this.

**Comment by SpoonsJTD** [comment]
Please check.
