### ISSUE TITLE
 A critical problem occured registering the ASM transformer class keepcalm.mods.bukkit.asm.transformers.BukkitAccessTransformer

### ISSUE THREAD

**Issue by kenneaal** [keepcalm/BukkitForge#181]
On server startup, the following error is logged:
2013-01-09 06:11:18 [INFO] [ForgeModLoader] Forge Mod Loader version 4.6.17.515 for Minecraft 1.4.6 loading
2013-01-09 06:11:18 [INFO] [STDOUT] Adding Accesstransformer map: bukkit_at.cfg
2013-01-09 06:11:18 [SEVERE] [ForgeModLoader] A critical problem occured registering the ASM transformer class keepcalm.mods.bukkit.asm.transformers.BukkitAccessTransformer
java.lang.NullPointerException
        at keepcalm.mods.bukkit.asm.transformers.BukkitAccessTransformer.<init>(BukkitAccessTransformer.java:23)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
        at java.lang.Class.newInstance0(Class.java:372)
        at java.lang.Class.newInstance(Class.java:325)
        at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:75)
        at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:238)
        at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
        at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
        at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1375)

Forge 4.6.17.515, BukkitForge Build #73.

**Comment by kenneaal** [comment]
Never mind, I am an idiot and leaving files in the wrong places. (Caused by ninjas in the coremods)
