### ISSUE TITLE
[templist] command causes SEVERE error

### ISSUE THREAD

**Issue by Bankst** [keepcalm/BukkitForge#186]
Running latest Bukkitforge in an FTB Direwolf20 server, and when using the "templist" command I get this output.  
2013-01-09 09:46:20 [INFO] [STDERR] org.bukkit.command.CommandException: Unhandled exception executing command 'templist' in plugin GroupManager v${GMVer} (${build.number}) (Phoenix)
2013-01-09 09:46:20 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
2013-01-09 09:46:20 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2013-01-09 09:46:20 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2013-01-09 09:46:20 [INFO] [STDERR]     at ho.al(DedicatedServer.java:309)
2013-01-09 09:46:20 [INFO] [STDERR]     at ho.r(DedicatedServer.java:271)
2013-01-09 09:46:20 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
2013-01-09 09:46:20 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-09 09:46:20 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-09 09:46:20 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-01-09 09:46:20 [INFO] [STDERR]     at org.anjocaido.groupmanager.GroupManager.onCommand(GroupManager.java:1605)
2013-01-09 09:46:20 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-01-09 09:46:20 [INFO] [STDERR]     ... 7 more

**Comment by SpoonsJTD** [comment]
I reproduced this with latest build.

**Comment by SpoonsJTD** [comment]
Is fixed if you use mirrors in your groupmanager config to 'alias' bukkit world names for forge world names.
