### ISSUE TITLE
[PlayerInteractEvent] causes NullPointerException

### ISSUE THREAD

**Issue by kenneaal** [keepcalm/BukkitForge#192]
2013-01-10 01:05:54 [SEVERE] [BukkitForge] Could not pass event PlayerInteractEvent to LogBlock v1.61
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:425)
        at net.minecraftforge.event.ASMEventHandler_109_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:28)
        at ir.a(ItemInWorldManager.java:159)
        at iv.a(NetServerHandler.java:509)
        at ei.a(SourceFile:46)
        at cg.b(TcpConnection.java:454)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at de.diddiz.LogBlock.listeners.ToolListener.onPlayerInteract(ToolListener.java:49)
        at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 20 more

**Comment by SpoonsJTD** [comment]
Please recheck this, may have been fixed with player object fix.

**Comment by SpoonsJTD** [comment]
No response.
