### ISSUE TITLE
BukkitForge-79

### ISSUE THREAD

**Issue by vasyacullin** [keepcalm/BukkitForge#194]
broken block
2013-01-10 05:50:26 [SEVERE] Encountered an unexpected exception NoClassDefFoundError
java.lang.NoClassDefFoundError: keepcalm/mods/blockbreak/EventFactory
    at ir.d(ItemInWorldManager.java:271)
    at ir.b(ItemInWorldManager.java:330)
    at ir.a(ItemInWorldManager.java:205)
    at iv.a(NetServerHandler.java:509)
    at ei.a(SourceFile:46)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.ClassNotFoundException: keepcalm.mods.blockbreak.EventFactory
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 14 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at net.minecraftforge.transformers.EventTransformer.transform(EventTransformer.java:29)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
    ... 16 more

**Comment by keepcalm** [comment]
Update, fixed
