### ISSUE TITLE
Exception at startup

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#2]
2012-12-04 09:00:42 [SEVERE] Encountered an unexpected exception t
t: Exception ticking world
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:663)
        at ho.r(DedicatedServer.java:252)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:494)
        at fy.run(SourceFile:856)
Caused by: java.lang.NoSuchMethodError: in.w()Ljava/lang/String;
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.getWorld(BukkitServer.ja$
        at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java$
        at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
        at org.bukkit.event.world.ChunkLoadEvent.<init>(ChunkLoadEvent.java:14)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkLoadEvent(F$
        at net.minecraftforge.event.ASMEventHandler_40_ForgeEventHandler_chunkL$
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java$
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at zs.c(Chunk.java:1025)
        at im.c(ChunkProviderServer.java:134)
        at im.d(ChunkProviderServer.java:150)
        at xv.e(World.java:496)
        at in.g(WorldServer.java:289)
        at in.b(WorldServer.java:138)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:657)
        ... 4 more

Running Server 1.4.5 with Forge Build 1.4.5-6.4.1.405

**Comment by Merbo** [comment]
It seems I have a similar issue.

**Comment by keepcalm** [comment]
Can you post the FML logs? It cut off the 5 crucial letters...

**Comment by keepcalm** [comment]
Although, I believe I have found the bug. It was a single line of code. Whoops. I'll fix it now.
