### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#20]
If i place the lastest jar in coremods, the server won´t start.

2012-12-15 01:45:47 [INFO] [ForgeModLoader] Forge Mod Loader version 4.5.2.459 for Minecraft 1.4.5 loading
2012-12-15 01:45:47 [INFO] [STDERR] Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
2012-12-15 01:45:47 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:175)
2012-12-15 01:45:47 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
2012-12-15 01:45:47 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
2012-12-15 01:45:47 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1369)
2012-12-15 01:45:47 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2012-12-15 01:45:47 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchLibraryManager.discoverCoreMods(RelaunchLibraryManager.java:317)
2012-12-15 01:45:47 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:102)
2012-12-15 01:45:47 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
2012-12-15 01:45:47 [INFO] [STDERR]     ... 3 more

**Comment by keepcalm** [comment]
The one in dist/ is broken. Many apologies. Fixing that now. (For future reference, if this happens and you're _desperate_ then add META-INF and bukkit_at.cfg into the jar, simple as that ;)
