### ISSUE TITLE
Error with build 82

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#201]
2013-01-10 23:53:19 [INFO] [STDOUT] WARNING: Internal task failed: 
2013-01-10 23:53:19 [INFO] [STDERR] java.lang.NullPointerException
2013-01-10 23:53:19 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.getName(BukkitPlayer.java:119)
2013-01-10 23:53:19 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.hashCode(BukkitPlayer.java:749)
2013-01-10 23:53:19 [INFO] [STDERR]     at java.util.WeakHashMap.hash(Unknown Source)
2013-01-10 23:53:19 [INFO] [STDERR]     at java.util.WeakHashMap.remove(Unknown Source)
2013-01-10 23:53:19 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.unsubscribeFromDefaultPerms(SimplePluginManager.java:680)
2013-01-10 23:53:19 [INFO] [STDERR]     at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:179)
2013-01-10 23:53:19 [INFO] [STDERR]     at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:153)
2013-01-10 23:53:19 [INFO] [STDERR]     at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:31)
2013-01-10 23:53:19 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:51)
2013-01-10 23:53:19 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:109)
2013-01-10 23:53:19 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:114)
2013-01-10 23:53:19 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.blockBreakSomehow(ForgeEventHandler.java:580)
2013-01-10 23:53:19 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_28_ForgeEventHandler_blockBreakSomehow_BlockDestroyEvent.invoke(.dynamic)
2013-01-10 23:53:19 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-01-10 23:53:19 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-01-10 23:53:19 [INFO] [STDERR]     at keepcalm.mods.events.ForgeEventHelper$1.run(ForgeEventHelper.java:156)
2013-01-10 23:53:19 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
2013-01-10 23:53:19 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:347)
2013-01-10 23:53:19 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:28)
2013-01-10 23:53:19 [INFO] [STDERR]     at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
2013-01-10 23:53:19 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
2013-01-10 23:53:19 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
2013-01-10 23:53:19 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:588)
2013-01-10 23:53:19 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-10 23:53:19 [INFO] [STDERR]     at fy.run(SourceFile:849)

**Comment by keepcalm** [comment]
Known, and irritating me beyond belief.

**Comment by SpoonsJTD** [comment]
Closing as dupe - captured in another issue.
