### ISSUE TITLE
2 Player on Server, than Server crashed

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#21]
When a second player on my server join crash the server

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 12/15/12 9:42 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: iq.h(F)Laob;
    at keepcalm.mods.bukkit.forgeHandler.PlayerUtilities.getTargetBlock(PlayerUtilities.java:17)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:220)
    at net.minecraftforge.event.ASMEventHandler_19_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
    at ir.a(ItemInWorldManager.java:378)
    at iv.a(NetServerHandler.java:525)
    at fl.a(SourceFile:58)
    at cg.b(TcpConnection.java:451)
    at iv.d(NetServerHandler.java:82)
    at iw.b(NetworkListenThread.java:55)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:704)
    at ho.r(DedicatedServer.java:252)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:600)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
    at fy.run(SourceFile:856)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.5
    Operating System: Linux (amd64) version 2.6.36.4-vs2.3.0.36.39-nc
    Java Version: 1.7.0_09, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 952955512 bytes (908 MB) / 1029046272 bytes (981 MB) up to 2863333376 bytes (2730 MB)
    JVM Flags: 2 total; -Xms1024M -Xmx3072M
    AABB Pool Size: 3979 (222824 bytes; 0 MB) allocated, 3791 (212296 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v7.23 FML v4.5.21.486 Minecraft Forge 6.4.1.436 26 mods loaded, 26 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Bukkit4Vanilla [Bukkit For Vanilla](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](bukkit4vanilla-1.4.5-2 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CustomSpawner [DrZhark's CustomSpawner](CustomMobSpawner 1.9.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MoCreatures [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v4.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_Lockit [Lockit](Lockit-0.0.6-1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MetallurgyCore [Metallurgy Core](Metallurgy Core 2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MetallurgyBase [Metallurgy Base](Metallurgy Base Metals 2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    MetallurgyNether [Metallurgy Nether](Metallurgy Nether Metals 2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCApple [Pam's HarvestCraft Apple](Pam's HarvestCraft - Apple 1.0 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCCorn [Pam's HarvestCraft Corn](Pam's HarvestCraft - Corn 1.0 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCCotton [Pam's HarvestCraft Cotton](Pam's HarvestCraft - Cotton 1.0 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCCucumber [Pam's HarvestCraft Cucumber](Pam's HarvestCraft - Cucumber 1.0 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCGrape [Pam's HarvestCraft Grape](Pam's HarvestCraft - Grape 1.0 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCLettuce [Pam's HarvestCraft Lettuce](Pam's HarvestCraft - Lettuce 1.0 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCOnion [Pam's HarvestCraft Onion](Pam's HarvestCraft - Onion 1.0 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCPeanut [Pam's HarvestCraft Peanut](Pam's HarvestCraft - Peanut 1.0 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCStrawberry [Pam's HarvestCraft Strawberry](Pam's HarvestCraft - Strawberry 1.0 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCTomato [Pam's HarvestCraft Tomato](Pam's HarvestCraft - Tomato 1.0 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PamHCBase [Pam's HarvestCraft Base](Pam's HarvestCraft Base 1.01 %28MC 1.4.5%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    weaponmod [Balkon's WeaponMod](Weaponmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Backpack [Backpack](backpack-1.5.4-1.4.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Bukkit4Vanilla Details: ~~NULL~~
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1359 (76104 bytes; 0 MB) allocated, 1277 (71512 bytes; 0 MB) used
    Player Count: 2 / 20; [iq['BlackwingDave'/249, l='world', x=-257.61, y=61.00, z=169.59], iq['Nefala'/255, l='world', x=-203.76, y=64.13, z=226.52]]
    Is Modded: Definitely; Server brand changed to 'forge,fml'
    Type: Dedicated Server (map_server.txt)

**Comment by Wolftein** [comment]
Are you downloading the one from https://github.com/keepcalm/BukkitForge/tree/master/dist

**Comment by Thornas88** [comment]
the server is running but when they cut a tree, for example, the server shows the message "End of Stream"

and as op have i no permissions to bukkit commands

The Serverlog

2012-12-15 17:32:28 [WARNING] [BukkitForge] Server permissions file permissions.yml is not valid YAML.
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadCustomPermissions(BukkitServer.java:932)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:888)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:241)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:41)
    at java.lang.Thread.run(Unknown Source)
2012-12-15 17:32:28 [INFO] [BukkitForge] Loaded plugins: 
2012-12-15 17:32:46 [WARNING] [Minecraft] Can't keep up! Did the system time change, or is the server overloaded?
2012-12-15 17:33:01 [WARNING] [Minecraft] Can't keep up! Did the system time change, or is the server overloaded?
2012-12-15 17:33:44 [INFO] [Minecraft] /127.0.0.1:53560 lost connection
2012-12-15 17:33:51 [FINEST] [ForgeModLoader] Received valid FML login packet from /127.0.0.1:53562
2012-12-15 17:33:52 [INFO] [Minecraft] User BlackwingDave connecting with mods []
2012-12-15 17:33:52 [INFO] [ForgeModLoader] User BlackwingDave connecting with mods []
2012-12-15 17:33:52 [INFO] [Minecraft] BlackwingDave[/127.0.0.1:53562] logged in with entity id 289 at (-505.0230754215264, 72.0, 251.55782123078995)
2012-12-15 17:33:54 [WARNING] [Minecraft] Can't keep up! Did the system time change, or is the server overloaded?
2012-12-15 17:34:16 [WARNING] [Minecraft] Can't keep up! Did the system time change, or is the server overloaded?
2012-12-15 17:34:20 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 289
java.lang.NullPointerException
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:206)
    at net.minecraftforge.event.ASMEventHandler_14_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
    at ir.a(ItemInWorldManager.java:147)
    at iv.a(NetServerHandler.java:445)
    at ej.a(SourceFile:46)
    at cg.b(TcpConnection.java:451)
    at iv.d(NetServerHandler.java:82)
    at iw.b(NetworkListenThread.java:55)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:704)
    at ho.r(DedicatedServer.java:252)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:600)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
    at fy.run(SourceFile:856)
2012-12-15 17:34:20 [WARNING] [Minecraft] Failed to handle packet for BlackwingDave/127.0.0.1: java.lang.NullPointerException
java.lang.NullPointerException
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:206)
    at net.minecraftforge.event.ASMEventHandler_14_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
    at ir.a(ItemInWorldManager.java:147)
    at iv.a(NetServerHandler.java:445)
    at ej.a(SourceFile:46)
    at cg.b(TcpConnection.java:451)
    at iv.d(NetServerHandler.java:82)
    at iw.b(NetworkListenThread.java:55)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:704)
    at ho.r(DedicatedServer.java:252)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:600)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
    at fy.run(SourceFile:856)

**Comment by keepcalm** [comment]
It's all fixed! You can find a new version at https://github.com/keepcalm/BukkitForge/tree/master/dist, which fixes this issue.
