### ISSUE TITLE
Won't work with DivineRPG

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#22]
I found the mod that is causing all my errors. DivineRPG

2012-12-15 12:14:53 [INFO] [STDERR] java.lang.ExceptionInInitializerError
2012-12-15 12:14:53 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:238)
2012-12-15 12:14:53 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_41_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
2012-12-15 12:14:53 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2012-12-15 12:14:53 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2012-12-15 12:14:53 [INFO] [STDERR]     at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
2012-12-15 12:14:53 [INFO] [STDERR]     at ir.a(ItemInWorldManager.java:378)
2012-12-15 12:14:53 [INFO] [STDERR]     at iv.a(NetServerHandler.java:525)
2012-12-15 12:14:53 [INFO] [STDERR]     at net.smart.moving.playerapi.NetServerHandler.a(NetServerHandler.java:39)
2012-12-15 12:14:53 [INFO] [STDERR]     at fl.a(SourceFile:58)
2012-12-15 12:14:53 [INFO] [STDERR]     at cg.b(TcpConnection.java:451)
2012-12-15 12:14:53 [INFO] [STDERR]     at iv.d(NetServerHandler.java:82)
2012-12-15 12:14:53 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:55)
2012-12-15 12:14:53 [INFO] [STDERR]     at ht.b(SourceFile:30)
2012-12-15 12:14:53 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
2012-12-15 12:14:53 [INFO] [STDERR]     at ho.r(DedicatedServer.java:252)
2012-12-15 12:14:53 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
2012-12-15 12:14:53 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
2012-12-15 12:14:53 [INFO] [STDERR]     at fy.run(SourceFile:856)
2012-12-15 12:14:53 [INFO] [STDERR] Caused by: java.lang.IllegalArgumentException: Missing Biome mapping for BiomeGenBase[24] - The Biome missing is Dravite
2012-12-15 12:14:53 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.block.BukkitBlock.<clinit>(BukkitBlock.java:448)
2012-12-15 12:14:53 [INFO] [STDERR]     ... 18 more
2012-12-15 12:14:53 [SEVERE] [Minecraft] Encountered an unexpected exception ExceptionInInitializerError

After that

2012-12-15 12:14:53 [SEVERE] [Minecraft] Encountered an unexpected exception ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:238)
        at net.minecraftforge.event.ASMEventHandler_41_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
        at ir.a(ItemInWorldManager.java:378)
        at iv.a(NetServerHandler.java:525)
        at net.smart.moving.playerapi.NetServerHandler.a(NetServerHandler.java:39)
        at fl.a(SourceFile:58)
        at cg.b(TcpConnection.java:451)
        at iv.d(NetServerHandler.java:82)
        at iw.b(NetworkListenThread.java:55)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
        at ho.r(DedicatedServer.java:252)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
        at fy.run(SourceFile:856)

**Comment by keepcalm** [comment]
This is a hard bug to fix, I need to work out how mods like EBXL add biomes, and how I can detect that. But I'll work on it.

**Comment by keepcalm** [comment]
... github doesn't close when I say 'solved'? Grr...

**Comment by agaricusb** [comment]
Maybe you can do something like this? https://github.com/MinecraftPortCentral/CraftBukkit/commit/b77dd9d9eef8204848c99dde7f153f42ca261b7c

**Comment by keepcalm** [comment]
thanks for pointing that out, that's a good idea :D
