### ISSUE TITLE
[PlayerMoveEvent] LoginSecurity

### ISSUE THREAD

**Issue by Benet** [keepcalm/BukkitForge#232]
2013-01-13 13:31:16 [SEVERE] [BukkitForge] Could not pass event PlayerMoveEvent to LoginSecurity v1.6.9.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:429)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerMove(ForgeEventHandler.java:700)
    at net.minecraftforge.event.ASMEventHandler_81_ForgeEventHandler_onPlayerMove_PlayerMoveEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at keepcalm.mods.events.ForgeEventHelper.onPlayerMove(ForgeEventHelper.java:192)
    at iv.a(NetServerHandler.java)
    at net.smart.moving.playerapi.NetServerHandler.a(NetServerHandler.java:24)
    at eb.a(SourceFile:136)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:705)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:601)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitLivingEntity.hasPotionEffect(BukkitLivingEntity.java:248)
    at me.lenis0012.ls.lsLogin.onPlayerMove(lsLogin.java:115)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    ... 20 more

http://dev.bukkit.org/server-mods/loginsecurity/

Plugin is working for me. It registers users and forces them to login, but creates infinite spam my log file is about 20mb !

**Comment by rom3ox** [comment]
i believe that playermove event its not implemented yet because afk, and enter and exit messages for a lot of plugins arent working yet. 

I hope it gets implemented soon because a lot of plugins use that event.
