### ISSUE TITLE
[Transporter] error

### ISSUE THREAD

**Issue by jakimfett** [keepcalm/BukkitForge#238]
The Transporter plugin throws a "compatibility class not found" error when loading "loading compatibility class com.frdfsnlght.transporter.compatibility.VukkitAPIClass"

Running:
Minecraft Server 1.4.7
Forge "Build 6.6.0.499: 2013-01-12 20:51:13 for MC: 1.4.7" 
BukkitForge Build #30 "BukkitForge-1.4.7-30.jar"
Transporter "R: v8.11 for CB 1.4.6-R0.3 Jan 03, 2013"

Full ForgeModLoader log below:

```
2013-01-13 11:20:37 [INFO] [ForgeModLoader] Forge Mod Loader version 4.7.10.524 for Minecraft 1.4.7 loading
2013-01-13 11:20:38 [INFO] [STDOUT] Adding Accesstransformer map: bukkit_at.cfg
2013-01-13 11:20:38 [INFO] [ForgeModLoader] Found valid fingerprint for Minecraft Forge. Certificate fingerprint de4cf8a3f3bc15635810044c39240bf96804ea7d
2013-01-13 11:20:38 [INFO] [STDOUT] Found global block break call: a(Lyc;IIIII)V
2013-01-13 11:20:38 [INFO] [STDOUT] Inserted instructions!
2013-01-13 11:20:38 [INFO] [STDOUT] Found target method: n(Lyc;III)V! Looking for landmark...
2013-01-13 11:20:38 [INFO] [STDOUT] Found insertion point - GETSTATIC followed by IF_ACMPEQ!
2013-01-13 11:20:38 [INFO] [STDOUT] Does bb equal null?
2013-01-13 11:20:38 [INFO] [STDOUT] Found landmark! Inserting code...
2013-01-13 11:20:38 [INFO] [STDOUT] Instructions have been compiled, adding to bytecode...
2013-01-13 11:20:38 [INFO] [STDOUT] Finished patching BlockDispenser!
2013-01-13 11:20:38 [INFO] [STDOUT] Transforming up...
2013-01-13 11:20:38 [INFO] [STDOUT] Inspecting 70 methods...
2013-01-13 11:20:38 [INFO] [STDOUT] Found matching constructor method in Item: <init>(I)V!
2013-01-13 11:20:38 [INFO] [STDOUT] Finished patching item-register method into BukkitForge!
2013-01-13 11:20:39 [INFO] [STDOUT] 210 recipes
2013-01-13 11:20:39 [INFO] [STDOUT] 27 achievements
2013-01-13 11:20:39 [INFO] [Minecraft] Starting minecraft server version 1.4.7
2013-01-13 11:20:39 [INFO] [ForgeModLoader] Attempting early MinecraftForge initialization
2013-01-13 11:20:39 [INFO] [STDOUT] MinecraftForge v6.6.0.499 Initialized
2013-01-13 11:20:39 [INFO] [ForgeModLoader] MinecraftForge v6.6.0.499 Initialized
2013-01-13 11:20:39 [INFO] [STDOUT] Replaced 84 ore recipies
2013-01-13 11:20:39 [INFO] [ForgeModLoader] Completed early MinecraftForge initialization
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Building injected Mod Containers [cpw.mods.fml.common.FMLDummyContainer, net.minecraftforge.common.ForgeDummyContainer]
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Attempting to load mods contained in the minecraft jar file and associated classes
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Found a minecraft related file at C:\Users\jakimfett\Downloads\server\minecraft_server.jar, examining for mod candidates
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Found a minecraft related file at C:\Users\jakimfett\Downloads\server\coremods\BukkitForge-1.4.7-30.jar, examining for mod candidates
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\argo-2.25.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\guava-12.0.1.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\asm-all-4.0.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\bcprov-jdk15on-147.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\commons-lang-2.3.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\ebean-2.8.1.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\gson-2.1-cb.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\sqlite-jdbc-3.7.2.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\snakeyaml-1.9.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\jansi-1.9.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\guava10-renamed.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Skipping known library file C:\Users\jakimfett\Downloads\server\lib\mysql-connector-java-5.1.14.jar
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Minecraft jar mods loaded successfully
2013-01-13 11:20:39 [INFO] [ForgeModLoader] Searching C:\Users\jakimfett\Downloads\server\mods for mods
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Examining file minecraft_server.jar for potential mods
2013-01-13 11:20:39 [FINE] [ForgeModLoader] The mod container minecraft_server.jar appears to be missing an mcmod.info file
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Examining file BukkitForge-1.4.7-30.jar for potential mods
2013-01-13 11:20:39 [FINE] [ForgeModLoader] The mod container BukkitForge-1.4.7-30.jar appears to be missing an mcmod.info file
2013-01-13 11:20:39 [FINE] [ForgeModLoader] Identified an FMLMod type mod keepcalm.mods.bukkit.BukkitContainer
2013-01-13 11:20:39 [FINEST] [ForgeModLoader] Parsed dependency info : [] [] []
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Identified an FMLMod type mod keepcalm.mods.events.BlockBreakContainer
2013-01-13 11:20:40 [FINEST] [ForgeModLoader] Parsed dependency info : [] [] []
2013-01-13 11:20:40 [INFO] [ForgeModLoader] Forge Mod Loader has identified 5 mods to load
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Received a system property request ''
2013-01-13 11:20:40 [FINE] [ForgeModLoader] System property request managing the state of 0 mods
2013-01-13 11:20:40 [FINE] [ForgeModLoader] After merging, found state information for 0 mods
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Activating mod mcp
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Activating mod FML
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Activating mod Forge
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Enabling mod BukkitForge
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Activating mod BukkitForge
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Enabling mod BlockBreak
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Activating mod BlockBreak
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Verifying mod requirements are satisfied
2013-01-13 11:20:40 [FINE] [ForgeModLoader] All mod requirements are satisfied
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Sorting mods into an ordered list
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Mod sorting completed successfully
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Mod sorting data:
2013-01-13 11:20:40 [FINE] [ForgeModLoader]     BukkitForge(BukkitForge:1.4.6-0): BukkitForge-1.4.7-30.jar ()
2013-01-13 11:20:40 [FINE] [ForgeModLoader]     BlockBreak(Block Break Event:1.4.6-0): BukkitForge-1.4.7-30.jar ()
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLConstructionEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLConstructionEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLConstructionEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLConstructionEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLConstructionEvent to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLConstructionEvent to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLConstructionEvent to mod BukkitForge
2013-01-13 11:20:40 [FINEST] [ForgeModLoader] Testing mod BukkitForge to verify it accepts its own version in a remote connection
2013-01-13 11:20:40 [FINEST] [ForgeModLoader] The mod BukkitForge accepts its own version (1.4.6-0)
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Attempting to inject @SidedProxy classes into BukkitForge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLConstructionEvent to mod BukkitForge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLConstructionEvent to mod BlockBreak
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Attempting to inject @SidedProxy classes into BlockBreak
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLConstructionEvent to mod BlockBreak
2013-01-13 11:20:40 [FINE] [ForgeModLoader] Mod signature data:
2013-01-13 11:20:40 [FINE] [ForgeModLoader]     mcp(Minecraft Coder Pack:7.26): minecraft.jar (NO VALID CERTIFICATE FOUND)
2013-01-13 11:20:40 [FINE] [ForgeModLoader]     FML(Forge Mod Loader:4.7.10.524): coremods (de4cf8a3f3bc15635810044c39240bf96804ea7d)
2013-01-13 11:20:40 [FINE] [ForgeModLoader]     Forge(Minecraft Forge:6.6.0.499): coremods (NO VALID CERTIFICATE FOUND)
2013-01-13 11:20:40 [FINE] [ForgeModLoader]     BukkitForge(BukkitForge:1.4.6-0): BukkitForge-1.4.7-30.jar (NO VALID CERTIFICATE FOUND)
2013-01-13 11:20:40 [FINE] [ForgeModLoader]     BlockBreak(Block Break Event:1.4.6-0): BukkitForge-1.4.7-30.jar (NO VALID CERTIFICATE FOUND)
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLPreInitializationEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLPreInitializationEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLPreInitializationEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLPreInitializationEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLPreInitializationEvent to mod Forge
2013-01-13 11:20:40 [INFO] [ForgeModLoader] Configured a dormant chunk cache size of 0
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLPreInitializationEvent to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLPreInitializationEvent to mod BukkitForge
2013-01-13 11:20:40 [INFO] [BukkitForge] Initializing configuration...
2013-01-13 11:20:40 [INFO] [BukkitForge] Set UUID to 1358103739934-683632060-1.4.6
2013-01-13 11:20:40 [INFO] [STDOUT] Successfully loaded users: 
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLPreInitializationEvent to mod BukkitForge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLPreInitializationEvent to mod BlockBreak
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLPreInitializationEvent to mod BlockBreak
2013-01-13 11:20:40 [INFO] [Minecraft] Loading properties
2013-01-13 11:20:40 [INFO] [Minecraft] Default game type: SURVIVAL
2013-01-13 11:20:40 [INFO] [Minecraft] Generating keypair
2013-01-13 11:20:40 [INFO] [Minecraft] Starting Minecraft server on *:25565
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLInitializationEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLInitializationEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLInitializationEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLInitializationEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLInitializationEvent to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLInitializationEvent to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLInitializationEvent to mod BukkitForge
2013-01-13 11:20:40 [INFO] [STDOUT] Class Transformation running on ItemInWorldManager...
2013-01-13 11:20:40 [INFO] [STDOUT] Found target method d(III)Z! Searching for landmarks...
2013-01-13 11:20:40 [INFO] [STDOUT] Found Block object ASTORE Node at 10
2013-01-13 11:20:40 [INFO] [STDOUT] Block object is in local object 4
2013-01-13 11:20:40 [INFO] [STDOUT] Found metadata local variable ISTORE Node at 19
2013-01-13 11:20:40 [INFO] [STDOUT] Metadata is in local variable 5
2013-01-13 11:20:40 [INFO] [STDOUT] Found IFNULL Node at 23
2013-01-13 11:20:40 [INFO] [STDOUT] Found ALOAD Node at offset 3 from IFNULL Node
2013-01-13 11:20:40 [INFO] [STDOUT] Patching method ir/d(III)Z...
2013-01-13 11:20:40 [INFO] [STDOUT] Method ir/d(III)Z at index 25
2013-01-13 11:20:40 [INFO] [STDOUT] Patching Complete!
2013-01-13 11:20:40 [INFO] [STDOUT] Found target for ItemInWorldManager transformation: a()V! Searching for landmarks...
2013-01-13 11:20:40 [INFO] [STDOUT] Found landmark: RETURN, searching for previous landmark...
2013-01-13 11:20:40 [INFO] [STDOUT] Found IF_ICMPEQ at index 227 to R, which is at 251. Inserting function call after this...
2013-01-13 11:20:40 [INFO] [STDOUT] Will insert code at: 228
2013-01-13 11:20:40 [INFO] [STDOUT] Using desc: (Lir;)V
2013-01-13 11:20:40 [INFO] [STDOUT] Finished compiling instruction nodes, inserting new instructions... at 228
2013-01-13 11:20:40 [INFO] [STDOUT] Finished patching ItemInWorldManager! The game will now continue!
2013-01-13 11:20:40 [INFO] [STDOUT] Found target method: a(Leb;)V! Inserting code...
2013-01-13 11:20:40 [INFO] [BukkitForge] Complete! Registering handlers...
2013-01-13 11:20:40 [INFO] [STDOUT] Class name matched creeper...
2013-01-13 11:20:40 [INFO] [STDOUT] Found insertion point! inserting code!
2013-01-13 11:20:40 [INFO] [STDOUT] Transforming EntitySheep...
2013-01-13 11:20:40 [INFO] [BukkitForge] Done!
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLInitializationEvent to mod BukkitForge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLInitializationEvent to mod BlockBreak
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLInitializationEvent to mod BlockBreak
2013-01-13 11:20:40 [FINEST] [ForgeModLoader] Attempting to deliver 0 IMC messages to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event IMCEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event IMCEvent to mod mcp
2013-01-13 11:20:40 [FINEST] [ForgeModLoader] Attempting to deliver 0 IMC messages to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event IMCEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event IMCEvent to mod FML
2013-01-13 11:20:40 [FINEST] [ForgeModLoader] Attempting to deliver 0 IMC messages to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event IMCEvent to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event IMCEvent to mod Forge
2013-01-13 11:20:40 [FINEST] [ForgeModLoader] Attempting to deliver 0 IMC messages to mod BukkitForge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event IMCEvent to mod BukkitForge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event IMCEvent to mod BukkitForge
2013-01-13 11:20:40 [FINEST] [ForgeModLoader] Attempting to deliver 0 IMC messages to mod BlockBreak
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event IMCEvent to mod BlockBreak
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event IMCEvent to mod BlockBreak
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLPostInitializationEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLPostInitializationEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLPostInitializationEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLPostInitializationEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLPostInitializationEvent to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLPostInitializationEvent to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLPostInitializationEvent to mod BukkitForge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLPostInitializationEvent to mod BukkitForge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLPostInitializationEvent to mod BlockBreak
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLPostInitializationEvent to mod BlockBreak
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLLoadCompleteEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLLoadCompleteEvent to mod mcp
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLLoadCompleteEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLLoadCompleteEvent to mod FML
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLLoadCompleteEvent to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLLoadCompleteEvent to mod Forge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLLoadCompleteEvent to mod BukkitForge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLLoadCompleteEvent to mod BukkitForge
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sending event FMLLoadCompleteEvent to mod BlockBreak
2013-01-13 11:20:40 [FINER] [ForgeModLoader] Sent event FMLLoadCompleteEvent to mod BlockBreak
2013-01-13 11:20:40 [INFO] [ForgeModLoader] Forge Mod Loader has successfully loaded 5 mods
2013-01-13 11:20:41 [INFO] [Minecraft] Preparing level "world"
2013-01-13 11:20:41 [FINE] [ForgeModLoader] The difference set is equal
2013-01-13 11:20:41 [INFO] [ForgeModLoader] Loading dimension 0 (world) (ho@1c385516)
2013-01-13 11:20:41 [INFO] [ForgeModLoader] Loading dimension 1 (world) (ho@1c385516)
2013-01-13 11:20:41 [INFO] [ForgeModLoader] Loading dimension -1 (world) (ho@1c385516)
2013-01-13 11:20:41 [INFO] [Minecraft] Preparing start region for level 0
2013-01-13 11:20:41 [INFO] [Minecraft] Done (0.805s)! For help, type "help" or "?"
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sending event FMLServerStartingEvent to mod mcp
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sent event FMLServerStartingEvent to mod mcp
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sending event FMLServerStartingEvent to mod FML
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sent event FMLServerStartingEvent to mod FML
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sending event FMLServerStartingEvent to mod Forge
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sent event FMLServerStartingEvent to mod Forge
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sending event FMLServerStartingEvent to mod BukkitForge
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sent event FMLServerStartingEvent to mod BukkitForge
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sending event FMLServerStartingEvent to mod BlockBreak
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sent event FMLServerStartingEvent to mod BlockBreak
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sending event FMLServerStartedEvent to mod mcp
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sent event FMLServerStartedEvent to mod mcp
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sending event FMLServerStartedEvent to mod FML
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sent event FMLServerStartedEvent to mod FML
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sending event FMLServerStartedEvent to mod Forge
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sent event FMLServerStartedEvent to mod Forge
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sending event FMLServerStartedEvent to mod BukkitForge
2013-01-13 11:20:41 [INFO] [STDOUT] iq['[Mod]'/158, l='world', x=114.50, y=65.62, z=260.50]
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sent event FMLServerStartedEvent to mod BukkitForge
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sending event FMLServerStartedEvent to mod BlockBreak
2013-01-13 11:20:41 [FINER] [ForgeModLoader] Sent event FMLServerStartedEvent to mod BlockBreak
2013-01-13 11:20:42 [INFO] [STDOUT] IS THE INSTANCE NULL? NO
2013-01-13 11:20:42 [INFO] [BukkitForge] Bukkit API for Vanilla, version 1.4.5-R0.2 starting up...
2013-01-13 11:20:42 [INFO] [STDOUT] Hello there, my parent is cpw.mods.fml.relauncher.RelaunchClassLoader
2013-01-13 11:20:42 [INFO] [BukkitForge] This server is running BukkitForge version git-BukkitForge-1.4.5-R1.0-b3000 jnks (Really: BukkitForge for MC 1.4.7) (Implementing API version 1.4.5-R0.2)
2013-01-13 11:20:42 [INFO] [BukkitForge] Completing load...
2013-01-13 11:20:42 [INFO] [BukkitForge] Plugins are being loaded...
2013-01-13 11:20:42 [INFO] [com.frdfsnlght.transporter.Transporter] [Transporter] Loading Transporter v8.11
2013-01-13 11:20:42 [INFO] [BukkitForge] Loading PostWorld plugins...
2013-01-13 11:20:42 [INFO] [com.frdfsnlght.transporter.Transporter] [Transporter] Enabling Transporter v8.11
2013-01-13 11:20:42 [INFO] [Minecraft] [Transporter] loading compatibility class com.frdfsnlght.transporter.compatibility.VukkitAPIClass
2013-01-13 11:20:42 [SEVERE] [Minecraft] [Transporter] compatibility class not found
2013-01-13 11:20:42 [SEVERE] [Minecraft] [Transporter] unable to find compatible server version, plugin is disabled
2013-01-13 11:20:42 [SEVERE] [BukkitForge] Error occurred while enabling Transporter v8.11 (Is it up to date?)
java.lang.NullPointerException
    at com.frdfsnlght.transporter.Config.getExportedGatesFile(Config.java:480)
    at com.frdfsnlght.transporter.Markers.exportJSON(Markers.java:123)
    at com.frdfsnlght.transporter.Markers.update(Markers.java:53)
    at com.frdfsnlght.transporter.Gates.save(Gates.java:95)
    at com.frdfsnlght.transporter.Transporter.onDisable(Transporter.java:167)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
    at com.frdfsnlght.transporter.Transporter.onEnable(Transporter.java:64)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:459)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:952)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:936)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:273)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
    at java.lang.Thread.run(Unknown Source)
2013-01-13 11:20:42 [INFO] [BukkitForge] Going to load perms file: permissions.yml
2013-01-13 11:20:42 [INFO] [BukkitForge] Server permissions file permissions.yml is empty, ignoring it
2013-01-13 11:20:42 [INFO] [BukkitForge] Loaded plugins: 
2013-01-13 11:20:42 [INFO] [BukkitForge] Transporter- Enabled: false
```

**Comment by keepcalm** [comment]
Try with latest builds, it might be fixed.

**Comment by jakimfett** [comment]
With Forge version 4.7.10.524 for Minecraft 1.4.7 and BukkitForge build #47 (Jan 19, 2013 6:35:59 AM), I'm still getting the same error, where compatibility class "com.frdfsnlght.transporter.compatibility.VukkitAPIClass" is not found.

```
2013-01-18 22:56:48 [INFO] [BukkitForge] This server is running CraftBukkit version git-BukkitForge-1.4.5-R1.0-b3000 jnks (Really: BukkitForge for MC 1.4.7) (Implementing API version 1.4.5-R0.2)
2013-01-18 22:56:48 [INFO] [BukkitForge] Completing load...
2013-01-18 22:56:48 [INFO] [BukkitForge] Plugins are being loaded...
2013-01-18 22:56:48 [INFO] [com.frdfsnlght.transporter.Transporter] [Transporter] Loading Transporter v8.11
2013-01-18 22:56:48 [INFO] [BukkitForge] Loading PostWorld plugins...
2013-01-18 22:56:48 [INFO] [com.frdfsnlght.transporter.Transporter] [Transporter] Enabling Transporter v8.11
2013-01-18 22:56:48 [INFO] [Minecraft] [Transporter] loading compatibility class com.frdfsnlght.transporter.compatibility.VukkitAPIClass
2013-01-18 22:56:48 [SEVERE] [Minecraft] [Transporter] compatibility class not found
2013-01-18 22:56:48 [SEVERE] [Minecraft] [Transporter] unable to find compatible server version, plugin is disabled
2013-01-18 22:56:48 [SEVERE] [BukkitForge] Error occurred while enabling Transporter v8.11 (Is it up to date?)
java.lang.NullPointerException
    at com.frdfsnlght.transporter.Config.getExportedGatesFile(Config.java:480)
    at com.frdfsnlght.transporter.Markers.exportJSON(Markers.java:123)
    at com.frdfsnlght.transporter.Markers.update(Markers.java:53)
    at com.frdfsnlght.transporter.Gates.save(Gates.java:95)
    at com.frdfsnlght.transporter.Transporter.onDisable(Transporter.java:167)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
    at com.frdfsnlght.transporter.Transporter.onEnable(Transporter.java:64)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:391)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:956)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:940)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:277)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Unknown Source)
2013-01-18 22:56:48 [INFO] [BukkitForge] Going to load perms file: permissions.yml
2013-01-18 22:56:48 [INFO] [BukkitForge] Server permissions file permissions.yml is empty, ignoring it
2013-01-18 22:56:48 [INFO] [BukkitForge] Loaded plugins: 
2013-01-18 22:56:48 [INFO] [BukkitForge] Transporter- Enabled: false
```

**Comment by alexbegt** [comment]
I have a working one but just one error in it

**Comment by jakimfett** [comment]
What's the error? And by "working one", do you mean a BukkitForge build working with Transporter?

**Comment by MichaelDanCurtis** [comment]
This is still not working

Minecraft Server 1.4.7
BukkitForge #110
Transporter v 8.12

2013-01-25 17:28:21 [INFO] [Minecraft] [Transporter] loading compatibility class com.frdfsnlght.transporter.compatibility.VukkitAPIClass
2013-01-25 17:28:21 [SEVERE] [Minecraft] [Transporter] compatibility class not found
2013-01-25 17:28:21 [SEVERE] [Minecraft] [Transporter] unable to find compatible server version, plugin is disabled

that is all, thank you for your hard work

**Comment by SpoonsJTD** [comment]
This appears to be a compatibility check. See if there is a way to disable compatibility check or ask the author to make it configurable.

**Comment by Brexman** [comment]
Was there a solution to this?
I am having the same problem. -_-
