### ISSUE TITLE
[BungeeCord] Issue

### ISSUE THREAD

**Issue by charlieTheBotDev** [keepcalm/BukkitForge#239]
My friend is setting up BungeeCord so that we have a central server hub to serve our 3 servers (1 Direwolf, 2 Bukkit).

We have the config all set up right but when we try to join from the hub it doesn't let us and throws this in the forge log:

2013-01-14 03:43:17 [FINEST] [ForgeModLoader] Received valid FML login packet from /127.0.0.1:49509
2013-01-14 03:43:47 [INFO] [STDERR] java.net.SocketTimeoutException: Read timed out
2013-01-14 03:43:47 [INFO] [STDERR]     at java.net.SocketInputStream.socketRead0(Native Method)
2013-01-14 03:43:47 [INFO] [STDERR]     at java.net.SocketInputStream.read(SocketInputStream.java:150)
2013-01-14 03:43:47 [INFO] [STDERR]     at java.net.SocketInputStream.read(SocketInputStream.java:121)
2013-01-14 03:43:47 [INFO] [STDERR]     at java.io.FilterInputStream.read(FilterInputStream.java:133)
2013-01-14 03:43:47 [INFO] [STDERR]     at org.bouncycastle.crypto.io.CipherInputStream.nextChunk(Unknown Source)
2013-01-14 03:43:47 [INFO] [STDERR]     at org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source)
2013-01-14 03:43:47 [INFO] [STDERR]     at java.io.FilterInputStream.read(FilterInputStream.java:83)
2013-01-14 03:43:47 [INFO] [STDERR]     at ef.a(Packet.java:142)
2013-01-14 03:43:47 [INFO] [STDERR]     at cg.i(TcpConnection.java:320)
2013-01-14 03:43:47 [INFO] [STDERR]     at cg.c(TcpConnection.java:540)
2013-01-14 03:43:47 [INFO] [STDERR]     at ch.run(SourceFile:93)
2013-01-14 03:43:47 [INFO] [Minecraft] Chazdude42 [/127.0.0.1:49509] lost connection

Is there any chance to get this working or is it doomed to never work with a BukkitForge server?

**Comment by keepcalm** [comment]
Check your server - the network is failing:

> 2013-01-14 03:43:47 [INFO] [STDERR] java.net.SocketTimeoutException: Read timed out

**Comment by charlieTheBotDev** [comment]
Apparently BungeeCord doesn't have Forge capability atm due to RedPower2 using a custom packet or something (https://github.com/ElasticPortalSuite/BungeeCord/issues/111).

Although, in theory this should handle the data the same way as bukkit would so this is possibly something you could look at. I'll let you decide I guess as you're the plugin dev(s) :P

**Comment by SpoonsJTD** [comment]
Checked out the thread. If MD-5 can't fix it, we will have no hope. :)

**Comment by charlieTheBotDev** [comment]
Lol. Looks like he is working at it. It just looks like people using non-standard packets and stuff that is screwing it over for the forge side
