### ISSUE TITLE
I cut leaves than i became "End Of Stream"

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#24]
the server is running but when they cut a leaves, for example, the server shows the message "End of Stream"

and as op have i no permissions to bukkit commands

The Serverlog

2012-12-15 17:32:28 [WARNING] [BukkitForge] Server permissions file permissions.yml is not valid YAML.
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadCustomPermissions(BukkitServer.java:932)
at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:888)
at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.(BukkitServer.java:241)
at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:41)
at java.lang.Thread.run(Unknown Source)
2012-12-15 17:32:28 [INFO] [BukkitForge] Loaded plugins: 
2012-12-15 17:32:46 [WARNING] [Minecraft] Can't keep up! Did the system time change, or is the server overloaded?
2012-12-15 17:33:01 [WARNING] [Minecraft] Can't keep up! Did the system time change, or is the server overloaded?
2012-12-15 17:33:44 [INFO] [Minecraft] /127.0.0.1:53560 lost connection
2012-12-15 17:33:51 [FINEST] [ForgeModLoader] Received valid FML login packet from /127.0.0.1:53562
2012-12-15 17:33:52 [INFO] [Minecraft] User BlackwingDave connecting with mods []
2012-12-15 17:33:52 [INFO] [ForgeModLoader] User BlackwingDave connecting with mods []
2012-12-15 17:33:52 [INFO] [Minecraft] BlackwingDave[/127.0.0.1:53562] logged in with entity id 289 at (-505.0230754215264, 72.0, 251.55782123078995)
2012-12-15 17:33:54 [WARNING] [Minecraft] Can't keep up! Did the system time change, or is the server overloaded?
2012-12-15 17:34:16 [WARNING] [Minecraft] Can't keep up! Did the system time change, or is the server overloaded?
2012-12-15 17:34:20 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 289
java.lang.NullPointerException
at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:206)
at net.minecraftforge.event.ASMEventHandler_14_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
at net.minecraftforge.event.EventBus.post(EventBus.java:103)
at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
at ir.a(ItemInWorldManager.java:147)
at iv.a(NetServerHandler.java:445)
at ej.a(SourceFile:46)
at cg.b(TcpConnection.java:451)
at iv.d(NetServerHandler.java:82)
at iw.b(NetworkListenThread.java:55)
at ht.b(SourceFile:30)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:704)
at ho.r(DedicatedServer.java:252)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:600)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
at fy.run(SourceFile:856)
2012-12-15 17:34:20 [WARNING] [Minecraft] Failed to handle packet for BlackwingDave/127.0.0.1: java.lang.NullPointerException
java.lang.NullPointerException
at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerSaysHai(ForgeEventHandler.java:206)
at net.minecraftforge.event.ASMEventHandler_14_ForgeEventHandler_playerSaysHai_PlayerInteractEvent.invoke(.dynamic)
at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
at net.minecraftforge.event.EventBus.post(EventBus.java:103)
at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:25)
at ir.a(ItemInWorldManager.java:147)
at iv.a(NetServerHandler.java:445)
at ej.a(SourceFile:46)
at cg.b(TcpConnection.java:451)
at iv.d(NetServerHandler.java:82)
at iw.b(NetworkListenThread.java:55)
at ht.b(SourceFile:30)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:704)
at ho.r(DedicatedServer.java:252)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:600)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
at fy.run(SourceFile:856)

**Comment by keepcalm** [comment]
can you post ForgeModLoader-server-0.log?
