### ISSUE TITLE
[PlayerSleepInBedEvent]

### ISSUE THREAD

**Issue by voxelhelp** [keepcalm/BukkitForge#256]
I can't sleep only with bukkitforge coremod enabled(without plugins)

Current error was at 1.4.6, now i've updated to 1.4.7 and latest forge *99 (don't remember) and it's still there.

Just clicking at a bed making my local singleplayer server shutdown with error.

---- Minecraft Crash Report ----
// There are four lights!

Time: 16.01.13 12:40
Description: Exception in world tick

java.lang.ClassCastException: ays cannot be cast to iq
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.playerGoToSleep(ForgeEventHandler.java:365)
    at net.minecraftforge.event.ASMEventHandler_45_ForgeEventHandler_playerGoToSleep_PlayerSleepInBedEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at qx.a(EntityPlayer.java:1438)
    at ayh.a(NetClientHandler.java:873)
    at dk.a(SourceFile:43)
    at cf.b(MemoryConnection.java:80)
    at ayh.d(NetClientHandler.java:240)
    at ayp.b(WorldClient.java:92)
    at net.minecraft.client.Minecraft.l(Minecraft.java:1872)
    at net.minecraft.client.Minecraft.J(Minecraft.java:846)
    at net.minecraft.client.Minecraft.run(Minecraft.java:771)
    at java.lang.Thread.run(Unknown Source)

**Comment by voxelhelp** [comment]
Thanks! It worked.
