### ISSUE TITLE
[ChunkUnloading] Unloading chunks = crash

### ISSUE THREAD

**Issue by clienthax** [keepcalm/BukkitForge#258]
2013-01-17 00:19:27 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-17 00:19:27 [INFO] [STDERR] java.lang.NullPointerException
2013-01-17 00:19:27 [INFO] [STDERR]     at aam.a(AnvilChunkLoader.java:274)
2013-01-17 00:19:27 [INFO] [STDERR]     at aam.a(AnvilChunkLoader.java:127)
2013-01-17 00:19:27 [INFO] [STDERR]     at im.b(ChunkProviderServer.java:232)
2013-01-17 00:19:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunk(BukkitWorld.java:317)
2013-01-17 00:19:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunk(BukkitWorld.java:287)
2013-01-17 00:19:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunk(BukkitWorld.java:283)
2013-01-17 00:19:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.unload(BukkitChunk.java:159)
2013-01-17 00:19:27 [INFO] [STDERR]     at ChunkGC.run(ChunkGC.java:51)
2013-01-17 00:19:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
2013-01-17 00:19:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:347)
2013-01-17 00:19:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:28)
2013-01-17 00:19:27 [INFO] [STDERR]     at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
2013-01-17 00:19:27 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
2013-01-17 00:19:27 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
2013-01-17 00:19:27 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:588)
2013-01-17 00:19:27 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)

**Comment by clienthax** [comment]
2013-01-17 00:41:34 [WARNING] [BukkitForge] Task #11 for ChunkGC v1.0 generated an excepti
on
java.lang.NullPointerException
        at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.isChunkInUse(BukkitWorld.java:408)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunk(BukkitWorld.java:305)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.unload(BukkitChunk.java:167)
        at ChunkGC.run(ChunkGC.java:51)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VSc
heduler.java:347)
        at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickH
andler.java:28)
        at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:
16)
        at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)

```
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:588)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
```

2013-01-17 00:41:34 [INFO] [STDERR] t: Ticking entity
2013-01-17 00:41:34 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(Minecraf
tServer.java:686)
2013-01-17 00:41:34 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-17 00:41:34 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(Minecraf
tServer.java:599)
2013-01-17 00:41:34 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(Minecr
aftServer.java:497)
2013-01-17 00:41:34 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-17 00:41:34 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-01-17 00:41:34 [INFO] [STDERR]     at zz.a(Chunk.java:1132)
2013-01-17 00:41:34 [INFO] [STDERR]     at yc.b(World.java:3634)
2013-01-17 00:41:34 [INFO] [STDERR]     at yc.a(World.java:1658)
2013-01-17 00:41:34 [INFO] [STDERR]     at lq.d(Entity.java:734)
2013-01-17 00:41:34 [INFO] [STDERR]     at md.e(EntityLiving.java:1536)
2013-01-17 00:41:34 [INFO] [STDERR]     at md.c(EntityLiving.java:1824)
2013-01-17 00:41:34 [INFO] [STDERR]     at ln.c(SourceFile:77)
2013-01-17 00:41:34 [INFO] [STDERR]     at ox.c(SourceFile:33)
2013-01-17 00:41:34 [INFO] [STDERR]     at md.j_(EntityLiving.java:843)
2013-01-17 00:41:34 [INFO] [STDERR]     at yc.a(World.java:2291)
2013-01-17 00:41:34 [INFO] [STDERR]     at in.a(WorldServer.java:647)
2013-01-17 00:41:34 [INFO] [STDERR]     at yc.g(World.java:2253)
2013-01-17 00:41:34 [INFO] [STDERR]     at yc.h(World.java:2107)
2013-01-17 00:41:34 [INFO] [STDERR]     at in.h(WorldServer.java:516)
2013-01-17 00:41:34 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(Minecraf
tServer.java:680)
2013-01-17 00:41:34 [INFO] [STDERR]     ... 4 more
2013-01-17 00:41:34 [SEVERE] [Minecraft] Encountered an unexpected exception t
t: Ticking entity
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:686)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at zz.a(Chunk.java:1132)
        at yc.b(World.java:3634)
        at yc.a(World.java:1658)
        at lq.d(Entity.java:734)
        at md.e(EntityLiving.java:1536)
        at md.c(EntityLiving.java:1824)
        at ln.c(SourceFile:77)
        at ox.c(SourceFile:33)
        at md.j_(EntityLiving.java:843)
        at yc.a(World.java:2291)
        at in.a(WorldServer.java:647)
        at yc.g(World.java:2253)
        at yc.h(World.java:2107)
        at in.h(WorldServer.java:516)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
        ... 4 more
2013-01-17 00:41:34 [SEVERE] [Minecraft] This crash report has been saved to: C:\voltz1.0.
6.\crash-reports\crash-2013-01-17_00.41.34-server.txt

**Comment by clienthax** [comment]
code that casues

`````` java
import org.bukkit.plugin.java.*;
import org.bukkit.entity.*;
import org.bukkit.command.*;
import org.bukkit.event.*;
import org.bukkit.event.player.*;
import org.bukkit.entity.*;
import org.bukkit.util.*;
import org.bukkit.*;
import java.util.*;
import java.io.*;
import org.bukkit.util.*;
import org.bukkit.block.*;
import org.bukkit.event.block.*;
import org.bukkit.potion.*;
import org.bukkit.event.world.*;
import org.bukkit.inventory.*;
import org.bukkit.event.entity.*;

public final class ChunkGC extends JavaPlugin implements Listener, Runnable
{
    public ChunkGC()
    {
    }

    public void run()
    {
        //int dist = getServer().getViewDistance();
        for (World world : getServer().getWorlds())
        {
            world.save();
            List<Player> players = world.getPlayers();
            int count = 0;
            parent: for (Chunk chunk1 : world.getLoadedChunks())
            {
                if (!chunk1.isLoaded())
                    continue;

                /*int x1 = chunk1.getX();
                int z1 = chunk1.getZ();
                for (Player player : players)
                {
                    Chunk chunk2 = player.getLocation().getChunk();
                    int x2 = chunk2.getX();
                    int z2 = chunk2.getZ();
                    if (Math.abs(x2 - x1) < dist || Math.abs(z2 - z1) < dist)
                        continue parent;

                }*/

                if (chunk1.unload(false, true))
                    ++count;

            }

            for (Player player : players)
                if (player.isOp())
                    player.sendMessage("[ChunkGC] Unloaded " + count + " chunks!");


        }

    }

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args)
    {
        if (label.equals("chunkgc") && sender.isOp())
            run();

        return true;
    }

    public void onEnable()
    {
        long delay = (3L * 60L * 1000L + 50L - 1L) / 50L;
        getServer().getScheduler().scheduleSyncRepeatingTask(this, this, delay, delay);
    }

    public void onDisable()
    {
        getServer().getScheduler().cancelTasks(this);
    }
}```
``````
