### ISSUE TITLE
[Custom Recipes] Error with plugins which add custom recipes

### ISSUE THREAD

**Issue by kriNon** [keepcalm/BukkitForge#259]
I've tested two plugins which both add a crafting recipe however these recipes do not seem to be working, it does not crash however the items to craft are not accessible.
These plugins are Teleport Bow and Ender Bow, they both come up with the same error:

[SEVERE] [BukkitForge] Error occurred while enabling TeleportBow v1.0.1 (Is it up to date?)
java.lang.ClassCastException: org.bukkit.inventory.ShapedRecipe cannot be cast to wp
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.addRecipe(BukkitServer.java:1075)
    at com.gizmoray.teleportbow.TeleportBow.onEnable(TeleportBow.java:35)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:459)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:952)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:936)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:273)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
    at java.lang.Thread.run(Unknown Source)

**Comment by clienthax** [comment]
Plugins that modify classes directly need to be ported, thius looks to be one of those plugins

**Comment by hsun324** [comment]
The reason why there is BukkitForge anyways is to allow for the easier use of Bukkit plugins. You can pretty much port any plugin but the Bukkit API is a much simpler system to use when making things that so not need much client integration. Anyways, if I have time, I'll look at it. (I'm not the official dev.)

Edit: This mod does not modify any base classes.

**Comment by kriNon** [comment]
So since it doesn't edit any base classes am I correct in assuming that it's an issue with BukkitForge?

**Comment by hsun324** [comment]
Pretty much. Especially because the exception doesn't include any references to base Bukkit classes.
