### ISSUE TITLE
[Residence] Residence nullpointer with PlayerInteractEvent

### ISSUE THREAD

**Issue by bogie** [keepcalm/BukkitForge#260]
Running PEX/Residence/OnTime/WorldEdit

2013-01-18 07:57:28 [SEVERE] [BukkitForge] Could not pass event PlayerInteractEvent to Residence v2.6.6.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:429)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:458)
        at net.minecraftforge.event.ASMEventHandler_117_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:28)
        at ir.a(ItemInWorldManager.java:159)
        at iv.a(NetServerHandler.java:509)
        at ei.a(SourceFile:46)
        at cg.b(TcpConnection.java:454)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException

**Comment by keepcalm** [comment]
I NEED MOAR LOGS please! The stuff below Caused by: java.lang.NullPointerException is the most relevant part!

**Comment by bogie** [comment]
Once again:

http://paste2.org/p/2778798

happened when trying to open a chest inside a residence, prior to that a player without access flags could open chests but not use enchant tables etc.
