### ISSUE TITLE
[DuisguiseCraft] No Disguising Plugins work.

### ISSUE THREAD

**Issue by keplersj** [keepcalm/BukkitForge#263]
I've tried a couple of different plugins and they all return pretty similar errors. Here is the error I got with DisguiseCraft:
2013-01-18 15:59:48 [SEVERE] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Could not aquire a required class
java.lang.ClassNotFoundException: keepcalm.mods.bukkit.bukkitAPI.entity.CraftPlayer
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at pgDev.bukkit.DisguiseCraft.DynamicClassFunctions.setClasses(DynamicClassFunctions.java:45)
    at pgDev.bukkit.DisguiseCraft.DisguiseCraft.onLoad(DisguiseCraft.java:92)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:913)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.reload(BukkitServer.java:893)
    at org.bukkit.Bukkit.reload(Bukkit.java:184)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at ho.al(DedicatedServer.java:309)
    at ho.r(DedicatedServer.java:271)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

**Comment by keepcalm** [comment]
Try the latest build (36). It might fix this.

**Comment by keplersj** [comment]
Just tried with build 55. Looks like it almost worked.

2013-01-19 18:29:30 [INFO] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Loading DisguiseCraft v4.3
2013-01-19 18:29:30 [SEVERE] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Could not aquire a required class
java.lang.ClassNotFoundException: keepcalm/mods/bukkit/bukkitAPI/entity/CraftPlayer
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at pgDev.bukkit.DisguiseCraft.DynamicClassFunctions.setClasses(DynamicClassFunctions.java:45)
    at pgDev.bukkit.DisguiseCraft.DisguiseCraft.onLoad(DisguiseCraft.java:92)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:917)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:273)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Thread.java:680)
2013-01-19 18:29:30 [SEVERE] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Could not dynamically locate required resources!
2013-01-19 18:29:30 [SEVERE] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Could not access datawatchers!

**Comment by alexbegt** [comment]
I can fix this.

**Comment by keplersj** [comment]
If I were more familiar with the MinecraftForge API, MCP, Bukkit API, and Java I'd try to fix it.

**Comment by alexbegt** [comment]
I fixed this error

**Comment by keplersj** [comment]
Just tried with build 60. Same Error.

2013-01-19 21:37:06 [INFO] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Loading DisguiseCraft v4.3
2013-01-19 21:37:06 [SEVERE] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Could not aquire a required class
java.lang.ClassNotFoundException: keepcalm/mods/bukkit/bukkitAPI/entity/CraftPlayer
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at pgDev.bukkit.DisguiseCraft.DynamicClassFunctions.setClasses(DynamicClassFunctions.java:45)
    at pgDev.bukkit.DisguiseCraft.DisguiseCraft.onLoad(DisguiseCraft.java:92)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:917)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:273)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Thread.java:680)
2013-01-19 21:37:06 [SEVERE] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Could not dynamically locate required resources!
2013-01-19 21:37:06 [SEVERE] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Could not access datawatchers!

**Comment by alexbegt** [comment]
Lol Sorry, I fixed part of the error.

**Comment by keplersj** [comment]
Just tried with build 81

2013-01-21 16:20:08 [INFO] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Loading DisguiseCraft v4.3
2013-01-21 16:20:08 [SEVERE] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Could not aquire a required class
java.lang.ClassNotFoundException: keepcalm/mods/bukkit/bukkitAPI/entity/CraftPlayer
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at pgDev.bukkit.DisguiseCraft.DynamicClassFunctions.setClasses(DynamicClassFunctions.java:45)
    at pgDev.bukkit.DisguiseCraft.DisguiseCraft.onLoad(DisguiseCraft.java:92)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:897)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:245)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Thread.java:680)
2013-01-21 16:20:08 [SEVERE] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Could not dynamically locate required resources!
2013-01-21 16:20:08 [SEVERE] [pgDev.bukkit.DisguiseCraft.DisguiseCraft] [DisguiseCraft] Could not access datawatchers!

**Comment by Nintendofreaker** [comment]
Funny thing, the disguise craft plugins don't work except Block Disguise (a plugin that let you turn to items in the game). Block disguise seems to work perfectly, but not the others.
