### ISSUE TITLE
[LWC] interact, NPE

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#267]
Plugin load correctly. Create Mysql tables. When place chest or try to access chest LWC make NPE.

2013-01-18 08:26:10 [INFO] [STDERR] java.lang.NullPointerException
2013-01-18 08:26:10 [INFO] [STDERR] at com.griefcraft.util.ProtectionFinder.tryLoadProtection(ProtectionFinder.java:274)
2013-01-18 08:26:10 [INFO] [STDERR] at com.griefcraft.util.ProtectionFinder.matchBlocks(ProtectionFinder.java:105)
2013-01-18 08:26:10 [INFO] [STDERR] at com.griefcraft.lwc.LWC.findProtection(LWC.java:1161)
2013-01-18 08:26:10 [INFO] [STDERR] at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:135)
2013-01-18 08:26:10 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-18 08:26:10 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2013-01-18 08:26:10 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-01-18 08:26:10 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Method.java:601)
2013-01-18 08:26:10 [INFO] [STDERR] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
2013-01-18 08:26:10 [INFO] [STDERR] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-01-18 08:26:10 [INFO] [STDERR] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-01-18 08:26:10 [INFO] [STDERR] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2013-01-18 08:26:10 [INFO] [STDERR] at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:458)
2013-01-18 08:26:10 [INFO] [STDERR] at net.minecraftforge.event.ASMEventHandler_50_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
2013-01-18 08:26:10 [INFO] [STDERR] at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-01-18 08:26:10 [INFO] [STDERR] at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-01-18 08:26:10 [INFO] [STDERR] at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:28)
2013-01-18 08:26:10 [INFO] [STDERR] at ir.a(ItemInWorldManager.java:389)
2013-01-18 08:26:10 [INFO] [STDERR] at iv.a(NetServerHandler.java:617)
2013-01-18 08:26:10 [INFO] [STDERR] at fk.a(SourceFile:58)
2013-01-18 08:26:10 [INFO] [STDERR] at cg.b(TcpConnection.java:454)
2013-01-18 08:26:10 [INFO] [STDERR] at iv.d(NetServerHandler.java:141)
2013-01-18 08:26:10 [INFO] [STDERR] at iw.b(NetworkListenThread.java:57)
2013-01-18 08:26:10 [INFO] [STDERR] at ht.b(SourceFile:30)
2013-01-18 08:26:10 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
2013-01-18 08:26:10 [INFO] [STDERR] at ho.r(DedicatedServer.java:270)
2013-01-18 08:26:10 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
2013-01-18 08:26:10 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-18 08:26:10 [INFO] [STDERR] at fy.run(SourceFile:849)

2013-01-18 08:26:35 [SEVERE] [BukkitForge] Could not pass event BlockPlaceEvent to LWC v4.3.1 (b767-git-MANUAL) (November 15, 2012)
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:429)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteraction(ForgeEventHandler.java:350)
at net.minecraftforge.event.ASMEventHandler_47_ForgeEventHandler_onPlayerInteraction_PlayerInteractEvent.invoke(.dynamic)
at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
at net.minecraftforge.event.EventBus.post(EventBus.java:103)
at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:28)
at ir.a(ItemInWorldManager.java:389)
at iv.a(NetServerHandler.java:617)
at fk.a(SourceFile:58)
at cg.b(TcpConnection.java:454)
at iv.d(NetServerHandler.java:141)
at iw.b(NetworkListenThread.java:57)
at ht.b(SourceFile:30)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
at ho.r(DedicatedServer.java:270)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
at com.griefcraft.util.ProtectionFinder.tryLoadProtection(ProtectionFinder.java:274)
at com.griefcraft.util.ProtectionFinder.matchBlocks(ProtectionFinder.java:105)
at com.griefcraft.lwc.LWC.findProtection(LWC.java:1161)
at com.griefcraft.listeners.LWCBlockListener.onBlockPlace(LWCBlockListener.java:324)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
... 20 more
2013-01-18 08:26:40 [INFO] [STDERR] java.lang.NullPointerException
2013-01-18 08:26:40 [INFO] [STDERR] at com.griefcraft.util.ProtectionFinder.tryLoadProtection(ProtectionFinder.java:274)
2013-01-18 08:26:40 [INFO] [STDERR] at com.griefcraft.util.ProtectionFinder.matchBlocks(ProtectionFinder.java:105)
2013-01-18 08:26:40 [INFO] [STDERR] at com.griefcraft.lwc.LWC.findProtection(LWC.java:1161)
2013-01-18 08:26:40 [INFO] [STDERR] at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:135)
2013-01-18 08:26:40 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-18 08:26:40 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2013-01-18 08:26:40 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-01-18 08:26:40 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Method.java:601)
2013-01-18 08:26:40 [INFO] [STDERR] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
2013-01-18 08:26:40 [INFO] [STDERR] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-01-18 08:26:40 [INFO] [STDERR] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-01-18 08:26:40 [INFO] [STDERR] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2013-01-18 08:26:40 [INFO] [STDERR] at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:458)
2013-01-18 08:26:40 [INFO] [STDERR] at net.minecraftforge.event.ASMEventHandler_50_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
2013-01-18 08:26:40 [INFO] [STDERR] at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-01-18 08:26:40 [INFO] [STDERR] at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-01-18 08:26:40 [INFO] [STDERR] at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:28)
2013-01-18 08:26:40 [INFO] [STDERR] at ir.a(ItemInWorldManager.java:389)
2013-01-18 08:26:40 [INFO] [STDERR] at iv.a(NetServerHandler.java:617)
2013-01-18 08:26:40 [INFO] [STDERR] at fk.a(SourceFile:58)
2013-01-18 08:26:40 [INFO] [STDERR] at cg.b(TcpConnection.java:454)
2013-01-18 08:26:40 [INFO] [STDERR] at iv.d(NetServerHandler.java:141)
2013-01-18 08:26:40 [INFO] [STDERR] at iw.b(NetworkListenThread.java:57)
2013-01-18 08:26:40 [INFO] [STDERR] at ht.b(SourceFile:30)
2013-01-18 08:26:40 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
2013-01-18 08:26:40 [INFO] [STDERR] at ho.r(DedicatedServer.java:270)
2013-01-18 08:26:40 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
2013-01-18 08:26:40 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-18 08:26:40 [INFO] [STDERR] at fy.run(SourceFile:849)
2013-01-18 08:26:48 [INFO] [STDERR] java.net.SocketException: Connection reset
2013-01-18 08:26:48 [INFO] [STDERR] at java.net.SocketInputStream.read(SocketInputStream.java:189)
2013-01-18 08:26:48 [INFO] [STDERR] at java.net.SocketInputStream.read(SocketInputStream.java:121)
2013-01-18 08:26:48 [INFO] [STDERR] at java.io.FilterInputStream.read(FilterInputStream.java:133)
2013-01-18 08:26:48 [INFO] [STDERR] at org.bouncycastle.crypto.io.CipherInputStream.nextChunk(Unknown Source)
2013-01-18 08:26:48 [INFO] [STDERR] at org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source)
2013-01-18 08:26:48 [INFO] [STDERR] at java.io.FilterInputStream.read(FilterInputStream.java:83)
2013-01-18 08:26:48 [INFO] [STDERR] at ef.a(Packet.java:142)
2013-01-18 08:26:48 [INFO] [STDERR] at cg.i(TcpConnection.java:320)
2013-01-18 08:26:48 [INFO] [STDERR] at cg.c(TcpConnection.java:540)
2013-01-18 08:26:48 [INFO] [STDERR] at ch.run(SourceFile:93)

When server stopped, there is another error:
2013-01-18 08:28:06 [SEVERE] [BukkitForge] Error occurred while disabling LWC v4.3.1 (b767-git-MANUAL) (November 15, 2012) (Is it up to date?)
java.lang.NullPointerException
at com.griefcraft.lwc.LWC.destruct(LWC.java:576)
at com.griefcraft.lwc.LWCPlugin.onDisable(LWCPlugin.java:202)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:483)
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.shutdown(BukkitServer.java:1196)
at keepcalm.mods.bukkit.forgeHandler.commands.BukkitCommandStop.b(BukkitCommandStop.java:42)
at x.a(CommandHandler.java:84)
at ho.al(DedicatedServer.java:309)
at ho.r(DedicatedServer.java:271)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
at fy.run(SourceFile:849)

All exceptions are written to console, but not to server.log file.

**Comment by alexbegt** [comment]
Fixed
