### ISSUE TITLE
[CombatTag][PrisonPerl] World class missing

### ISSUE THREAD

**Issue by interfect** [keepcalm/BukkitForge#271]
(The title should actually read _PrisonPearl_)

I have a couple of mods that don't work because the World class is not present. I get traces like:

2013-01-19 03:20:33 [SEVERE] [BukkitForge] Could not load './plugins/ported_CombatTag.jar' in folder './plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/World
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:198)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:912)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:273)
        at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/World
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:187)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.World
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:44)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:39)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 9 more

Any ETA for implementation of the World class?

**Comment by keepcalm** [comment]
That's an MC class. And I should've fixed all these issues... Try updating...
**EDIT**
Open your BukkitForge.jar with winRAR and replace vcb2obf.srg with vcb2obf_1.4.6.srg. Should work then.

**Comment by SpoonsJTD** [comment]
This should be resolved with the magic class loading stuff.
