### ISSUE TITLE
[AuthMe] NPE

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#273]
AuthME plugin does not work. Throw NPE and no need to login to play.

2013-01-19 14:28:55 [SEVERE] [BukkitForge] Could not pass event PlayerJoinEvent to AuthMe v2.7.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:385)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at keepcalm.mods.bukkit.forgeHandler.PlayerTracker$1.run(PlayerTracker.java:46)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
        at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventoryPlayer.setArmorContents(BukkitInventoryPlayer.java:58)
        at uk.org.whoami.authme.api.API.setPlayerInventory(API.java:152)
        at uk.org.whoami.authme.listener.AuthMePlayerListener.onPlayerJoin(AuthMePlayerListener.java:697)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:383)
        ... 5 more

**Comment by ruifung** [comment]
Does not happen for me. Using build 54.

**Comment by ficolas** [comment]
Does happen to me.

**Comment by ruifung** [comment]
Correction: It appears to be related to the protect inventory feature. I usually turn it off.

**Comment by ghost** [comment]
When inventory protect is off, authme work, but before login:
- player can drop all inventory
- player can move around spawn location (when move disabled in the config :( )
- maybe player can chatting (not tested)

**Comment by ruifung** [comment]
No plugin which stops players from moving works, tested on build 78. Example: Essentials afk freeze.

**Comment by vemacs** [comment]
Well, it looks like both PlayerJoinEvent and some portions of PlayerMoveEvent aren't implemented.

**Comment by SpoonsJTD** [comment]
vemacs, I believe the events are implemented, they just don't have an entry in the BukkitEventFactory. keepcalm generates them directly in ForgeEventHandler. I know PlayerJoinEvent is implemented because we just fixed the player object being passed during the event.

Edit: Sorry, PlayerJoinEvent is fired in PlayerTracker.

**Comment by vemacs** [comment]
SpoonsJTD: I just added PlayerJoinEvent in the factory. See the pull request:
https://github.com/keepcalm/BukkitForge/pull/315

**Comment by ruifung** [comment]
Okay... what about playerMoveEvent ?

**Comment by alexbegt** [comment]
Its just the plugin
