### ISSUE TITLE
AuthMe Trows errors. Could you please fix/patch it? I really need it for my server

### ISSUE THREAD

**Issue by ficolas** [keepcalm/BukkitForge#274]
AuthMe Trows errors. Could you please fix/patch it? I really need it for my server

2013-01-19 14:28:55 [SEVERE] [BukkitForge] Could not pass event PlayerJoinEvent to AuthMe v2.7.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:385)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
at keepcalm.mods.bukkit.forgeHandler.PlayerTracker$1.run(PlayerTracker.java:46)
at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventoryPlayer.setArmorContents(BukkitInventoryPlayer.java:58)
at uk.org.whoami.authme.api.API.setPlayerInventory(API.java:152)
at uk.org.whoami.authme.listener.AuthMePlayerListener.onPlayerJoin(AuthMePlayerListener.java:697)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:383)
... 5 more

**Comment by SpoonsJTD** [comment]
You win the prize for best dupe ever, posting a dupe one hour after the previous issue was posted, making the original numerically one before yours.

**Comment by ficolas** [comment]
... I diden't looked at other issues.
