### ISSUE TITLE
[Towny] Not enabling

### ISSUE THREAD

**Issue by dedo1911** [keepcalm/BukkitForge#281]
Am I the only one that still can't use Towny?

2013-01-20 03:34:18 [INFO] [com.palmergames.bukkit.towny.Towny] [Towny] Enabling Towny v0.82.0.9
2013-01-20 03:34:18 [INFO] [STDOUT] ====================      Towny      ========================
2013-01-20 03:34:18 [INFO] [STDOUT] [Towny] Database: [Load] flatfile [Save] flatfile
2013-01-20 03:34:18 [INFO] [com.palmergames.bukkit.towny.Towny] [Towny] Disabling Towny v0.82.0.9
2013-01-20 03:34:18 [INFO] [STDOUT] ==============================================================
2013-01-20 03:34:18 [INFO] [STDOUT] [Towny] Version: 0.82.0.9 - Mod Disabled
2013-01-20 03:34:18 [INFO] [STDOUT] =============================================================
2013-01-20 03:34:18 [SEVERE] [BukkitForge] Error occurred while enabling Towny v0.82.0.9 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.palmergames.bukkit.towny.listeners.TownyPlayerListener@760cffee while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:499)
        at com.palmergames.bukkit.towny.Towny.registerEvents(Unknown Source)
        at com.palmergames.bukkit.towny.Towny.onEnable(Unknown Source)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:423)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:956)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:940)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:277)
        at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
        at java.lang.Thread.run(Unknown Source)

Also, when i've updated from r30 to r60 it "updated" every plugin to a ported_ version. Do i've to remove the _original_ one and just keep the ported? Ty

**Comment by BubblyLemon** [comment]
This error may be due to towny looking for a craftbukkit version that isn't there (seeing as this bukkitforge)

To enable towny I had to go into its config and change it to ignore other versions of craftbukkit

**Comment by cheekyvimto** [comment]
I can confirm, disabling the craftbukkit check in the config, does load this plugin (0.82.0.0)

I'm still having some command based issues, but I need to check if thats due to config before reporting.

**Comment by keepcalm** [comment]
Yep, disable version checking or change the CB version setting in BukkitForge.cfg
