### ISSUE TITLE
[AdminCmd] /spawn

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#295]
/spawn does not work:

2013-01-20 14:48:44 [WARNING] [BukkitForge] Task #21 for AdminCmd v7.0.1-SNAPSHOT (BUILD 23.12.2012 @ 19:03:42) generated an exception
java.lang.RuntimeException: Can't get field dimension from in@6c2dd6cb
        at be.Balor.Tools.Compatibility.Reflect.FieldUtils.getField(FieldUtils.java:53)
        at be.Balor.Tools.Utils.teleport(Utils.java:1670)
        at be.Balor.Tools.Utils.teleportWithChunkCheck(Utils.java:1661)
        at be.Balor.bukkit.AdminCmd.ACHelper.spawn(ACHelper.java:1302)
        at be.Balor.Manager.Commands.Spawn.Spawn$DelayedTeleport.run(Spawn.java:121)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:347)
        at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:37)
        at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
        at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.NoSuchFieldException: dimension
        at java.lang.Class.getDeclaredField(Class.java:1899)
        at be.Balor.Tools.Compatibility.Reflect.FieldUtils.getObjectField(FieldUtils.java:86)
        at be.Balor.Tools.Compatibility.Reflect.FieldUtils.getField(FieldUtils.java:47)
        ... 13 more

**Comment by SpoonsJTD** [comment]
Bad reflection, bad. Not likely to support this add-in based on how it's getting dimension.
