### ISSUE TITLE
Build 70 can't connect

### ISSUE THREAD

**Issue by shakey2** [keepcalm/BukkitForge#302]
deja vu much?

2013-01-20 17:24:28 [INFO] [STDERR] java.net.SocketException: Software caused connection abort: recv failed
2013-01-20 17:24:28 [INFO] [STDERR]     at java.net.SocketInputStream.socketRead0(Native Method)
2013-01-20 17:24:28 [INFO] [STDERR]     at java.net.SocketInputStream.read(Unknown Source)
2013-01-20 17:24:28 [INFO] [STDERR]     at java.net.SocketInputStream.read(Unknown Source)
2013-01-20 17:24:28 [INFO] [STDERR]     at java.io.FilterInputStream.read(Unknown Source)
2013-01-20 17:24:28 [INFO] [STDERR]     at org.bouncycastle.crypto.io.CipherInputStream.nextChunk(Unknown Source)
2013-01-20 17:24:28 [INFO] [STDERR]     at org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source)
2013-01-20 17:24:28 [INFO] [STDERR]     at java.io.DataInputStream.readFully(Unknown Source)
2013-01-20 17:24:28 [INFO] [STDERR]     at java.io.DataInputStream.readLong(Unknown Source)
2013-01-20 17:24:28 [INFO] [STDERR]     at java.io.DataInputStream.readDouble(Unknown Source)
2013-01-20 17:24:28 [INFO] [STDERR]     at ec.a(SourceFile:69)
2013-01-20 17:24:28 [INFO] [STDERR]     at ef.a(Packet.java:166)
2013-01-20 17:24:28 [INFO] [STDERR]     at cg.i(TcpConnection.java:320)
2013-01-20 17:24:28 [INFO] [STDERR]     at cg.c(TcpConnection.java:540)
2013-01-20 17:24:28 [INFO] [STDERR]     at ch.run(SourceFile:93)
2013-01-20 17:24:28 [INFO] [Minecraft] Disconnecting shakey2 [/127.0.0.1:1480]: Internal server error
2013-01-20 17:24:28 [SEVERE] [ForgeModLoader] Error handling login related packet - connection from shakey2 [/127.0.0.1:1480] refused
java.lang.NullPointerException
    at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.playerLoggedIn(ConnectionHandler.java:122)
    at cpw.mods.fml.common.network.NetworkRegistry.playerLoggedIn(NetworkRegistry.java:161)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePlayerLogin(FMLNetworkHandler.java:281)
    at gm.a(ServerConfigurationManager.java:143)
    at it.completeConnection(NetLoginHandler.java:195)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:153)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
    at it.d(NetLoginHandler.java:179)
    at it.c(NetLoginHandler.java:72)
    at hu.a(ServerListenThread.java:56)
    at ht.b(SourceFile:29)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
2013-01-20 17:24:28 [WARNING] [Minecraft] Failed to handle packet for shakey2 [/127.0.0.1:1480]: java.lang.NullPointerException
java.lang.NullPointerException
    at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.playerLoggedIn(ConnectionHandler.java:122)
    at cpw.mods.fml.common.network.NetworkRegistry.playerLoggedIn(NetworkRegistry.java:161)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePlayerLogin(FMLNetworkHandler.java:281)
    at gm.a(ServerConfigurationManager.java:143)
    at it.completeConnection(NetLoginHandler.java:195)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:153)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
    at it.d(NetLoginHandler.java:179)
    at it.c(NetLoginHandler.java:72)
    at hu.a(ServerListenThread.java:56)
    at ht.b(SourceFile:29)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

**Comment by CrAzD** [comment]
Is there anyway to get the names of mystcraft ages?
