### ISSUE TITLE
Access to Base Classes

### ISSUE THREAD

**Issue by keplersj** [keepcalm/BukkitForge#318]
Ok not much of an issue but more of an enhancement idea.

For the few Bukkit plugins that import base classes, couldn't we redirect them to the correct classes. From what I gather from the JSONAPI source bukkit server give access to base classes through net.minecraft.server.vVERSION.CLASS. Because we are using Forge we should be able to give direct access to these classes. Doing this could fix the JSONAPI issue.

**Comment by keepcalm** [comment]
that's already implemented - see fd8ad53c45807b34515512e977bfa92613541659

**Comment by keplersj** [comment]
So sorry. It been a while since I upgraded.

**Comment by keplersj** [comment]
Just tried running JSONAPI with build 81
It looks like it is still having issue accessing the base class it needs.

2013-01-21 16:20:08 [SEVERE] [BukkitForge] Could not load './plugins/JSONAPI.jar' in folder './plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_6/World
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:211)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:892)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:245)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_6/World
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:200)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_6.World
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:44)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:39)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 9 more

**Comment by Manawyrm** [comment]
Problem fixed with custom build of JSONApi:
https://github.com/Manawyrm/jsonapi
