### ISSUE TITLE
Crash When Crafting With ExtremeBiomes Wood

### ISSUE THREAD

**Issue by Nonsanity** [keepcalm/BukkitForge#323]
I don't know if this is restricted to EB wood only, or is a general crafting crash, but I'll find out soon. Here's the stack trace:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.BukkitPlayerCache.getBukkitPlayer(BukkitPlayerCache.java:15)
    at keepcalm.mods.bukkit.forgeHandler.BukkitCraftingHandler.onCrafting(BukkitCraftingHandler.java:62)
    at cpw.mods.fml.common.registry.GameRegistry.onItemCrafted(GameRegistry.java:309)
    at sq.a(SlotCrafting.java:118)
    at rq.a(SourceFile:166)
    at ayo.a(PlayerControllerMP.java:461)
    at avf.a(GuiContainer.java:620)
    at codechicken.nei.forge.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.forge.GuiContainerManager.handleMouseClick(GuiContainerManager.java:587)
    at avf.a(GuiContainer.java:461)
    at aul.d(SourceFile:127)
    at avf.d(GuiContainer.java:722)
    at aul.m(SourceFile:111)

**Comment by Nonsanity** [comment]
It's any crafting that causes the crash for us. I'll try removing NEI and see if that helps.

(I've tried several versions of BukkitForge, old and new. And the latest NEI and ChickenCore.)

**Comment by keplersj** [comment]
Got any plugins installed?

**Comment by Nonsanity** [comment]
A few from the "working" list, yes:

AutoMessage, Essentials, iChat, VoxelSniper, WorldBorder, WorldEdit, and WorldGuard

I know the fill function of WorldBorder doesn't work, and VoxelSniper may have some problems. Otherwise things seem to be working as far as they've been configured. (Just set up the server.)

Removing NEI stopped the client-side crash whenever anyone attempted to take the output of a crafting table (or from the in-inventory crafting). Upon re-logging in, the raw materials would be found on the ground. The item was not crafted.

**Comment by SpoonsJTD** [comment]
Is this still an issue? If so, please post entire error log (especially the part of the stack trace that says 'Caused by:').
