### ISSUE TITLE
[TeleportSuite 2.2.2] Not Working and Error in Console

### ISSUE THREAD

**Issue by oppositeZERO** [keepcalm/BukkitForge#326]
So when using for example the command /tploc x y z The following error is given. Not sure if this in on your end or thiers, but i though i better post it just incase.

Cheers

edit: using build # 87

2013-01-22 02:20:04 [INFO] [BukkitForge] MyHeRoZeRo issued server command: tplocation0 150 0
2013-01-22 02:20:04 [INFO] [STDERR] org.bukkit.command.CommandException: Unhandled exception executing command 'tplocation' in plugin TeleportSuite v2.2.2-b160
2013-01-22 02:20:04 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
2013-01-22 02:20:04 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2013-01-22 02:20:04 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2013-01-22 02:20:04 [INFO] [STDERR]     at iv.d(NetServerHandler.java:768)
2013-01-22 02:20:04 [INFO] [STDERR]     at iv.a(NetServerHandler.java:734)
2013-01-22 02:20:04 [INFO] [STDERR]     at cu.a(SourceFile:44)
2013-01-22 02:20:04 [INFO] [STDERR]     at cg.b(TcpConnection.java:454)
2013-01-22 02:20:04 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2013-01-22 02:20:04 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-01-22 02:20:04 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-01-22 02:20:04 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
2013-01-22 02:20:04 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-22 02:20:04 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
2013-01-22 02:20:04 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-22 02:20:04 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-22 02:20:04 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-01-22 02:20:04 [INFO] [STDERR]     at net.krinsoft.teleportsuite.TeleportPlayer.<init>(TeleportPlayer.java:74)
2013-01-22 02:20:04 [INFO] [STDERR]     at net.krinsoft.teleportsuite.TeleportManager.register(TeleportManager.java:36)
2013-01-22 02:20:04 [INFO] [STDERR]     at net.krinsoft.teleportsuite.TeleportManager.getPlayer(TeleportManager.java:56)
2013-01-22 02:20:04 [INFO] [STDERR]     at net.krinsoft.teleportsuite.commands.TPLocationCommand.runCommand(TPLocationCommand.java:38)
2013-01-22 02:20:04 [INFO] [STDERR]     at com.pneumaticraft.commandhandler.teleportsuite.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
2013-01-22 02:20:04 [INFO] [STDERR]     at com.pneumaticraft.commandhandler.teleportsuite.CommandHandler.processFoundCommands(CommandHandler.java:143)
2013-01-22 02:20:04 [INFO] [STDERR]     at com.pneumaticraft.commandhandler.teleportsuite.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
2013-01-22 02:20:04 [INFO] [STDERR]     at com.pneumaticraft.commandhandler.teleportsuite.CommandHandler.locateAndRunCommand(CommandHandler.java:71)
2013-01-22 02:20:04 [INFO] [STDERR]     at net.krinsoft.teleportsuite.TeleportSuite.onCommand(TeleportSuite.java:88)
2013-01-22 02:20:04 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-01-22 02:20:04 [INFO] [STDERR]     ... 14 more

**Comment by SpoonsJTD** [comment]
This should be fixed. Re-open if not.
