### ISSUE TITLE
Essentials dont work

### ISSUE THREAD

**Issue by Kristallflamme** [keepcalm/BukkitForge#33]
Hello!

First time: Great work ! Im so happy over your Mod.
(sorry about my english :) im from germany)
But i have a problem with essentials.
Essentials,EssentialsGroupManager and EssentialsChat are in pluginlist but they doesnt work :(
When I join the Server it doesent give me a welcomes message. 
This commands  works:
/tp 
/setspawn
/setwarp
/tphere

And an another problem is that when you make the command /tp or /spawn in Nether,that you spawn anywhere in nether.

I hope you can help me :)

Greetings from Germany
Sandra

The Error Message in Group Manager:
2012-12-19 20-04
=============================== GM ERROR LOG ===============================
= ERROR REPORT START - ${GMVer} (${build.number}) (Phoenix) =

java.lang.IllegalArgumentException: The following file couldn't pass on Parser.
./plugins/GroupManager/worlds/world/groups.yml
    at org.anjocaido.groupmanager.dataholder.WorldDataHolder.loadGroups(WorldDataHolder.java:497)
    at org.anjocaido.groupmanager.dataholder.WorldDataHolder.loadGroups(WorldDataHolder.java:417)
    at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.loadWorld(WorldsHolder.java:629)
    at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.loadWorld(WorldsHolder.java:591)
    at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.initialWorldLoading(WorldsHolder.java:88)
    at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.initialLoad(WorldsHolder.java:78)
    at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.resetWorldsHolder(WorldsHolder.java:70)
    at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.<init>(WorldsHolder.java:59)
    at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:161)
    at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:85)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:889)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:873)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:232)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:36)
    at java.lang.Thread.run(Unknown Source)
Caused by: unacceptable character '?' (0xFFFD) special characters are not allowed
in "<reader>", position 597
    at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:98)
    at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:191)
    at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:63)
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:423)
    at org.anjocaido.groupmanager.dataholder.WorldDataHolder.loadGroups(WorldDataHolder.java:492)
    ... 17 more
#

**Comment by keepcalm** [comment]
Your GroupManager error is not the problem, but the easiest way to fix it is to remove the question mark in plugins/GroupManager/worlds/world/groups.yml. I will inspect my code and try to work out what's wrong.

**Comment by xKillerbees** [comment]
Doing a /spawn after a /setspawn brings up 

Error: Null

**Comment by Manawyrm** [comment]
erm. My server does not even know the command /spawn.
Are you sure, you are using the current build from BukkitForge and are using the patched Version of Essentials?

**Comment by xKillerbees** [comment]
Yes, I never report an issue unless I'm on the latest.

**Comment by Manawyrm** [comment]
Sorry, i can't seem to reproduce this. My server does not have /spawn.
What plugins do you have installed?

EDIT: Whoops. Confirmed. There's a mistake there! Will look into it...

**Comment by Manawyrm** [comment]
OK. The bug seems to sit deeper in the code. I will open another issue for that!
