### ISSUE TITLE
[CraftItemEvent] Error when crafting items.

### ISSUE THREAD

**Issue by charlieTheBotDev** [keepcalm/BukkitForge#337]
I tried to install Tekkit Customiser for the banned item stuff and it didn't work properly. I didn't notice why to start with so I stopped looking for a problem and ignored the plugin. However, I forgot to remove it and just noticed this being spammed in the logs by people:

2013-01-23 06:15:15 [SEVERE] [BukkitForge] Could not pass event CraftItemEvent to TekkitCustomizer v1.5.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:397)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at keepcalm.mods.bukkit.forgeHandler.BukkitCraftingHandler.onCrafting(BukkitCraftingHandler.java:64)
        at cpw.mods.fml.common.registry.GameRegistry.onItemCrafted(GameRegistry.java:309)
        at sq.a(SlotCrafting.java:118)
        at rq.a(SourceFile:166)
        at iv.a(NetServerHandler.java:906)
        at dc.a(SourceFile:31)
        at cg.b(TcpConnection.java:454)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.ArrayIndexOutOfBoundsException

I couldn't see an issue related to the CraftItemEvent so I figured I'd make one. Sorry if there is one or this is fixed, I haven't got round to updating for a little while and I'm still on build 80.

**Comment by SpoonsJTD** [comment]
This is fixed, sort of. The exception is caused by CraftItemEvent passing -1 as the item number. This exception is guarded against now.
