### ISSUE TITLE
[Backup] Failed to backup worlds: Exception in BackupWorlds.

### ISSUE THREAD

**Issue by eagl3s1ght** [keepcalm/BukkitForge#338]
**Coremods used:**
BukkitForge-1.4.7-90
[1.4.6]TreeCapitator.Forge.1.4.6.r03.Uni.CoreMod
CodeChickenCore 0.7.0.2
NotEnoughItems 1.4.5.0

```
2013-01-22 23:06:04 [INFO] [BukkitForge.BukkitForge] [Backup] Failed to backup worlds: Exception in BackupWorlds.
2013-01-22 23:06:04 [INFO] [BukkitForge.BukkitForge] [Backup] Please provide following error with support request:
2013-01-22 23:06:04 [INFO] [STDOUT] java.io.FileNotFoundException: Source 'World\Nether' does not exist
2013-01-22 23:06:04 [INFO] [STDOUT]     at com.bukkitbackup.full.utils.FileUtils.copyDirectory(FileUtils.java:204)
2013-01-22 23:06:04 [INFO] [STDOUT]     at com.bukkitbackup.full.utils.FileUtils.copyDirectory(FileUtils.java:145)
2013-01-22 23:06:04 [INFO] [STDOUT]     at com.bukkitbackup.full.utils.FileUtils.copyDirectory(FileUtils.java:114)
2013-01-22 23:06:04 [INFO] [STDOUT]     at com.bukkitbackup.full.threading.tasks.BackupWorlds.doWorlds(BackupWorlds.java:139)
2013-01-22 23:06:04 [INFO] [STDOUT]     at com.bukkitbackup.full.threading.BackupTask.run(BackupTask.java:109)
2013-01-22 23:06:04 [INFO] [STDOUT]     at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
2013-01-22 23:06:04 [INFO] [STDOUT]     at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VAsyncTask.run(B4VAsyncTask.java:54)
2013-01-22 23:06:04 [INFO] [STDOUT]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2013-01-22 23:06:04 [INFO] [STDOUT]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2013-01-22 23:06:04 [INFO] [STDOUT]     at java.lang.Thread.run(Unknown Source)
```

**Comment by SpoonsJTD** [comment]
BackupWorlds assumes it knows where the world folders live, which it does incorrectly for BukkitForge.
