### ISSUE TITLE
[Essentials-Economy] Error calling command /sell java.lang.Exception

### ISSUE THREAD

**Issue by eagl3s1ght** [keepcalm/BukkitForge#340]
**Coremods used:**
BukkitForge-1.4.7-90
[1.4.6]TreeCapitator.Forge.1.4.6.r03.Uni.CoreMod
CodeChickenCore 0.7.0.2
NotEnoughItems 1.4.5.0

```
2013-01-23 01:14:27 [INFO] [com.earth2me.essentials.Essentials] [Essentials] calculated command (sell) cost for eaglesight as 0.0
2013-01-23 01:14:27 [WARNING] [Minecraft] Error calling command /sell
java.lang.Exception: Âº4That item cannot be sold to the server.
    at com.earth2me.essentials.commands.Commandsell.sellItem(Commandsell.java:109)
    at com.earth2me.essentials.commands.Commandsell.run(Commandsell.java:84)
    at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:96)
    at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:407)
    at com.earth2me.essentials.Essentials.onCommand(Essentials.java:313)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
```

**Comment by alexbegt** [comment]
May i ask plugins?

**Comment by eagl3s1ght** [comment]
@alexbegt Ofcourse! I just reproduced the error using Bukkitforge Build 95 and only the Essentials suite downloaded from here: http://ess.ementalo.com/repository/download/bt9/4812:id/Essentials-full.zip which appears to be Essentials Pre2.9.7.5. 

Further testing shows the same problem using Bukkitforge Build 95 + Essentials suite Dev2.10.3, /ess debug log:

```
2013-01-25 05:06:37 [WARNING] [Minecraft] Error calling command /sell
java.lang.Exception: º6/sell itemname -1 will sell all but one item, etc.
        at com.earth2me.essentials.commands.Commandsell.sellItem(Commandsell.java:158)
        at com.earth2me.essentials.commands.Commandsell.run(Commandsell.java:84)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:96)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:422)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:318)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
        at x.a(CommandHandler.java:82)
        at iv.d(NetServerHandler.java:768)
        at iv.a(NetServerHandler.java:734)
        at cu.a(SourceFile:44)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
```

**Comment by Sageavatar** [comment]
When used in-game to /sell an item the error returned (in-game) states that "You do not have enough of X to sell"

**Comment by keepcalm** [comment]
@eagl3s1ght, does it have a 'Caused by: ...' bit?

**Comment by eagl3s1ght** [comment]
@keepcalm, Nope. Here's another test for you, on Bukkitforge build 198 with Essentials Pre2.9.7.5. http://pastebin.com/0jVYScEq Full forgemodloader log this time. :8ball: Also ran /bukkitforge debug on, /debug start and /ess debug :dancer:

**Comment by eagl3s1ght** [comment]
Seems fixed as of Bukkitforge build 209. Or, I could just have installed a plugin which made it work. If this was an intended fix then feel free to mark it as closed. Either way, I am super happy for /sell to be working. :+1:

**Comment by Sageavatar** [comment]
I can confirm fixed. I'm using Chestshop (which has also recently been fixed) as well as MCJobs and Vault. Sell works perfectly. Thanks again!!!!

**Comment by Sageavatar** [comment]
It works okay then eagl3s1ght?

**Comment by Sageavatar** [comment]
Sorry keepcalm, I actually just found another bug with /sell.

When using the command /sell hand, you will be paid for all of the sold item in your inventory that match the item in your hand. Although, the only items that disappear are the one in your hand.

I will double check but I believe that there are no errors printed in the console. I'll also try debugging and post tomorrow.

**Comment by eagl3s1ght** [comment]
@Sageavatar, I have already opened a new issue #490 for that. Please use search! :)

**Comment by Sageavatar** [comment]
Issue #490 References this.
