### ISSUE TITLE
[Honeypot] bukkitforgebuild 91

### ISSUE THREAD

**Issue by shakey2** [keepcalm/BukkitForge#342]
When I try to use the honeypot command with the honeypot plugin it just prints the command in chat. And what I mean by that is it just prints /honeypot in my chatlog.

**Comment by keplersj** [comment]
A log of what happens when the plugin is loaded and what happens when you type the command would help the most.

**Comment by shakey2** [comment]
Edit: My bad I didn't see the error on the console.

2013-01-23 15:50:13 [SEVERE] [BukkitForge] Error occurred while enabling Honeypot v1.4.4.2 (Is it up to date?)
java.lang.NullPointerException
    at com.argo.bukkit.util.PermissionSystem.getSystemInUseString(PermissionSystem.java:100)
    at com.argo.bukkit.util.PermissionSystem.setupPermissions(PermissionSystem.java:178)
    at com.argo.bukkit.util.PermissionSystem.setupPermissions(PermissionSystem.java:131)
    at com.argo.bukkit.honeypot.Honeypot.onEnable(Honeypot.java:52)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:430)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:936)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:920)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:256)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Unknown Source)

**Comment by keplersj** [comment]
What build are you using?

**Comment by shakey2** [comment]
bukkit forge build is in the title, using latest honeypot build(1.4.4.2).

edit: just tried with bukkitforge build 95, the problem is still there.
edit2: oddly if I use it on my offline server it doesn't work but when I put it on my public server it started working for some reason... Not sure if I should close this..
