### ISSUE TITLE
Can you Port this Plugins

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#35]
Greetings keepcalm can you port this plugins. Here my log.

I hope is usefull for you:

2012-12-20 17:10:33 [INFO] [BukkitForge] Plugins are being loaded...
2012-12-20 17:10:34 [INFO] [net.milkbowl.vault.Vault] [Vault] Loading Vault v1.2.22-b277
2012-12-20 17:10:34 [INFO] [com.dthielke.herochat.Herochat] [Herochat] Loading Herochat v5.6.1
2012-12-20 17:10:34 [INFO] [net.milkbowl.vault.Vault] [Vault] Enabling Vault v1.2.22-b277
2012-12-20 17:10:34 [INFO] [Minecraft] [Vault][Permission] SuperPermissions loaded as backup permission system.
2012-12-20 17:10:34 [INFO] [Minecraft] [Vault] Enabled Version 1.2.22-b277
2012-12-20 17:10:34 [INFO] [BukkitForge] Loading PostWorld plugins...
2012-12-20 17:10:34 [INFO] [com.dthielke.herochat.Herochat] [Herochat] Enabling Herochat v5.6.1
2012-12-20 17:10:34 [INFO] [Minecraft] [Herochat] Version 5.6.1 is enabled.
2012-12-20 17:10:35 [INFO] [Minecraft] [Herochat] Saving channels
2012-12-20 17:10:35 [INFO] [Minecraft] [Herochat] Save complete
2012-12-20 17:10:35 [INFO] [BukkitForge] Going to load perms file: permissions.yml
2012-12-20 17:10:35 [WARNING] [BukkitForge] Server permissions file permissions.yml is not valid YAML.
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadCustomPermissions(BukkitServer.java:923)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:879)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:232)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:36)
    at java.lang.Thread.run(Unknown Source)
2012-12-20 17:10:35 [INFO] [BukkitForge] Loaded plugins: 
2012-12-20 17:10:35 [INFO] [BukkitForge] Vault- Enabled: true
2012-12-20 17:10:35 [INFO] [BukkitForge] Herochat- Enabled: true

and have you a BukkitForge Website?

**Comment by Thornas88** [comment]
and can you make a tutorial about port a plugin.

**Comment by ariaththewise** [comment]
To port a plugin i thing you basically need to grab its source, copy it into Minecraft/src, and begin fixing errors ;) .

BukkitForge brings the BukkitAPI to Forge, so, i don't think you need to fix too many errors, because, the classes and methods the plugins seeks from the BukkitAPI should be here.

See ya!.

**Comment by Thornas88** [comment]
can you tell my step by step. I have the source.

**Comment by ariaththewise** [comment]
I fear there isn't any "step by step" way to port code, because each person has his own programming style.
Anyway, i do not think this is the best place to ask this.

I would suggest you to post this in the BukkitForge thread, to keep the issues section of GitHub as clean as possible :) .

See ya!

**Comment by keepcalm** [comment]
You need to change any net.minecraft.server references to their proper MCP names, change any com.google to guava10.com.google, but the problem you have is a bug in my code.
