### ISSUE TITLE
Server Crash with Build 86

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#355]
I Update today to Build 95

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 1/23/13 11:27 PM
Description: Exception in server tick loop

java.lang.NullPointerException
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:206)
    at net.minecraftforge.event.ASMEventHandler_44_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:338)
    at md.a(EntityLiving.java:993)
    at ow.a(SourceFile:195)
    at drzhark.customspawner.CustomSpawner.entityDespawnCheck(CustomSpawner.java:720)
    at drzhark.customspawner.CustomSpawner.despawnMob(CustomSpawner.java:800)
    at drzhark.customspawner.CustomSpawner.despawnMob(CustomSpawner.java:765)
    at drzhark.mocreatures.MoCServerTickHandler.onTickInGame(MoCServerTickHandler.java:44)
    at drzhark.mocreatures.MoCServerTickHandler.tickEnd(MoCServerTickHandler.java:95)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:634)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

**Comment by krim404** [comment]
Looks like this crash doesn't come from BF. Error points to Mo Creatures.

**Comment by dennis2001** [comment]
sometimes I get a crash on startup with build 90:

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 1/27/13 3:41 AM
Description: Exception ticking world

java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java:54)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkLoadEvent.<init>(ChunkLoadEvent.java:14)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkLoadEvent(ForgeEventHandler.java:492)
    at net.minecraftforge.event.ASMEventHandler_73_ForgeEventHandler_chunkLoadEvent_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at zz.c(Chunk.java:1086)
    at im.c(ChunkProviderServer.java:150)
    at im.d(ChunkProviderServer.java:166)
    at yc.e(World.java:521)
    at in.g(WorldServer.java:331)
    at in.b(WorldServer.java:180)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:669)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java:54)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkLoadEvent.<init>(ChunkLoadEvent.java:14)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkLoadEvent(ForgeEventHandler.java:492)
    at net.minecraftforge.event.ASMEventHandler_73_ForgeEventHandler_chunkLoadEvent_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at zz.c(Chunk.java:1086)
    at im.c(ChunkProviderServer.java:150)
    at im.d(ChunkProviderServer.java:166)
    at yc.e(World.java:521)
    at in.g(WorldServer.java:331)
    at in.b(WorldServer.java:180)

**Comment by keepcalm** [comment]
Methinks you should check jenkins before reporting bugs. And also make a new issue for unrelated bugs.
