### ISSUE TITLE
BukkitForge 1.4.6

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#36]
Is this Normal?

2012-12-21 11:29:29 [WARNING] [Minecraft] Can't keep up! Did the system time change, or is the server overloaded?
2012-12-21 11:29:32 [INFO] [STDERR] java.lang.IllegalArgumentException: Stream cannot be null
2012-12-21 11:29:32 [INFO] [STDERR]     at org.apache.commons.lang.Validate.notNull(Validate.java:203)
2012-12-21 11:29:32 [INFO] [STDERR]     at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:197)
2012-12-21 11:29:32 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.help.HelpYamlReader.<init>(HelpYamlReader.java:30)
2012-12-21 11:29:32 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.help.SimpleHelpMap.<init>(SimpleHelpMap.java:48)
2012-12-21 11:29:32 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:148)
2012-12-21 11:29:32 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:38)
2012-12-21 11:29:32 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2012-12-21 11:29:32 [INFO] [STDERR] java.lang.IllegalArgumentException: Stream cannot be null
2012-12-21 11:29:32 [INFO] [STDERR]     at org.apache.commons.lang.Validate.notNull(Validate.java:203)
2012-12-21 11:29:32 [INFO] [STDERR]     at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:120)
2012-12-21 11:29:32 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:184)
2012-12-21 11:29:32 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:38)
2012-12-21 11:29:32 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2012-12-21 11:29:33 [INFO] [BukkitForge] Bukkit API for Vanilla, version 1.4.5-3 starting up...
2012-12-21 11:29:33 [INFO] [BukkitForge] This server is running Minecraft Server 1.4.6, using FML 4.6.12.511, MinecraftForge 6.5.0.467, MCP v7.25 version BukkitForVanilla 1.4.5-R0.2 (Implementing API version 1.4.5-R0.2)
2012-12-21 11:29:33 [INFO] [STDERR] java.lang.IllegalArgumentException: Stream cannot be null
2012-12-21 11:29:33 [INFO] [STDERR]     at org.apache.commons.lang.Validate.notNull(Validate.java:203)
2012-12-21 11:29:33 [INFO] [STDERR]     at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:197)
2012-12-21 11:29:33 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.help.HelpYamlReader.<init>(HelpYamlReader.java:30)
2012-12-21 11:29:33 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.help.SimpleHelpMap.<init>(SimpleHelpMap.java:48)
2012-12-21 11:29:33 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:206)
2012-12-21 11:29:33 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:38)
2012-12-21 11:29:33 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2012-12-21 11:29:34 [INFO] [BukkitForge] Completing load...
2012-12-21 11:29:34 [INFO] [BukkitForge] Plugin folder doesn't exist: C:\Users\TEST\Desktop\Server 1.4.6.\plugins
2012-12-21 11:29:34 [INFO] [STDERR] java.lang.IllegalArgumentException: Stream cannot be null
2012-12-21 11:29:34 [INFO] [STDERR]     at org.apache.commons.lang.Validate.notNull(Validate.java:203)
2012-12-21 11:29:34 [INFO] [STDERR]     at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:197)
2012-12-21 11:29:34 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.help.HelpYamlReader.<init>(HelpYamlReader.java:30)
2012-12-21 11:29:34 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.help.SimpleHelpMap.initializeGeneralTopics(SimpleHelpMap.java:95)
2012-12-21 11:29:34 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:869)
2012-12-21 11:29:34 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:229)
2012-12-21 11:29:34 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:38)
2012-12-21 11:29:34 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2012-12-21 11:29:34 [INFO] [BukkitForge] Loading PostWorld plugins...
2012-12-21 11:29:34 [INFO] [BukkitForge] Going to load perms file: permissions.yml
2012-12-21 11:29:34 [INFO] [BukkitForge] Loaded plugins:

**Comment by Thornas88** [comment]
and please update all Essentials Ports, i becam Errors by all commands.

**Comment by ariaththewise** [comment]
I seriously don't understand why start trying v1.4.6.
We all (Bukkit too) should keep testing and polishing v1.4.5.

I don't understand the hurry, i suppose people loves dealing with new bugs every time :) .
