### ISSUE TITLE
[Worldguard] Entry Flag not working 

### ISSUE THREAD

**Issue by josua27176** [keepcalm/BukkitForge#362]
For world guard the entry flag and flags like entry are not working

**Comment by kopylov** [comment]
2013-01-25 10:50:40 [SEVERE] [BukkitForge] Could not pass event BlockPlaceEvent to LWC v4.3.1 (b767-git-MANUAL) (November 15, 2012)
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:397)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteraction(ForgeEventHandler.java:354)
    at net.minecraftforge.event.ASMEventHandler_102_ForgeEventHandler_onPlayerInteraction_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
    at ir.a(ItemInWorldManager.java:389)
    at iv.a(NetServerHandler.java:617)
    at fk.a(SourceFile:58)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:141)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at com.griefcraft.util.ProtectionFinder.tryLoadProtection(ProtectionFinder.java:274)
    at com.griefcraft.util.ProtectionFinder.matchBlocks(ProtectionFinder.java:105)
    at com.griefcraft.lwc.LWC.findProtection(LWC.java:1161)
    at com.griefcraft.listeners.LWCBlockListener.onBlockPlace(LWCBlockListener.java:324)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:395)
    ... 20 more
2013-01-25 10:50:42 [INFO] [STDERR] java.lang.NullPointerException
2013-01-25 10:50:42 [INFO] [STDERR]     at com.griefcraft.util.ProtectionFinder.tryLoadProtection(ProtectionFinder.java:274)
2013-01-25 10:50:42 [INFO] [STDERR]     at com.griefcraft.util.ProtectionFinder.matchBlocks(ProtectionFinder.java:105)
2013-01-25 10:50:42 [INFO] [STDERR]     at com.griefcraft.lwc.LWC.findProtection(LWC.java:1161)
2013-01-25 10:50:42 [INFO] [STDERR]     at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:135)
2013-01-25 10:50:42 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-25 10:50:42 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-01-25 10:50:42 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-01-25 10:50:42 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-01-25 10:50:42 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:395)
2013-01-25 10:50:42 [INFO] [STDERR]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
2013-01-25 10:50:42 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-01-25 10:50:42 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2013-01-25 10:50:42 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:461)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_105_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
2013-01-25 10:50:42 [INFO] [STDERR]     at ir.a(ItemInWorldManager.java:389)
2013-01-25 10:50:42 [INFO] [STDERR]     at iv.a(NetServerHandler.java:617)
2013-01-25 10:50:42 [INFO] [STDERR]     at fk.a(SourceFile:58)
2013-01-25 10:50:42 [INFO] [STDERR]     at cg.b(TcpConnection.java:458)
2013-01-25 10:50:42 [INFO] [STDERR]     at iv.d(NetServerHandler.java:141)
2013-01-25 10:50:42 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-01-25 10:50:42 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
2013-01-25 10:50:42 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-01-25 10:50:42 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-25 10:50:42 [INFO] [STDERR]     at fy.run(SourceFile:849)

**Comment by SpoonsJTD** [comment]
Dupe, and  believe this is fixed.
