### ISSUE TITLE
AuthMe Inventory not being protected

### ISSUE THREAD

**Issue by ruifung** [keepcalm/BukkitForge#366]
Caused by: java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventoryPlayer.setArmorContents(BukkitInventoryPlayer.java:59)
    at uk.org.whoami.authme.api.API.setPlayerInventory(API.java:170)
    at uk.org.whoami.authme.listener.AuthMePlayerListener.onPlayerQuit(AuthMePlayerListener.java:712)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:344)

**Comment by SpoonsJTD** [comment]
Dupe of  #273

**Comment by ruifung** [comment]
Oops. My bad, forgot about that.
