### ISSUE TITLE
Build 114 doesnt start.

### ISSUE THREAD

**Issue by FakedVI** [keepcalm/BukkitForge#370]
java.lang.IllegalArgumentException: Directory must be a directory
        at org.apache.commons.lang.Validate.isTrue(Validate.java:157)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:104)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:892)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:242)
        at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
        at java.lang.Thread.run(Thread.java:722)

**Comment by Bucky420** [comment]
works for me :P

**Comment by FakedVI** [comment]
Ehh... everytime it pops up with this message :(

**Comment by FakedVI** [comment]
2013-01-25 13:27:04 [INFO] [BukkitForge] Bukkit API for Vanilla, version 1.4.5-R0.2 starting up...
2013-01-25 13:27:04 [INFO] [BukkitForge] This server is running BukkitForge version git-Bukkit-1.4.5-R1.0-b3000jnks (Really: BukkitForge for MC 1.4.7) (Implementing API version 1.4.5-R0.2)
2013-01-25 13:27:04 [INFO] [BukkitForge] Plugins are being loaded...
2013-01-25 13:27:04 [SEVERE] [ForgeModLoader] Something real bad happened! The BukkitAPI will not be running for this Minecraft session.
You should _probably_ report this bug to the developer(s) at https://github.com/keepcalm/BukkitForge/issues
java.lang.IllegalArgumentException: Directory must be a directory
        at org.apache.commons.lang.Validate.isTrue(Validate.java:157)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:104)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:892)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:242)
        at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
        at java.lang.Thread.run(Thread.java:722)

Latest try, build 114. Does that every time I run the server.

**Comment by FakedVI** [comment]
OK SOLVED!

plugins was a file instead of directory, must of slipped my finger and instead of make directory i made a file :)
