### ISSUE TITLE
[Multiverse-Core] crashes server

### ISSUE THREAD

**Issue by evhub** [keepcalm/BukkitForge#374]
I get multiple different errors when running the server with the plugin Multiverse-Core  ([Link](http://dev.bukkit.org/server-mods/multiverse-core/)). Hopefully this issue can be resolved, this is a plugin I really rely on.

crash-reports/crash-2013-01-25_22.40.11-server.txt

```
---- Minecraft Crash Report ----
// My bad.

Time: 1/25/13 10:40 PM
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
    at in.a(WorldServer.java:536)
    at in.b(WorldServer.java:178)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:669)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at in.a(WorldServer.java:536)
    at in.b(WorldServer.java:178)

-- Affected level --
Details:
    Level name: DIM112
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 32 Drop: 0
    Level seed: -7581047654637648127
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (146,64,316), Chunk: (at 2,4,12 in 9,19; contains blocks 144,0,304 to 159,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 79 game time, 79 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 119200 (now: false), thunder time: 149180 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:669)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_05, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 262612560 bytes (250 MB) / 499953664 bytes (476 MB) up to 4225236992 bytes (4029 MB)
    JVM Flags: 2 total; -Xincgc -Xmx4G
    AABB Pool Size: 2779 (155624 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.26 FML v4.7.4.520 Minecraft Forge 6.6.0.497 37 mods loaded, 37 mods active
    mcp [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CodeChickenCore [CodeChicken Core] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge] (BukkitForge-1.4.7-116.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event] (BukkitForge-1.4.7-116.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    SAP_Man [SanAndreasPs Managers] (0_SAPManPack_v13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Core [BuildCraft] (abuildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Builders [BC Builders] (abuildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Energy [BC Energy] (abuildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Factory [BC Factory] (abuildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Transport [BC Transport] (abuildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BuildCraft|Silicon [BC Silicon] (abuildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EmasherCore [EmasherCore] (aEmasherCore-1.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    IC2 [IndustrialCraft 2] (aindustrialcraft-2_1.112.170-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Additional-Buildcraft-Objects [Additional Buildcraft Objects] (buildcraft-Z-additional-buildcraft-objects-0.9.6.73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChickenChunks [ChickenChunks] (ChickenChunks 1.2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CompactSolars [Compact Solar Arrays] (compactsolars-universal-1.4.6-3.2.0.21.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ComputerCraft [ComputerCraft] (ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CCTurtle [ComputerCraft Turtles] (ComputerCraft1.481.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ClaySoldiersMod [Clay Soldiers Mod] (CSM_v9_05.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CustomStuff2 [Custom Stuff 2] (customStuff2_0.9.7_Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    DungeonPack [DungeonPack] (DungeonPack 1.4.6 v2 Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    LegendaryBeasts [Legendary Beasts] (Forge_LegendaryBeastsAlpha1.4.6.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EmasherGas [GasCraft] (GasCraft-1.3.2-BETA-C.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    InfernalMobs [Infernal Mobs] (InfernalMobs_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AS_Kenshiro [Kenshiro Mod] (KenshiroMod_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Mystcraft [Mystcraft] (mystcraft-uni-1.4.6-0.9.5.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ObsidiPlates [Obsidian Pressure Plates] (obsidiplates-universal-1.2.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PowerCrystalsCore [PowerCrystals Core] (PowerCrystalsCore_1.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Railcraft [Railcraft] (Railcraft_1.4.6-6.14.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    RopesPlus [Ropes+] (RopePlus_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AS_UpdateCheck [AtomicStryker Update Check Mod] (UpdateCheckerMod_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    AdvancedPowerManagement [Advanced Power Management] (zAdvancedPowerManagement-1.1.55-IC2_1.112.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EmasherWorldGen [A Sufficient Number of Biomes] (zAS#B-1.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    ChargePads [Charge Pads] (zchargepads-universal-2.3.0.58.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    PowerConverters [Power Converters] (zPowerConverters_2.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: 1.4.6 (Bukkit API version 1.4.5-R0.2)
Plugins Loaded:Vault v1.2.22-b277: Enabled, WorldEdit v5.5.1: Enabled and Multiverse-Core v2.5-b651: Enabled
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 652 (36512 bytes; 0 MB) allocated, 651 (36456 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)
```

ForgeModLoader-server-0.log (Only relevant parts)

```
[com.onarandombox.MultiverseCore.MultiverseCore] [Multiverse-Core] Loading Multiverse-Core v2.5-b651

[...]

[com.onarandombox.MultiverseCore.MultiverseCore] [Multiverse-Core] Enabling Multiverse-Core v2.5-b651
2013-01-25 22:40:03 [INFO] [Minecraft] [AllPay] - Version 10.0 - using only an item based economy for Multiverse-Core v2.5-b651
2013-01-25 22:40:09 [INFO] [Minecraft] [Multiverse-Core] Loading World & Settings - 'worldx' - Env: NETHER - Type: NORMAL & seed: -7581047654637648127
2013-01-25 22:40:09 [INFO] [ForgeModLoader] Loading dimension 112 (DIM112) (ho@3fdc0ab7)
2013-01-25 22:40:09 [INFO] [ForgeModLoader] Loading dimension 112 (DIM112) (ho@3fdc0ab7)
2013-01-25 22:40:10 [INFO] [STDOUT] Preparing start region for level 3 (Seed: -7581047654637648127)Preparing spawn area for worldx, 0%
2013-01-25 22:40:11 [INFO] [STDERR] t: Exception ticking world
2013-01-25 22:40:11 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:675)
2013-01-25 22:40:11 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-25 22:40:11 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-01-25 22:40:11 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-25 22:40:11 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-25 22:40:11 [INFO] [STDERR] Caused by: java.lang.IllegalStateException: TickNextTick list out of synch
2013-01-25 22:40:11 [INFO] [STDERR]     at in.a(WorldServer.java:536)
2013-01-25 22:40:11 [INFO] [STDERR]     at in.b(WorldServer.java:178)
2013-01-25 22:40:11 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:669)
2013-01-25 22:40:11 [INFO] [STDERR]     ... 4 more
2013-01-25 22:40:11 [SEVERE] [Minecraft] Encountered an unexpected exception t
t: Exception ticking world
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:675)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.IllegalStateException: TickNextTick list out of synch
    at in.a(WorldServer.java:536)
    at in.b(WorldServer.java:178)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:669)
    ... 4 more
2013-01-25 22:40:11 [SEVERE] [Minecraft] This crash report has been saved to: C:\Users\Evan\SkyDrive\Minecraft\WARNING - DO NOT MODIFY\Mod Server\.\crash-reports\crash-2013-01-25_22.40.11-server.txt

[...]

2013-01-25 22:41:44 [WARNING] [Minecraft] [Multiverse-Core] Spawn location from world.dat file was unsafe. Adjusting...
2013-01-25 22:41:44 [WARNING] [Minecraft] [Multiverse-Core] Original Location: X: 146 Y: 64 Z: 316 P: 0 Y: 0 
2013-01-25 22:41:44 [INFO] [Minecraft] [Multiverse-Core] New Spawn for 'overworld' is located at: overworld:151.50,69.00,320.50:0.00:0.00
2013-01-25 22:41:45 [SEVERE] [BukkitForge] Error occurred while enabling Multiverse-Core v2.5-b651 (Is it up to date?)
java.lang.IllegalStateException: Lost reference to bukkit world 'overworld'
    at com.onarandombox.MultiverseCore.MVWorld.getCBWorld(MVWorld.java:488)
    at com.onarandombox.MultiverseCore.MVWorld$1.get(MVWorld.java:107)
    at com.onarandombox.MultiverseCore.MVWorld$1.get(MVWorld.java:96)
    at com.onarandombox.MultiverseCore.WorldProperties.isPVPEnabled(WorldProperties.java:439)
    at com.onarandombox.MultiverseCore.MVWorld.isPVPEnabled(MVWorld.java:808)
    at com.onarandombox.MultiverseCore.MVWorld.validateProperties(MVWorld.java:188)
    at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:91)
    at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56)
    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:408)
    at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:228)
    at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:178)
    at com.onarandombox.MultiverseCore.utils.WorldManager.loadDefaultWorlds(WorldManager.java:604)
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:306)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:379)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:887)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:871)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:227)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Unknown Source)
2013-01-25 22:41:45 [INFO] [BukkitForge] Going to load perms file: permissions.yml
2013-01-25 22:41:45 [INFO] [BukkitForge] Server permissions file permissions.yml is empty, ignoring it
2013-01-25 22:41:45 [INFO] [BukkitForge] Loaded plugins: 
2013-01-25 22:41:45 [INFO] [BukkitForge] Vault- Enabled: true
2013-01-25 22:41:45 [INFO] [BukkitForge] WorldEdit- Enabled: true
2013-01-25 22:41:45 [INFO] [BukkitForge] Multiverse-Core- Enabled: true
```

**Comment by gravypod** [comment]
MV is doing something out of sync with the main Thread. This is causing problems. Needs some looking into

**Comment by SpoonsJTD** [comment]
MV doesn't work (as logged in another issue), but it should not be throwing exceptions anymore.
