### ISSUE TITLE
Hawkeye Errors

### ISSUE THREAD

**Issue by Jadedwolf** [keepcalm/BukkitForge#383]
Latest hawkeye reloaded build and bukkitforge 129

2013-01-26 19:01:28 [SEVERE] [BukkitForge] Could not pass event BlockBreakEvent to HawkEye v1.1.0
org.bukkit.event.EventException
        at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:61)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at keepcalm.mods.bukkit.forgeHandler.BlockBreakEventHandler.onBlockBreak(BlockBreakEventHandler.java:32)
        at net.minecraftforge.event.ASMEventHandler_99_BlockBreakEventHandler_onBlockBreak_PlayerBreakBlockEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at keepcalm.mods.events.EventFactory.onBlockHarvested(EventFactory.java:11)
        at ir.d(ItemInWorldManager.java:271)
        at ir.b(ItemInWorldManager.java:330)
        at ir.a(ItemInWorldManager.java:205)
        at iv.a(NetServerHandler.java:509)
        at ei.a(SourceFile:46)
        at cg.b(TcpConnection.java:454)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at uk.co.oliwali.HawkEye.listeners.MonitorBlockListener.onBlockBreak(MonitorBlockListener.java:43)
        at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:58)
        ... 22 more
2013-01-26 19:01:30 [INFO] [STDOUT] Processing Shard
2013-01-26 19:01:36 [INFO] [STDOUT] Processing Shard
2013-01-26 19:01:40 [INFO] [STDOUT] Processing Shard
2013-01-26 19:01:44 [INFO] [STDOUT] Processing Shard

**Comment by SpoonsJTD** [comment]
Please recheck.

**Comment by eagl3s1ght** [comment]
BF230 with HawkEye V1.0.7b not generating any exceptions so far.

**Comment by SpoonsJTD** [comment]
Thanks!
