### ISSUE TITLE
Error with FeedTheBeast

### ISSUE THREAD

**Issue by FeuerTeufel** [keepcalm/BukkitForge#387]
Wenn i will join then :
Error handling login related packet - connection from xx_tomi_xx [/**_.**_.**_.**_:5039] refused
java.lang.NullPointerException
        at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.playerLoggedIn(ConnectionHandler.java:121)
        at cpw.mods.fml.common.network.NetworkRegistry.playerLoggedIn(NetworkRegistry.java:161)
        at cpw.mods.fml.common.network.FMLNetworkHandler.handlePlayerLogin(FMLNetworkHandler.java:281)
        at gm.a(ServerConfigurationManager.java:143)
        at it.completeConnection(NetLoginHandler.java:195)
        at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:153)
        at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
        at it.d(NetLoginHandler.java:179)
        at it.c(NetLoginHandler.java:72)
        at hu.a(ServerListenThread.java:56)
        at ht.b(SourceFile:29)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)

**Comment by gravypod** [comment]
1. Make sure that BukkitForge's jar is inside the "coremods" folder
2. What does their screen say?

**Comment by SpoonsJTD** [comment]
Can't reproduce.
