### ISSUE TITLE
Citizens loads but crashes

### ISSUE THREAD

**Issue by Sgttomva** [keepcalm/BukkitForge#390]
Citizens 2.0.7 wont load Citizens 1.2.1 loads but crashes when trying to create NPC.

**Comment by gravypod** [comment]
Can we see a crashlog?

**Comment by Sgttomva** [comment]
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:393)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:221)
    at net.minecraftforge.event.ASMEventHandler_138_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:338)
    at md.a(EntityLiving.java:993)
    at ow.a(SourceFile:195)
    at lq.d(Entity.java:1087)
    at lq.d(Entity.java:960)
    at md.e(EntityLiving.java:1436)
    at md.c(EntityLiving.java:1824)
    at md.j_(EntityLiving.java:843)
    at ow.j_(SourceFile:106)
    at yc.a(World.java:2293)
    at in.a(WorldServer.java:647)
    at yc.g(World.java:2255)
    at yc.h(World.java:2109)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/resources/npclib/CraftNPC
    at net.citizensnpcs.listeners.EntityListen.onEntityDamage(EntityListen.java:29)
    at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
    ... 26 more
2013-01-31 18:08:29 [INFO] [BukkitForge] sgttomva issued server command: npccreate storm
2013-01-31 18:08:29 [INFO] [STDERR] java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/Packet
2013-01-31 18:08:29 [INFO] [STDERR]     at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:112)
2013-01-31 18:08:29 [INFO] [STDERR]     at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:138)
2013-01-31 18:08:29 [INFO] [STDERR]     at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:218)
2013-01-31 18:08:29 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-31 18:08:29 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-01-31 18:08:29 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-01-31 18:08:29 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-01-31 18:08:29 [INFO] [STDERR]     at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:254)
2013-01-31 18:08:29 [INFO] [STDERR]     at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:146)
2013-01-31 18:08:29 [INFO] [STDERR]     at net.citizensnpcs.Citizens.onCommand(Citizens.java:144)
2013-01-31 18:08:29 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-01-31 18:08:29 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2013-01-31 18:08:29 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2013-01-31 18:08:29 [INFO] [STDERR]     at iv.d(NetServerHandler.java:768)
2013-01-31 18:08:29 [INFO] [STDERR]     at iv.a(NetServerHandler.java:734)
2013-01-31 18:08:29 [INFO] [STDERR]     at cu.a(SourceFile:44)
2013-01-31 18:08:29 [INFO] [STDERR]     at cg.b(TcpConnection.java:458)
2013-01-31 18:08:29 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2013-01-31 18:08:29 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-01-31 18:08:29 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-01-31 18:08:29 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
2013-01-31 18:08:29 [INFO] [STDERR]     at ho.r(DedicatedServer.java:269)
2013-01-31 18:08:29 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-01-31 18:08:29 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-31 18:08:29 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-31 18:08:29 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.Packet
2013-01-31 18:08:29 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:180)
2013-01-31 18:08:29 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:175)
2013-01-31 18:08:29 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-01-31 18:08:29 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-01-31 18:08:29 [INFO] [STDERR]     ... 25 more
2013-01-31 18:08:30 [INFO] [STDERR] java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/EntityPlayer
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass1(Native Method)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.security.SecureClassLoader.defineClass(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:242)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:194)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:290)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:186)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:175)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass1(Native Method)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.security.SecureClassLoader.defineClass(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:242)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:194)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:290)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:186)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:175)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at net.citizensnpcs.listeners.EntityListen.onEntityDamage(EntityListen.java:29)
2013-01-31 18:08:30 [INFO] [STDERR]     at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
2013-01-31 18:08:30 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:221)
2013-01-31 18:08:30 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_138_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
2013-01-31 18:08:30 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-01-31 18:08:30 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-01-31 18:08:30 [INFO] [STDERR]     at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:338)
2013-01-31 18:08:30 [INFO] [STDERR]     at md.a(EntityLiving.java:993)
2013-01-31 18:08:30 [INFO] [STDERR]     at ow.a(SourceFile:195)
2013-01-31 18:08:30 [INFO] [STDERR]     at lq.d(Entity.java:1087)
2013-01-31 18:08:30 [INFO] [STDERR]     at lq.d(Entity.java:960)
2013-01-31 18:08:30 [INFO] [STDERR]     at md.e(EntityLiving.java:1536)
2013-01-31 18:08:30 [INFO] [STDERR]     at md.c(EntityLiving.java:1824)
2013-01-31 18:08:30 [INFO] [STDERR]     at md.j_(EntityLiving.java:843)
2013-01-31 18:08:30 [INFO] [STDERR]     at ow.j_(SourceFile:106)
2013-01-31 18:08:30 [INFO] [STDERR]     at yc.a(World.java:2293)
2013-01-31 18:08:30 [INFO] [STDERR]     at in.a(WorldServer.java:647)
2013-01-31 18:08:30 [INFO] [STDERR]     at yc.g(World.java:2255)
2013-01-31 18:08:30 [INFO] [STDERR]     at yc.h(World.java:2109)
2013-01-31 18:08:30 [INFO] [STDERR]     at in.h(WorldServer.java:516)
2013-01-31 18:08:30 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
2013-01-31 18:08:30 [INFO] [STDERR]     at ho.r(DedicatedServer.java:269)
2013-01-31 18:08:30 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-01-31 18:08:30 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-31 18:08:30 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-31 18:08:30 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.EntityPlayer
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:180)
2013-01-31 18:08:30 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:175)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-01-31 18:08:30 [INFO] [STDERR]     ... 51 more

**Comment by gravypod** [comment]
Yes, we cannot fix that, they are attempting to use net.minecraft.server code. It is not supported by bukkit anymore as well.

**Comment by Sgttomva** [comment]
That server log was from my local mindcrack  server with thebnewest version
of bukkitforge, 190 I believe

**Comment by SpoonsJTD** [comment]
Use latest dev build and disable version check in the config.
