### ISSUE TITLE
[Runecraft] not working

### ISSUE THREAD

**Issue by evhub** [keepcalm/BukkitForge#392]
Runecraft ([Link](http://www.minecraftforum.net/topic/26803-softwarepluginbukkit-runecraft-214-e-bukkit-only-vanilla-port-in-progress/)) doesn't work and gives this error:

```
2013-01-27 23:00:16 [SEVERE] [BukkitForge] Error occurred while enabling Runecraft v0.12 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/World
    at Runecraft.onEnable(Runecraft.java:45)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:426)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:871)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:855)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:226)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:44)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.World
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:180)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:175)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 9 more
```

**Comment by gravypod** [comment]
This plugin wont work in Bukkit anymore as well. They are using code from minecraft that they shouldn't be.

**Comment by WhiplashD** [comment]
Pretty sure Runecraft is working in bukkit now, is there any plans on making it compatible with bukkit forge?

**Comment by SpoonsJTD** [comment]
WhiplashD, did you try it in a recent build?

**Comment by WhiplashD** [comment]
In Bukkit or bukkitforge? I have it on my current server (tekkit lite 0.5.9) which is running bukkitforge (latest version), and the same error EV opened up with still pops up. I've tried several of the runes and none work.

**Comment by bbcisdabomb** [comment]
Just tried Runecraft 2.16_c in vanilla bukkit and it worked fine. I'd like to add Runecraft to my server - is there a log or something I could submit to help?
