### ISSUE TITLE
server crash on startup

### ISSUE THREAD

**Issue by kaedelus** [keepcalm/BukkitForge#4]
Any ideas why this happened?

java.lang.IllegalArgumentException: Unknown entity
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:142)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.getBukkitEntity(BukkitEventFactory.java:102)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callCreatureSpawnEvent(BukkitEventFactory.java:272)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onEntityJoinWorld(ForgeEventHandler.java:63)
    at net.minecraftforge.event.ASMEventHandler_80_ForgeEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at xv.a(World.java:3723)
    at zs.c(Chunk.java:1065)
    at im.c(ChunkProviderServer.java:134)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:313)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:287)
    at ho.c(DedicatedServer.java:163)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:461)
    at fy.run(SourceFile:856)

**Comment by keepcalm** [comment]
left out a couple of entities updating to 1.4.5 O.o

Fixing it now

**Comment by dirge0** [comment]
Can you release the fixed version?
