### ISSUE TITLE
[WorldBorder] Task Exception for WorldBorder Fill Command

### ISSUE THREAD

**Issue by Factor2** [keepcalm/BukkitForge#404]
Hi

I dont think the /wb fill command works properly. Upon trying the command and confirming the command, the server console generates this output;

CONSOLE: [INFO] X issued server command: wborderfill confirm
WorldBorder: Filling out world to border at the command of player "X".
CONSOLE: [WARNING] Task #20 for WorldBorder v1.6.1 generated an exception

I believe it may have something to do with BukkitForge

Running BukkitForge-1.4.7-175

Edit:

I tried to cancel the command, using /wb fill cancel, and got an error in the console;

2:47:20 AM CONSOLE: [INFO] X issued server command: wborderfill cancel
2:47:20 AM CONSOLE: [INFO] org.bukkit.command.CommandException: Unhandled exception executing command 'wborder' in plugin WorldBorder v1.6.1
2:47:20 AM CONSOLE: [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
2:47:20 AM CONSOLE: [INFO] at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2:47:20 AM CONSOLE: [INFO] at x.a(CommandHandler.java:82)
2:47:20 AM CONSOLE: [INFO] at iv.d(NetServerHandler.java:768)
2:47:20 AM CONSOLE: [INFO] at iv.a(NetServerHandler.java:734)
2:47:20 AM CONSOLE: [INFO] at cu.a(SourceFile:44)
2:47:20 AM CONSOLE: [INFO] at cg.b(TcpConnection.java:458)
2:47:20 AM CONSOLE: [INFO] at iv.d(NetServerHandler.java:136)
2:47:20 AM CONSOLE: [INFO] at iw.b(NetworkListenThread.java:57)
2:47:20 AM CONSOLE: [INFO] at ht.b(SourceFile:30)
2:47:20 AM CONSOLE: [INFO] at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
2:47:20 AM CONSOLE: [INFO] at ho.r(DedicatedServer.java:269)
2:47:20 AM CONSOLE: [INFO] at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2:47:20 AM CONSOLE: [INFO] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2:47:20 AM CONSOLE: [INFO] at fy.run(SourceFile:849)
2:47:20 AM CONSOLE: [INFO] Caused by: java.lang.NullPointerException
2:47:20 AM CONSOLE: [INFO] at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.isChunkInUse(BukkitWorld.java:417)
2:47:20 AM CONSOLE: [INFO] at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunkRequest(BukkitWorld.java:299)
2:47:20 AM CONSOLE: [INFO] at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.unloadChunkRequest(BukkitWorld.java:295)
2:47:20 AM CONSOLE: [INFO] at com.wimbli.WorldBorder.WorldFillTask.stop(WorldFillTask.java:323)
2:47:20 AM CONSOLE: [INFO] at com.wimbli.WorldBorder.WorldFillTask.cancel(WorldFillTask.java:304)
2:47:20 AM CONSOLE: [INFO] at com.wimbli.WorldBorder.Config.StopFillTask(Config.java:270)
2:47:20 AM CONSOLE: [INFO] at com.wimbli.WorldBorder.WBCommand.cmdFill(WBCommand.java:749)
2:47:20 AM CONSOLE: [INFO] at com.wimbli.WorldBorder.WBCommand.onCommand(WBCommand.java:503)
2:47:20 AM CONSOLE: [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2:47:20 AM CONSOLE: [INFO] ... 14 more

**Comment by gravypod** [comment]
Test with the latest build, It might work

**Comment by Factor2** [comment]
Tried with build 196. I still receive this output;

CONSOLE: [INFO] X issued server command: wborder2
CONSOLE: [INFO] X issued server command: wborderoverworld fill 20
CONSOLE: [INFO] X issued server command: wborderfill confirm
WorldBorder: Filling out world to border at the command of player "X".
CONSOLE: [WARNING] Task #50 for WorldBorder v1.6.1 generated an exception

Not sure if its working as intended.

**Comment by mrdeadlocked** [comment]
I get a error with WB as well

2013-02-04 04:33:09 [INFO] [STDERR] org.bukkit.command.CommandException: Unhandled exception executing command 'wborder' in plugin WorldBorder v1.6.1
2013-02-04 04:33:09 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
2013-02-04 04:33:09 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2013-02-04 04:33:09 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2013-02-04 04:33:09 [INFO] [STDERR]     at iv.d(NetServerHandler.java:768)
2013-02-04 04:33:09 [INFO] [STDERR]     at iv.a(NetServerHandler.java:734)
2013-02-04 04:33:09 [INFO] [STDERR]     at cu.a(SourceFile:44)
2013-02-04 04:33:09 [INFO] [STDERR]     at cg.b(TcpConnection.java:458)
2013-02-04 04:33:09 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2013-02-04 04:33:09 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-02-04 04:33:09 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-02-04 04:33:09 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
2013-02-04 04:33:09 [INFO] [STDERR]     at ho.r(DedicatedServer.java:269)
2013-02-04 04:33:09 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-02-04 04:33:09 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-02-04 04:33:09 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-02-04 04:33:09 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-02-04 04:33:09 [INFO] [STDERR]     at org.bukkit.craftbukkit.CraftWorld.isChunkInUse(CraftWorld.java:366)
2013-02-04 04:33:09 [INFO] [STDERR]     at org.bukkit.craftbukkit.CraftWorld.unloadChunkRequest(CraftWorld.java:294)
2013-02-04 04:33:09 [INFO] [STDERR]     at org.bukkit.craftbukkit.CraftWorld.unloadChunkRequest(CraftWorld.java:290)
2013-02-04 04:33:09 [INFO] [STDERR]     at com.wimbli.WorldBorder.WorldFillTask.stop(WorldFillTask.java:323)
2013-02-04 04:33:09 [INFO] [STDERR]     at com.wimbli.WorldBorder.WorldFillTask.cancel(WorldFillTask.java:304)
2013-02-04 04:33:09 [INFO] [STDERR]     at com.wimbli.WorldBorder.Config.StopFillTask(Config.java:270)
2013-02-04 04:33:09 [INFO] [STDERR]     at com.wimbli.WorldBorder.WBCommand.cmdFill(WBCommand.java:749)
2013-02-04 04:33:09 [INFO] [STDERR]     at com.wimbli.WorldBorder.WBCommand.onCommand(WBCommand.java:503)
2013-02-04 04:33:09 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-02-04 04:33:09 [INFO] [STDERR]     ... 14 more

**Comment by recon88** [comment]
Still not working with the latest builds.

**Comment by mrdeadlocked** [comment]
Same as recon88. Waiting and anxious. terrain generation is something that's been missing!

**Comment by gravypod** [comment]
We are still working on getting events working, then we will tend to this.

**Comment by recon88** [comment]
Well switching to mcpc then until you guys got all that stuff working...

**Comment by mrdeadlocked** [comment]
mcpc work along with forger server?

**Comment by recon88** [comment]
mcpc IS a forge/bukkit server ;)
