### ISSUE TITLE
[build 79][worldedit npe] no-clue as to why this happens 

### ISSUE THREAD

**Issue by Bucky420** [keepcalm/BukkitForge#407]
2013-01-30 06:05:18 [WARNING] [Minecraft.WorldEdit] WorldEdit: Failed to do NMS safe block set
java.lang.NullPointerException
        at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:1330)
        at com.sk89q.worldedit.EditSession.rawSetBlock(EditSession.java:237)
        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:707)
        at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1409)
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247)
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
        at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
        at x.a(CommandHandler.java:82)
        at iv.d(NetServerHandler.java:768)
        at iv.a(NetServerHandler.java:734)
        at cu.a(SourceFile:44)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)

seams to happen when you do //undo

**Comment by shakey2** [comment]
That is an OLD build, we are on build 184 now. I'd suggest updating, there are no "stable" builds yet so there isn't much reason to hold back updating for that long.

**Comment by Bucky420** [comment]
im updaitng now :D
