### ISSUE TITLE
Survival games.

### ISSUE THREAD

**Issue by Benet** [keepcalm/BukkitForge#414]
2013-01-31 12:01:46 [INFO] [BukkitForge] Benets7 issued server command: survivalgamessetlobbywall
2013-01-31 12:01:46 [INFO] [STDERR] java.lang.ClassCastException: org.bukkit.craftbukkit.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
2013-01-31 12:01:46 [INFO] [STDERR]     at com.skitscape.survivalgames.LobbyManager.loadSigns(LobbyManager.java:64)
2013-01-31 12:01:46 [INFO] [STDERR]     at com.skitscape.survivalgames.LobbyManager.setLobbySignsFromSelection(LobbyManager.java:159)
2013-01-31 12:01:46 [INFO] [STDERR]     at com.skitscape.survivalgames.commands.SetLobbyWall.onCommand(SetLobbyWall.java:20)
2013-01-31 12:01:46 [INFO] [STDERR]     at com.skitscape.survivalgames.CommandHandler.onCommand(CommandHandler.java:122)
2013-01-31 12:01:46 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-01-31 12:01:46 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2013-01-31 12:01:46 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2013-01-31 12:01:46 [INFO] [STDERR]     at iv.d(NetServerHandler.java:768)
2013-01-31 12:01:46 [INFO] [STDERR]     at iv.a(NetServerHandler.java:734)
2013-01-31 12:01:46 [INFO] [STDERR]     at cu.a(SourceFile:44)
2013-01-31 12:01:46 [INFO] [STDERR]     at cg.b(TcpConnection.java:458)
2013-01-31 12:01:46 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2013-01-31 12:01:46 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-01-31 12:01:46 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-01-31 12:01:46 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
2013-01-31 12:01:46 [INFO] [STDERR]     at ho.r(DedicatedServer.java:269)
2013-01-31 12:01:46 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-01-31 12:01:46 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-31 12:01:46 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-31 12:03:08 [WARNING] [Minecraft] Can't keep up! Did the system time change, or is the server overloaded?

Creating arena and teleports are working.

**Comment by keepcalm** [comment]
What did you do?

**Comment by Benet** [comment]
http://dev.bukkit.org/server-mods/survival-games/pages/setup/lobby/

I created this sign wall, typed /sg setlobbywall to activate it and server console printed this error. Of course wall didn't worked.
