### ISSUE TITLE
Mystcraft Issue?

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#423]
There seems to be an issue with regards to Mystcraft having and owning ages... I get kicked whenever I try to use one.

I am using the latest version of the Direwolf20 ModPack, with BukkitForge being the only change (Plugins: bPermissions, BOSEconomy, WorldGuard and WorldEdit). I am an op.

Log Errors

ForgeModLoader-server-0.log (Extract):

2013-02-01 11:04:54 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 3505
java.lang.NullPointerException
    at iv.a(NetServerHandler.java:639)
    at fk.a(SourceFile:58)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
2013-02-01 11:04:54 [WARNING] [Minecraft] Failed to handle packet for Propoke24/192.168.2.7: java.lang.NullPointerException
java.lang.NullPointerException
    at iv.a(NetServerHandler.java:639)
    at fk.a(SourceFile:58)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
2013-02-01 11:04:54 [INFO] [STDOUT] RemovePlayer: Propoke24
2013-02-01 11:04:54 [INFO] [STDOUT] Unloading Player: Propoke24
2013-02-01 11:05:04 [FINEST] [ForgeModLoader] Received valid FML login packet from /192.168.2.7:51054

And the server.log:

2013-02-01 11:04:49 [INFO] Giving Propoke24 1 of Descriptive Book
2013-02-01 11:04:54 [WARNING] Failed to handle packet for Propoke24/192.168.2.7: java.lang.NullPointerException
java.lang.NullPointerException
    at iv.a(NetServerHandler.java:639)
    at fk.a(SourceFile:58)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

This doesn't crash the server - just disconnects me, and I can re-join (As shown by the last entry in the forge log)

Hope you can find the fix soon. I don't know if this error occurs with regards to Twilight Forest (Never used the Mod, so I don't know how to test)

Thank you in advance,

Propoke24

**Comment by SpoonsJTD** [comment]
Lots of world management changes have been made, please recheck.

**Comment by secondfry** [comment]
Mystcraft 0.10.0.0 works for me correctly.
