### ISSUE TITLE
Command Failure

### ISSUE THREAD

**Issue by creodor** [keepcalm/BukkitForge#43]
Using the latest version (1.4.6-6) of BukkitForge, I attempt to use any command, and it fails with a message like this one:

2012-12-24 02:59:53 [INFO] [STDOUT] Allowing user creodor to run commandtp
2012-12-24 02:59:53 [INFO] [STDERR] org.bukkit.command.CommandException: Unhandled exception executing command 'tp' in plugin Essentials v${build.number}
2012-12-24 02:59:53 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
2012-12-24 02:59:53 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:117)
2012-12-24 02:59:53 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2012-12-24 02:59:53 [INFO] [STDERR]     at iv.d(NetServerHandler.java:768)
2012-12-24 02:59:53 [INFO] [STDERR]     at iv.a(NetServerHandler.java:734)
2012-12-24 02:59:53 [INFO] [STDERR]     at cu.a(SourceFile:44)
2012-12-24 02:59:53 [INFO] [STDERR]     at cg.b(TcpConnection.java:454)
2012-12-24 02:59:53 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2012-12-24 02:59:53 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2012-12-24 02:59:53 [INFO] [STDERR]     at ht.b(SourceFile:30)
2012-12-24 02:59:53 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
2012-12-24 02:59:53 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2012-12-24 02:59:53 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
2012-12-24 02:59:53 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2012-12-24 02:59:53 [INFO] [STDERR]     at fy.run(SourceFile:849)
2012-12-24 02:59:53 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2012-12-24 02:59:53 [INFO] [STDERR]     at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:308)
2012-12-24 02:59:53 [INFO] [STDERR]     at com.earth2me.essentials.Essentials.onCommand(Essentials.java:299)
2012-12-24 02:59:53 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2012-12-24 02:59:53 [INFO] [STDERR]     ... 14 more

---

I'm not sure how relevant it is, but during server launch, this error is generated for a couple of the essentials plugins (again, using the latest from Github, 2.9.5)

2012-12-24 02:59:22 [SEVERE] [BukkitForge] Error occurred while enabling Essentials v${build.number} (Is it up to date?)
java.lang.NoClassDefFoundError: guava10/com/google/common/io/Files
    at com.earth2me.essentials.EssentialsConf.save(EssentialsConf.java:360)
    at com.earth2me.essentials.EssentialsConf.save(EssentialsConf.java:339)
    at com.earth2me.essentials.EssentialsUpgrade.updateSpawnsToNewSpawnsConfig(EssentialsUpgrade.java:731)
    at com.earth2me.essentials.EssentialsUpgrade.afterSettings(EssentialsUpgrade.java:812)
    at com.earth2me.essentials.Essentials.onEnable(Essentials.java:165)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:901)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:885)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:236)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:38)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: guava10.com.google.common.io.Files
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 13 more

---

Finally, when I attempt to run the /stop command in the console, all i get is:

/stop
2012-12-24 03:05:37 [INFO] [STDOUT] Allowing user Server to run commandstop
2012-12-24 03:05:37 [INFO] [BukkitForge] CONSOLE: Stopping the server..
2012-12-24 03:05:37 [INFO] [BukkitForge] Stopping the Bukkit API 1.4.6

But the server does not actually stop. I can run the command as often as I like, and get no different response. I end up having to kill the process manually.

---

Forge is presently #473. I tested this both with and without additional mods and get the same result in either case. I also had these (or similar) errors with every other 1.4.6 version of BukkitForge. I did NOT have this error with 1.4.5 BukkitForge.
Normally I would be inclined to create separate issues for each of these, but in this case they all seem related. I can provide additional information if required.

**Comment by keepcalm** [comment]
Ya, sorry about this, the whole transition isn't working to well. Fix is to download [this](https://github.com/keepcalm/BukkitForge/blob/master/lib/guava10-renamed.jar?raw=true) and put it in the mods folder. That's a temporary fix, mind... As for stop, sorry. I'll fix that.

**Comment by creodor** [comment]
Seems to be working with that file. Stop is still not behaving properly, but at least you got me part of the way there! Thanks for the quick response, and hopefully you can get stop working soon :)

**Comment by keepcalm** [comment]
Sweet! I'll fix that in a few days.
