### ISSUE TITLE
Hawkeye PlayerInteractEvent Bug

### ISSUE THREAD

**Issue by profjb** [keepcalm/BukkitForge#434]
This is the error that turns up on my console pretty much every 2 seconds. It seems to be conflicting with a person breaking a block. It SEVERELY lags the server each time. Im wondering if their is a fix or better blocklog plugin. Thanks!

sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
02.02 22:50:49 [Server] INFO at uk.co.oliwali.HawkEye.listeners.MonitorPlayerListener.onPlayerInteract(MonitorPlayerListener.java:112)
02.02 22:50:49 [Server] INFO at uk.co.oliwali.HawkEye.ContainerAccessManager.checkInventoryOpen(ContainerAccessManager.java:55)
02.02 22:50:49 [Server] INFO at uk.co.oliwali.HawkEye.util.InventoryUtil.getContainerContents(InventoryUtil.java:131)
02.02 22:50:49 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventory.getContents(BukkitInventory.java:44)
02.02 22:50:49 [Server] INFO at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventory.getSize(BukkitInventory.java:31)
02.02 22:50:49 [Server] INFO Caused by: java.lang.NullPointerException
02.02 22:50:49 [Server] INFO at fy.run(SourceFile:849)
02.02 22:50:49 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
02.02 22:50:49 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
02.02 22:50:49 [Server] INFO at ho.r(DedicatedServer.java:269)
02.02 22:50:49 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
02.02 22:50:49 [Server] INFO at ht.b(SourceFile:30)
02.02 22:50:49 [Server] INFO at iw.b(NetworkListenThread.java:57)
02.02 22:50:49 [Server] INFO at iv.d(NetServerHandler.java:136)
02.02 22:50:49 [Server] INFO at cg.b(TcpConnection.java:458)
02.02 22:50:49 [Server] INFO at fk.a(SourceFile:58)
02.02 22:50:49 [Server] INFO at iv.a(NetServerHandler.java:578)
02.02 22:50:49 [Server] INFO at ir.a(ItemInWorldManager.java:389)
02.02 22:50:49 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
02.02 22:50:49 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
02.02 22:50:49 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
02.02 22:50:49 [Server] INFO at net.minecraftforge.event.ASMEventHandler_120_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
02.02 22:50:49 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:464)
02.02 22:50:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
02.02 22:50:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
02.02 22:50:49 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
02.02 22:50:49 [Server] INFO at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:61)
02.02 22:50:49 [Server] INFO org.bukkit.event.EventException
02.02 22:50:49 [Server] SEVERE Could not pass event PlayerInteractEvent to HawkEye v1.1.0

**Comment by SpoonsJTD** [comment]
From what I've heard, Hawkeye works now.

**Comment by eagl3s1ght** [comment]
@SpoonsJTD This one still seems to be alive.

`03-03 16:14:08 [SEVERE] [BukkitForge] Could not pass event PlayerInteractEvent to HawkEye v1.0.7b
org.bukkit.event.EventException
        at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:58)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at keepcalm.mods.bukkit.BukkitEventRouter.callEvent(BukkitEventRouter.java:24)
        at keepcalm.mods.bukkit.BukkitEventRouters$PlayerCaller$PlayerInteractCaller.callEvent(BukkitEventRouters.java:161)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:390)
        at net.minecraftforge.event.ASMEventHandler_84_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at ir.a(ItemInWorldManager.java:159)
        at iv.a(NetServerHandler.java:509)
        at ei.a(SourceFile:46)
        at cg.i(TcpConnection.java:347)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
Caused by: java.lang.NullPointerException
        at uk.co.oliwali.HawkEye.listeners.MonitorPlayerListener.onPlayerInteract(MonitorPlayerListener.java:104)
        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at uk.co.oliwali.HawkEye.listeners.HawkEyeListener$1.execute(HawkEyeListener.java:56)
        ... 16 more`
