### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Talenemrys** [keepcalm/BukkitForge#435]
Howdy there, I'm having a problem with BukkitForge, using Direwolf's pack (v5), and BukkitForge Build 200.. I can't start my server!

Starting the server abruptly ennds before anything much can be loaded:

~~~~~~READ FROM BOTTOM TO TOP~~~~~

03.02 01:16:51 [Server] SEVERE This crash report has been saved to: /./crash-reports/crash-2013-02-03_01.16.51-server.txt
03.02 01:16:51 [Server] INFO at fy.run(SourceFile:849)
03.02 01:16:51 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
03.02 01:16:51 [Server] INFO at ho.c(DedicatedServer.java:64)
03.02 01:16:51 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
03.02 01:16:51 [Server] INFO at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
03.02 01:16:51 [Server] INFO at cpw.mods.fml.common.Loader.loadMods(Loader.java:461)
03.02 01:16:51 [Server] INFO at cpw.mods.fml.common.Loader.sortModList(Loader.java:222)
03.02 01:16:51 [Server] INFO cpw.mods.fml.common.MissingModsException
03.02 01:16:51 [Server] SEVERE Encountered an unexpected exception MissingModsException
03.02 01:16:51 [Server] INFO at fy.run(SourceFile:849)
03.02 01:16:51 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
03.02 01:16:51 [Server] INFO at ho.c(DedicatedServer.java:64)
03.02 01:16:51 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
03.02 01:16:51 [Server] INFO at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
03.02 01:16:51 [Server] INFO at cpw.mods.fml.common.Loader.loadMods(Loader.java:461)
03.02 01:16:51 [Server] INFO at cpw.mods.fml.common.Loader.sortModList(Loader.java:222)
03.02 01:16:51 [Server] INFO cpw.mods.fml.common.MissingModsException
03.02 01:16:51 [Server] SEVERE The mod MiscPeripherals (MiscPeripherals) requires mods [ComputerCraft, CCTurtle] to be available
03.02 01:16:51 [Server] INFO Forge Mod Loader has identified 46 mods to load
03.02 01:16:49 [Server] INFO Searching /mods for mods
03.02 01:16:49 [Server] INFO Completed early MinecraftForge initialization
03.02 01:16:49 [Server] INFO Replaced 84 ore recipies
03.02 01:16:48 [Server] INFO MinecraftForge v6.6.0.515 Initialized
03.02 01:16:48 [Server] INFO MinecraftForge v6.6.0.515 Initialized
03.02 01:16:48 [Server] INFO Attempting early MinecraftForge initialization
03.02 01:16:48 [Server] INFO Starting minecraft server version 1.4.7
03.02 01:16:48 [Server] INFO 27 achievements
03.02 01:16:48 [Server] INFO 210 recipes
03.02 01:16:48 [Server] INFO Inserted GameData hook
03.02 01:16:47 [Server] INFO Adding Accesstransformer map: nei_at.cfg
03.02 01:16:47 [Server] INFO Adding Accesstransformer map: codechickencore_at.cfg
03.02 01:16:47 [Server] INFO Found valid fingerprint for Minecraft Forge. Certificate fingerprint de4cf8a3f3bc15635810044c39240bf96804ea7d
03.02 01:16:46 [Server] INFO Download complete
03.02 01:16:46 [Server] INFO Downloading file http://files.minecraftforge.net/fmllibs/bcprov-jdk15on-147.jar
03.02 01:16:46 [Server] INFO Download complete
03.02 01:16:46 [Server] INFO Downloading file http://files.minecraftforge.net/fmllibs/asm-all-4.0.jar
03.02 01:16:46 [Server] INFO Download complete
03.02 01:16:46 [Server] INFO Downloading file http://files.minecraftforge.net/fmllibs/guava-12.0.1.jar
03.02 01:16:46 [Server] INFO Download complete
03.02 01:16:45 [Server] INFO Downloading file http://files.minecraftforge.net/fmllibs/argo-2.25.jar
03.02 01:16:45 [Server] INFO Forge Mod Loader version 4.7.22.539 for Minecraft 1.4.7 loading
03.02 01:16:45 [Multicraft] Loaded config for "Mod: Direwolf20"
03.02 01:16:45 [Multicraft] Starting server!

```

The contents of the Error text document are as follows:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2/3/13 1:16 AM
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
    at cpw.mods.fml.common.Loader.sortModList(Loader.java:222)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:461)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Linux (amd64) version 2.6.32-279.19.1.el6.x86_64
    Java Version: 1.7.0_01, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1169093816 bytes (1114 MB) / 1507328000 bytes (1437 MB) up to 1507328000 bytes (1437 MB)
    JVM Flags: 2 total; -Xmx1500M -Xms1500M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.26a FML v4.7.22.539 Minecraft Forge 6.6.0.515 46 mods loaded, 46 mods active
    mcp [Minecraft Coder Pack] (minecraft.jar) Unloaded
    FML [Forge Mod Loader] (coremods) Unloaded
    Forge [Minecraft Forge] (coremods) Unloaded
    CodeChickenCore [CodeChicken Core] (coremods) Unloaded
    NotEnoughItems [Not Enough Items] (coremods) Unloaded
    Thaumcraft [Thaumcraft] (Thaumcraft.zip) Unloaded
    EE3 [Equivalent Exchange 3] (ee3.jar) Unloaded
    EnderStorage [EnderStorage] (enderstorage.jar) Unloaded
    BinnieCore [Binnie Core] (extrabees.zip) Unloaded
    ExtraBees [Extra Bees] (extrabees.zip) Unloaded
    ExtrabiomesXL [ExtrabiomesXL] (extrabiomesxl.jar) Unloaded
    factorization [Factorization] (factorization.jar) Unloaded
    Forestry [Forestry for Minecraft] (forestry.jar) Unloaded
    GraviGun [GraviGun] (gravigun.zip) Unloaded
    GraviSuite [Gravitation Suite] (gravisuite.zip) Unloaded
    IC2 [IndustrialCraft 2] (ic2.jar) Unloaded
    IC2NuclearControl [Nuclear Control] (ic2nuclearcontrol.zip) Unloaded
    IronChest [Iron Chest] (ironchest.zip) Unloaded
    MiscPeripherals [MiscPeripherals] (miscperipherals.zip) Unloaded
    ModularForceFieldSystem [Modular ForceField System V2] (modularforcefieldsystem.zip) Unloaded
    Mystcraft [Mystcraft] (mystcraft.zip) Unloaded
    ObsidiPlates [Obsidian Pressure Plates] (obsidiplates.zip) Unloaded
    OmniTools [OmniTools] (omnitools.zip) Unloaded
    PortalGun [Portal Gun] (portalgun.zip) Unloaded
    Railcraft [Railcraft] (railcraft.zip) Unloaded
    RedPowerCompat [RP Compat] (redpowercompat.zip) Unloaded
    RedPowerCore [RedPower] (redpowercore.zip) Unloaded
    RedPowerBase [RP Base] (redpowercore.zip) Unloaded
    RedPowerWiring [RP Wiring] (redpowerdigital.zip) Unloaded
    RedPowerLogic [RP Logic] (redpowerdigital.zip) Unloaded
    RedPowerLighting [RP Lighting] (redpowerdigital.zip) Unloaded
    RedPowerWorld [RP World] (redpowermechanical.zip) Unloaded
    RedPowerMachine [RP Machine] (redpowermechanical.zip) Unloaded
    RedPowerControl [RP Control] (redpowermechanical.zip) Unloaded
    SoulShards [SoulShards] (soulshards.zip) Unloaded
    StevesCarts [Steve's Carts] (stevescarts.zip) Unloaded
    ThermalExpansion [Thermal Expansion] (thermalexpansion.zip) Unloaded
    ThermalExpansion|Energy [Energy] (thermalexpansion.zip) Unloaded
    ThermalExpansion|Factory [Factory] (thermalexpansion.zip) Unloaded
    ThermalExpansion|NEI [NEI] (thermalexpansion.zip) Unloaded
    ThermalExpansion|Transport [Transport] (thermalexpansion.zip) Unloaded
    TwilightForest [The Twilight Forest] (twilightforest.zip) Unloaded
    WR-CBE|Addons [WR-CBE Addons] (wirelessredstoneaddons.jar) Unloaded
    WR-CBE|Core [WR-CBE Core] (wirelessredstonecore.jar) Unloaded
    WR-CBE|RedPower [WR-CBE RedPower] (wirelessredstoneredpower.jar) Unloaded
    XyCraft [XyCraft] (xycraft.zip) Unloaded
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)
```

**Comment by shakey2** [comment]
"03.02 01:16:51 [Server] SEVERE The mod MiscPeripherals (MiscPeripherals) requires mods [ComputerCraft, CCTurtle] to be available"

Looks to me like your problem has nothing to do with Bukkitforge

**Comment by Talenemrys** [comment]
Sorry, I've worked it out, my hosting is deleting the bukkitforge jar as the server is using it, and that's just where the error is thrown.. I thought it was bukkitforge, as it only occured when this jar was in the coremods folder, but I think I have it now, never mind
