### ISSUE TITLE
[LogBlock] Cannot use query tools

### ISSUE THREAD

**Issue by darkvirus** [keepcalm/BukkitForge#441]
When issuing the command lb tool or lb toolblock i get the item (wood pickaxe or bedrock) but then a message saying error, check server.log.

This is then found in the forge log.

Build #91 of Bukkitforge as its the only one permissions works with
Latest logblock

013-02-04 04:54:07 [INFO] [BukkitForge] Darkvirusx issued server command: lbtoolblock
2013-02-04 04:54:07 [WARNING] [BukkitForge] Exception in commands handler: 
java.lang.NullPointerException
    at de.diddiz.LogBlock.CommandsHandler.onCommand(CommandsHandler.java:144)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
2013-02-04 04:54:08 [SEVERE] [BukkitForge] Could not pass event PlayerInteractEvent to LogBlock v1.70
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:397)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:464)
    at net.minecraftforge.event.ASMEventHandler_118_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
    at ir.a(ItemInWorldManager.java:389)
    at iv.a(NetServerHandler.java:578)
    at fk.a(SourceFile:58)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at de.diddiz.LogBlock.listeners.ToolListener.onPlayerInteract(ToolListener.java:51)
    at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:395)
    ... 20 more

**Comment by ghost** [comment]
You have to update to the latest builds of BukkitForge since it works, using an older build and complaining about bugs in it is kind of pointless.
