### ISSUE TITLE
This mod never works..

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#45]
2012-12-25 16:30:48 [SEVERE] [ForgeModLoader] Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue
2012-12-25 16:30:48 [SEVERE] [ForgeModLoader] 
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML [Forge Mod Loader](coremods) Unloaded->Constructed
    Forge [Minecraft Forge](coremods) Unloaded->Constructed
    BukkitForge [BukkitForge](BukkitForge-1.4.6-6.jar) Unloaded->Errored
2012-12-25 16:30:48 [SEVERE] [ForgeModLoader] The following problems were captured during this phase
2012-12-25 16:30:48 [SEVERE] [ForgeModLoader] Caught exception from BukkitForge
java.lang.NullPointerException
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:445)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:478)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:345)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
2012-12-25 16:30:48 [INFO] [STDERR] java.lang.NullPointerException
2012-12-25 16:30:48 [INFO] [STDERR]     at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:445)
2012-12-25 16:30:48 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-12-25 16:30:48 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-12-25 16:30:48 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-12-25 16:30:48 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2012-12-25 16:30:48 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2012-12-25 16:30:48 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2012-12-25 16:30:48 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2012-12-25 16:30:48 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2012-12-25 16:30:48 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2012-12-25 16:30:48 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
2012-12-25 16:30:48 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-12-25 16:30:48 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-12-25 16:30:48 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-12-25 16:30:48 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2012-12-25 16:30:48 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2012-12-25 16:30:48 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2012-12-25 16:30:48 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2012-12-25 16:30:48 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2012-12-25 16:30:48 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2012-12-25 16:30:48 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
2012-12-25 16:30:48 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.loadMods(Loader.java:478)
2012-12-25 16:30:48 [INFO] [STDERR]     at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
2012-12-25 16:30:48 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:345)
2012-12-25 16:30:48 [INFO] [STDERR]     at ho.c(DedicatedServer.java:64)
2012-12-25 16:30:48 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
2012-12-25 16:30:48 [INFO] [STDERR]     at fy.run(SourceFile:849)
2012-12-25 16:30:48 [SEVERE] [Minecraft] Encountered an unexpected exception NullPointerException
java.lang.NullPointerException
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:445)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:478)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:345)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
2012-12-25 16:30:48 [SEVERE] [Minecraft] This crash report has been saved to: C:\Server 1.4.6.\crash-reports\crash-2012-12-25_16.30.48-server.txt
2012-12-25 16:30:51 [INFO] [Minecraft] Stopping server
2012-12-25 16:30:51 [INFO] [Minecraft] Saving worlds
2012-12-25 16:30:51 [INFO] [STDERR] Exception in thread "Thread-4" java.lang.NullPointerException
2012-12-25 16:30:51 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
2012-12-25 16:30:51 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.k(MinecraftServer.java:406)
2012-12-25 16:30:51 [INFO] [STDERR]     at fx.run(SourceFile:837)

**Comment by Wolftein** [comment]
Was due to the lastest Forge version, my bad.
