### ISSUE TITLE
WorldBorder Exception

### ISSUE THREAD

**Issue by BBBRV** [keepcalm/BukkitForge#456]
Trying to initiate a fill command triggers this exception (using #215)

2013-02-05 10:43:29 [WARNING] [BukkitForge] Task #11 for WorldBorder v1.6.1 generated an exception
java.lang.NullPointerException
        at org.bukkit.craftbukkit.CraftWorld.isChunkInUse(CraftWorld.java:367)
        at org.bukkit.craftbukkit.CraftWorld.unloadChunkRequest(CraftWorld.java:295)
        at org.bukkit.craftbukkit.CraftWorld.unloadChunkRequest(CraftWorld.java:291)
        at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:205)
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:52)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
        at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:38)
        at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
        at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:588)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)

**Comment by gravypod** [comment]
Some of the chunk code is still not 100%. We are working on this currently

**Comment by BBBRV** [comment]
Ah, okay. Any ETA? Not trying to be a hassle or anything, just wondering

**Comment by gravypod** [comment]
Uuum... No idea. I am working on some of the world/player stuff ATM but Keepcalm isnt here right now. Ill try and post here again when we fix it. Sorry for the wait!

**Comment by BBBRV** [comment]
No problem! keep up the good work :)

**Comment by BBBRV** [comment]
Still not working on build #227 :(

**Comment by recon88** [comment]
Same here using the newest build:

```
2013-02-11 00:26:11 [WARNUNG] [BukkitForge] Task #11 for WorldBorder v1.6.1 generated an exception
java.lang.NullPointerException
        at org.bukkit.craftbukkit.CraftWorld.isChunkInUse(CraftWorld.java:367)
        at org.bukkit.craftbukkit.CraftWorld.unloadChunkRequest(CraftWorld.java:295)
        at org.bukkit.craftbukkit.CraftWorld.unloadChunkRequest(CraftWorld.java:291)
        at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:205)
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:52)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
        at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:38)
        at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
        at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:588)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
```

**Comment by mrdeadlocked** [comment]
Same as recon88. Waiting and anxious. terrain generation is something that's been missing!
