### ISSUE TITLE
PlayerChatEvent broken?

### ISSUE THREAD

**Issue by noahmayr** [keepcalm/BukkitForge#458]
Every time a player says something in chat the console shows this error:
'java.lang.NoSuchMethodError: com.dthielke.herochat.ChannelChatEvent.getBukkitEvent()Lorg/bukkit/event/player/PlayerChatEvent;'

I tried the exact same setup of plugins with craftbukkit to make sure it's not a herochat bug and it seems to be fine. 

**Stacktrace:**

```
2013-02-05 18:40:41 [SEVERE] [BukkitForge] Could not pass event ChannelChatEvent to uIRCBridge v0.2 org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:393)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
    at com.dthielke.herochat.MessageHandler.throwChannelEvent(MessageHandler.java:166)
    at com.dthielke.herochat.MessageHandler.handle(MessageHandler.java:90)
    at com.dthielke.herochat.HCPlayerListener$1.run(HCPlayerListener.java:35)
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:52)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
    at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:588)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NoSuchMethodError: com.dthielke.herochat.ChannelChatEvent.getBukkitEvent()Lorg/bukkit/event/player/PlayerChatEvent;
    at net.ultimateminecraft.uircbridge.EventListener.onChannelChat(EventListener.java:29)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
    ... 15 more
```

**Comment by gravypod** [comment]
Can we get a full stack trace (the full error)

**Comment by noahmayr** [comment]
Added stacktrace.

**Comment by noahmayr** [comment]
That was an accident >_<

**Comment by gravypod** [comment]
uIRCBridge v0.2 might be out of date. Doesn't look like its our fault.

**Comment by noahmayr** [comment]
Why is it working with regular craftbukkit then?
`CraftBukkit version git-Bukkit-1.4.7-R1.0-b2624jnks (MC: 1.4.7) (Implementing API version 1.4.7-R1.0`

**Comment by dequis** [comment]
[semi-offtopic]
Someone on #craftirc told me that uIRCBridge seemed to be outdated. He uses craftbukkit. There was a fixed build in the comments of the bukkitdev page but it got censored ('no external links'), so i decided to go ahead and make my own fixed build in case someone else asks again for a build that works. Compiling the failing module clearly says the following:

```
net/ultimateminecraft/uircbridge/EventListener.java:29: cannot find symbol
symbol  : method getBukkitEvent()
location: class com.dthielke.herochat.ChannelChatEvent
                        String message = e.getBukkitEvent().getMessage();
                                          ^
1 error
```

Looks like the getBukkitEvent() of the herochat API is gone. When I tried to find out if anyone used the herochat API and needed this method, google showed me this thread.
[/semi-offtopic]

**I can replicate this issue with both craftbukkit and bukkitforge** - this person from #craftirc can replicate it too. **This issue doesn't belong here**. I don't think you're using the same .jars for both CB and BF, you probably have the unofficial fixed version in CB, or an older herochat, because there's no way this can work otherwise

**Comment by gravypod** [comment]
@dequis Thank you!
