### ISSUE TITLE
Worldedit, no such method "ans.c()Llq" on CraftCreatureSpawner.getCreatureTypeName

### ISSUE THREAD

**Issue by dequis** [keepcalm/BukkitForge#462]
To reproduce, do any kind of action over a mob spawner. I noticed it first with a //replacenear (that didn't affect the spawner block, only accessed it), but it's easier to reproduce with "/tool info" then right click on the spawner.

```
2013-02-07 00:39:33 [SEVERE] [BukkitForge] Could not pass event PlayerInteractEvent to WorldEdit v3-67178da
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:393)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:463)
        at net.minecraftforge.event.ASMEventHandler_122_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:578)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.NoSuchMethodError: ans.c()Llq;
        at org.bukkit.craftbukkit.block.CraftCreatureSpawner.getCreatureTypeName(CraftCreatureSpawner.java:56)
        at com.sk89q.worldedit.bukkit.BukkitWorld.copyFromWorld(BukkitWorld.java:637)
        at com.sk89q.worldedit.LocalWorld.getBlock(LocalWorld.java:585)
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:1322)
        at com.sk89q.worldedit.EditSession.rawGetBlock(EditSession.java:407)
        at com.sk89q.worldedit.tools.QueryTool.actPrimary(QueryTool.java:41)
        at com.sk89q.worldedit.WorldEdit.handleBlockRightClick(WorldEdit.java:1315)
        at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:165)
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
        ... 20 more
```

**Comment by dequis** [comment]
I'm dumb and didn't specify what I'm running. FTB mindcrack 8.0.1, BukkitForge-1.4.7-219, worldedit 5.5.2 snapshot (git 67178da).

**Comment by AlexMason** [comment]
I can confirm this.

**Comment by secondfry** [comment]
Still exists as on build 255.

```
2013-03-05 05:38:56 [INFO] [STDERR] java.lang.NoSuchMethodError: ans.c()Llq;
2013-03-05 05:38:56 [INFO] [STDERR]     at org.bukkit.craftbukkit.block.CraftCreatureSpawner.getCreatureTypeName(CraftCreatureSpawner.java:56)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.bukkit.BukkitWorld.copyFromWorld(BukkitWorld.java:638)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.LocalWorld.getBlock(LocalWorld.java:585)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:1323)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.EditSession.rawGetBlock(EditSession.java:407)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:361)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:403)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.commands.RegionCommands.regenerateChunk(RegionCommands.java:365)
2013-03-05 05:38:56 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-03-05 05:38:56 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2013-03-05 05:38:56 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-03-05 05:38:56 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Method.java:601)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:533)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:257)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:1)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:520)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1394)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247)
2013-03-05 05:38:56 [INFO] [STDERR]     at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
2013-03-05 05:38:56 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2013-03-05 05:38:56 [INFO] [STDERR]     at keepcalm.mods.bukkit.nmsforge.CommandHandlerImpl.a(CommandHandlerImpl.java:92)...
```
