### ISSUE TITLE
Le crash at load: just after loading worlds

### ISSUE THREAD

**Issue by jesusthekiller** [keepcalm/BukkitForge#475]
FINAL NOTE: Reapired, look at comment below.

NOTE: Error in 227, 226 & 225. No checked before.

NOTE 2: FML log: http://dl.dropbox.com/u/27919856/ForgeModLoader-server-2.log

It happened to me while making server at my PC:

---- Minecraft Crash Report ----

Time: 2/8/13 9:09 PM
Description: Exception in server tick loop

java.lang.NullPointerException
    at org.bukkit.craftbukkit.CraftChunk.getWorld(CraftChunk.java:70)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkPopulateEvent.<init>(ChunkPopulateEvent.java:16)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.populateChunks(ForgeEventHandler.java:925)
    at net.minecraftforge.event.ASMEventHandler_134_ForgeEventHandler_populateChunks_Post.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at abb.a(ChunkProviderGenerate.java:601)
    at im.a(ChunkProviderServer.java:258)
    at zz.a(Chunk.java:1258)
    at im.c(ChunkProviderServer.java:153)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:310)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
    at ho.c(DedicatedServer.java:180)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_09, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 206046664 bytes (196 MB) / 437846016 bytes (417 MB) up to 477233152 bytes (455 MB)
    JVM Flags: 2 total; -Xms256M -Xmx512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.26a FML v4.7.22.539 Minecraft Forge 6.6.0.515 59 mods loaded, 59 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ComputerCraft [ComputerCraft](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CCTurtle [ComputerCraft Turtles](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion [Thermal Expansion](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OmniTools [OmniTools](omnitools.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2 [IndustrialCraft 2](ic2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](advancedmachines.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AdvancedSolarPanel [Advanced Solar Panels](advancedsolarpanel.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ChickenChunks [ChickenChunks](chickenchunks.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    EnderStorage [EnderStorage](enderstorage.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](extrabiomesxl.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forestry [Forestry for Minecraft](forestry.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BinnieCore [Binnie Core](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ExtraBees [Extra Bees](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    factorization [Factorization](factorization.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    GraviSuite [Gravitation Suite](gravisuite.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Railcraft [Railcraft](railcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerCore [RedPower](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerBase [RP Base](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerMachine [RP Machine](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerCompat [RP Compat](redpowercompat.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerWiring [RP Wiring](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerLogic [RP Logic](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerLighting [RP Lighting](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerWorld [RP World](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerControl [RP Control](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Factory [Factory](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Energy [Energy](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Transport [Transport](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TwilightForest [The Twilight Forest](twilightforest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    XyCraft [XyCraft](xycraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    GregTech_Addon [GregTech-Addon](GregTech.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2NuclearControl [Nuclear Control](ic2nuclearcontrol.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IronChest [Iron Chest](ironchest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](modularforcefieldsystem.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TC [Traincraft](traincraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    drceph.petrogen [Petroleum Generator](petrogen.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    PortalGun [Portal Gun](portalgun.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    SoulShards [SoulShards](soulshards.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    StevesCarts [Steve's Carts](stevescarts.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|NEI [NEI](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|Core [WR-CBE Core](wirelessredstonecore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|Addons [WR-CBE Addons](wirelessredstoneaddons.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](wirelessredstoneredpower.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BukkitForge Details: BukkitForge null-null (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:[Didn't get far enough to load plugins :/]
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by jesusthekiller** [comment]
Ok, repaired, that's what is error:

bukkitForge doesn't generate world
