### ISSUE TITLE
Command Blocks do not work with bukkitforge installed?

### ISSUE THREAD

**Issue by squidicuzz** [keepcalm/BukkitForge#476]
I am trying to use this command through a command block: `/tp @p 0 64 0`
But it is not working.

The message in console says: `[BukkitForge] @ issued server command: /tp@p 0 64 0` .... `Error: Player not found.`

I am not sure what is causing it, but without bukkitforge installed, or if I remove all plugins from `\plugins`,  the Command Blocks work.

`@p @r @a`  all do not work, and return `Error: Player not found.`   I am not 100% sure this is bukkitforges fault, but it's where I have narrowed down my search so far.

Thanks for the help!

**Comment by fhntv24** [comment]
that is plugins "bug"-Essentials. he can telepotr to X Y Z coord's only with tppos command.with tp command it teleporting player to player,AND HE CANT TP TO X,Y,Z!!!!!!

that is all what i want to say))))

**Comment by squidicuzz** [comment]
No, this has nothing to do with essentials.  `@p @r @a`  DO NOT WORK, when used in the commandblock and bukkitforge is installed.  That command was chosen mainly as an example for this ticket.

**Comment by fhntv24** [comment]
No no,it's cant find user with user name 0 :D do you have Essentials installed? if yes,just try to delete it,and it THAT WILL work,beacos Bukkit forge dont edit Command block....really just try :/

**Comment by squidicuzz** [comment]
Why does Essentials break command blocks?  It shouldn't interact with them at all. :s

**Comment by fhntv24** [comment]
Essentials DONT break command block's,it changing it :/ command block it's like you-try bu youself type in chat /tp YouNick 0 64 0 .....mod's/admin's close that issue,it's "wrong"

**Comment by squidicuzz** [comment]
err... right.  

This is still an issue in BukkitForge, since essentials doesn't cause this issue on regular bukkit server.

**Comment by fhntv24** [comment]
no it's do

**Comment by eagl3s1ght** [comment]
@squidicuzz @fhntv24 I can confirm this bug. 

I tested the command "/tp @p -34 70 361" on CraftBukkit (with Essentials), it worked fine. 
Using the same command with Bukkitforge causes this error: **Error: Player not found.**

```
2013-02-15 05:54:14 [INFO] [BukkitForge] @ issued server command: tp@p 0 60 0
2013-02-15 05:54:14 [INFO] [STDOUT] Error: Player not found.
2013-02-15 05:54:14 [WARNING] [Minecraft] Error calling command /tp
com.earth2me.essentials.commands.PlayerNotFoundException: º4Player not found.
        at com.earth2me.essentials.commands.EssentialsCommand.getPlayer(EssentialsCommand.java:88)
        at com.earth2me.essentials.commands.EssentialsCommand.getPlayer(EssentialsCommand.java:48)
        at com.earth2me.essentials.commands.Commandtp.run(Commandtp.java:102)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:108)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:403)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:313)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
        at x.a(CommandHandler.java:82)
        at ann.a(SourceFile:34)
        at ajo.b(SourceFile:44)
        at in.a(WorldServer.java:170)
        at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:225)
        at in.b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:333)
        at me.nallar.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:454)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)
```

**Comment by squidicuzz** [comment]
This error also occurs with other commands and Command Blocks. 

I've tested BukkitForge with a plugin, that gets the command passed through the command block, and it either returns `0` or the special characters `@p @a @r`.  On Craftbukkit, it returns a player name.

**Comment by zuch0698o** [comment]
the tag {player} is also not recognized... :/ this is an amazing plugin but for an rpg server this is a big bug

**Comment by Gangreendavid** [comment]
Still no command block functionality with this? I'm running BukkitForge and Essentials and still have this issue? What's happeneing with BukkitForge? Will this get fixed at some point or should I look for alternative mods?

**Comment by alexbegt** [comment]
Why not use mcpc+?
