### ISSUE TITLE
[Plugin] MCJobs returns spamming error (BF Build 230)

### ISSUE THREAD

**Issue by eagl3s1ght** [keepcalm/BukkitForge#491]
```
2013-02-11 15:25:59 [SEVERE] [BukkitForge] Could not pass event CraftItemEvent to mcjobs v3.1.8
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:393)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
    at keepcalm.mods.bukkit.forgeHandler.BukkitCraftingHandler.onCrafting(BukkitCraftingHandler.java:63)
    at cpw.mods.fml.common.registry.GameRegistry.onItemCrafted(GameRegistry.java:336)
    at immibis.tubestuff.TileAutoCraftingMk2.decreaseInput(TileAutoCraftingMk2.java:224)
    at immibis.tubestuff.TileAutoCraftingMk2.makeOutput(TileAutoCraftingMk2.java:198)
    at immibis.tubestuff.TileAutoCraftingMk2.g(TileAutoCraftingMk2.java:268)
    at yc.h_net_minecraft_world_World_updateEntities_p0(World.java:456)
    at yc.h(World.java)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:334)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:239)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:103)
    at fy.run(SourceFile:849)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at rq.a(SourceFile:88)
    at org.bukkit.craftbukkit.inventory.CraftInventoryView.getItem(CraftInventoryView.java:67)
    at org.bukkit.event.inventory.InventoryClickEvent.getCurrentItem(InventoryClickEvent.java:52)
    at com.dmgkz.mcjobs.listeners.Crafting.craftEvent(Crafting.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
    ... 17 more
```

**Comment by enterprise12nx** [comment]
I believe that is a common error, if your using anything besides vanilla like quarrys, jobs trys to send Money and experience to the quarry, but since the quarry isnt a player it cant, causing an error.
this is why most if any job plugins dont really work for Tekkit.

you could try this: http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&ved=0CDIQFjAA&url=http%3A%2F%2Fwww.curse.com%2Fserver-mods%2Fminecraft%2Fjobz&ei=MDcZUcdfpJrRAZasgegH&usg=AFQjCNHMZ97xUCidkNxBrLCMf3TRDxf2UA&bvm=bv.42080656,d.dmQ

Although its required to have Mcmmo (which i hate)

And its a crafting error, are you trying to use a AutoCraftingTable?
or Project table?
Crafting Table Mk III?

**Comment by eagl3s1ght** [comment]
```
And its a crafting error, are you trying to use a AutoCraftingTable?
or Project table?
Crafting Table Mk III?
```

My users have that for sure.

```
this is why most if any job plugins dont really work for Tekkit.
```

The problem can probably be fixed with Bukkitforge, so I am not really interested in another plugin ^_^

**Comment by enterprise12nx** [comment]
probably not, the error is jobs side, they have been trying to make it tekkit compatible if you check MCjobs Bukkit page, under What they plant to do, but i could be wrong, im using Jobs also and i get some errors, you could try

http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&ved=0CEAQFjAC&url=http%3A%2F%2Fwww.curse.com%2Fserver-mods%2Fminecraft%2Fjobs&ei=gq8ZUfmhLOi40gG494CwBA&usg=AFQjCNEjvZDaT61MH6wQRazbuFuK6KqCoA&bvm=bv.42261806,d.dmQ

As i get no errors with this, only thing is you gotta make the jobs yourself /=
