### ISSUE TITLE
[Essentials-Protect] java.sql.SQLException when using Sqlite in Essentials config.yml

### ISSUE THREAD

**Issue by eagl3s1ght** [keepcalm/BukkitForge#492]
```
2013-02-11 15:27:37 [SEVERE] [Minecraft] null
java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:65)
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:62)
        at com.mchange.v2.c3p0.stmt.GooGooStatementCache.acquireStatement(GooGooStatementCache.java:562)
        at com.mchange.v2.c3p0.stmt.GooGooStatementCache.checkoutStatement(GooGooStatementCache.java:168)
        at com.mchange.v2.c3p0.impl.NewPooledConnection.checkoutStatement(NewPooledConnection.java:277)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:199)
        at com.earth2me.essentials.protect.data.ProtectedBlockSQLite.getStatementDeleteByLocation(ProtectedBlockSQLite.java:89)
        at com.earth2me.essentials.protect.data.ProtectedBlockJDBC.unprotectBlock(ProtectedBlockJDBC.java:387)
        at com.earth2me.essentials.protect.EssentialsProtectBlockListener.onBlockBreak(EssentialsProtectBlockListener.java:265)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at keepcalm.mods.bukkit.forgeHandler.BlockBreakEventHandler.onBlockBreak(BlockBreakEventHandler.java:32)
        at net.minecraftforge.event.ASMEventHandler_59_BlockBreakEventHandler_onBlockBreak_PlayerBreakBlockEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at keepcalm.mods.events.EventFactory.onBlockHarvested(EventFactory.java:11)
        at ir.d(ItemInWorldManager.java:271)
        at ir.b(ItemInWorldManager.java:330)
        at ir.a(ItemInWorldManager.java:237)
        at iv.a(NetServerHandler.java:514)
        at ei.a(SourceFile:46)
        at cg.i(TcpConnection.java:347)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
Caused by: java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:503)
        at com.mchange.v2.c3p0.stmt.GooGooStatementCache.acquireStatement(GooGooStatementCache.java:552)
        ... 27 more
```

**Comment by eagl3s1ght** [comment]
I just tried switching to MySQL, and it appears I recieve the same null exception with that.

```
2013-02-15 05:46:19 [SEVERE] [Minecraft] null
java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.InterruptedException
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:65)
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:62)
        at com.mchange.v2.c3p0.stmt.GooGooStatementCache.acquireStatement(GooGooStatementCache.java:562)
        at com.mchange.v2.c3p0.stmt.GooGooStatementCache.checkoutStatement(GooGooStatementCache.java:168)
        at com.mchange.v2.c3p0.impl.NewPooledConnection.checkoutStatement(NewPooledConnection.java:277)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:199)
        at com.earth2me.essentials.protect.data.ProtectedBlockMySQL.getStatementDeleteByLocation(ProtectedBlockMySQL.java:141)
        at com.earth2me.essentials.protect.data.ProtectedBlockJDBC.unprotectBlock(ProtectedBlockJDBC.java:387)
        at com.earth2me.essentials.protect.EssentialsProtectBlockListener.onBlockBreak(EssentialsProtectBlockListener.java:229)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
        at keepcalm.mods.bukkit.forgeHandler.BlockBreakEventHandler.onBlockBreak(BlockBreakEventHandler.java:32)
        at net.minecraftforge.event.ASMEventHandler_59_BlockBreakEventHandler_onBlockBreak_PlayerBreakBlockEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at keepcalm.mods.events.EventFactory.onBlockHarvested(EventFactory.java:11)
        at ir.d(ItemInWorldManager.java:271)
        at ir.b(ItemInWorldManager.java:307)
        at ir.a(ItemInWorldManager.java:170)
        at iv.a(NetServerHandler.java:509)
        at ei.a(SourceFile:46)
        at cg.i(TcpConnection.java:347)
        at cg.readNetworkPacket(TcpConnection.java:37)
        at ch.run(PatchTcpReaderThread.java:24)
Caused by: java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:503)
        at com.mchange.v2.c3p0.stmt.GooGooStatementCache.acquireStatement(GooGooStatementCache.java:552)
        ... 27 more
```
