### ISSUE TITLE
[groupmanager] Bukkitforge 1.4.7-230 build, Error when using /manuadd [player] NEVER happened before

### ISSUE THREAD

**Issue by enterprise12nx** [keepcalm/BukkitForge#498]
org.bukkit.command.CommandException: unhandled exception executing command 'manuadd' in plugin groupmanager  v2.0 (2.9.6) (Phoenix)

it has a keepcalm error in it.

it seem manpromote is the same error. possibly all of groupmanager?

**Comment by ElgarL** [comment]
You have posted no log or anything to go off.

**Comment by enterprise12nx** [comment]
Here

2013-02-11 23:17:19 [INFO] [BukkitForge] Server issued server command: manuaddenter owner
2013-02-11 23:17:19 [INFO] [STDERR] org.bukkit.command.CommandException: Unhandled exception executing command 'manuadd' in plugin GroupManager v2.0 (2.9.6) (Phoenix)
2013-02-11 23:17:19 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
2013-02-11 23:17:19 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2013-02-11 23:17:19 [INFO] [STDERR]     at x.a(CommandHandler.java:82)
2013-02-11 23:17:19 [INFO] [STDERR]     at ho.al(DedicatedServer.java:308)
2013-02-11 23:17:19 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-02-11 23:17:19 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-02-11 23:17:19 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-02-11 23:17:19 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-02-11 23:17:19 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-02-11 23:17:19 [INFO] [STDERR]     at org.bukkit.craftbukkit.CraftServer.getOfflinePlayers(CraftServer.java:1249)
2013-02-11 23:17:19 [INFO] [STDERR]     at org.anjocaido.groupmanager.GroupManager.validatePlayer(GroupManager.java:2004)
2013-02-11 23:17:19 [INFO] [STDERR]     at org.anjocaido.groupmanager.GroupManager.onCommand(GroupManager.java:504)
2013-02-11 23:17:19 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-02-11 23:17:19 [INFO] [STDERR]     ... 7 morek of errors for some reason,

**Comment by eagl3s1ght** [comment]
Works fine for me. Your problem is something else, not Bukkitforge. Maybe TickThreading?

**Comment by enterprise12nx** [comment]
idk, it just started when i got the new version of bukkitforge, ive been using groupmanager and the commands and same version for a week or 2

i just got the new version and thts when it did that, ive been using that command every day to add the new ppl tht come from guest to member..so idk /=

**Comment by enterprise12nx** [comment]
It only happens if the player is offline..any suggestions?

**Comment by eagl3s1ght** [comment]
@enterprise12nx You can't add a player who has not been on the server if that's what you mean. That's a Group Manager limitation as far as I know. I have been running BF230 since you posted this, and not once have I gotten this error, while adding offline players and online players. Perhaps it's a plugin conflict? Plugin list? It would also help with a full FORGEMODLOADER log, hence "7 morek of errors for some reason,"

**Comment by ElgarL** [comment]
GM can add new players (offline) who haven't been on the server before without issue.
Pastebin a full startup log.

**Comment by eagl3s1ght** [comment]
`2013-02-27 02:00:39 [INFO] [BukkitForge] Server issued server command: manuaddnotch builder overworld
2013-02-27 02:00:39 [INFO] [STDOUT] Player not found!
2013-02-27 02:00:39 [INFO] [STDOUT] /manuadd <player> <group> | optional [world]`

@ElgarL Oh wow, that is news to me. I have always gotten the "Player not found" error. Looking into it, I found the /mantogglevalidate command and after that, adding offline players work fine. I'm on BF230 and Group Manager v2.0.95 (Phoenix)

`2013-02-27 02:03:13 [INFO] [BukkitForge] Server issued server command: manuaddnotch builder overworld
2013-02-27 02:03:13 [INFO] [STDOUT] You changed player 'notch' group to 'Builder' in world 'overworld'.`

**Comment by enterprise12nx** [comment]
tht fixed it, thanks!
