### ISSUE TITLE
NoSuchMethodError: org.bukkit.craftbukkit.inventory.....

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#500]
Newest versions of all. Shop doesn't get created.

12.02 20:24:46 [Server] INFO at fy.run(SourceFile:849)
12.02 20:24:46 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
12.02 20:24:46 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:588)
12.02 20:24:46 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:288)
12.02 20:24:46 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:120)
12.02 20:24:46 [Server] INFO at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
12.02 20:24:46 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:38)
12.02 20:24:46 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
12.02 20:24:46 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:52)
12.02 20:24:46 [Server] INFO at org.maxgamer.QuickShop.ShopManager$1.run(ShopManager.java:295)
12.02 20:24:46 [Server] INFO at org.maxgamer.QuickShop.Shop.ChestShop.onLoad(ChestShop.java:626)
12.02 20:24:46 [Server] INFO at org.maxgamer.QuickShop.Shop.DisplayItem.respawn(DisplayItem.java:64)
12.02 20:24:46 [Server] INFO at org.maxgamer.QuickShop.Shop.DisplayItem.spawn(DisplayItem.java:51)
12.02 20:24:46 [Server] INFO at org.maxgamer.QuickShop.Util.NMS.safeGuard(NMS.java:189)
12.02 20:24:46 [Server] INFO at org.maxgamer.QuickShop.Util.NMS$1.safeGuard(NMS.java:26)
12.02 20:24:46 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(Lorg/bukkit/inventory/ItemStack;)Lnet/minecraft/server/ItemStack;
12.02 20:24:46 [Server] WARNING Task #71 for QuickShop v3.7.1 generated an exception

**Comment by SpoonsJTD** [comment]
Please post the rest of the log, you are missing the part of it that we need to see.
