### ISSUE TITLE
[Essentials] /feed <player> returns Error: rp.b(F)V but feeds player.

### ISSUE THREAD

**Issue by eagl3s1ght** [keepcalm/BukkitForge#502]
Bukkitforge Build 230
Essentials Pre2.9.5

```
2013-02-15 05:57:54 [WARNING] [Minecraft] Error calling command /feed
java.lang.NoSuchMethodError: rp.b(F)V
        at org.bukkit.craftbukkit.entity.CraftPlayer.setSaturation(CraftPlayer.java:658)
        at com.earth2me.essentials.commands.Commandfeed.feedOtherPlayers(Commandfeed.java:48)
        at com.earth2me.essentials.commands.Commandfeed.run(Commandfeed.java:23)
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:96)
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:407)
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:313)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
        at x.a(CommandHandler.java:82)
        at iv.d(NetServerHandler.java:768)
        at iv.a(NetServerHandler.java:734)
        at cu.a(SourceFile:44)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
        at iw.b(NetworkListenThread.java)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:259)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:176)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:104)
        at fy.run(SourceFile:849)
```

**Comment by fhntv24** [comment]
that is only visual glich,dont care about it.(it's can be bug with you v. of Essentials,for me all ok)

**Comment by eagl3s1ght** [comment]
@fhntv24, This forum is used to report issues with Bukkitforge in conjunction with Bukkit plugins and it exists because the developers care about the bugs.

**Comment by Sageavatar** [comment]
It is because they care that we are lucky enough to have people like them to take the tremendous amount of time to develop a combination API so we can happily (and easily) use our favorite plugins with the newest version of Tekkit Lite. We owe them for sure.

**Comment by fhntv24** [comment]
@eagl3s1ght i was have same problem on Bukkit without mods,so that is not BukKit forge problem

**Comment by eagl3s1ght** [comment]
@fhntv24 I just tested this on CraftBukkit and didn't run into this error, what makes you think that you're right about this when you were wrong about /tp?

**Comment by Taeir** [comment]
I tried some things myself, and it seems that if you access the player.setSaturation() method, you will get this error.
It is probably just a case of forgetting to include a method.

It is also not a visual glitch. The setFoodLevel method works, and fills your food bar, but your saturation will be still what it was before, meaning that you will get hungry alot faster.
