### ISSUE TITLE
Exception in server tick loop  java.lang.NullPointerException

### ISSUE THREAD

**Issue by StealthyBatman** [keepcalm/BukkitForge#504]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2/13/13 3:32 PM
Description: Exception in server tick loop

java.lang.NullPointerException
    at org.bukkit.craftbukkit.CraftChunk.getWorld(CraftChunk.java:70)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkPopulateEvent.<init>(ChunkPopulateEvent.java:16)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.populateChunks(ForgeEventHandler.java:925)
    at net.minecraftforge.event.ASMEventHandler_136_ForgeEventHandler_populateChunks_Post.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at abb.a(ChunkProviderGenerate.java:601)
    at im.a(ChunkProviderServer.java:258)
    at zz.a(Chunk.java:1258)
    at im.c(ChunkProviderServer.java:153)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:310)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
    at ho.c(DedicatedServer.java:180)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
# 

This is what I get when trying to run BukkitForge with Direwolf20 server. Any thoughts?

**Comment by SpoonsJTD** [comment]
This exception no longer occurs.
