### ISSUE TITLE
Towny(Towny Advanced) plugin Issue

### ISSUE THREAD

**Issue by axzxc1236** [keepcalm/BukkitForge#51]
I am using vanilla server (version  1.4.5), forge version is 6.4.2.445,and forge bukkit version is BukkitForge-1.4.5-3.

I want to use Towny.But Towny doesn't work

The Towny version I want to use.==>http://dev.bukkit.org/server-mods/towny-advanced/files/22-towny-jar-0-82-0-2/

Server log:
2012-12-29 11:35:18 [INFO] [com.palmergames.bukkit.towny.Towny] [Towny] Enabling
 Towny v0.82.0.2
#2012-12-29 11:35:18 [INFO] [STDOUT] ====================      Towny      =======

2012-12-29 11:35:19 [INFO] [STDOUT] [Towny] Database: [Load] flatfile [Save] fla
tfile
2012-12-29 11:35:20 [INFO] [com.palmergames.bukkit.towny.Towny] [Towny] Disablin
g Towny v0.82.0.2
#2012-12-29 11:35:20 [INFO] [STDOUT] ============================================

2012-12-29 11:35:20 [INFO] [STDOUT] [Towny] Version: 0.82.0.2 - Mod Disabled
#2012-12-29 11:35:20 [INFO] [STDOUT] ============================================

2012-12-29 11:35:20 [SEVERE] [BukkitForge] Error occurred while enabling Towny v
0.82.0.2 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com
.palmergames.bukkit.towny.listeners.TownyPlayerListener@756b5ac7 while not enabl
ed
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginMana
ger.java:499)
        at com.palmergames.bukkit.towny.Towny.registerEvents(Unknown Source)
        at com.palmergames.bukkit.towny.Towny.onEnable(Unknown Source)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:374)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:381)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.j
ava:889)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServe
r.java:873)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:
232)
        at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:36)
        at java.lang.Thread.run(Unknown Source)

Can you help me?   Sorry for my bad English.

**Comment by xKillerbees** [comment]
You have to disable version check within the towny config for it to enable. But doing that only gets it to load, it doesn't register the user and it has been reported by me.

**Comment by keepcalm** [comment]
or, update to a newer build. I fixed that issue a few versions ago. Newer builds are [here](http://build.aegisgaming.org/job/BukkitForge)
