### ISSUE TITLE
[Essentials] [Worlguard/Worldedit] [Coreprotect] [Remote Toolkit Plugin] [Chairs Plugin] [LWC]

### ISSUE THREAD

**Issue by enterprise12nx** [keepcalm/BukkitForge#517]
Here are all the errors i have, and all the errors i have seen in the lists, i do this to try and organise all the issues into one to help you out!

[Essentials] 
- Vanish Still Does Not Work
- /temp ban, bans but only permanently not the set time you ban them for.
- /back on death, I have the perms set, - essentials.back - essentials.back.ondeath
- Essentials spawn does not work when ppl first join, they dont appear AT set spawn.

[Worldguard/Worldedit]
- when executing most 'WE' commands their are errors, fixwater and most commands i hear havent been working.  I have the - worldedit.\* perm set, yet it says i dont have perm.
- 'WG' when i try to see flags, it only lists some.  

[WORLD EDIT ERROR]

2013-02-16 15:44:58 [INFO] [BukkitForge] enterprise12 issued server command: /setgrass
2013-02-16 15:44:58 [WARNING] [Minecraft.WorldEdit] WorldEdit: Failed to do NMS access for direct NBT data copy
java.lang.NullPointerException
    at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:1311)
    at com.sk89q.worldedit.EditSession.rawGetBlock(EditSession.java:407)
    at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:361)
    at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:258)
    at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1151)
    at com.sk89q.worldedit.commands.RegionCommands.set(RegionCommands.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:533)
    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:257)
    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:1)
    at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:520)
    at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
    at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1394)
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247)
    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

[Common Problems]
- When using /f show, trying to see WG flags, etc.  The list gets cut off
- When chatting, your chat gets cut off, MC bug? or FB?

[CoreProtect]
- still not working, /co inspect returns with nothing when inspecting blocks USUALLY
- rollbacks dont work, i assume for restores too

[Remote Toolkit Plugin]

2013-02-16 15:22:05 [INFO] [com.drdanick.McRKit.plugin.RTKPlugin] [RemoteToolkitPlugin] Enabling RemoteToolkitPlugin vR10_A14.5
2013-02-16 15:22:05 [INFO] [STDOUT] Memory max: 2388000768 bytes
2013-02-16 15:22:05 [INFO] [STDOUT] Memory total: 1569259520 bytes
2013-02-16 15:22:05 [INFO] [STDERR] ERROR LOADING TOOLKIT PLUGIN: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.CraftServer.getReader()
2013-02-16 15:22:05 [INFO] [STDERR] java.lang.NoSuchMethodException: org.bukkit.craftbukkit.CraftServer.getReader()
2013-02-16 15:22:05 [INFO] [STDERR]     at java.lang.Class.getMethod(Unknown Source)
2013-02-16 15:22:05 [INFO] [STDERR]     at com.drdanick.McRKit.plugin.LegacySupport.initMetrics(LegacySupport.java:16)
2013-02-16 15:22:05 [INFO] [STDERR]     at com.drdanick.McRKit.plugin.RTKPlugin.onEnable(RTKPlugin.java:111)
2013-02-16 15:22:05 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-02-16 15:22:05 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:426)
2013-02-16 15:22:05 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
2013-02-16 15:22:05 [INFO] [STDERR]     at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:838)
2013-02-16 15:22:05 [INFO] [STDERR]     at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:822)
2013-02-16 15:22:05 [INFO] [STDERR]     at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:235)
2013-02-16 15:22:05 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
2013-02-16 15:22:05 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2013-02-16 15:22:05 [INFO] [Minecraft] Remote Toolkit Plugin R10_A14.5 enabled!

[Chairs Plugin]

2013-02-16 15:40:41 [SEVERE] [BukkitForge] Could not pass event PlayerMoveEvent to Chairs v1.16.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:393)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerMove(ForgeEventHandler.java:801)
    at net.minecraftforge.event.ASMEventHandler_66_ForgeEventHandler_onPlayerMove_PlayerMoveEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at keepcalm.mods.events.ForgeEventHelper.onPlayerMove(ForgeEventHelper.java:206)
    at iv.a(NetServerHandler.java)
    at eb.a(SourceFile:136)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_4_R1/entity/CraftPlayer
    at net.spoothie.chairs.Chairs.sendSit(Chairs.java:145)
    at net.spoothie.chairs.EventListener.onPlayerMove(EventListener.java:50)
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
    ... 19 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_4_R1.entity.CraftPlayer
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:180)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:175)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 25 more

[LWC]
- lwc still is not working i believe, correct me if im wrong?

**Comment by enterprise12nx** [comment]
Has anybody reviewed this yet?

**Comment by streaky** [comment]
A "same here" on RTK w/build 244. Not sure if it's actually working, haven't got to that yet but it does claim it's loaded.

**Comment by enterprise12nx** [comment]
it works fine for me, just an error that i thought should be mentioned, restarts and commands work

**Comment by Sageavatar** [comment]
RTK Works fine for me. Commands, remote console access from other machines and my phone. Wish I could get ride of the RKPINK though.

Suggestion @enterprise12nx : Don't post tons of issues to the same thread. Each issue needs it's own thread. Research and see if there are posts related to your issue. Post there. Otherwise, we have TONS of extra issues and our information is scattered. For instance, your LWC issue could have been commented in #134 or #267 . You can see the Issue. This makes more work for guys like @SpoonsJTD who has to sort thorough updates on the 172 currently open issues (who knows how many of those are dupes.). Thank you!

**Comment by streaky** [comment]
Yeah seems to work okay - I guess it reads console for something, but that it's not super important to it's operation. Personally thought it was worth mentioning and found the same error in this thread so confirmed it for the latest build at the time.

**Comment by SpoonsJTD** [comment]
Almost if not all of these are dupes. Please check existing issues before posting and please limit issue to ONE problem.
