### ISSUE TITLE
Build 239

### ISSUE THREAD

**Issue by mkiplm** [keepcalm/BukkitForge#520]
this error appears with new build, any fixxes but keeping the latest?

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2/17/13 10:55 AM
Description: Exception in server tick loop

java.lang.ClassCastException: aas cannot be cast to TFC.WorldGen.TFCProvider
    at TFC.Handlers.ServerTickHandler.tickStart(ServerTickHandler.java:58)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
    at cpw.mods.fml.common.FMLCommonHandler.onWorldLoadTick(FMLCommonHandler.java:303)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:464)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.6
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_05, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 115953544 bytes (110 MB) / 286629888 bytes (273 MB) up to 5316411392 bytes (5070 MB)
    JVM Flags: 2 total; -Xincgc -Xmx5G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 47, tallocated: 6881
    FML: MCP v7.25 FML v4.6.15.514 Minecraft Forge 6.5.0.486 21 mods loaded, 21 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's Core Mod [fihgu's Core Mod](minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mod_SmartMoving [Smart Moving](minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-239.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-239.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    powertools_shared [Power Tools Shared](1.4.6_power_tools_shared_0.1.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    powertools_chunkprotection [Chunk Protection](1.4.6_chunkprotection_0.1.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    powertools_setspawn [SetSpawn](1.4.6_setspawn_0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    CustomNpcs [CustomNpcs 1.4.5](CustomNPCs_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Dynmap [Dynmap](Dynmap-1.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    EnjinMinecraftPlugin [EnjinMinecraftPlugin](EnjinMinecraftPlugin.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    fihgu's Protection Mod [fihgu's Protection Mod](fihgus Protection Mod%282.1.2%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Lanterns [Lanterns](Lanterns 1.1.5 Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    mbolz [medical mod](medical v7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Railcraft [Railcraft](Railcraft_1.4.6-6.14.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    SimplyHorses [Simply Horses](SimplyHorses_1.4.7_pre6.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TerraFirmaCraft [TerraFirmaCraft](TFCraft-Universal-Core-B2-Build75.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TradeBoothMod [Trade Booth Mod](tradebooth.0.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    TC [Traincraft](Traincraft-3.1.13_030.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    BukkitForge Details: BukkitForge null-null (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:WorldBorder v1.6.1: Enabled, RWtorchLight v1.2.1: Enabled, GroupManager v2.0 (2.9.6) (Phoenix): Enabled, WorldEdit v5.5.1: Enabled, Towny v0.82.1.0: Enabled, Register v1.8: Enabled, Permissions v3.1.6: Enabled, Vault v1.2.23-b301: Enabled, Questioner v0.6: Enabled, LWC v4.3.1 (b827-git-MANUAL) (February 10, 2013): Enabled, WorldGuard v5.7.1: Enabled, Essentials vPre2.10.1.4: Enabled, TownyChat v0.36: Disabled, EssentialsProtect vPre2.10.1.4: Disabled, EssentialsSpawn vPre2.10.1.4: Disabled, WebAuctionPlus v1.1.7: Disabled, BKCommonLib v1.47: Disabled, EssentialsChat vPre2.10.1.4: Disabled, EssentialsAntiBuild vPre2.10.1.4: Disabled and Factions v1.8.0: Disabled
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 48; []
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by SpoonsJTD** [comment]
What is TFC?

**Comment by dequis** [comment]
I'm guessing it's terrafirmacraft

**Comment by SpoonsJTD** [comment]
Try with latest build.

**Comment by mkiplm** [comment]
still messing up

build 255

java.lang.ClassCastException: aas cannot be cast to TFC.WorldGen.TFCProvider
    at TFC.Handlers.ServerTickHandler.tickStart(ServerTickHandler.java:58)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
    at cpw.mods.fml.common.FMLCommonHandler.onWorldLoadTick(FMLCommonHandler.java:303)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:464)
    at fy.run(SourceFile:849)
