### ISSUE TITLE
[WorldEdit] error 

### ISSUE THREAD

**Issue by Cestis** [keepcalm/BukkitForge#526]
Gets that error every time if issued any WE command. With big area crashing server.

2013-02-19 22:43:35 [INFO] [BukkitForge] Cestis issued server command: /cut
2013-02-19 22:43:35 [WARNING] [Minecraft.WorldEdit] WorldEdit: Failed to do NMS access for direct NBT data copy
java.lang.NullPointerException
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:1311)
        at com.sk89q.worldedit.EditSession.rawGetBlock(EditSession.java:407)
        at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:361)
        at com.sk89q.worldedit.CuboidClipboard.copy(CuboidClipboard.java:266)
        at com.sk89q.worldedit.commands.ClipboardCommands.cut(ClipboardCommands.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:533)
        at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:257)
        at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:1)
        at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:520)
        at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
        at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1394)
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247)
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
        at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
        at keepcalm.mods.bukkit.forgeHandler.CommandHandlerImpl.a(CommandHandlerImpl.java:99)
        at x.a(CommandHandler.java:17)
        at iv.d(NetServerHandler.java:768)
        at iv.a(NetServerHandler.java:734)
        at cu.a(SourceFile:44)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)

**Comment by various123** [comment]
Same problem. It spams the console madly.
