### ISSUE TITLE
[LWC]Internal Error

### ISSUE THREAD

**Issue by TheEisbaer** [keepcalm/BukkitForge#529]
Hey, I downloaded the latest version of Bukkitforge and LWC but ingame I get 
"LWC internal Error. Please notify an admin immediatly. 
:PLAYER_INTERACT"
How do I fix this?

This is what the Server gets:
2013-02-21 20:04:20 [INFO] [STDERR] com.griefcraft.scripting.ModuleException: LW
C Module threw an uncaught exception! LWC version: 4.3.1 (b767)
2013-02-21 20:04:20 [INFO] [STDERR]     at com.griefcraft.scripting.ModuleLoader
.dispatchEvent(ModuleLoader.java:358)
2013-02-21 20:04:20 [INFO] [STDERR]     at com.griefcraft.listeners.LWCPlayerLis
tener.onPlayerInteract(LWCPlayerListener.java:189)
2013-02-21 20:04:20 [INFO] [STDERR]     at sun.reflect.GeneratedMethodAccessor26
.invoke(Unknown Source)
2013-02-21 20:04:20 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorI
mpl.invoke(Unknown Source)
2013-02-21 20:04:20 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unkno
wn Source)
2013-02-21 20:04:20 [INFO] [STDERR]     at org.bukkit.plugin.java.JavaPluginLoad
er$1.execute(JavaPluginLoader.java:391)
2013-02-21 20:04:20 [INFO] [STDERR]     at org.bukkit.plugin.RegisteredListener.
callEvent(RegisteredListener.java:66)
2013-02-21 20:04:20 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager
.fireEvent(SimplePluginManager.java:482)
2013-02-21 20:04:20 [INFO] [STDERR]     at org.bukkit.plugin.SimplePluginManager
.callEvent(SimplePluginManager.java:464)
2013-02-21 20:04:20 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.For
geEventHandler.interactEvent(ForgeEventHandler.java:477)
2013-02-21 20:04:20 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHand
ler_125_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
2013-02-21 20:04:20 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHand
ler.invoke(ASMEventHandler.java:35)
2013-02-21 20:04:20 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.pos
t(EventBus.java:103)
2013-02-21 20:04:20 [INFO] [STDERR]     at net.minecraftforge.event.ForgeEventFa
ctory.onPlayerInteract(ForgeEventFactory.java:34)
2013-02-21 20:04:20 [INFO] [STDERR]     at ir.a(ItemInWorldManager.java:389)
2013-02-21 20:04:20 [INFO] [STDERR]     at iv.a(NetServerHandler.java:578)
2013-02-21 20:04:20 [INFO] [STDERR]     at fk.a(SourceFile:58)
2013-02-21 20:04:20 [INFO] [STDERR]     at cg.b(TcpConnection.java:458)
2013-02-21 20:04:20 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2013-02-21 20:04:20 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-02-21 20:04:20 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-02-21 20:04:20 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
r(MinecraftServer.java:703)
2013-02-21 20:04:20 [INFO] [STDERR]     at ho.r(DedicatedServer.java:269)
2013-02-21 20:04:20 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
q(MinecraftServer.java:599)
2013-02-21 20:04:20 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
run(MinecraftServer.java:497)
2013-02-21 20:04:20 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-02-21 20:04:20 [INFO] [STDERR] Caused by: com.griefcraft.scripting.ModuleEx
ception: LWC Module threw an uncaught exception! LWC version: 4.3.1 (b767)
2013-02-21 20:04:20 [INFO] [STDERR]     at com.griefcraft.scripting.ModuleLoader
.dispatchEvent(ModuleLoader.java:358)
2013-02-21 20:04:20 [INFO] [STDERR]     at com.griefcraft.modules.create.CreateM
odule.onBlockInteract(CreateModule.java:116)
2013-02-21 20:04:20 [INFO] [STDERR]     at com.griefcraft.scripting.ModuleLoader
.dispatchEvent(ModuleLoader.java:334)
2013-02-21 20:04:20 [INFO] [STDERR]     ... 25 more
2013-02-21 20:04:20 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-02-21 20:04:20 [INFO] [STDERR]     at com.griefcraft.sql.PhysDB.getProtecti
onCount(PhysDB.java:165)
2013-02-21 20:04:20 [INFO] [STDERR]     at com.griefcraft.modules.limits.LimitsV
2$DefaultLimit.getProtectionCount(LimitsV2.java:112)
2013-02-21 20:04:20 [INFO] [STDERR]     at com.griefcraft.modules.limits.LimitsV
2.hasReachedLimit(LimitsV2.java:286)
2013-02-21 20:04:20 [INFO] [STDERR]     at com.griefcraft.modules.limits.LimitsV
2.onRegisterProtection(LimitsV2.java:162)
2013-02-21 20:04:20 [INFO] [STDERR]     at com.griefcraft.scripting.ModuleLoader
.dispatchEvent(ModuleLoader.java:346)
2013-02-21 20:04:20 [INFO] [STDERR]     ... 27 more

**Comment by Sageavatar** [comment]
My suspicion is that _you_ don't. If a throwable wasn't caught, it's either a Bukkitforge issue or a LWC Issue. Did LWC work for you before? (I beleive it has been broken)

**Comment by SpoonsJTD** [comment]
Dupity dupe dupe dupe.
