### ISSUE TITLE
[NoLagg] plugin (1.4.6):loads but doesn't work because dependency 'BKCommonLib' gives error

### ISSUE THREAD

**Issue by wasbeer** [keepcalm/BukkitForge#53]
Can you please port NoLagg? I think this would be a major contribution to Minecraft Forge Servers.
Below you can find my error log:

2012-12-25 19:16:29 [INFO] [BukkitForge] Starting the API, implementing Bukkit API version 1.4.6
2012-12-25 19:16:30 [INFO] [BukkitForge] Bukkit API for Vanilla, version 1.4.6 starting up...
2012-12-25 19:16:30 [INFO] [BukkitForge] This server is running Minecraft Server 1.4.6, using FML 4.6.12.511, MinecraftForge 6.5.0.480, MCP v7.25 version git-BukkitForge-1.4.5-R1.0-b3000jnks (Really: BukkitForge for MC 1.4.6) (Implementing API version 1.4.5-R0.2)
2012-12-25 19:16:30 [INFO] [BukkitForge] Completing load...
2012-12-25 19:16:30 [INFO] [BukkitForge] Plugins are being loaded...
2012-12-25 19:16:30 [INFO] [com.bergerkiller.bukkit.common.internal.CommonPlugin] [BKCommonLib] Loading BKCommonLib v1.4
2012-12-25 19:16:30 [INFO] [com.bergerkiller.bukkit.nolagg.NoLagg] [NoLagg] Loading NoLagg v1.89.2
2012-12-25 19:16:30 [INFO] [com.bergerkiller.bukkit.common.internal.CommonPlugin] [BKCommonLib] Enabling BKCommonLib v1.4
2012-12-25 19:16:30 [SEVERE] [BukkitForge] [BKCommonLib] BKCommonLib can only run on a CraftBukkit build compatible with Minecraft v1_4_6
2012-12-25 19:16:30 [SEVERE] [BukkitForge] [BKCommonLib] Please look for an available BKCommonLib update:
2012-12-25 19:16:30 [SEVERE] [BukkitForge] [BKCommonLib] http://dev.bukkit.org/server-mods/bkcommonlib/
2012-12-25 19:16:30 [INFO] [com.bergerkiller.bukkit.common.internal.CommonPlugin] [BKCommonLib] Disabling BKCommonLib v1.4
2012-12-25 19:16:30 [INFO] [com.bergerkiller.bukkit.nolagg.NoLagg] [NoLagg] Enabling NoLagg v1.89.2
2012-12-25 19:16:30 [SEVERE] [BukkitForge] Error occurred while enabling NoLagg v1.89.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/bergerkiller/bukkit/common/permissions/PermissionEnum
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
    at org.bukkit.plugin.java.JavaPluginLoader.getClassByName0(JavaPluginLoader.java:300)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:76)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at com.bergerkiller.bukkit.nolagg.NoLagg.permissions(NoLagg.java:32)
    at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:548)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:901)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:885)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:231)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:38)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.bergerkiller.bukkit.common.permissions.PermissionEnum
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 25 more
2012-12-25 19:16:30 [INFO] [BukkitForge] Loading PostWorld plugins...
2012-12-25 19:16:30 [INFO] [BukkitForge] Going to load perms file: permissions.yml
2012-12-25 19:16:30 [INFO] [BukkitForge] Loaded plugins: 
2012-12-25 19:16:30 [INFO] [BukkitForge] BKCommonLib- Enabled: false
2012-12-25 19:16:30 [INFO] [BukkitForge] NoLagg- Enabled: true

**Comment by Wolftein** [comment]
NoLagg use and override Minecraft code, that will be hard to port.

**Comment by keepcalm** [comment]
Yes, sorry but it ships re-implementations of things and that will be hard to port.
