### ISSUE TITLE
Server Crash on starting up

### ISSUE THREAD

**Issue by uberbuild** [keepcalm/BukkitForge#537]
We recently edited a plugin and has been our only change to the server after around almost a week of perfect us 1 change to allow people to build in the nether in group manager has now changed the server and will crash every time it is started up and have to be killed using HTOP in ssh,.

Error Report: 
(Not sure if this is best way to post this)

---- Minecraft Crash Report ----
// Oops.

Time: 24/02/13 18:37
Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:810)
    at java.util.HashMap$EntryIterator.next(HashMap.java:851)
    at java.util.HashMap$EntryIterator.next(HashMap.java:849)
    at com.google.common.collect.AbstractMultimap$KeySet$1.next(AbstractMultimap.java:913)
    at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:498)
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:71)
    at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:279)
    at ho.c(DedicatedServer.java:180)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Linux (amd64) version 3.2.13-grsec-xxxx-grs-ipv6-64
    Java Version: 1.6.0_24, Sun Microsystems Inc.
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Sun Microsystems Inc.
    Memory: 15787211456 bytes (15055 MB) / 20580073472 bytes (19626 MB) up to 20580073472 bytes (19626 MB)
    JVM Flags: 2 total; -Xmx20G -Xms20G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.26a FML v4.7.32.553 Minecraft Forge 6.6.1.524 59 mods loaded, 59 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-243.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHCore [CoFH Core](CoFHCore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ComputerCraft [ComputerCraft](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CCTurtle [ComputerCraft Turtles](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion [Thermal Expansion](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OmniTools [OmniTools](omnitools.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2 [IndustrialCraft 2](IC2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TwilightForest [The Twilight Forest](TwilightForest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    factorization [Factorization](factorization.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](extrabiomes.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forestry [Forestry for Minecraft](forestry.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Railcraft [Railcraft](railcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerCore [RedPower](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerBase [RP Base](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerMachine [RP Machine](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerCompat [RP Compat](redpowercompat.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerWiring [RP Wiring](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerLogic [RP Logic](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerLighting [RP Lighting](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerWorld [RP World](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerControl [RP Control](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Factory [Factory](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Energy [Energy](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Transport [Transport](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    XyCraft [XyCraft](xycraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    GregTech_Addon [GregTech-Addon](GregTech.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IronChest [Iron Chest](IronChest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    PortalGun [Portal Gun](PortalGun.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    StevesCarts [Steve's Carts](StevesCarts.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](advancedmachines.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AdvancedSolarPanel [Advanced Solar Panels](advancedsolarpanel.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ChickenChunks [ChickenChunks](chickenchunks.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    EnderStorage [EnderStorage](enderstorage.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BinnieCore [Binnie Core](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ExtraBees [Extra Bees](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    GraviSuite [Gravitation Suite](gravisuite.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](modularforcefieldsystem.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TC [Traincraft](traincraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    drceph.petrogen [Petroleum Generator](petrogen.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    SoulShards [SoulShards](soulshards.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|Core [WR-CBE Core](wirelessredstonecore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|Addons [WR-CBE Addons](wirelessredstoneaddons.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](wirelessredstoneredpower.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BukkitForge Details: BukkitForge null-null (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:[Didn't get far enough to load plugins :/]
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 120; []
    Is Modded: Definitely; Server brand changed to 'forge,fml'
    Type: Dedicated Server (map_server.txt)

**Comment by eagl3s1ght** [comment]
@uberbuild What version of Bukkitforge are you using?
