### ISSUE TITLE
Pixelmon, Server Crash while battling trainers and players.

### ISSUE THREAD

**Issue by TinBritches** [keepcalm/BukkitForge#540]
I am running a pixelmon server with a few mods, figu's core mod 2.1.2 and figu's login mod 2.1.2. I was trying to use bukkitforge to load a few plugins like Essentials, Factions, ChestShop and Vault. I have downloaded the most up to date versions of these plugins from bukkit's website(including Factions 1.8). I have run the server for several days without bukkitforge, but when I run with bukkitforge, I get crashes when attempting to battle. Here is a recent crash report:

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2/25/13 12:21 AM
Description: Exception in server tick loop

java.lang.NullPointerException
    at pixelmon.battles.controller.BattleController.takeTurn(BattleController.java:183)
    at pixelmon.battles.controller.BattleController.update(BattleController.java:115)
    at pixelmon.battles.BattleRegistry.updateBattles(BattleRegistry.java:58)
    at pixelmon.battles.BattleTickHandler.tickStart(BattleTickHandler.java:12)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:120)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:296)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:664)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Linux (amd64) version 3.2.0-29-generic
    Java Version: 1.7.0_13, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 128832168 bytes (122 MB) / 541851648 bytes (516 MB) up to 1431699456 bytes (1365 MB)
    JVM Flags: 2 total; -Xmx1536M -Xmx1536M
    AABB Pool Size: 8665 (485240 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.26a FML v4.7.32.553 Minecraft Forge 6.6.1.527 8 mods loaded, 8 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Pixelmon [Pixelmon](Pixelmon 2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    fihgu's Core Mod [fihgu's Core Mod](fihgus Core Mod%282.1.2%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    fihgu's Login Mod [fihgu's Login Mod](fihgus Login Mod%282.1.2%29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BukkitForge Details: BukkitForge null-null (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:Vault v1.2.23-b301: Enabled, Essentials v2.10.1: Enabled, ChestShop v3.50t0041: Enabled, EssentialsChat v2.10.1: Enabled, EssentialsProtect v2.10.1: Enabled, EssentialsSpawn v2.10.1: Enabled, EssentialsAntiBuild v2.10.1: Enabled and Factions v1.8.0: Enabled
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 2305 (129080 bytes; 0 MB) allocated, 1893 (106008 bytes; 0 MB) used
    Player Count: 2 / 20; [iq['TOMMYNATER'/665, l='world', x=56.33, y=69.49, z=-18.86], iq['TinBritches'/7895, l='world', x=64.92, y=68.00, z=-12.65]]
    Is Modded: Definitely; Server brand changed to 'forge,fml'
    Type: Dedicated Server (map_server.txt)

I wasn't sure if these errors are due to bukkitforge or a plugin, any and all advice is MUCH appreciated.

Thank you!

**Comment by TinBritches** [comment]
I updated Forge Mod Loader and BukkitForge. Also removed Chestshop and Vault for now. Issues seem to have been resolved. I believe it was an issue with Forge Mod Loader.

**Comment by alpharulesirulee** [comment]
[15:22:28] [Server thread/WARN]: Unable to find spawn biome
[15:22:39] [Server thread/INFO]: Preparing start region for level 0
[15:22:40] [Server thread/INFO]: Preparing spawn area: 11%
[15:22:41] [Server thread/INFO]: Preparing spawn area: 21%
[15:22:42] [Server thread/INFO]: Preparing spawn area: 30%
[15:22:43] [Server thread/INFO]: Preparing spawn area: 38%
[15:22:44] [Server thread/INFO]: Preparing spawn area: 48%
[15:22:45] [Server thread/INFO]: Preparing spawn area: 56%
[15:22:46] [Server thread/INFO]: Preparing spawn area: 64%
[15:22:47] [Server thread/INFO]: Preparing spawn area: 72%
[15:22:48] [Server thread/INFO]: Preparing spawn area: 79%
[15:22:49] [Server thread/INFO]: Preparing spawn area: 85%
[15:22:50] [Server thread/INFO]: Preparing spawn area: 93%
[15:22:52] [Server thread/INFO]: Preparing spawn area: 97%
[15:22:52] [Server thread/INFO]: Changing view distance to 8, from 10
[15:22:52] [Server thread/INFO]: highway95[local:E:b41a7644] logged in with entity id 19153 at (270.5, 230.0, 1537.5)
[15:22:53] [Server thread/INFO]: highway95 joined the game
[15:22:56] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3459ms behind, skipping 69 tick(s)
[15:23:00] [AromaBackup/INFO]: [§1AromaBackup§r] Starting Backup. Server may lag for a bit!
[15:23:02] [AromaBackup/INFO]: [§1AromaBackup§r] Server Backup Done!
[15:23:02] [AromaBackup/INFO]: [§1AromaBackup§r] Next scheduled backup in 30 minutes.
[15:23:13] [Client thread/INFO]: [CHAT] [§1AromaBackup§r] Starting Backup. Server may lag for a bit!
[15:23:14] [Client thread/INFO]: [CHAT] [§1AromaBackup§r] Server Backup Done!
[15:23:14] [Client thread/INFO]: [CHAT] [§1AromaBackup§r] Next scheduled backup in 30 minutes.
[15:23:16] [Aroma1997Core VersionChecking/INFO]: [CHAT] Aroma1997Core failed to do VersionChecking. Either there is something wrong with your network connection or with my server.
[15:24:09] [Server thread/INFO]: Stopping server
[15:24:09] [Server thread/INFO]: Saving players
[15:24:09] [Server thread/INFO]: Saving worlds
[15:24:09] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[15:24:11] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[15:24:20] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1092) ~[blt.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NoSuchFieldError: manager
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147052_b(GuiContainerCreative.java) ~[bfl.class:?]
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:650) ~[bfl.class:?]
    at com.pixelmonmod.pixelmon.client.gui.inventory.GuiCreativeInventoryExtended.func_73863_a(GuiCreativeInventoryExtended.java:93) ~[GuiCreativeInventoryExtended.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) ~[blt.class:?]
    ... 9 more
---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/24/15 3:24 PM
Description: Rendering screen

java.lang.NoSuchFieldError: manager
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147052_b(GuiContainerCreative.java)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:650)
    at com.pixelmonmod.pixelmon.client.gui.inventory.GuiCreativeInventoryExtended.func_73863_a(GuiCreativeInventoryExtended.java:93)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
