### ISSUE TITLE
[Essential Buy/Sell/Trade] Signs not working

### ISSUE THREAD

**Issue by Maximuscr31** [keepcalm/BukkitForge#541]
All signs seem to be working but Buy signs in version 246. They show up in blue text like valid, but nothing happens when you right click them. Console also spews forth all this

25.02 01:26:48 [Server] INFO at com.earth2me.essentials.signs.SignPlayerListener.onPlayerInteract(SignPlayerListener.java:74)
25.02 01:26:48 [Server] INFO at com.earth2me.essentials.signs.EssentialsSign.onSignInteract(EssentialsSign.java:86)
25.02 01:26:48 [Server] INFO at com.earth2me.essentials.signs.SignBuy.onSignInteract(SignBuy.java:30)
25.02 01:26:48 [Server] INFO at com.earth2me.essentials.Trade.pay(Trade.java:140)
25.02 01:26:48 [Server] INFO at com.earth2me.essentials.craftbukkit.InventoryWorkaround.addAllItems(InventoryWorkaround.java:40)
25.02 01:26:48 [Server] INFO at org.bukkit.craftbukkit.inventory.CraftInventory.setContents(CraftInventory.java:64)
25.02 01:26:48 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 27 or less
25.02 01:26:48 [Server] INFO at fy.run(SourceFile:849)
25.02 01:26:48 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
25.02 01:26:48 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
25.02 01:26:48 [Server] INFO at ho.r(DedicatedServer.java:269)
25.02 01:26:48 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
25.02 01:26:48 [Server] INFO at ht.b(SourceFile:30)
25.02 01:26:48 [Server] INFO at iw.b(NetworkListenThread.java:57)
25.02 01:26:48 [Server] INFO at iv.d(NetServerHandler.java:136)
25.02 01:26:48 [Server] INFO at cg.b(TcpConnection.java:458)
25.02 01:26:48 [Server] INFO at fk.a(SourceFile:58)
25.02 01:26:48 [Server] INFO at iv.a(NetServerHandler.java:578)
25.02 01:26:48 [Server] INFO at ir.a(ItemInWorldManager.java:389)
25.02 01:26:48 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
25.02 01:26:48 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
25.02 01:26:48 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
25.02 01:26:48 [Server] INFO at net.minecraftforge.event.ASMEventHandler_116_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
25.02 01:26:48 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:421)
25.02 01:26:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
25.02 01:26:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
25.02 01:26:48 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
25.02 01:26:48 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:393)
25.02 01:26:48 [Server] INFO org.bukkit.event.EventException
25.02 01:26:48 [Server] SEVERE Could not pass event PlayerInteractEvent to Essentials v2.10.1
25.02 01:26:48 [Multicraft] Skipped 40 lines due to rate limit (30/s)
25.02 01:26:46 [Server] INFO at com.earth2me.essentials.signs.SignPlayerListener.onPlayerInteract(SignPlayerListener.java:74)
25.02 01:26:46 [Server] INFO at com.earth2me.essentials.signs.EssentialsSign.onSignInteract(EssentialsSign.java:86)
25.02 01:26:46 [Server] INFO at com.earth2me.essentials.signs.SignBuy.onSignInteract(SignBuy.java:30)
25.02 01:26:46 [Server] INFO at com.earth2me.essentials.Trade.pay(Trade.java:140)
25.02 01:26:46 [Server] INFO at com.earth2me.essentials.craftbukkit.InventoryWorkaround.addAllItems(InventoryWorkaround.java:40)
25.02 01:26:46 [Server] INFO at org.bukkit.craftbukkit.inventory.CraftInventory.setContents(CraftInventory.java:64)
25.02 01:26:46 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 27 or less
25.02 01:26:46 [Server] INFO at fy.run(SourceFile:849)
25.02 01:26:46 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
25.02 01:26:46 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
25.02 01:26:46 [Server] INFO at ho.r(DedicatedServer.java:269)
25.02 01:26:46 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
25.02 01:26:46 [Server] INFO at ht.b(SourceFile:30)
25.02 01:26:46 [Server] INFO at iw.b(NetworkListenThread.java:57)
25.02 01:26:46 [Server] INFO at iv.d(NetServerHandler.java:136)
25.02 01:26:46 [Server] INFO at cg.b(TcpConnection.java:458)
25.02 01:26:46 [Server] INFO at fk.a(SourceFile:58)
25.02 01:26:46 [Server] INFO at iv.a(NetServerHandler.java:578)
25.02 01:26:46 [Server] INFO at ir.a(ItemInWorldManager.java:389)
25.02 01:26:46 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
25.02 01:26:46 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
25.02 01:26:46 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
25.02 01:26:46 [Server] INFO at net.minecraftforge.event.ASMEventHandler_116_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
25.02 01:26:46 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:421)
25.02 01:26:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
25.02 01:26:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
25.02 01:26:46 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
25.02 01:26:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:393)
25.02 01:26:46 [Server] INFO org.bukkit.event.EventException
25.02 01:26:46 [Server] SEVERE Could not pass event PlayerInteractEvent to Essentials v2.10.1
25.02 01:26:46 [Multicraft] Skipped 40 lines due to rate limit (30/s)
25.02 01:26:45 [Server] INFO at com.earth2me.essentials.signs.SignPlayerListener.onPlayerInteract(SignPlayerListener.java:74)
25.02 01:26:45 [Server] INFO at com.earth2me.essentials.signs.EssentialsSign.onSignInteract(EssentialsSign.java:86)
25.02 01:26:45 [Server] INFO at com.earth2me.essentials.signs.SignBuy.onSignInteract(SignBuy.java:30)
25.02 01:26:45 [Server] INFO at com.earth2me.essentials.Trade.pay(Trade.java:140)
25.02 01:26:45 [Server] INFO at com.earth2me.essentials.craftbukkit.InventoryWorkaround.addAllItems(InventoryWorkaround.java:40)
25.02 01:26:45 [Server] INFO at org.bukkit.craftbukkit.inventory.CraftInventory.setContents(CraftInventory.java:64)
25.02 01:26:45 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 27 or less
25.02 01:26:45 [Server] INFO at fy.run(SourceFile:849)
25.02 01:26:45 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
25.02 01:26:45 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
25.02 01:26:45 [Server] INFO at ho.r(DedicatedServer.java:269)
25.02 01:26:45 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
25.02 01:26:45 [Server] INFO at ht.b(SourceFile:30)
25.02 01:26:45 [Server] INFO at iw.b(NetworkListenThread.java:57)
25.02 01:26:45 [Server] INFO at iv.d(NetServerHandler.java:136)
25.02 01:26:45 [Server] INFO at cg.b(TcpConnection.java:458)
25.02 01:26:45 [Server] INFO at fk.a(SourceFile:58)
25.02 01:26:45 [Server] INFO at iv.a(NetServerHandler.java:578)
25.02 01:26:45 [Server] INFO at ir.a(ItemInWorldManager.java:389)
25.02 01:26:45 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
25.02 01:26:45 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
25.02 01:26:45 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
25.02 01:26:45 [Server] INFO at net.minecraftforge.event.ASMEventHandler_116_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
25.02 01:26:45 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:421)
25.02 01:26:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
25.02 01:26:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
25.02 01:26:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
25.02 01:26:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:393)
25.02 01:26:45 [Server] INFO org.bukkit.event.EventException
25.02 01:26:45 [Server] SEVERE Could not pass event PlayerInteractEvent to Essentials v2.10.1
25.02 01:26:45 [Multicraft] Skipped 40 lines due to rate limit (30/s)
25.02 01:26:44 [Server] INFO at com.earth2me.essentials.signs.SignPlayerListener.onPlayerInteract(SignPlayerListener.java:74)
25.02 01:26:44 [Server] INFO at com.earth2me.essentials.signs.EssentialsSign.onSignInteract(EssentialsSign.java:86)
25.02 01:26:44 [Server] INFO at com.earth2me.essentials.signs.SignBuy.onSignInteract(SignBuy.java:30)
25.02 01:26:44 [Server] INFO at com.earth2me.essentials.Trade.pay(Trade.java:140)
25.02 01:26:44 [Server] INFO at com.earth2me.essentials.craftbukkit.InventoryWorkaround.addAllItems(InventoryWorkaround.java:40)
25.02 01:26:44 [Server] INFO at org.bukkit.craftbukkit.inventory.CraftInventory.setContents(CraftInventory.java:64)
25.02 01:26:44 [Server] INFO Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected 27 or less
25.02 01:26:44 [Server] INFO at fy.run(SourceFile:849)
25.02 01:26:44 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
25.02 01:26:44 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
25.02 01:26:44 [Server] INFO at ho.r(DedicatedServer.java:269)
25.02 01:26:44 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
25.02 01:26:44 [Server] INFO at ht.b(SourceFile:30)
25.02 01:26:44 [Server] INFO at iw.b(NetworkListenThread.java:57)
25.02 01:26:44 [Server] INFO at iv.d(NetServerHandler.java:136)
25.02 01:26:44 [Server] INFO at cg.b(TcpConnection.java:458)
25.02 01:26:44 [Server] INFO at fk.a(SourceFile:58)
25.02 01:26:44 [Server] INFO at iv.a(NetServerHandler.java:578)
25.02 01:26:44 [Server] INFO at ir.a(ItemInWorldManager.java:389)
25.02 01:26:44 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
25.02 01:26:44 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)

**Comment by Maximuscr31** [comment]
I made a edit. This was as of version 246.

**Comment by AlexMason** [comment]
Unfortunatly this is still happening in 251

**Comment by Sageavatar** [comment]
Worse, in my mind, is that [TRADE] Signs don't work. As all of the other shop plugins don't currently work, (Oh god please correct me if I'm wrong -- I'm pretty desperate to stop using Trade - O - Mats). Not sure if the console errors are the same or not. I'm not on my server ATM.

**Comment by eagl3s1ght** [comment]
@Sageavatar, that (and this reply) is not really relevant to this issue forum. Maybe use http://www.bukkitforge.com if you need to find a good, working chestshop plugin. For example, chestshop works great (except maybe for mod items)

**Comment by SpoonsJTD** [comment]
Updated to include Sell and Trade.

**Comment by tonnic** [comment]
It works now ?. I'll test when I'm home

**Comment by Maximuscr31** [comment]
It hasn't been updated in 3 days. He might have gotten it fixed, we just got to wait on the upload. Probably will be version 253

**Comment by SpoonsJTD** [comment]
I didn't say I fixed it, I updated this issue to include sell and trade as well, although it looks like someone removed my title change.

**Comment by Dreadcor** [comment]
Buy/sell works with the latest build. Trade still being looked at though..

**Comment by Maximuscr31** [comment]
It takes money out of the balance but gives no item when using a buy sign as of version 255

**Comment by Ev3rM0r3** [comment]
Confirmed, latest version doesn't give items on purchase, but does sell.
