### ISSUE TITLE
[WorldEdit] not functioning in Forge mod dimensions

### ISSUE THREAD

**Issue by Oliverj102** [keepcalm/BukkitForge#544]
I realise this has been in other threads but the ones in question have been closed saying its fixed but the problem is continuing.

Basically world edit won't work in the end of twilight forrest. It works in the nether tho, which is strange. I am using the Jenkins 252 build from here and the latest worldedit jar. 

Any help would be great

**Comment by dequis** [comment]
console error messages?

**Comment by Oliverj102** [comment]
There isn't one, I says it's changed x amount of blocks but they have not, could hhis possibly be the plugin thinking I'm in the overworld? It's fine in the nether and overworld, no where else

**Comment by SpoonsJTD** [comment]
I am guessing this will apply to Myst ages as well.

**Comment by eagl3s1ght** [comment]
I decided to test this for funsies. Testing is done on Tekkit Lite 0.5.7.1 with the latest WorldEdit and WorldGuard releases (not beta/pre). Summary: Execution works and blocks are changed, but returns errors. The results are found below. Twilight Forest NOT tested.

**The End testing:**
Every command seems to work, tested ones:
//hpos
//pos
//chunk
//set 20
//set 0
//regen

Blocks changed -count was also correct, //chunk //set 0 returned 6926 blocks changed.

**Mystage testing:**
Same as above.

Tested those in two different ages. Both worked fine.
This error seems to happen every command.

`2013-02-28 19:28:00 [WARNING] [Minecraft.WorldEdit] WorldEdit: Failed to do NMS access for direct NBT data copy
java.lang.NullPointerException
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:1311)
        at com.sk89q.worldedit.EditSession.rawGetBlock(EditSession.java:407)
        at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:361)
        at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:403)
        at com.sk89q.worldedit.commands.RegionCommands.regenerateChunk(RegionCommands.java:365)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:533)
        at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:257)
        at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:1)
        at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:520)
        at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
        at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1394)
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247)
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
        at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
        at keepcalm.mods.bukkit.nmsforge.CommandHandlerImpl.a(CommandHandlerImpl.java:94)
        at x.a(CommandHandler.java:14)
        at iv.d(NetServerHandler.java:768)
        at iv.a(NetServerHandler.java:734)
        at cu.a(SourceFile:44)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)`

This error only happened the first time I used //regen.

`2013-02-28 19:28:00 [WARNING] [Minecraft.WorldEdit] WorldEdit: Failed to do NMS safe block set
java.lang.NullPointerException
        at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:1330)
        at com.sk89q.worldedit.EditSession.rawSetBlock(EditSession.java:237)
        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:707)
        at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1409)
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247)
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
        at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
        at keepcalm.mods.bukkit.nmsforge.CommandHandlerImpl.a(CommandHandlerImpl.java:94)
        at x.a(CommandHandler.java:14)
        at iv.d(NetServerHandler.java:768)
        at iv.a(NetServerHandler.java:734)
        at cu.a(SourceFile:44)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)`

**Comment by Oliverj102** [comment]
I'm using mindcrack latest build, mystcraft is disabled, end and nether refuse to accept world edit commands, well, refuse to actually change anything there.

**Comment by eagl3s1ght** [comment]
@Oliverj102 I just tested this on Mindcrack v8.1.1 with BF252 and latest Worldguard/Worldedit, it worked flawlessly- except for the same error as I mentioned above.

I did notice you wrote " in the end of twilight forrest." to which I am clueless- I have not been able to open a Nether Portal or End Portal inside the Twilight Forest.

![ss 2013-03-01 at 12 07 32 ](https://f.cloud.github.com/assets/1024958/207754/e11cba36-81fb-11e2-83d4-fd5b2fa36233.jpg)

**Edit**
Ok, I have recreated your problem now. It had nothing to do with Twilight Forest for me though. WorldEdit is not working in The End of Mindcrack server. No errors except for the two I posted earlier (which don't seem to be related to actually changing any blocks, as it has shown both when working and not.)

To be clear, WorldEdit changing blocks in Nether worked for me.

**Comment by Oliverj102** [comment]
Any ideas why mine are not working? Could all the plugins need reinstalling with all the worlds in place?

**Comment by Oliverj102** [comment]
Or is it literally mindcracks issue rather then the plugins
