### ISSUE TITLE
[Resolved] Issue with lastest build past 235 relating to mystcraft

### ISSUE THREAD

**Issue by aortal** [keepcalm/BukkitForge#546]
http://pastebin.com/7SAi0jx1

Anyone with the same problem or issue? When removing mystcraft it all works fine.

java.lang.NullPointerException
        at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.initDimension(DimensionManagerImpl.java:190)
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:68)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:758)
        at codechicken.chunkloader.ChunkLoaderManager.getWorld(ChunkLoaderManager.java:504)
        at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:328)
        at codechicken.chunkloader.ChunkLoaderManager.revivePlayerLoaders(ChunkLoaderManager.java:797)
        at codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:791)
        at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java:39)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:139)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:283)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:689)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)

**Comment by gccruz** [comment]
The error occurs even without this mod installed. Don't think its because of bukkitforge. here is my error after I removed bukkitforge
Time: 2/27/13 4:55 AM
Description: Exception in server tick loop

java.lang.NullPointerException
    at com.xcompwiz.mystcraft.generation.AgeData.getStorageObject(AgeData.java:375)
    at com.xcompwiz.mystcraft.world.AgeController.reconstruct(AgeController.java:228)
    at com.xcompwiz.mystcraft.world.AgeController.<init>(AgeController.java:98)
    at com.xcompwiz.mystcraft.world.WorldProviderMyst.b(WorldProviderMyst.java:60)
    at aaq.a(WorldProvider.java:61)
    at yc.<init>(World.java:281)
    at in.<init>(WorldServer.java:103)
    at ih.<init>(SourceFile:10)
    at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:242)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:758)
    at codechicken.chunkloader.ChunkLoaderManager.getWorld(ChunkLoaderManager.java:504)
    at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:328)
    at codechicken.chunkloader.ChunkLoaderManager.revivePlayerLoaders(ChunkLoaderManager.java:797)
    at codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:791)
    at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java:39)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:139)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:283)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:689)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

**Comment by aortal** [comment]
If I remove mystcraft, the server loads correctly.

Here is the main error:

2013-02-27 05:00:32 [INFO] [ForgeModLoader] Loading dimension 56 (world) (ho@453534c9)
2013-02-27 05:00:32 [INFO] [STDERR] java.lang.NullPointerException
2013-02-27 05:00:32 [INFO] [STDERR]     at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.initDimension(DimensionManagerImpl.java:190)
2013-02-27 05:00:32 [INFO] [STDERR]     at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:68)
2013-02-27 05:00:32 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:758)
2013-02-27 05:00:32 [INFO] [STDERR]     at codechicken.chunkloader.ChunkLoaderManager.getWorld(ChunkLoaderManager.java:504)
2013-02-27 05:00:32 [INFO] [STDERR]     at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:328)
2013-02-27 05:00:32 [INFO] [STDERR]     at codechicken.chunkloader.ChunkLoaderManager.revivePlayerLoaders(ChunkLoaderManager.java:797)
2013-02-27 05:00:32 [INFO] [STDERR]     at codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:791)
2013-02-27 05:00:32 [INFO] [STDERR]     at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java:39)
2013-02-27 05:00:32 [INFO] [STDERR]     at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
2013-02-27 05:00:32 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:139)
2013-02-27 05:00:32 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:283)
2013-02-27 05:00:32 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:689)
2013-02-27 05:00:32 [INFO] [STDERR]     at ho.r(DedicatedServer.java:269)
2013-02-27 05:00:32 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-02-27 05:00:32 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-02-27 05:00:32 [INFO] [STDERR]     at fy.run(SourceFile:849)

**Comment by aortal** [comment]
Manged to fix it.

It's actually caused by Chickenchunks. 

Edit the config and set reload-dimensions=false.

Changing this will stop the mystcraft dimensions from being loaded on server restart.

Before doing this be sure to have the original agebook or a linking book otherwise you might be locked out of the world.

Once the server is started use your linkbook/age_book or portal system to force the world to load.
