### ISSUE TITLE
[Essentials-Signs] Buy/Sell/Trade not working

### ISSUE THREAD

**Issue by SpoonsJTD** [keepcalm/BukkitForge#547]
There appears to be an issue with a call to a Bukkit inventory function.

 Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected
 27 or less
 at org.bukkit.craftbukkit.inventory.CraftInventory.setContents(CraftInventory.java:64)
 at com.earth2me.essentials.craftbukkit.InventoryWorkaround.addAllItems(InventoryWorkaround.java:40)

**Comment by SpoonsJTD** [comment]
Made dupe hehe.
