### ISSUE TITLE
[Plugin] SimpleRegionMarket works but throws error on load.

### ISSUE THREAD

**Issue by eagl3s1ght** [keepcalm/BukkitForge#548]
Bukkitforge v252

`02-28 06:59:14 [SEVERE] [BukkitForge] Error occurred while enabling SimpleRegionMarket v3.2.0 (Is it up to date?)
java.lang.NullPointerException
    at com.sk89q.worldguard.bukkit.WorldConfiguration.getBoolean(WorldConfiguration.java:199)
    at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:301)
    at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:191)
    at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:202)
    at com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(WorldGuardPlugin.java:828)
    at me.ienze.SimpleRegionMarket.WorldGuardManager.getProtectedRegion(WorldGuardManager.java:57)
    at me.ienze.SimpleRegionMarket.TokenManager.checkRegions(TokenManager.java:236)
    at me.ienze.SimpleRegionMarket.SimpleRegionMarket.onEnable(SimpleRegionMarket.java:108)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:426)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:811)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:795)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:214)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Unknown Source)`

**Comment by SpoonsJTD** [comment]
This appears to be a plugin issue where it can't get all of its configuration. Check to see if there's a config folder and/or file and that the permissions are set so the plugin can access.

**Comment by eagl3s1ght** [comment]
It's probably related to the World naming. My guess is that this plugin tries to load WorldGuard regions, but is unable to because of their naming? The SimpleRegionMarket config files themselves do seem to work fine.

Should I contact the plugin author to try give some error messages when this happens?

**Comment by SpoonsJTD** [comment]
Ah, that makes sense. Maybe the author could check WorldGuard for aliases to figure out where the world folders are?

**Comment by eagl3s1ght** [comment]
[I have asked the authors about fixing this publicly via their Bukkit Plugin page.](http://dev.bukkit.org/server-mods/simple-region-market/?comment=1675)
