### ISSUE TITLE
plugins being loaded error

### ISSUE THREAD

**Issue by mosemister** [keepcalm/BukkitForge#551]
yer, brand new to bukkitforge and the first time i use it, this error came up

5:26:14 PM CONSOLE: [INFO] java.net.SocketException: Software caused connection abort: recv failed
5:26:14 PM CONSOLE: [INFO] Starting BukkitForge null-null(CB-Version: git-Bukkit-1.4.5-R1.0-b3000jnks (Really: BukkitForge for MC 1.4.7)).
5:26:14 PM CONSOLE: [INFO] This server is running BukkitForge version git-Bukkit-1.4.5-R1.0-b3000jnks (Really: BukkitForge for MC 1.4.7) (Implementing API version 1.4.7-R0.1)
5:26:14 PM CONSOLE: [INFO] at java.net.SocketInputStream.socketRead0(Native Method)
5:26:14 PM CONSOLE: [INFO] at java.net.SocketInputStream.read(Unknown Source)
5:26:14 PM CONSOLE: [INFO] at java.net.SocketInputStream.read(Unknown Source)
5:26:14 PM CONSOLE: [INFO] at java.net.SocketInputStream.read(Unknown Source)
5:26:14 PM CONSOLE: [INFO] at java.io.FilterInputStream.read(Unknown Source)
5:26:14 PM CONSOLE: [INFO] at ef.a(Packet.java:142)
5:26:14 PM CONSOLE: [INFO] at cg.i(TcpConnection.java:324)
5:26:14 PM CONSOLE: [INFO] at cg.c(TcpConnection.java:544)
5:26:14 PM CONSOLE: [INFO] at ch.run(SourceFile:93)
5:26:14 PM CONSOLE: [INFO] Plugins are being loaded...
5:26:14 PM CONSOLE: [SEVERE] Something real bad happened! The CraftAPI will not be running for this Minecraft session.

im running a normal tekkit light server,
plz help, bukkits so good

**Comment by eagl3s1ght** [comment]
@mosemister Please post the whole ForgeModLoader.log..

**Comment by SpoonsJTD** [comment]
Please make sure BukkitForge is in coremods not mods.
