### ISSUE TITLE
[Plugin] InvMaster returns error on command.

### ISSUE THREAD

**Issue by eagl3s1ght** [keepcalm/BukkitForge#554]
Tested on BF255.
Command used: /inv <player>
Related: #432 

`[STDERR] org.bukkit.command.CommandException: Unhandled exception executing command 'inventory' in plugin InvMaster v1.1
[STDERR]  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[STDERR]  at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
[STDERR]  at keepcalm.mods.bukkit.nmsforge.CommandHandlerImpl.a(CommandHandlerImpl.java:92)
[STDERR]  at x.a(CommandHandler.java:14)
[STDERR]  at iv.d(NetServerHandler.java:768)
[STDERR]  at iv.a(NetServerHandler.java:734)
[STDERR]  at cu.a(SourceFile:44)
[STDERR]  at cg.b(TcpConnection.java:458)
[STDERR]  at iv.d(NetServerHandler.java:136)
[STDERR]  at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
[STDERR]  at iw.b(NetworkListenThread.java)
[STDERR]  at ht.b(SourceFile:30)
[STDERR]  at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:328)
[STDERR]  at ho.r(DedicatedServer.java:269)
[STDERR]  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:224)
[STDERR]  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:143)
[STDERR]  at fy.run(SourceFile:849)
[STDERR] Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_4_R1/inventory/CraftItemStack
[STDERR]  at com.deaboy.invmaster.playerfile.PlayerFile.importInventory(PlayerFile.java:230)
[STDERR]  at com.deaboy.invmaster.playerfile.PlayerFile.<init>(PlayerFile.java:43)
[STDERR]  at com.deaboy.invmaster.InvMaster.openPlayerFile(InvMaster.java:77)
[STDERR]  at com.deaboy.invmaster.InvMasterCommands.onCommand(InvMasterCommands.java:51)
[STDERR]  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[STDERR]  ... 16 more
[STDERR] Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_4_R1.inventory.CraftItemStack
[STDERR]  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:180)
[STDERR]  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:175)
[STDERR]  at java.lang.ClassLoader.loadClass(Unknown Source)
[STDERR]  at java.lang.ClassLoader.loadClass(Unknown Source)
[STDERR]  ... 21 more`

**Comment by dequis** [comment]
Should be basically the same issue as #553 (versioned OBC class names)
