### ISSUE TITLE
Error Without a startup (FTB)

### ISSUE THREAD

**Issue by zerwih** [keepcalm/BukkitForge#558]
When i run the Feed The best server(Mindcrack) in a console server say
## 

2013-03-03 12:05:03 [SEVERE] [ForgeModLoader] A critical problem occured registering the ASM transformer class miscperipherals.asm.OverrideIfLoadedTransformer
java.lang.ClassNotFoundException: miscperipherals.asm.OverrideIfLoadedTransformer
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:77)
    at miscperipherals.core.MiscPeripherals.onLoad(MiscPeripherals.java:167)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:487)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:505)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:351)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at net.minecraftforge.transformers.EventTransformer.transform(EventTransformer.java:29)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
##     ... 34 more 

SECOND PART

2013-03-03 12:05:03 [SEVERE] [ForgeModLoader] [Modual ForceField System] cannot read remote Version file!
java.io.FileNotFoundException: https://raw.github.com/Thunderdark/ModularForceFieldSystem/master/src/minecraft/versioninfo
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at chb.mods.mffs.common.Versioninfo.newestversion(Versioninfo.java:61)
    at chb.mods.mffs.common.ModularForceFieldSystem.preInit(ModularForceFieldSystem.java:251)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:487)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:505)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:351)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
##     at fy.run(SourceFile:849)

And i have no idea how to fix it :(

**Comment by dequis** [comment]
This error message doesn't mention bukkitforge at all. Does it only happen when you use bukkitforge, and removing it lets you start it normally?

**Comment by zerwih** [comment]
When i remove bukkitforge server starts normally.
How to fix this errors?
May be remove something or add something in  to jar file or in a folder?

**Comment by xfloh22** [comment]
i get both those errors with and without bukkitforge and it works fine. the second error you posted is just saying that it cant determine what version of the mod it is... i think.... not sure though.

**Comment by JHall25** [comment]
I get similar errors on my custom modpack server and it is the bukkit forge because i've been running it for at least a couple of months and the only thing i've changed is the bukkitforge and it claims something about 1.3 . My server is 1.4.7 and i know i have the right version so i wonder if it's a specific mod confliction.
