### ISSUE TITLE
Null Pointer on startup

### ISSUE THREAD

**Issue by SchrodingersFat** [keepcalm/BukkitForge#560]
Even without loading any plugins, the following error is thrown at startup. 

http://pastebin.com/zCwuhVWr

**Comment by dequis** [comment]
Copypasting here in case the pastebin expires (the "github flavored markdown" link explains how to do code blocks)

```
java.lang.NullPointerException
        at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.initDimension(DimensionManagerImpl.java:195)
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:68)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:758)
        at codechicken.chunkloader.ChunkLoaderManager.getWorld(ChunkLoaderManager.java:504)
        at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.revive(ChunkLoaderManager.java:328)
        at codechicken.chunkloader.ChunkLoaderManager.revivePlayerLoaders(ChunkLoaderManager.java:797)
        at codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:791)
        at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java:39)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:138)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:282)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:689)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
```
