### ISSUE TITLE
CommandBook wont load on startup

### ISSUE THREAD

**Issue by BearFather** [keepcalm/BukkitForge#563]
I'm a real noob to FTB server.  But been running bukkit servers for awhile. So I hope I'm just a noob and not a bug. Not sure what versions of plugins you support.

Running FTB Minecrack with BukkitForge-1.4.7-255.jar    I have in plugins, PEX, CommandBook, and CraftIRC.  CraftIRC works, and PEX not sure but I can list the commands, but no plugin using it. Running lastest devbukkit release on all plugins.

During the loading of the server I get this:

2013-03-04 12:44:45 [SEVERE] [BukkitForge] Could not load './plugins/CommandBook.jar' in folder './plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandPermissionsException
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:206)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:232)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:767)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:208)
        at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/CommandPermissionsException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:195)
        ... 6 more

**Comment by iarspider** [comment]
CommandBook needs WorldEdit to be installed.

**Comment by BearFather** [comment]
Told you it was a noob issue.  I knew that not sure why it didn't click.
