### ISSUE TITLE
[WorldEdit] java.lang.NoClassDefFoundError: net/minecraft/server/Block

### ISSUE THREAD

**Issue by tubaboy26** [keepcalm/BukkitForge#566]
I'm running the latest version of WorldEdit and BukkitForge

03-05 16:12:52 [INFO] [STDERR] java.lang.NoClassDefFoundError: net/minecraft/ser
ver/Block
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.worldedit.bukkit.BukkitWorld.isVali
dBlockType(BukkitWorld.java:872)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.worldedit.WorldEdit.getBlock(WorldE
dit.java:413)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.worldedit.WorldEdit.getBlock(WorldE
dit.java:354)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.worldedit.WorldEdit.getBlock(WorldE
dit.java:548)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.worldedit.WorldEdit.getBlockPattern
(WorldEdit.java:607)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.worldedit.commands.RegionCommands.s
et(RegionCommands.java:74)
03-05 16:12:52 [INFO] [STDERR]  at sun.reflect.NativeMethodAccessorImpl.invoke0(
Native Method)
03-05 16:12:52 [INFO] [STDERR]  at sun.reflect.NativeMethodAccessorImpl.invoke(U
nknown Source)
03-05 16:12:52 [INFO] [STDERR]  at sun.reflect.DelegatingMethodAccessorImpl.invo
ke(Unknown Source)
03-05 16:12:52 [INFO] [STDERR]  at java.lang.reflect.Method.invoke(Unknown Sourc
e)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.minecraft.util.commands.CommandsMan
ager.invokeMethod(CommandsManager.java:522)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.worldedit.WorldEdit$1.invokeMethod(
WorldEdit.java:240)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.worldedit.WorldEdit$1.invokeMethod(
WorldEdit.java:171)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.minecraft.util.commands.CommandsMan
ager.executeMethod(CommandsManager.java:509)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.minecraft.util.commands.CommandsMan
ager.execute(CommandsManager.java:425)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.worldedit.WorldEdit.handleCommand(W
orldEdit.java:1338)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.worldedit.bukkit.WorldEditPlugin.on
Command(WorldEditPlugin.java:197)
03-05 16:12:52 [INFO] [STDERR]  at com.sk89q.bukkit.util.DynamicPluginCommand.ex
ecute(DynamicPluginCommand.java:52)
03-05 16:12:52 [INFO] [STDERR]  at keepcalm.mods.bukkit.forgeHandler.commands.Co
mmandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
03-05 16:12:52 [INFO] [STDERR]  at keepcalm.mods.bukkit.nmsforge.CommandHandlerI
mpl.a(CommandHandlerImpl.java:92)
03-05 16:12:52 [INFO] [STDERR]  at x.a(CommandHandler.java:14)
03-05 16:12:52 [INFO] [STDERR]  at iv.d(NetServerHandler.java:818)
03-05 16:12:52 [INFO] [STDERR]  at iv.a(NetServerHandler.java:778)
03-05 16:12:52 [INFO] [STDERR]  at cu.a(SourceFile:44)
03-05 16:12:52 [INFO] [STDERR]  at cg.b(TcpConnection.java:458)
03-05 16:12:52 [INFO] [STDERR]  at iv.d(NetServerHandler.java:141)
03-05 16:12:52 [INFO] [STDERR]  at iw.b_net_minecraft_network_NetworkListenThrea
d_networkTick_p0(NetworkListenThread.java:57)
03-05 16:12:52 [INFO] [STDERR]  at iw.b(NetworkListenThread.java)
03-05 16:12:52 [INFO] [STDERR]  at ht.b(SourceFile:30)
03-05 16:12:52 [INFO] [STDERR]  at net.minecraft.server.MinecraftServer.r(Minecr
aftServer.java:326)
03-05 16:12:52 [INFO] [STDERR]  at ho.r(DedicatedServer.java:269)
03-05 16:12:52 [INFO] [STDERR]  at net.minecraft.server.MinecraftServer.q(Minecr
aftServer.java:222)
03-05 16:12:52 [INFO] [STDERR]  at net.minecraft.server.MinecraftServer.run(Mine
craftServer.java:141)
03-05 16:12:52 [INFO] [STDERR]  at fy.run(SourceFile:849)

**Comment by dequis** [comment]
Do you have ForgeEssentials? It's known to cause this exact issue.

We didn't have a bug reported for it yet, so even if you 'fix' it yourself by removing FE, don't close the ticket.
