### ISSUE TITLE
[Enjin] - Bukkitforge Version 

### ISSUE THREAD

**Issue by enterprise12nx** [keepcalm/BukkitForge#568]
2013-03-06 15:04:50 [INFO] [BukkitForge] Server issued server command: enjinpush
2013-03-06 15:04:50 [INFO] [STDERR] org.bukkit.command.CommandException: Unhandled exception executing command 'enjin' in plugin Enjin Minecraft Plugin v2.4.1-tekkit
2013-03-06 15:04:50 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
2013-03-06 15:04:50 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
2013-03-06 15:04:50 [INFO] [STDERR]     at keepcalm.mods.bukkit.nmsforge.CommandHandlerImpl.a(CommandHandlerImpl.java:92)
2013-03-06 15:04:50 [INFO] [STDERR]     at x.a(CommandHandler.java:14)
2013-03-06 15:04:50 [INFO] [STDERR]     at ho.al(DedicatedServer.java:308)
2013-03-06 15:04:50 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-03-06 15:04:50 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
2013-03-06 15:04:50 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-03-06 15:04:50 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-03-06 15:04:50 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-03-06 15:04:50 [INFO] [STDERR]     at org.bukkit.craftbukkit.CraftServer.getOfflinePlayers(CraftServer.java:1220)
2013-03-06 15:04:50 [INFO] [STDERR]     at com.enjin.officialplugin.EnjinMinecraftPlugin.onCommand(EnjinMinecraftPlugin.java:599)
2013-03-06 15:04:50 [INFO] [STDERR]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-03-06 15:04:50 [INFO] [STDERR]     ... 8 more

**Comment by dequis** [comment]
Modpack details? Can this plugin be downloaded?

**Comment by enterprise12nx** [comment]
I am using tekkit lite, yes it can be downloaded Its The BukkitForge Version Here:
Enjin Site: http://www.enjin.com/
Plugin Site: http://dev.bukkit.org/server-mods/emp/
Download Version: http://resources.guild-hosting.net/948/downloads/emp/2.4.1-tekkit/EnjinMinecraftPlugin.jar

There is a Forge Version in development, but it barely works.
