### ISSUE TITLE
b255: Incompatible with Feed The Beast Ultimate 1.0.1 - crash on startup

### ISSUE THREAD

**Issue by WebMaka** [keepcalm/BukkitForge#573]
Now that Feed The Beast has released their "ultimate" modpack, I tested it with BukkitForge build 255. This is what it did during startup:

2013-03-08 15:38:30 [INFO] [STDOUT] THIS SERVER IS RUNNING BUKKITFORGE null-null. JUST IN CASE SOMEONE ASKS!
2013-03-08 15:38:31 [INFO] [STDERR] Exception in thread "main" java.lang.NoClassDefFoundError: gm
2013-03-08 15:38:31 [INFO] [STDERR]     at java.lang.Class.getDeclaredMethods0(Native Method)
2013-03-08 15:38:31 [INFO] [STDERR]     at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at java.lang.Class.getDeclaredMethod(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at cpw.mods.fml.relauncher.ReflectionHelper.findMethod(ReflectionHelper.java:170)
2013-03-08 15:38:31 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:138)
2013-03-08 15:38:31 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
2013-03-08 15:38:31 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
2013-03-08 15:38:31 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: gm
2013-03-08 15:38:31 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
2013-03-08 15:38:31 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     ... 7 more
2013-03-08 15:38:31 [INFO] [STDERR] Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: ig
2013-03-08 15:38:31 [INFO] [STDERR]     at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at org.objectweb.asm.ClassWriter.a(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at org.objectweb.asm.Frame.a(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at org.objectweb.asm.Frame.a(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
2013-03-08 15:38:31 [INFO] [STDERR]     at com.eoware.asm.asmagic.AsmagicClassTransformer.transformClass(AsmagicClassTransformer.java:88)
2013-03-08 15:38:31 [INFO] [STDERR]     at com.eoware.asm.asmagic.AsmagicClassTransformer.transform(AsmagicClassTransformer.java:29)
2013-03-08 15:38:31 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.transformers.BukkitAsmagicTransformer.transform(BukkitAsmagicTransformer.java:67)
2013-03-08 15:38:31 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
2013-03-08 15:38:31 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
2013-03-08 15:38:31 [INFO] [STDERR]     ... 9 more

Needless to say, it's a no-joy type thing. Hopefully it's a simple fix...

**Comment by void513** [comment]
Strange i was unable to recreate the error. did you add any other mods or core coremods to it?

**Comment by dequis** [comment]
Another user got exactly the same error with tekkit lite 0.6.0. I could reproduce it, and seems to be a conflict with `[1.4.6]TreeCapitator.Forge.1.4.6.r07.Uni.CoreMod.jar`, which doesn't seem to be part of ftb ultimate.

edit: i'd like to know the same thing void513 asked.

**Comment by WebMaka** [comment]
That could well be it, as we -are- running TreeCapitator.

**Comment by dequis** [comment]
Then it duplicates #570

**Comment by SpoonsJTD** [comment]
Dupe
