### ISSUE TITLE
OpenInv Plugin is not loading.

### ISSUE THREAD

**Issue by noahmayr** [keepcalm/BukkitForge#574]
#### Stacktrace:

```
2013-03-09 12:12:00 [INFO] [com.lishid.openinv.OpenInv] [OpenInv] Enabling OpenInv v1.9.7
2013-03-09 12:12:00 [SEVERE] [BukkitForge] Error occurred while enabling OpenInv v1.9.7 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/IInventory
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:186)
    at com.lishid.openinv.internal.InternalAccessor.Initialize(InternalAccessor.java:40)
    at com.lishid.openinv.OpenInv.onEnable(OpenInv.java:65)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:426)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:811)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:795)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:214)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.IInventory
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:180)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:175)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 12 more
```

**Comment by noahmayr** [comment]
Probably related to #455.
