### ISSUE TITLE
Tekkit Lite 0.6.1

### ISSUE THREAD

**Issue by Bigifty** [keepcalm/BukkitForge#586]
I have looked through the posts and didnt see a post on this issue but I have seen posts on other sites. This is from my log:
java.lang.ClassNotFoundException: keepcalm.mods.events.asm.transformers.events.BlockEventHelpers
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:77)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:238)
    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
Caused by: java.lang.AbstractMethodError
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
    ... 8 more

and it stops right there and will not move. 

I have been looking and I have tried Bukkitforge 1.5-5 nothing works. If anyone has any ideas I will take them.

**Comment by jmbjorndalen** [comment]
I've seen comments in the following thread suggesting that 250 will work (245 for one): 

http://forums.technicpack.net/threads/bukkitforge-getting-bukkit-plugins-on-tekkit-lite.34804/page-22

I'm not sure if this helps, but maybe one extra bit of info for debugging.
