### ISSUE TITLE
[LWC] Hopper (Branch 1.5)

### ISSUE THREAD

**Issue by Fundaris** [keepcalm/BukkitForge#595]
Hi, i freshly setuped a test server with 1.5.1 bukkitforgebuild and got a problem with lwc.

2013-03-29 23:37:45 [SCHWERWIEGEND] [BukkitForge] Error occurred while enabling LWC v4.3.2 (b858-git-MANUAL) (March 16, 2013) (Is it up to date?)
java.lang.NoSuchFieldError: HOPPER
    at com.griefcraft.sql.PhysDB.performDatabaseUpdates(PhysDB.java:453)
    at com.griefcraft.sql.PhysDB.load(PhysDB.java:393)
    at com.griefcraft.lwc.LWC.load(LWC.java:1422)
    at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:200)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:426)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:852)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:836)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:212)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:49)
    at java.lang.Thread.run(Thread.java:636)

The called function is                 blacklistedBlocks.add(Integer.toString(Material.HOPPER.getId()));

**Comment by Fundaris** [comment]
Material.java is not up to date :/

**Comment by alexbegt** [comment]
Fixed
