### ISSUE TITLE
Can't connect to my server with Bukkit4Vanilla

### ISSUE THREAD

**Issue by Woryk** [keepcalm/BukkitForge#6]
Hello,
I test Bukkit4Vanilla in my local Minecraft server and the server launch correctly but when I'm connecting to the server he crash 1 minute after.
This is my crash report :

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 09/12/12 15:58
Description: Ticking entity

java.lang.IllegalArgumentException: No enum const class org.bukkit.event.entity.EntityDamageEvent$DamageCause.inWall
    at java.lang.Enum.valueOf(Unknown Source)
    at org.bukkit.event.entity.EntityDamageEvent$DamageCause.valueOf(EntityDamageEvent.java:69)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:76)
    at net.minecraftforge.event.ASMEventHandler_3_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:313)
    at md.a(EntityLiving.java:928)
    at qj.a(SourceFile:44)
    at md.y(EntityLiving.java:535)
    at lq.j_(Entity.java:398)
    at md.j_(EntityLiving.java:743)
    at qj.j_(SourceFile:30)
    at qp.j_(SourceFile:29)
    at xv.a(World.java:2258)
    at in.a(WorldServer.java:604)
    at xv.g(World.java:2221)
    at xv.h(World.java:2068)
    at in.h(WorldServer.java:473)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:673)
    at ho.r(DedicatedServer.java:252)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
    at fy.run(SourceFile:856)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.lang.Enum.valueOf(Unknown Source)
    at org.bukkit.event.entity.EntityDamageEvent$DamageCause.valueOf(EntityDamageEvent.java:69)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingAttack(ForgeEventHandler.java:76)
    at net.minecraftforge.event.ASMEventHandler_3_ForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:313)
    at md.a(EntityLiving.java:928)
    at qj.a(SourceFile:44)
    at md.y(EntityLiving.java:535)
    at lq.j_(Entity.java:398)
    at md.j_(EntityLiving.java:743)
    at qj.j_(SourceFile:30)
    at qp.j_(SourceFile:29)
    at xv.a(World.java:2258)
    at in.a(WorldServer.java:604)
    at xv.g(World.java:2221)

-- Entity being ticked --
Details:
    Entity Type: Spider (qp)
    Entity ID: 2634
    Name: Spider
    Exact location: -94,50, 39,00, 317,50
    Block location: World: (-95,39,317), Chunk: (at 1,2,13 in -6,19; contains blocks -96,0,304 to -81,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Momentum: 0,00, -0,08, 0,00
Stacktrace:
    at xv.h(World.java:2068)
    at in.h(WorldServer.java:473)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [iq['Woryk'/2577, l='world', x=-187,50, y=65,03, z=251,50]]
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: 6780546681224150515
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-188,64,244), Chunk: (at 4,4,4 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 208 game time, 208 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 101197 (now: false), thunder time: 114192 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:673)
    at ho.r(DedicatedServer.java:252)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
    at fy.run(SourceFile:856)

-- System Details --
Details:
    Minecraft Version: 1.4.5
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.6.0_37, Sun Microsystems Inc.
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Sun Microsystems Inc.
    Memory: 739986016 bytes (705 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 2 total; -Xmx1024M -Xms1024M
    AABB Pool Size: 4443 (248808 bytes; 0 MB) allocated, 2628 (147168 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.23 FML v4.5.2.459 Minecraft Forge 6.4.1.409 4 mods loaded, 4 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Bukkit4Vanilla [Bukkit For Vanilla](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 709 (39704 bytes; 0 MB) allocated, 385 (21560 bytes; 0 MB) used
    Player Count: 1 / 20; [iq['Woryk'/2577, l='world', x=-187,50, y=65,03, z=251,50]]
    Is Modded: Definitely; Server brand changed to 'forge,fml'
    Type: Dedicated Server (map_server.txt)

**Comment by dirge0** [comment]
I think he fixed this issue, but not yet released it.

**Comment by Woryk** [comment]
Ok, thanks for your fast response.

**Comment by keepcalm** [comment]
Yup, already fixed, same as #1
