### ISSUE TITLE
MoCreatures + Towny

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#60]
2012-12-30 06:24:01 [WARNING] [com.palmergames.bukkit.towny.Towny] [Towny] Task #8 for Towny v0.82.0.0 generated an exception
java.lang.IllegalArgumentException: Unknown entity
        at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:214)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.getLivingEntities(BukkitWorld.java:703)
        at com.palmergames.bukkit.towny.tasks.MobRemovalTimerTask.run(Unknown Source)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:345)
        at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:23)
        at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
        at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)

Also Chat is not working i'm getting

"[g][world]{permsuffix} Owner AM AH Wolftein{permsuffix}: Message Here"

**Comment by keepcalm** [comment]
Chat bug - I noticed it, no clue, I'll try and fix it eventually, getEntity I thought I fixed. But I'll fix it. Again ;)
