### ISSUE TITLE
[Bukkit Forge] build 259 - Tekkit Lite 0.6.1 Not Working

### ISSUE THREAD

**Issue by enterprise12nx** [keepcalm/BukkitForge#613]
Here is the error report:

2013-04-06 13:51:21 [INFO] [ForgeModLoader] Forge Mod Loader version 4.7.35.556 for Minecraft 1.4.7 loading
2013-04-06 13:51:21 [INFO] [ForgeModLoader] Downloading file http://files.minecraftforge.net/fmllibs/argo-2.25.jar
2013-04-06 13:51:21 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:21 [INFO] [ForgeModLoader] Downloading file http://files.minecraftforge.net/fmllibs/guava-12.0.1.jar
2013-04-06 13:51:23 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:23 [INFO] [ForgeModLoader] Downloading file http://files.minecraftforge.net/fmllibs/asm-all-4.0.jar
2013-04-06 13:51:23 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:23 [INFO] [ForgeModLoader] Downloading file http://files.minecraftforge.net/fmllibs/bcprov-jdk15on-147.jar
2013-04-06 13:51:24 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:24 [INFO] [ForgeModLoader] Downloading file http://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.3/commons-lang-2.3.jar
2013-04-06 13:51:24 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:24 [INFO] [ForgeModLoader] Downloading file http://repo.maven.apache.org/maven2/org/avaje/ebean/2.8.1/ebean-2.8.1.jar
2013-04-06 13:51:25 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:25 [INFO] [ForgeModLoader] Downloading file https://github.com/keepcalm/BukkitForge/blob/master/lib/gson-2.1-cb.jar?raw=true
2013-04-06 13:51:28 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:28 [INFO] [ForgeModLoader] Downloading file http://repo.maven.apache.org/maven2/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.jar
2013-04-06 13:51:29 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:29 [INFO] [ForgeModLoader] Downloading file http://repo.maven.apache.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
2013-04-06 13:51:29 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:29 [INFO] [ForgeModLoader] Downloading file http://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.9/snakeyaml-1.9.jar
2013-04-06 13:51:29 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:29 [INFO] [ForgeModLoader] Downloading file http://repo.maven.apache.org/maven2/org/fusesource/jansi/jansi/1.9/jansi-1.9.jar
2013-04-06 13:51:29 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:29 [INFO] [ForgeModLoader] Downloading file https://github.com/keepcalm/BukkitForge/blob/master/lib/guava10-renamed.jar?raw=true
2013-04-06 13:51:31 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:31 [INFO] [ForgeModLoader] Downloading file https://github.com/keepcalm/BukkitForge/blob/master/lib/SpecialSource-1.3-SNAPSHOT.jar?raw=true
2013-04-06 13:51:33 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:33 [INFO] [ForgeModLoader] Downloading file http://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.14/mysql-connector-java-5.1.14.jar
2013-04-06 13:51:33 [INFO] [ForgeModLoader] Download complete
2013-04-06 13:51:34 [INFO] [STDOUT] Bukkitforge call to getASMTransformer ...
2013-04-06 13:51:34 [INFO] [STDOUT] Bukkitforge call to getASMTransformer ...
2013-04-06 13:51:34 [INFO] [STDOUT] Adding Accesstransformer map: bukkit_at.cfg
2013-04-06 13:51:34 [SEVERE] [ForgeModLoader] A critical problem occured registering the ASM transformer class keepcalm.mods.events.asm.transformers.events.BlockEventHelpers
java.lang.ClassNotFoundException: keepcalm.mods.events.asm.transformers.events.BlockEventHelpers
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:77)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:238)
    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
Caused by: java.lang.AbstractMethodError
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
    ... 8 more
2013-04-06 13:51:34 [SEVERE] [ForgeModLoader] A critical problem occured registering the ASM transformer class keepcalm.mods.events.asm.transformers.events.EntityEventHelpers
java.lang.ClassNotFoundException: keepcalm.mods.events.asm.transformers.events.EntityEventHelpers
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:77)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:238)
    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
Caused by: java.lang.AbstractMethodError
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
    ... 8 more
2013-04-06 13:51:34 [SEVERE] [ForgeModLoader] A critical problem occured registering the ASM transformer class keepcalm.mods.bukkit.asm.transformers.BukkitAsmagicTransformer
java.lang.ClassNotFoundException: keepcalm.mods.bukkit.asm.transformers.BukkitAsmagicTransformer
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:77)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:238)
    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
Caused by: java.lang.AbstractMethodError
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
    ... 8 more
2013-04-06 13:51:34 [INFO] [STDERR] Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: cpw/mods/fml/common/asm/ASMTransformer
2013-04-06 13:51:34 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:175)
2013-04-06 13:51:34 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
2013-04-06 13:51:34 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
2013-04-06 13:51:34 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
2013-04-06 13:51:34 [INFO] [STDERR] Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/common/asm/ASMTransformer
2013-04-06 13:51:34 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass1(Native Method)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.security.SecureClassLoader.defineClass(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.net.URLClassLoader.defineClass(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.net.URLClassLoader.access$100(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.net.URLClassLoader$1.run(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.net.URLClassLoader$1.run(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.security.AccessController.doPrivileged(Native Method)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.net.URLClassLoader.findClass(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:110)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:77)
2013-04-06 13:51:34 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:238)
2013-04-06 13:51:34 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
2013-04-06 13:51:34 [INFO] [STDERR]     ... 3 more
2013-04-06 13:51:34 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.asm.ASMTransformer
2013-04-06 13:51:34 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-04-06 13:51:34 [INFO] [STDERR]     ... 18 more
2013-04-06 13:51:34 [INFO] [STDERR] Caused by: java.lang.AbstractMethodError
2013-04-06 13:51:34 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
2013-04-06 13:51:34 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
2013-04-06 13:51:34 [INFO] [STDERR]     ... 20 more

I have heard removing Tree Capitator fixes it..i removed the config and the coremod of it..nothing changed. Thanks for your time in looking into this.

**Comment by Fundaris** [comment]
Hey u shoud use an other Version BF 259 is for MC 1.5.1 :) Last 1.4.7 build is 257
