### ISSUE TITLE
Error when saving - Redstone Ether

### ISSUE THREAD

**Issue by SquaredTiki** [keepcalm/BukkitForge#618]
When trying to save the following error is logged to the console:

```
java.lang.NullPointerException
    at codechicken.wirelessredstone.core.RedstoneEtherServer.saveEther(RedstoneEtherServer.java:66)
    at codechicken.wirelessredstone.core.WRCoreEventHandler.onWorldSave(WRCoreEventHandler.java:57)
    at net.minecraftforge.event.ASMEventHandler_111_WRCoreEventHandler_onWorldSave_Save.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at in.a(WorldServer.java:845)
    at org.bukkit.craftbukkit.CraftWorld.save(CraftWorld.java:803)
    at org.bukkit.command.defaults.SaveCommand.execute(SaveCommand.java:30)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at keepcalm.mods.bukkit.nmsforge.CommandHandlerImpl.a(CommandHandlerImpl.java:92)
    at x.a(CommandHandler.java:14)
    at ho.al(DedicatedServer.java:308)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
```

The latest version of BukkitForge is being used

**Comment by Ionaru** [comment]
Anything else you can tell me about the crash? Error log, what other mods are you using, 1.5.1 or 1.4.7?

**Comment by SquaredTiki** [comment]
It does not crash rather just logs the error. It is 1.4.7 with the following mods: http://d.pr/i/5vZD

It started happening after I updated a few mods in particular namely:
- Wireless Redstone
- NEI
- CodeChickenCore
- Chicken Chunks
- Mekanism
- MFFS
- Electric Expansion
- Ender Storage

**Comment by Ionaru** [comment]
Does everything work? Or are there features not working because of this?

**Comment by SquaredTiki** [comment]
Everything works however the log file becomes quite a large size over time and also (this may or may not be related) but if the server is left on for about 2-3 days straight it becomes impossible to connect to despite it being running fine.

**Comment by Ionaru** [comment]
And you are running BukkitForge 257?

**Comment by SquaredTiki** [comment]
Yes, I am indeed

**Comment by Ionaru** [comment]
Then I don't know what's causing the trouble, a (temporary) solution is to restart the server everyday and delete the log file every now and then.

**Comment by SquaredTiki** [comment]
That's the solution I've employed at the moment, thanks anyway for your help!

**Comment by Ionaru** [comment]
I'm sorry I couldn't help you fix it.
Would anyone else like to try? :P
