### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by shakey2** [keepcalm/BukkitForge#62]
I'm getting this error:

2012-12-30 16:14:45 [FINEST] [ForgeModLoader] Received valid FML login packet from /127.0.0.1:4886
2012-12-30 16:14:45 [INFO] [Minecraft] Disconnecting shakey2 [/127.0.0.1:4886]: Internal server error
2012-12-30 16:14:45 [SEVERE] [ForgeModLoader] Error handling login related packet - connection from shakey2 [/127.0.0.1:4886] refused
java.lang.NullPointerException
    at org.bukkit.Bukkit.getPluginManager(Bukkit.java:140)
    at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.connectionReceived(ConnectionHandler.java:66)
    at cpw.mods.fml.common.network.NetworkRegistry.connectionReceived(NetworkRegistry.java:169)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:133)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
    at it.d(NetLoginHandler.java:179)
    at it.c(NetLoginHandler.java:72)
    at hu.a(ServerListenThread.java:56)
    at ht.b(SourceFile:29)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
2012-12-30 16:14:45 [WARNING] [Minecraft] Failed to handle packet for shakey2 [/127.0.0.1:4886]: java.lang.NullPointerException
java.lang.NullPointerException
    at org.bukkit.Bukkit.getPluginManager(Bukkit.java:140)
    at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.connectionReceived(ConnectionHandler.java:66)
    at cpw.mods.fml.common.network.NetworkRegistry.connectionReceived(NetworkRegistry.java:169)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:133)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
    at it.d(NetLoginHandler.java:179)
    at it.c(NetLoginHandler.java:72)
    at hu.a(ServerListenThread.java:56)
    at ht.b(SourceFile:29)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

**Comment by keepcalm** [comment]
Wait a few seconds - BukkitForge takes longer to load than the server does. I'll fix it so it doesn't NPE today

**Comment by shakey2** [comment]
No I'm waiting several minutes and I still get that error even after the console has stop showing new info. I just get internal server error on my client.
