### ISSUE TITLE
Error in start server and client game

### ISSUE THREAD

**Issue by FlyBlb** [keepcalm/BukkitForge#624]
Server:
2013-04-28 14:45:02 [INFO] [ForgeModLoader] Forge Mod Loader version 5.1.29.661 for Minecraft 1.5.1 loading
2013-04-28 14:45:02 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) Client VM, version 1.7.0_21, running on Windows XP:x86:5.1, installed at C:\Program Files\Java\jre7
2013-04-28 14:45:02 [FINE] [ForgeModLoader] Java classpath at launch is C:\Documents and Settings\PS\Plocha\Servery\Upside_Down Zombie Server\minecraft_server.jar
2013-04-28 14:45:02 [FINE] [ForgeModLoader] Java library path at launch is C:\Program Files\Java\jre7\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\wbem;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Program Files\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\QuickTime\QTSystem;C:\Program Files\MySQL\MySQL Server 5.0\bin;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\Program Files\TortoiseSVN\bin;C:\WINDOWS\system32\WindowsPowerShell\v1.0;C:\Program Files\Common Files\Microsoft Shared\Windows Live;.
2013-04-28 14:45:02 [FINE] [ForgeModLoader] Enabling runtime deobfuscation
2013-04-28 14:45:02 [WARNING] [ForgeModLoader] The coremod keepcalm.mods.bukkit.asm.BukkitASMLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-04-28 14:45:02 [WARNING] [ForgeModLoader] The coremod codechicken.core.asm.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-04-28 14:45:02 [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-04-28 14:45:02 [INFO] [ForgeModLoader] Downloading file https://github.com/keepcalm/BukkitForge/blob/master/lib/SpecialSource-1.3-SNAPSHOT.jar?raw=true
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] There was a problem downloading the file SpecialSource-1.3-SNAPSHOT.jar automatically. Perhaps you have an environment without internet access. You will need to download the file manually or restart and let it try again

2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] There were errors during initial FML setup. Some files failed to download or were otherwise corrupted. You will need to manually obtain the following files from these download links and ensure your lib directory is clean. 
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/argo-small-3.2.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/guava-14.0-rc3.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/asm-all-4.1.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/bcprov-jdk15on-148.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/deobfuscation_data_1.5.1.zip
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/scala-library.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.3/commons-lang-2.3.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/org/avaje/ebean/2.8.1/ebean-2.8.1.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download https://github.com/keepcalm/BukkitForge/blob/master/lib/gson-2.1-cb.jar?raw=true
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.9/snakeyaml-1.9.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/org/fusesource/jansi/jansi/1.9/jansi-1.9.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download https://github.com/keepcalm/BukkitForge/blob/master/lib/guava10-renamed.jar?raw=true
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download https://github.com/keepcalm/BukkitForge/blob/master/lib/SpecialSource-1.3-SNAPSHOT.jar?raw=true
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.14/mysql-connector-java-5.1.14.jar
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] <===========>
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] The following is the errors that caused the setup to fail. They may help you diagnose and resolve the issue
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] A download error occured
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] <<< ==== >>>
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] The following is diagnostic information for developers to review.
2013-04-28 14:45:04 [SEVERE] [ForgeModLoader] Error details
java.lang.RuntimeException: A download error occured
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.downloadFile(RelaunchLibraryManager.java:548)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:165)
    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:172)
    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:147)
    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:45)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1354)
Caused by: java.io.FileNotFoundException: https://github.com/keepcalm/BukkitForge/blob/master/lib/SpecialSource-1.3-SNAPSHOT.jar?raw=true
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.downloadFile(RelaunchLibraryManager.java:532)
    ... 5 more
Caused by: java.io.FileNotFoundException: https://github.com/keepcalm/BukkitForge/blob/master/lib/SpecialSource-1.3-SNAPSHOT.jar?raw=true
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
    at java.net.URLConnection.getHeaderFieldLong(Unknown Source)
    at java.net.URLConnection.getContentLengthLong(Unknown Source)
    at java.net.URLConnection.getContentLength(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.downloadFile(RelaunchLibraryManager.java:531)
    ... 5 more
2013-04-28 14:45:04 [INFO] [STDERR] Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: A fatal error occured and FML cannot continue
2013-04-28 14:45:04 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:192)
2013-04-28 14:45:04 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:147)
2013-04-28 14:45:04 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:45)
2013-04-28 14:45:04 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1354)
2013-04-28 14:45:04 [INFO] [STDERR] Caused by: java.lang.RuntimeException: A fatal error occured and FML cannot continue
2013-04-28 14:45:04 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:261)
2013-04-28 14:45:04 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:172)
2013-04-28 14:45:04 [INFO] [STDERR]     ... 3 more

Client:
2013-04-28 14:46:09 [INFO] [ForgeModLoader] Forge Mod Loader version 5.1.43.674 for Minecraft 1.5.1 loading
2013-04-28 14:46:09 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) Client VM, version 1.7.0_21, running on Windows XP:x86:5.1, installed at C:\Program Files\Java\jre7
2013-04-28 14:46:09 [FINE] [ForgeModLoader] Java classpath at launch is MultiMCLauncher.jar
2013-04-28 14:46:09 [FINE] [ForgeModLoader] Java library path at launch is C:\Program Files\Java\jre7\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\wbem;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Program Files\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\QuickTime\QTSystem;C:\Program Files\MySQL\MySQL Server 5.0\bin;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\Program Files\TortoiseSVN\bin;C:\WINDOWS\system32\WindowsPowerShell\v1.0;C:\Program Files\Common Files\Microsoft Shared\Windows Live;.
2013-04-28 14:46:09 [FINE] [ForgeModLoader] Enabling runtime deobfuscation
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] All core mods are successfully located
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Discovering coremods
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found a candidate coremod BukkitForge-1.5.1-CUSTOM_BUILD.jar
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Loading coremod BukkitForge-1.5.1-CUSTOM_BUILD.jar
2013-04-28 14:46:09 [WARNING] [ForgeModLoader] The coremod keepcalm.mods.bukkit.asm.BukkitASMLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Loaded coremod BukkitForge-1.5.1-CUSTOM_BUILD.jar
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found a candidate coremod CodeChickenCore 0.8.6.3.jar
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Loading coremod CodeChickenCore 0.8.6.3.jar
2013-04-28 14:46:09 [WARNING] [ForgeModLoader] The coremod codechicken.core.asm.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Loaded coremod CodeChickenCore 0.8.6.3.jar
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found a candidate coremod DynamicLights_1.5.1.jar
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Loading coremod DynamicLights_1.5.1.jar
2013-04-28 14:46:09 [WARNING] [ForgeModLoader] The coremod atomicstryker.dynamiclights.common.DLFMLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Loaded coremod DynamicLights_1.5.1.jar
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found a candidate coremod NotEnoughItems 1.5.2.10.jar
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Loading coremod NotEnoughItems 1.5.2.10.jar
2013-04-28 14:46:09 [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Loaded coremod NotEnoughItems 1.5.2.10.jar
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file argo-small-3.2.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file guava-14.0-rc3.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file asm-all-4.1.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file bcprov-jdk15on-148.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file deobfuscation_data_1.5.1.zip present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file scala-library.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file commons-lang-2.3.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file ebean-2.8.1.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file gson-2.1-cb.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file sqlite-jdbc-3.7.2.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file json-simple-1.1.1.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file snakeyaml-1.9.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file jansi-1.9.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Found library file guava10-renamed.jar present and correct in lib dir
2013-04-28 14:46:09 [FINEST] [ForgeModLoader] Downloading file https://github.com/keepcalm/BukkitForge/blob/master/lib/SpecialSource-1.3-SNAPSHOT.jar?raw=true
2013-04-28 14:46:09 [INFO] [ForgeModLoader] Downloading file https://github.com/keepcalm/BukkitForge/blob/master/lib/SpecialSource-1.3-SNAPSHOT.jar?raw=true
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] There was a problem downloading the file SpecialSource-1.3-SNAPSHOT.jar automatically. Perhaps you have an environment without internet access. You will need to download the file manually or restart and let it try again

2013-04-28 14:46:10 [FINEST] [ForgeModLoader] Found library file mysql-connector-java-5.1.14.jar present and correct in lib dir
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] There were errors during initial FML setup. Some files failed to download or were otherwise corrupted. You will need to manually obtain the following files from these download links and ensure your lib directory is clean. 
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/argo-small-3.2.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/guava-14.0-rc3.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/asm-all-4.1.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/bcprov-jdk15on-148.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/deobfuscation_data_1.5.1.zip
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://files.minecraftforge.net/fmllibs/scala-library.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.3/commons-lang-2.3.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/org/avaje/ebean/2.8.1/ebean-2.8.1.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download https://github.com/keepcalm/BukkitForge/blob/master/lib/gson-2.1-cb.jar?raw=true
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.9/snakeyaml-1.9.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/org/fusesource/jansi/jansi/1.9/jansi-1.9.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download https://github.com/keepcalm/BukkitForge/blob/master/lib/guava10-renamed.jar?raw=true
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download https://github.com/keepcalm/BukkitForge/blob/master/lib/SpecialSource-1.3-SNAPSHOT.jar?raw=true
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] **\* Download http://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.14/mysql-connector-java-5.1.14.jar
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] <===========>
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] The following is the errors that caused the setup to fail. They may help you diagnose and resolve the issue
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] A download error occured
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] <<< ==== >>>
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] The following is diagnostic information for developers to review.
2013-04-28 14:46:10 [SEVERE] [ForgeModLoader] Error details
java.lang.RuntimeException: A download error occured
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.downloadFile(RelaunchLibraryManager.java:548)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:165)
    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:172)
    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchApplet(FMLRelauncher.java:259)
    at cpw.mods.fml.relauncher.FMLRelauncher.appletEntry(FMLRelauncher.java:229)
    at net.minecraft.client.MinecraftApplet.init(MinecraftApplet.java:25)
    at net.minecraft.Launcher.init(Launcher.java:108)
    at MCFrame.start(MCFrame.java:72)
    at MultiMCLauncher.main(MultiMCLauncher.java:275)
Caused by: java.io.FileNotFoundException: https://github.com/keepcalm/BukkitForge/blob/master/lib/SpecialSource-1.3-SNAPSHOT.jar?raw=true
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.downloadFile(RelaunchLibraryManager.java:532)
    ... 8 more
Caused by: java.io.FileNotFoundException: https://github.com/keepcalm/BukkitForge/blob/master/lib/SpecialSource-1.3-SNAPSHOT.jar?raw=true
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
    at java.net.URLConnection.getHeaderFieldLong(Unknown Source)
    at java.net.URLConnection.getContentLengthLong(Unknown Source)
    at java.net.URLConnection.getContentLength(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.downloadFile(RelaunchLibraryManager.java:531)
    ... 8 more
2013-04-28 14:46:13 [INFO] [STDERR] Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: A fatal error occured and FML cannot continue
2013-04-28 14:46:13 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:192)
2013-04-28 14:46:13 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.relaunchApplet(FMLRelauncher.java:259)
2013-04-28 14:46:13 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.appletEntry(FMLRelauncher.java:229)
2013-04-28 14:46:13 [INFO] [STDERR]     at net.minecraft.client.MinecraftApplet.init(MinecraftApplet.java:25)
2013-04-28 14:46:13 [INFO] [STDERR]     at net.minecraft.Launcher.init(Launcher.java:108)
2013-04-28 14:46:13 [INFO] [STDERR]     at MCFrame.start(MCFrame.java:72)
2013-04-28 14:46:13 [INFO] [STDERR]     at MultiMCLauncher.main(MultiMCLauncher.java:275)
2013-04-28 14:46:13 [INFO] [STDERR] Caused by: java.lang.RuntimeException: A fatal error occured and FML cannot continue
2013-04-28 14:46:13 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:261)
2013-04-28 14:46:13 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:172)
2013-04-28 14:46:13 [INFO] [STDERR]     ... 6 more

Im added bukkitforge 1.5.1 to Coremods.. :/ Please help :'(

**Comment by FlyBlb** [comment]
Fixed! To client dont use! And is to server CodeChickenCore remove. And worked!

**Comment by alexbegt** [comment]
Server side mod.
