### ISSUE TITLE
 A critical server error occured handling a packet, kicking <player>

### ISSUE THREAD

**Issue by iarspider** [keepcalm/BukkitForge#626]
When I try to place a block (any) on a specific spot on my server, I get kicked with "Internal server error":

```
2013-04-29 22:22:13 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 360584282
java.lang.NullPointerException
        at org.bukkit.craftbukkit.block.CraftSign.<init>(CraftSign.java:19)
        at org.bukkit.craftbukkit.block.CraftBlock.getState(CraftBlock.java:236)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteraction(ForgeEventHandler.java:311)
        at net.minecraftforge.event.ASMEventHandler_116_ForgeEventHandler_onPlayerInteraction_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:579)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
2013-04-29 22:22:13 [WARNING] [Minecraft] Failed to handle packet for iarspider/91.207.115.15: java.lang.NullPointerException
java.lang.NullPointerException
        at org.bukkit.craftbukkit.block.CraftSign.<init>(CraftSign.java:19)
        at org.bukkit.craftbukkit.block.CraftBlock.getState(CraftBlock.java:236)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteraction(ForgeEventHandler.java:311)
        at net.minecraftforge.event.ASMEventHandler_116_ForgeEventHandler_onPlayerInteraction_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:579)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849) 
```

**Comment by iarspider** [comment]
There is (of course) no sign at this spot. Some more observations: 
1) I can place a Glass Pane (vanilla) on this spot and not get kicked
2) I can place a RP2 Cover on this spot, but only from one side
