### ISSUE TITLE
Tfc Map generating

### ISSUE THREAD

**Issue by mkiplm** [keepcalm/BukkitForge#627]
well using 1.5.1 and cant generate map with tfc mod, fix this please i posted in the past about it.

2013-04-30 20:07:20 [INFO] [STDOUT] Transforming it using keepcalm.mods.bukkit.a
sm.replacements.EntityTracker_BukkitForge !test!
2013-04-30 20:07:20 [INFO] [ForgeModLoader] Loading dimension 0 (world) (net.min
ecraft.server.dedicated.DedicatedServer@261cc709)
2013-04-30 20:07:20 [INFO] [ForgeModLoader] Loading dimension 1 (world) (net.min
ecraft.server.dedicated.DedicatedServer@261cc709)
2013-04-30 20:07:20 [INFO] [ForgeModLoader] Loading dimension -1 (world) (net.mi
necraft.server.dedicated.DedicatedServer@261cc709)
2013-04-30 20:07:20 [INFO] [Minecraft-Server] Preparing start region for level 0

2013-04-30 20:07:21 [INFO] [STDERR] java.lang.NullPointerException
2013-04-30 20:07:21 [INFO] [STDERR]     at TFC.Core.TFC_Climate.getRainfall(TFC_
Climate.java:359)
2013-04-30 20:07:21 [INFO] [STDERR]     at TFC.WorldGen.Generators.WorldGenJungl
e.generate(WorldGenJungle.java:85)
2013-04-30 20:07:21 [INFO] [STDERR]     at TFC.WorldGen.BiomeDecoratorTFC.func_7
6794_a(BiomeDecoratorTFC.java:109)
2013-04-30 20:07:21 [INFO] [STDERR]     at TFC.WorldGen.BiomeDecoratorTFC.func_7
6796_a(BiomeDecoratorTFC.java:241)
2013-04-30 20:07:21 [INFO] [STDERR]     at TFC.WorldGen.TFCBiome.func_76728_a(TF
CBiome.java:216)
2013-04-30 20:07:21 [INFO] [STDERR]     at TFC.WorldGen.TFCChunkProviderGenerate
.func_73153_a(TFCChunkProviderGenerate.java:178)
2013-04-30 20:07:21 [INFO] [STDERR]     at net.minecraft.world.gen.ChunkProvider
Server.func_73153_a(ChunkProviderServer.java:258)
2013-04-30 20:07:21 [INFO] [STDERR]     at net.minecraft.world.chunk.Chunk.func_
76624_a(Chunk.java:1249)
2013-04-30 20:07:21 [INFO] [STDERR]     at net.minecraft.world.gen.ChunkProvider
Server.func_73158_c(ChunkProviderServer.java:153)
2013-04-30 20:07:21 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
func_71222_d(MinecraftServer.java:281)
2013-04-30 20:07:21 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
func_71247_a(MinecraftServer.java:255)
2013-04-30 20:07:21 [INFO] [STDERR]     at net.minecraft.server.dedicated.Dedica
tedServer.func_71197_b(DedicatedServer.java:185)
2013-04-30 20:07:21 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
run(MinecraftServer.java:429)
2013-04-30 20:07:21 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftS
erver.run(SourceFile:573)
2013-04-30 20:07:21 [SEVERE] [Minecraft-Server] Encountered an unexpected except
ion NullPointerException
java.lang.NullPointerException
        at TFC.Core.TFC_Climate.getRainfall(TFC_Climate.java:359)
        at TFC.WorldGen.Generators.WorldGenJungle.generate(WorldGenJungle.java:8
5)
        at TFC.WorldGen.BiomeDecoratorTFC.func_76794_a(BiomeDecoratorTFC.java:10
9)
        at TFC.WorldGen.BiomeDecoratorTFC.func_76796_a(BiomeDecoratorTFC.java:24
1)
        at TFC.WorldGen.TFCBiome.func_76728_a(TFCBiome.java:216)
        at TFC.WorldGen.TFCChunkProviderGenerate.func_73153_a(TFCChunkProviderGe
nerate.java:178)
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProvide
rServer.java:258)
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1249)
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProvide
rServer.java:153)
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.jav
a:281)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.jav
a:255)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(Dedicated
Server.java:185)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
2013-04-30 20:07:21 [SEVERE] [Minecraft-Server] This crash report has been saved
 to: C:\Users\Joe\Desktop\test - Copy.\crash-reports\crash-2013-04-30_20.07.21-
server.txt

**Comment by mkiplm** [comment]
bump bump?
