### ISSUE TITLE
CraftAPI Something real bad happend!

### ISSUE THREAD

**Issue by bakabakabakabaka** [keepcalm/BukkitForge#628]
[SEVERE] [ForgeModLoader] Something real bad happened! The CraftAPI will not be running for this Minecraft session.
You should _probably_ report this bug to the developer(s) at https://github.com/keepcalm/BukkitForge/issues
java.lang.NullPointerException
        at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.initDimension(DimensionManagerImpl.java:195)
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:68)
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:729)
        at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.cacheWorld(BukkitForgeWorldCache.java:78)
        at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.tryGetWorld(BukkitForgeWorldCache.java:95)
        at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.get(BukkitForgeWorldCache.java:43)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.<init>(CraftServer.java:193)
        at keepcalm.mods.bukkit.asm.BukkitStarter.r

http://pastebin.com/PDEXpPfB

**Comment by alexbegt** [comment]
Forge?

**Comment by mksvco** [comment]
Getting this too. @keepcalm pls halp

http://pastebin.com/UeYhKDvJ

**Comment by mksvco** [comment]
It looks like it was galacticraft. Disabling it worked

**Comment by Takedown031** [comment]
IS there any way to make it work WITHOUT disabling?

EDIT: Dimensional Doors was the one screwing it for me, its disabled now but I really would like to re-enable it

**Comment by alexbegt** [comment]
I need to recreate this.

**Comment by DennisWindhouwer** [comment]
I also ran into this issue using bukkitforge on the newest Tekkit. Yesterday my server worked fine, I explored some of the dimensions from Dimensional Doors for the first time on that server during that day (the server was new, all I had was a wooden house when I started to explore the dimensional doors stuff). Today it no longer works, right before it throws the exception it does this: 

2013-05-09 11:17:14 [INFO] [ForgeModLoader] Unloading dimension -23
2013-05-09 11:17:14 [INFO] [ForgeModLoader] Loading dimension -23 (world) (net.minecraft.server.dedicated.DedicatedServer@1f5ff045)
2013-05-09 11:17:14 [SEVERE] [ForgeModLoader] Something real bad happened! The CraftAPI will not be running for this Minecraft session.

Disabling Dimensional Doors fixed it for me.
