### ISSUE TITLE
Bug with TekkitLite 0.6.5

### ISSUE THREAD

**Issue by danteint** [keepcalm/BukkitForge#630]
Running on debian squeeze, tried to intsall Vault and mChat

You should _probably_ report this bug to the developer(s) at https://github.com/keepcalm/BukkitForge/issues
java.lang.NullPointerException
        at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.initDimension(DimensionManagerImpl.java:190)
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:68)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:758)
        at keepcalm.mods.bukkit.CraftWorldCache.cacheWorld(CraftWorldCache.java:80)
        at keepcalm.mods.bukkit.CraftWorldCache.tryGetWorld(CraftWorldCache.java:97)
        at keepcalm.mods.bukkit.CraftWorldCache.get(CraftWorldCache.java:45)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:187)
        at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)

**Comment by Fundaris** [comment]
Forge and Bukkitforge build please
