### ISSUE TITLE
When starting up my server

### ISSUE THREAD

**Issue by jwc17** [keepcalm/BukkitForge#636]
I get the following error only when I have BukkitForge-1.5.1-291 in the coremods folder on my Voltz server. I am not sure why it won't work and I would appreciate some help. Thanks!
## 

2013-05-16 12:46:58 [INFO] [ForgeModLoader] Forge Mod Loader version 4.7.35.556 for Minecraft 1.4.7 loading
2013-05-16 12:46:58 [INFO] [STDOUT] Bukkitforge call to getASMTransformer ...
2013-05-16 12:46:58 [INFO] [STDOUT] Bukkitforge call to getASMTransformer ...
2013-05-16 12:46:58 [INFO] [STDOUT] Adding Accesstransformer map: bukkit_at.cfg
2013-05-16 12:46:58 [SEVERE] [ForgeModLoader] A critical problem occured registering the ASM transformer class keepcalm.mods.events.asm.transformers.events.BlockEventHelpers
java.lang.ClassNotFoundException: keepcalm.mods.events.asm.transformers.events.BlockEventHelpers
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:77)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:238)
    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
Caused by: java.lang.AbstractMethodError
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
    ... 8 more
2013-05-16 12:46:58 [SEVERE] [ForgeModLoader] A critical problem occured registering the ASM transformer class keepcalm.mods.events.asm.transformers.events.EntityEventHelpers
java.lang.ClassNotFoundException: keepcalm.mods.events.asm.transformers.events.EntityEventHelpers
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:77)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:238)
    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
Caused by: java.lang.AbstractMethodError
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
    ... 8 more
2013-05-16 12:46:58 [SEVERE] [ForgeModLoader] A critical problem occured registering the ASM transformer class keepcalm.mods.bukkit.asm.transformers.BukkitAsmagicTransformer
java.lang.ClassNotFoundException: keepcalm.mods.bukkit.asm.transformers.BukkitAsmagicTransformer
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:77)
    at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:238)
    at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
    at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
    at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
Caused by: java.lang.AbstractMethodError
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
    ... 8 more
2013-05-16 12:46:58 [INFO] [STDERR] Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: cpw/mods/fml/common/asm/ASMTransformer
2013-05-16 12:46:58 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:175)
2013-05-16 12:46:58 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:133)
2013-05-16 12:46:58 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:33)
2013-05-16 12:46:58 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1376)
2013-05-16 12:46:58 [INFO] [STDERR] Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/common/asm/ASMTransformer
2013-05-16 12:46:58 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass1(Native Method)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.security.SecureClassLoader.defineClass(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.net.URLClassLoader.defineClass(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.net.URLClassLoader.access$100(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.net.URLClassLoader$1.run(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.net.URLClassLoader$1.run(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.security.AccessController.doPrivileged(Native Method)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.net.URLClassLoader.findClass(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:110)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:77)
2013-05-16 12:46:58 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:238)
2013-05-16 12:46:58 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:155)
2013-05-16 12:46:58 [INFO] [STDERR]     ... 3 more
2013-05-16 12:46:58 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.asm.ASMTransformer
2013-05-16 12:46:58 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-05-16 12:46:58 [INFO] [STDERR]     ... 18 more
2013-05-16 12:46:58 [INFO] [STDERR] Caused by: java.lang.AbstractMethodError
2013-05-16 12:46:58 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:228)
2013-05-16 12:46:58 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:173)
2013-05-16 12:46:58 [INFO] [STDERR]     ... 20 more

**Comment by Fundaris** [comment]
Hi please use the last 1.4.7 build and not 1.5.1 
http://build.technicpack.net/job/BukkitForge/257/artifact/build/dist/BukkitForge-1.4.7-257.jar
