### ISSUE TITLE
BukkitForge won't load

### ISSUE THREAD

**Issue by Aycardus** [keepcalm/BukkitForge#637]
Hello, we recently installed the new Tekkit with the spaceships and what not. Everything working fine, we had plugins installed and all working properly. Yesterday, Wendnesday 5/15/2013, I shut the server down for a few minutes to add some plugins. Started it back up, said it was online, I left it for a few minutes because I knew it was going to tell me that BukkitForge was loading. I came back to my computer and attempted to log on, said it was still loading. So I waited some more, still loading, waited some more, still loading. I got to a point where I figured I'd leave it for the night. Still loading. I went into the ForgeModLoader crash.txt. and it said I should report this, so here I am, and I'd like to know how to make BukkitForge work again. :l 

2013-05-16 19:34:21 [SEVERE] [ForgeModLoader] Something real bad happened! The CraftAPI will not be running for this Minecraft session.
You should _probably_ report this bug to the developer(s) at https://github.com/keepcalm/BukkitForge/issues
java.lang.NullPointerException
    at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.initDimension(DimensionManagerImpl.java:195)
    at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:68)
    at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:729)
    at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.cacheWorld(BukkitForgeWorldCache.java:78)
    at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.tryGetWorld(BukkitForgeWorldCache.java:95)
    at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.get(BukkitForgeWorldCache.java:43)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.<init>(CraftServer.java:198)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
    at java.lang.Thread.run(Unknown Source)

**Comment by Fundaris** [comment]
Hi,
Could u please post Forge version and bukkitforge build?

**Comment by fire3797** [comment]
The same thing happened to me

**Comment by alexbegt** [comment]
Fundaris commented 2 days ago 
Hi,
Could u please post Forge version and bukkitforge build?

**Comment by Ionaru** [comment]
Forge version 7.8.0.700
BukkitForge version 1.5.1-292 (latest as of this date)

This error occurs even without any mods installed.

Server log:
http://pastebin.com/LQNzTq9A

Crash log:
https://dl.dropboxusercontent.com/u/43514962/crash-2013-05-24_13.14.42-server.txt

**Comment by Fundaris** [comment]
@Ionaru could u try build 283
http://build.technicpack.net/job/BukkitForge/283/artifact/build/dist/BukkitForge-1.5.1-283.jar
and post feedback ty :)

**Comment by Ionaru** [comment]
It doesn't work, I get the same error.

**Comment by Fundaris** [comment]
wait why u try a 1.5.1 build with 1.5.2 server?! It's not compatible please see the over issue #639 
And those errors are not even close ...

**Comment by alexbegt** [comment]
http://bukkitforge.com/BukkitForge-1.5.2-1.jar

**Comment by theflyingemu** [comment]
I know this issue is a month old but I encountered the same issue/error on my Hexxit 1.0.0 server using BukkitForge 1.5.2-1 and was only able to resolve the issue by disabling the DimensionalDoors-1.5.2R1.4.0RC1-149 mod.
