### ISSUE TITLE
Bukkitforge issue tekkit 1.0.6

### ISSUE THREAD

**Issue by mop8899** [keepcalm/BukkitForge#638]
You should _probably_ report this bug to the developer(s) at https://github.com/keepcalm/BukkitForge/issues
java.lang.NullPointerException
at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.initDimension(DimensionManagerImpl.java:195)
at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:68)
at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:729)
at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.cacheWorld(BukkitForgeWorldCache.java:78)
at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.tryGetWorld(BukkitForgeWorldCache.java:95)
at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.get(BukkitForgeWorldCache.java:43)
at org.bukkit.craftbukkit.v1_5_R2.CraftServer.<init>(CraftServer.java:198)
at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
at java.lang.Thread.run(Unknown Source)
2013-05-19 21:32:23 [INFO] [ForgeModLoader] Unloading dimension -23
2013-05-19 21:32:46 [INFO] [Minecraft-Server] Disconnecting mop8899 [/74.45.70.252:65520]: Patience, my padawan! BukkitForge is still loading.

**Comment by Fundaris** [comment]
looks similar to #637 could u pls post Forge and Bukkitforgeversion there? And maybe plugins when u installed them?

**Comment by mop8899** [comment]
v1_5_R2.?

**Comment by mop8899** [comment]
If that's not it I don't know how to tell.
.
