### ISSUE TITLE
Server NoSuchMethodError crash MC 1.5.2

### ISSUE THREAD

**Issue by calclavia** [keepcalm/BukkitForge#639]
---- Minecraft Crash Report ----
// Don't do that.

Time: 5/25/13 2:48 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.WorldServer.L()Lnet/minecraft/world/storage/WorldInfo;
    at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.setWorld(DimensionManagerImpl.java:141)
    at net.minecraftforge.common.DimensionManager.setWorld(DimensionManager.java:63)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:142)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:238)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:430)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Linux (amd64) version 2.6.32-5-vserver-amd64
    Java Version: 1.7.0_03, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 414228360 bytes (395 MB) / 663748608 bytes (633 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -Xms512M -Xmx1024M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.51 FML v5.2.10.703 Minecraft Forge 7.8.0.703 54 mods loaded, 54 mods active
    mcp{7.44} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML{5.2.10.703} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge{7.8.0.703} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHCore{1.5.2.2} [CoFH Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CodeChickenCore{0.8.6.6} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NotEnoughItems{1.5.2.13} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    PowerCrystalsCore{1.1.6} [PowerCrystals Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BukkitForge{Unknown} [BukkitForge](BukkitForge-1.5.1-292.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BlockBreak{1.4.6-0} [Block Break Event](BukkitForge-1.5.1-292.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHNetwork{1.5.2.2} [CoFHNetwork](CoFHCore-1.5.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHWorld{1.5.2.2} [CoFHWorld](CoFHCore-1.5.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    GalacticraftCore{0.1.35} [Galacticraft Core](Galacticraft-1.5.2-a0.1.35.262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AssemblyLine{0.3.5.137} [Assembly Line](AssemblyLine_v0.3.5.137.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AtomicScience{0.5.2} [Atomic Science](Atomic_Science_v0.5.2.47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Biotech{0.2.1} [Biotech](Biotech-v0.2.1.31.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ComplexMachines{0.3.3} [Complex Machines](ComplexMachines_v0.3.3.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ICBM|Contraption{1.2.0} [ICBM](ICBM_Contraption_v1.2.0.108.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Core{3.5.3} [BuildCraft](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Builders{3.5.3} [BC Builders](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Energy{3.5.3} [BC Energy](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Factory{3.5.3} [BC Factory](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Transport{3.5.3} [BC Transport](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded{1.5.1R2.5.4} [MineFactory Reloaded](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ElectricExpansion{2.2.1.49} [Electric Expansion](ElectricExpansion_v2.2.1.49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ExtrabiomesXL{3.13.1} [ExtrabiomesXL](ExtrabiomesXL-universal-1.5.2-3.13.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ICBM|Sentry{1.2.0} [ICBM](ICBM_Sentry_v1.2.0.108.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ICBM|Explosion{1.2.0} [ICBM](ICBM_Explosion_v1.2.0.108.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFFS{3.0.1} [Modular Force Field System](MFFS_v3.0.1.121.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Mekanism{5.5.6} [Mekanism](Mekanism-v5.5.6.63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MekanismGenerators{5.5.6} [MekanismGenerators](MekanismGenerators-v5.5.6.63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MekanismTools{5.5.6} [MekanismTools](MekanismTools-v5.5.6.63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    minechem{@VERSION@} [MineChem](MineChem_v3.0.0.123.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatAtum{1.5.1R2.5.4} [MFR Compat: Atum](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatBiomesOPlenty{1.5.1R2.5.4} [MFR Compat: Biomes O' Plenty](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatChococraft{1.5.1R2.5.4} [MFR Compat: Chococraft](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.5.1R2.5.4} [MFR Compat: ExtraBiomes](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatForestry{1.5.1R2.5.4} [MFR Compat: Forestry](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatForestryPre{1.5.1R2.5.4} [MFR Compat: Forestry (2)](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatIC2{1.5.1R2.5.4} [MFR Compat: IC2](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatMagicalCrops{1.5.1R2.5.4} [MFR Compat: Magical Crops](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatNatura{1.5.1R2.5.4} [MFR Compat: Natura](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatPams{1.5.1R2.5.4} [MFR Compat: Pam's Mods](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatRP2{1.5.1R2.5.4} [MFR Compat: RP2](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatSoulShards{1.5.1R2.5.4} [MFR Compat: SoulShards](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.5.1R2.5.4} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatThaumcraft{1.5.1R2.5.4} [MFR Compat: Thaumcraft](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatTConstruct{1.5.1R2.5.4} [MFR Compat: TConstruct](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.5.1R2.5.4} [MFR Compat: TwilightForest](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatVanilla{1.5.1R2.5.4} [MFR Compat: Vanilla](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MineFactoryReloaded|CompatXyCraft{1.5.1R2.5.4} [MFR Compat: XyCraft](MineFactoryReloaded-2.5.4-665.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    mmmPowersuits{0.6.0-444} [MachineMuse's Modular Powersuits](ModularPowersuits-0.6.0-444.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion{2.4.3.0} [Thermal Expansion](ThermalExpansion-2.4.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Silicon{3.5.3} [BC Silicon](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AppliedEnergistics{rv.10.n} [Applied Energistics](appeng-rv10-n.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BukkitForge Details: BukkitForge null-null (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:[Didn't get far enough to load plugins :/]
    Profiler Position: N/A (disabled)
    Player Count: 0 / 10; []
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by alexbegt** [comment]
Why thank you, I'll work on this :)

**Comment by Ionaru** [comment]
Looks a lot like #637 

keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.setWorld

Forge version 7.8.0.700
BukkitForge version 1.5.1-292 (latest as of this date)

Server log:
http://pastebin.com/LQNzTq9A

Crash log:
https://dl.dropboxusercontent.com/u/43514962/crash-2013-05-24_13.14.42-server.txt

**Comment by Fundaris** [comment]
@Ionaru not even close
It's 1.5.2 when u need a working 1.5.1 build try 283
and when u need to refernce then use the first one! its #628 

@calclavia is this selfbuild? when yes try this one:
http://bukkitforge.com/BukkitForge-1.5.2-1.jar It's more uptodate then git :)

**Comment by calclavia** [comment]
This link should seriously be public. I think a lot of servers owner might want it.

**Comment by alexbegt** [comment]
Calclavia, I'm about to push it to public, after i fine tooth it.

**Comment by calclavia** [comment]
Is it public now?

**Comment by alexbegt** [comment]
Its public, after i fix jenkins
