### ISSUE TITLE
Tekkit Lite 0.65, BukkitForge Build 145

### ISSUE THREAD

**Issue by zbaylin** [keepcalm/BukkitForge#642]
I keep getting this error. Please help!

java.lang.NullPointerException
    at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.initDimension(DimensionManagerImpl.java:190)
    at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:68)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:758)
    at keepcalm.mods.bukkit.CraftWorldCache.cacheWorld(CraftWorldCache.java:80)
    at keepcalm.mods.bukkit.CraftWorldCache.tryGetWorld(CraftWorldCache.java:97)
    at keepcalm.mods.bukkit.CraftWorldCache.get(CraftWorldCache.java:45)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:187)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Thread.java:722)

**Comment by Ionaru** [comment]
#637 

Same issue

**Comment by Fundaris** [comment]
@Ionaru  also not the same issue ~.~ 
@zbaylin try this build pls http://jenkins.bukkitforge.com:8080/job/BukkitForge-1.4.7/4/artifact/build/dist/BukkitForge-1.4.7-4.jar
