### ISSUE TITLE
Something real bad happened! The CraftAPI will not be running for this Minecraft session. You should *probably* report this bug to the developer(s)

### ISSUE THREAD

**Issue by mds818** [keepcalm/BukkitForge#643]
Running Tekkit and got this error.

BukkitForge 1.5.1-292
Tekkit v1.0.6
When login we get message: Patience, my padawan! BukkitForge is still loading.

Error:

2013-05-26 17:16:15 [SEVERE] [ForgeModLoader] Something real bad happened!
The CraftAPI will not be running for this Minecraft session.
You should _probably_ report this bug to the developer(s) at https://github.com/
keepcalm/BukkitForge/issues
java.lang.NullPointerException
        at keepcalm.mods.bukkit.nmsforge.DimensionManagerImpl.initDimension(Dime
nsionManagerImpl.java:195)
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionMan
ager.java:68)
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.jav
a:729)
        at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.cacheWorld(BukkitForg
eWorldCache.java:78)
        at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.tryGetWorld(BukkitFor
geWorldCache.java:95)
        at keepcalm.mods.bukkitforge.BukkitForgeWorldCache.get(BukkitForgeWorldC
ache.java:43)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.<init>(CraftServer.java:19
8)
        at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
        at java.lang.Thread.run(Unknown Source)

**Comment by Ionaru** [comment]
Same issue again 
#637
