### ISSUE TITLE
NEI Crash

### ISSUE THREAD

**Issue by calclavia** [keepcalm/BukkitForge#659]
BukkitForge crashes with NEI Using MC 1.5.2, latest BukkitForge build

2013-07-05 22:04:30 [INFO] [ForgeModLoader] Forge Mod Loader version 5.2.23.738 for Minecraft 1.5.2 loading
2013-07-05 22:04:30 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_10, running on Linux:amd64:2.6.32-042stab075.2, installed at /usr/java/jdk1.7.0_10/jre
2013-07-05 22:04:30 [FINE] [ForgeModLoader] Java classpath at launch is minecraft_server.jar
2013-07-05 22:04:30 [FINE] [ForgeModLoader] Java library path at launch is /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2013-07-05 22:04:30 [FINE] [ForgeModLoader] Enabling runtime deobfuscation
2013-07-05 22:04:30 [WARNING] [ForgeModLoader] The coremod cofh.asm.CoFHPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-07-05 22:04:30 [WARNING] [ForgeModLoader] The coremod codechicken.core.asm.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-07-05 22:04:30 [WARNING] [ForgeModLoader] The coremod micdoodle8.mods.galacticraft.asm.GalacticraftPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-07-05 22:04:30 [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-07-05 22:04:30 [FINE] [ForgeModLoader] The coremod powercrystals.core.CoreLoader requested minecraft version 1.5.2 and minecraft is 1.5.2. It will be loaded.
2013-07-05 22:04:30 [WARNING] [ForgeModLoader] The coremod keepcalm.mods.bukkit.asm.BukkitASMLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-07-05 22:04:30 [WARNING] [ForgeModLoader] The coremod mods.immibis.microblocks.coremod.MicroblocksCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2013-07-05 22:04:31 [INFO] [Galacticraft] 1.5.2
2013-07-05 22:04:31 [INFO] [Galacticraft] Successfully Registered Transformer
2013-07-05 22:04:31 [INFO] [Galacticraft] 1.5.2
2013-07-05 22:04:31 [INFO] [STDOUT] Adding Accesstransformer map: pcc_at.cfg
2013-07-05 22:04:31 [INFO] [STDOUT] Bukkitforge call to getASMTransformer ...
2013-07-05 22:04:31 [INFO] [STDOUT] Bukkitforge call to getASMTransformer ...
2013-07-05 22:04:31 [INFO] [STDOUT] Adding Accesstransformer map: bukkit_at.cfg
2013-07-05 22:04:32 [INFO] [STDOUT] Found global block break call: a(Laab;IIIII)V
2013-07-05 22:04:32 [INFO] [STDOUT] Inserted instructions!
2013-07-05 22:04:32 [INFO] [STDOUT] Galacticraft successfully injected bytecode into: ng
2013-07-05 22:04:33 [INFO] [STDOUT] Galacticraft successfully injected bytecode into: sq
2013-07-05 22:04:33 [INFO] [STDERR] Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: aqg
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:192)
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.relaunchServer(FMLRelauncher.java:147)
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.handleServerRelaunch(FMLRelauncher.java:45)
2013-07-05 22:04:33 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1367)
2013-07-05 22:04:33 [INFO] [STDERR] Caused by: java.lang.NoClassDefFoundError: aqg
2013-07-05 22:04:33 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.transformers.BukkitAsmagicTransformer.addClasses(BukkitAsmagicTransformer.java:69)
2013-07-05 22:04:33 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.transformers.BukkitAsmagicTransformer.createClassesToTransform(BukkitAsmagicTransformer.java:42)
2013-07-05 22:04:33 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.transformers.BukkitAsmagicTransformer.<init>(BukkitAsmagicTransformer.java:92)
2013-07-05 22:04:33 [INFO] [STDERR]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2013-07-05 22:04:33 [INFO] [STDERR]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2013-07-05 22:04:33 [INFO] [STDERR]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2013-07-05 22:04:33 [INFO] [STDERR]     at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
2013-07-05 22:04:33 [INFO] [STDERR]     at java.lang.Class.newInstance0(Class.java:372)
2013-07-05 22:04:33 [INFO] [STDERR]     at java.lang.Class.newInstance(Class.java:325)
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.registerTransformer(RelaunchClassLoader.java:122)
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchLibraryManager.handleLaunch(RelaunchLibraryManager.java:271)
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.FMLRelauncher.setupHome(FMLRelauncher.java:172)
2013-07-05 22:04:33 [INFO] [STDERR]     ... 3 more
2013-07-05 22:04:33 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: aqg
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:238)
2013-07-05 22:04:33 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2013-07-05 22:04:33 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2013-07-05 22:04:33 [INFO] [STDERR]     ... 15 more
2013-07-05 22:04:33 [INFO] [STDERR] Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/common/ISidedInventory
2013-07-05 22:04:33 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass1(Native Method)
2013-07-05 22:04:33 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
2013-07-05 22:04:33 [INFO] [STDERR]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:227)
2013-07-05 22:04:33 [INFO] [STDERR]     ... 17 more
2013-07-05 22:04:33 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.ISidedInventory
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:238)
2013-07-05 22:04:33 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2013-07-05 22:04:33 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2013-07-05 22:04:33 [INFO] [STDERR]     ... 21 more
2013-07-05 22:04:33 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-07-05 22:04:33 [INFO] [STDERR]     at codechicken.core.asm.FeatureHackTransformer.usp(FeatureHackTransformer.java:72)
2013-07-05 22:04:33 [INFO] [STDERR]     at codechicken.core.asm.FeatureHackTransformer.transform(FeatureHackTransformer.java:63)
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:352)
2013-07-05 22:04:33 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:225)
2013-07-05 22:04:33 [INFO] [STDERR]     ... 23 more

**Comment by alexbegt** [comment]
Alright, So You ran this on the server and got this?

**Comment by calclavia** [comment]
Yup, crashed upon start up. I have NEI and a bunch of my mods on it. Removed BukkitForge and everything worked.

**Comment by alexbegt** [comment]
Any kind of modpack?

**Comment by calclavia** [comment]
The Voltz modpack + a couple of mods such as Thermal Expansion. You want a complete list?

**Comment by alexbegt** [comment]
Sure.
