### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by shakey2** [keepcalm/BukkitForge#66]
When I connect to the server I get the sky but no chunks load and I just keep falling until I get a timeout.
This is the server error I get:

2012-12-30 23:12:02 [INFO] [Minecraft] shakey2[/127.0.0.1:4108] logged in with entity id 332 at (2599.003850904665, 70.0, 2352.793792655894)
2012-12-30 23:12:05 [INFO] [STDERR] java.lang.NoClassDefFoundError: org/apache/commons/lang/NotImplementedException
2012-12-30 23:12:05 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.playerLoggedIn(ConnectionHandler.java:120)
2012-12-30 23:12:05 [INFO] [STDERR]     at cpw.mods.fml.common.network.NetworkRegistry.playerLoggedIn(NetworkRegistry.java:161)
2012-12-30 23:12:05 [INFO] [STDERR]     at cpw.mods.fml.common.network.FMLNetworkHandler.handlePlayerLogin(FMLNetworkHandler.java:281)
2012-12-30 23:12:05 [INFO] [STDERR]     at gm.a(ServerConfigurationManager.java:143)
2012-12-30 23:12:05 [INFO] [STDERR]     at it.completeConnection(NetLoginHandler.java:195)
2012-12-30 23:12:05 [INFO] [STDERR]     at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:153)
2012-12-30 23:12:05 [INFO] [STDERR]     at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
2012-12-30 23:12:05 [INFO] [STDERR]     at it.d(NetLoginHandler.java:179)
2012-12-30 23:12:05 [INFO] [STDERR]     at it.c(NetLoginHandler.java:72)
2012-12-30 23:12:05 [INFO] [STDERR]     at hu.a(ServerListenThread.java:56)
2012-12-30 23:12:05 [INFO] [STDERR]     at ht.b(SourceFile:29)
2012-12-30 23:12:05 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
2012-12-30 23:12:05 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2012-12-30 23:12:05 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
2012-12-30 23:12:05 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2012-12-30 23:12:05 [INFO] [STDERR]     at fy.run(SourceFile:849)
2012-12-30 23:12:05 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.NotImplementedException
2012-12-30 23:12:05 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:179)
2012-12-30 23:12:05 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2012-12-30 23:12:05 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2012-12-30 23:12:05 [INFO] [STDERR]     ... 16 more
2012-12-30 23:12:05 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2012-12-30 23:12:05 [INFO] [STDERR]     at org.objectweb.asm.ClassReader.<init>(Unknown Source)
2012-12-30 23:12:05 [INFO] [STDERR]     at net.minecraftforge.transformers.EventTransformer.transform(EventTransformer.java:29)
2012-12-30 23:12:05 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:222)
2012-12-30 23:12:05 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:171)
2012-12-30 23:12:05 [INFO] [STDERR]     ... 18 more
2012-12-30 23:12:05 [SEVERE] [Minecraft] Encountered an unexpected exception NoClassDefFoundError
java.lang.NoClassDefFoundError: org/apache/commons/lang/NotImplementedException
    at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.playerLoggedIn(ConnectionHandler.java:120)
    at cpw.mods.fml.common.network.NetworkRegistry.playerLoggedIn(NetworkRegistry.java:161)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePlayerLogin(FMLNetworkHandler.java:281)
    at gm.a(ServerConfigurationManager.java:143)
    at it.completeConnection(NetLoginHandler.java:195)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:153)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
    at it.d(NetLoginHandler.java:179)
    at it.c(NetLoginHandler.java:72)
    at hu.a(ServerListenThread.java:56)
    at ht.b(SourceFile:29)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.NotImplementedException
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:179)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 16 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at net.minecraftforge.transformers.EventTransformer.transform(EventTransformer.java:29)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:222)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:171)
    ... 18 more

If I try to log in again I just get timed out again.

**Comment by keepcalm** [comment]
Try updating forge, something on its side is failing...

**Comment by shakey2** [comment]
I updated to the last forge build for 1.4.6(6.5.0.489), its still crashing with the same error. I also updated to the latest build of bukkitforge on jenkins(26).

**Comment by keepcalm** [comment]
Ok, I'm going to go and bug someone on the forge forums...

**Comment by shakey2** [comment]
I got it to work by putting it in the coremods folder.
