### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Tampa** [keepcalm/BukkitForge#669]
I gave it 16gigs still crashes with this error.

2013-09-07 15:39:54 [SEVERE] Encountered an unexpected exception OutOfMemoryError
java.lang.OutOfMemoryError: PermGen space
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
    at java.lang.Class.getConstructor0(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
    at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
    at sun.reflect.MethodAccessorGenerator.generateConstructor(Unknown Source)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:161)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:407)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75822_a(AnvilChunkLoader.java:103)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75815_a(AnvilChunkLoader.java:83)
    at net.minecraft.world.gen.ChunkProviderServer.func_73239_e(ChunkProviderServer.java:182)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:118)
    at net.minecraft.server.management.PlayerInstance.<init>(PlayerInstance.java:36)
    at net.minecraft.server.management.PlayerManager.func_72690_a(SourceFile:172)
    at net.minecraft.server.management.PlayerManager.func_72683_a(SourceFile:203)
    at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:214)
    at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:262)
    at net.minecraft.server.management.ServerConfigurationManager.func_72355_a(ServerConfigurationManager.java:130)
    at net.minecraft.network.NetLoginHandler.completeConnection(NetLoginHandler.java:194)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:166)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:120)
    at net.minecraft.network.NetLoginHandler.func_72529_d(NetLoginHandler.java:178)
    at net.minecraft.network.NetLoginHandler.func_72532_c(NetLoginHandler.java:71)
    at net.minecraft.server.ServerListenThread.func_71766_a(ServerListenThread.java:55)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:29)

**Comment by alexbegt** [comment]
Try -XX:MaxPermSize=128M
