### ISSUE TITLE
JSONAPI Not Loading

### ISSUE THREAD

**Issue by BenWawa** [keepcalm/BukkitForge#672]
I get the following error everytime I run my server:

[10:11:06] [Server thread/ERROR]: Could not load 'plugins\JSONAPI.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ProtocolLib
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:201) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugins(CraftServer.java:350) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.<init>(CraftServer.java:312) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
    at net.minecraft.server.v1_7_R1.PlayerList.<init>(PlayerList.java:63) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
    at net.minecraft.server.v1_7_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
    at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:126) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFil

**Comment by alexbegt** [comment]
I didn't know this is a bukkitforge error.

**Comment by master801** [comment]
You're running it for 1.7. And missing a dependency. :\
