### ISSUE TITLE
[Gringotts] trying to use gringotts

### ISSUE THREAD

**Issue by Nekuroi** [keepcalm/BukkitForge#69]
I get this when i try to use gringotts plugin
plugin: http://dev.bukkit.org/server-mods/gringotts/
lib: http://repo1.maven.org/maven2/org/apache/derby/derby/10.9.1.0/derby-10.9.1.0.jar
using lastest 1.4.6 forge (6.5.0.489)

2012-12-31 03:17:33 [SEVERE] [BukkitForge] Error occurred while enabling Gringotts v1.4.0-RC1 (Is it up to date?)
java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.gestern.gringotts.DAO.<clinit>(DAO.java:35)
        at org.gestern.gringotts.Accounting.<init>(Accounting.java:17)
        at org.gestern.gringotts.Gringotts.onEnable(Gringotts.java:61)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:857)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:841)
        at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:231)
        at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:45)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.SecurityException: sealing violation: can't seal package org.apache.derby.iapi.jdbc: already loaded
        at java.net.URLClassLoader.getAndVerifyPackage(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName0(JavaPluginLoader.java:300)
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:76)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.apache.derby.jdbc.EmbeddedDriver.boot(Unknown Source)
        at org.apache.derby.jdbc.EmbeddedDriver.<clinit>(Unknown Source)
        ... 13 more

**Comment by keepcalm** [comment]
That's a strange error...

**Comment by SpoonsJTD** [comment]
I was able to load Gringotts with latest BukkitForge build. Re-open if you can't.
