### ISSUE TITLE
[MagicSpells] Issues

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#70]
Hi i have follow errors with magicspells

2012-12-31 09:50:19 [INFO] [BukkitForge] Plugins are being loaded...
2012-12-31 09:50:20 [INFO] [com.nisovin.magicspells.MagicSpells] [MagicSpells] Loading MagicSpells v2.11
2012-12-31 09:50:20 [INFO] [BukkitForge] Loading PostWorld plugins...
2012-12-31 09:50:20 [INFO] [com.nisovin.magicspells.MagicSpells] [MagicSpells] Enabling MagicSpells v2.11
2012-12-31 09:50:21 [SEVERE] [BukkitForge] Error occurred while enabling MagicSpells v2.11 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/Packet
    at com.nisovin.magicspells.MagicSpells.load(MagicSpells.java:168)
    at com.nisovin.magicspells.MagicSpells.onEnable(MagicSpells.java:136)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:904)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:888)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:237)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:50)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 10 more
2012-12-31 09:50:21 [INFO] [BukkitForge] Going to load perms file: permissions.yml
2012-12-31 09:50:21 [INFO] [BukkitForge] Server permissions file permissions.yml is empty, ignoring it
2012-12-31 09:50:22 [INFO] [BukkitForge] Loaded plugins: 
2012-12-31 09:50:22 [INFO] [BukkitForge] MagicSpells- Enabled: true

**Comment by keepcalm** [comment]
It accesses MC classes, so it will need a port.

**Comment by Thornas88** [comment]
the plugin run and 60% of the spells works

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.nisovin.magicspells.MagicSpells$7.execute(MagicSpells.java:801)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:470)
    at keepcalm.mods.bukkit.forgeHandler.PlayerTracker$1.run(PlayerTracker.java:37)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.nisovin.magicspells.util.ExperienceBarManager.update(ExperienceBarManager.java:21)
    at com.nisovin.magicspells.util.ExperienceBarManager.update(ExperienceBarManager.java:15)
    at com.nisovin.magicspells.mana.ManaSystem.showManaOnExperienceBar(ManaSystem.java:243)
    at com.nisovin.magicspells.mana.ManaSystem.showMana(ManaSystem.java:201)
    at com.nisovin.magicspells.mana.ManaHandler.showMana(ManaHandler.java:25)
    at com.nisovin.magicspells.mana.ManaSystem.createManaBar(ManaSystem.java:114)
    at com.nisovin.magicspells.MagicPlayerListener.onPlayerJoin(MagicPlayerListener.java:26)
    ... 10 more

java.lang.NullPointerException
    at com.nisovin.magicspells.util.ExperienceBarManager.update(ExperienceBarManager.java:21)
    at com.nisovin.magicspells.util.ExperienceBarManager.update(ExperienceBarManager.java:15)
    at com.nisovin.magicspells.mana.ManaSystem.showManaOnExperienceBar(ManaSystem.java:243)
    at com.nisovin.magicspells.mana.ManaSystem.showMana(ManaSystem.java:201)
    at com.nisovin.magicspells.mana.ManaHandler.showMana(ManaHandler.java:25)
    at com.nisovin.magicspells.mana.ManaSystem.createManaBar(ManaSystem.java:114)
    at com.nisovin.magicspells.MagicPlayerListener.onPlayerJoin(MagicPlayerListener.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.nisovin.magicspells.MagicSpells$7.execute(MagicSpells.java:801)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:470)
    at keepcalm.mods.bukkit.forgeHandler.PlayerTracker$1.run(PlayerTracker.java:37)
    at java.lang.Thread.run(Unknown Source)

---

spell errors

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.nisovin.magicspells.MagicSpells$7.execute(MagicSpells.java:801)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:470)
    at keepcalm.mods.bukkit.forgeHandler.PlayerTracker$1.run(PlayerTracker.java:37)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.nisovin.magicspells.util.ExperienceBarManager.update(ExperienceBarManager.java:21)
    at com.nisovin.magicspells.util.ExperienceBarManager.update(ExperienceBarManager.java:15)
    at com.nisovin.magicspells.mana.ManaSystem.showManaOnExperienceBar(ManaSystem.java:243)
    at com.nisovin.magicspells.mana.ManaSystem.showMana(ManaSystem.java:201)
    at com.nisovin.magicspells.mana.ManaHandler.showMana(ManaHandler.java:25)
    at com.nisovin.magicspells.mana.ManaSystem.createManaBar(ManaSystem.java:114)
    at com.nisovin.magicspells.MagicPlayerListener.onPlayerJoin(MagicPlayerListener.java:26)
    ... 10 more

java.lang.NullPointerException
    at com.nisovin.magicspells.util.ExperienceBarManager.update(ExperienceBarManager.java:21)
    at com.nisovin.magicspells.util.ExperienceBarManager.update(ExperienceBarManager.java:15)
    at com.nisovin.magicspells.mana.ManaSystem.showManaOnExperienceBar(ManaSystem.java:243)
    at com.nisovin.magicspells.mana.ManaSystem.showMana(ManaSystem.java:201)
    at com.nisovin.magicspells.mana.ManaHandler.showMana(ManaHandler.java:25)
    at com.nisovin.magicspells.mana.ManaSystem.createManaBar(ManaSystem.java:114)
    at com.nisovin.magicspells.MagicPlayerListener.onPlayerJoin(MagicPlayerListener.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.nisovin.magicspells.MagicSpells$7.execute(MagicSpells.java:801)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:470)
    at keepcalm.mods.bukkit.forgeHandler.PlayerTracker$1.run(PlayerTracker.java:37)
    at java.lang.Thread.run(Unknown Source)

Version: 2.12

java.lang.ClassCastException: in cannot be cast to org.bukkit.World
    at keepcalm.mods.bukkit.bukkitAPI.BukkitWorld.generateTree(BukkitWorld.java:577)
    at com.nisovin.magicspells.spells.targeted.TreeSpell.growTree(TreeSpell.java:69)
    at com.nisovin.magicspells.spells.targeted.TreeSpell.castSpell(TreeSpell.java:45)
    at com.nisovin.magicspells.Spell.handleCast(Spell.java:455)
    at com.nisovin.magicspells.Spell.cast(Spell.java:415)
    at com.nisovin.magicspells.CastCommand.onCommand(CastCommand.java:111)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:454)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

Version: 2.12

ava.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.hidePlayer(BukkitPlayer.java:683)
    at com.nisovin.magicspells.spells.buff.InvisibilitySpell.castSpell(InvisibilitySpell.java:55)
    at com.nisovin.magicspells.Spell.handleCast(Spell.java:455)
    at com.nisovin.magicspells.Spell.cast(Spell.java:415)
    at com.nisovin.magicspells.CastCommand.onCommand(CastCommand.java:111)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:454)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

Version: 2.12

java.lang.ClassCastException: qz cannot be cast to rb
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitLivingEntity.launchProjectile(BukkitLivingEntity.java:296)
    at com.nisovin.magicspells.spells.instant.ProjectileSpell.castSpell(ProjectileSpell.java:154)
    at com.nisovin.magicspells.Spell.handleCast(Spell.java:455)
    at com.nisovin.magicspells.Spell.cast(Spell.java:415)
    at com.nisovin.magicspells.CastCommand.onCommand(CastCommand.java:111)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:454)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

Version: 2.12

java.lang.ClassCastException: rh cannot be cast to rb
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitLivingEntity.launchProjectile(BukkitLivingEntity.java:296)
    at com.nisovin.magicspells.spells.instant.FreezeSpell.castSpell(FreezeSpell.java:58)
    at com.nisovin.magicspells.Spell.handleCast(Spell.java:455)
    at com.nisovin.magicspells.Spell.cast(Spell.java:415)
    at com.nisovin.magicspells.CastCommand.onCommand(CastCommand.java:111)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:454)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

Version: 2.12

ava.lang.ClassCastException: org.bukkit.inventory.ItemStack cannot be cast to keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitItemStack
    at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventoryPlayer.setHelmet(BukkitInventoryPlayer.java:65)
    at com.nisovin.magicspells.spells.buff.GillsSpell.castSpell(GillsSpell.java:50)
    at com.nisovin.magicspells.Spell.handleCast(Spell.java:455)
    at com.nisovin.magicspells.Spell.cast(Spell.java:415)
    at com.nisovin.magicspells.CastCommand.onCommand(CastCommand.java:111)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:454)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

Version: 2.12

sorry for the many errors

keeclam you make a god job ;)

**Comment by SpoonsJTD** [comment]
Please try with recent build now that plugins are auto-ported.
