### ISSUE TITLE
[CoreProtect] Can't rollback due to use of NMS classes

### ISSUE THREAD

**Issue by minecrafter** [keepcalm/BukkitForge#72]
This should likely be a ported mod, or BukkitForge needs to do some ClassLoader magic to funnel attempted NMS calls through itself instead.

Just reporting this, because most Bukkit plugin bugs reported relate to missing NMS classes.

2012-12-31 08:00:51 [INFO] [STDERR] Exception in thread "Thread-14" java.lang.NoClassDefFoundError: net/minecraft/server/World
2012-12-31 08:00:51 [INFO] [STDERR]     at net.coreprotect.Functions.dataProcessor(Functions.java:2620)
2012-12-31 08:00:51 [INFO] [STDERR]     at net.coreprotect.CoreProtect$2BasicThread2.run(CoreProtect.java:624)
2012-12-31 08:00:51 [INFO] [STDERR]     at java.lang.Thread.run(Thread.java:722)
2012-12-31 08:00:51 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.World
2012-12-31 08:00:51 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
2012-12-31 08:00:51 [INFO] [STDERR]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
2012-12-31 08:00:51 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2012-12-31 08:00:51 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2012-12-31 08:00:51 [INFO] [STDERR]     ... 3 more

**Comment by keepcalm** [comment]
Ok. Another port...

**Comment by SpoonsJTD** [comment]
Loads fine but gets disabled due to compatibility check.

**Comment by profjb** [comment]
I support this fixing of this, atm i run hawkeye and it's terribly laggy and causes alot of hash error bugs.

**Comment by alexbegt** [comment]
Minecrafter. Still have this problem?

**Comment by alexbegt** [comment]
Fixed
