### ISSUE TITLE
Build 21 issue

### ISSUE THREAD

**Issue by Tampa** [keepcalm/BukkitForge#74]
I don't know whats wrong so im just posting the errors im running into.

2012-12-31 18:55:17 [INFO] [STDERR] Exception in thread "BukkitCoreAPI-0" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/constructor/BaseConstructor
2012-12-31 18:55:17 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:45)
2012-12-31 18:55:17 [INFO] [STDERR]     at java.lang.Thread.run(Thread.java:722)
2012-12-31 18:55:17 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.constructor.BaseConstructor
2012-12-31 18:55:17 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:179)
2012-12-31 18:55:17 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2012-12-31 18:55:17 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2012-12-31 18:55:17 [INFO] [STDERR]     ... 2 more
2012-12-31 18:55:17 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2012-12-31 18:55:17 [INFO] [STDERR]     at org.objectweb.asm.ClassReader.<init>(Unknown Source)
2012-12-31 18:55:17 [INFO] [STDERR]     at net.minecraftforge.transformers.EventTransformer.transform(EventTransformer.java:29)
2012-12-31 18:55:17 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:222)
2012-12-31 18:55:17 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:171)
2012-12-31 18:55:17 [INFO] [STDERR]     ... 4 more

**Comment by keepcalm** [comment]
Try updating forge.

**Comment by Tampa** [comment]
Updated to latest Forge for 146 and build 26.

2013-01-01 13:53:04 [INFO] [STDERR] Exception in thread "BukkitCoreAPI-0" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/constructor/BaseConstructor
2013-01-01 13:53:04 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:45)
2013-01-01 13:53:04 [INFO] [STDERR]     at java.lang.Thread.run(Thread.java:722)
2013-01-01 13:53:04 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.constructor.BaseConstructor
2013-01-01 13:53:04 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:179)
2013-01-01 13:53:04 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2013-01-01 13:53:04 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2013-01-01 13:53:04 [INFO] [STDERR]     ... 2 more
2013-01-01 13:53:04 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-01-01 13:53:04 [INFO] [STDERR]     at org.objectweb.asm.ClassReader.<init>(Unknown Source)
2013-01-01 13:53:04 [INFO] [STDERR]     at net.minecraftforge.transformers.EventTransformer.transform(EventTransformer.java:29)
2013-01-01 13:53:04 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:222)
2013-01-01 13:53:04 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:171)
2013-01-01 13:53:04 [INFO] [STDERR]     ... 4 more

Did you forget some yaml constructor?

**Comment by Tampa** [comment]
Putting it into coremods worked just now, but worldedit and the other plugins are not working e.g. the wand axe isnt selecting

**Comment by Manawyrm** [comment]
I have the same issue as Tampa... The Wandaxe in WorldEdit aswell as the VoxelSniper Arrows do not work ):

BukkitForge itself does work fine, commands like //drain work nicely!

EDIT: I'm using build26!

**Comment by keepcalm** [comment]
Yes, WorldEdit is very broken at the moment, I'm working on solving that.

As for the error log, I didn't forget anything, forge's transformer is NullPointering. Try updating forge.

**Comment by Manawyrm** [comment]
Thanks for your answer! 

Could you tell us, where Forge is giving you the empty variables?
It seems like it has something to do with the player handling.

**Comment by keepcalm** [comment]
No, it's forge code itself - my code has no issues in this respect, forge is broken, I'm reporting a bug now.

**Comment by Tampa** [comment]
The thing is it has to go into coremods folder not into the mods folder. Thats what caused the error i posted. I dont know where i got the idea to put it into the mods folder, but doing that does not work serverside.

**Comment by keepcalm** [comment]
It won't work anywhere...

**Comment by Manawyrm** [comment]
I wrote a reply in FML forums! Please have a look into it...
