### ISSUE TITLE
Herochat Issues

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#77]
This Errors cam when i wrote

2013-01-01 12:20:12 [WARNING] [com.dthielke.herochat.Herochat] [Herochat] Task #15 for Herochat v5.6.1 generated an exception
java.lang.RuntimeException: Chatter (BlackwingDave) not found.
    at com.dthielke.herochat.MessageHandler.handle(MessageHandler.java:77)
    at com.dthielke.herochat.HCPlayerListener$1.run(HCPlayerListener.java:35)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:345)
    at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:23)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
2013-01-01 12:20:12 [INFO] [Minecraft] <§4BlackwingDave§r> sdf

and this came when i the server leave

2013-01-01 12:26:18 [SEVERE] [BukkitForge] Could not pass event PlayerQuitEvent to Herochat v5.6.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:480)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
    at keepcalm.mods.bukkit.forgeHandler.PlayerTracker.onPlayerLogout(PlayerTracker.java:52)
    at cpw.mods.fml.common.registry.GameRegistry.onPlayerLogout(GameRegistry.java:348)
    at gm.e(ServerConfigurationManager.java:228)
    at iv.a(NetServerHandler.java:648)
    at cg.b(TcpConnection.java:461)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at com.dthielke.herochat.YMLChatterStorage.update(YMLChatterStorage.java:87)
    at com.dthielke.herochat.YMLChatterStorage.removeChatter(YMLChatterStorage.java:70)
    at com.dthielke.herochat.ChatterManager.removeChatter(ChatterManager.java:61)
    at com.dthielke.herochat.ChatterManager.removeChatter(ChatterManager.java:72)
    at com.dthielke.herochat.HCPlayerListener.onPlayerQuit(HCPlayerListener.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 16 more

**Comment by keepcalm** [comment]
Fixed the second one as of recent builds

**Comment by keepcalm** [comment]
I'm fairly certain I fixed this...
