### ISSUE TITLE
Unknown Error [Towny]

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#79]
2013-01-01 16:17:56 [WARNING] [com.palmergames.bukkit.towny.Towny] [Towny] Task #12 for Towny v0.82.0.0 generated an exception
java.lang.NullPointerException
        at zz.a(Chunk.java:768)
        at yc.a(World.java:554)
        at yc.c(World.java:532)
        at keepcalm.mods.bukkit.bukkitAPI.block.BukkitBlock.setTypeIdAndData(BukkitBlock.java:113)
        at com.palmergames.bukkit.towny.regen.PlotBlockData.restoreNextBlock(Unknown Source)
        at com.palmergames.bukkit.towny.tasks.RepeatingTimerTask.run(Unknown Source)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:345)
        at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:23)
        at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
        at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
2013-01-01 16:18:00 [INFO] [STDERR] t: Ticking entity
2013-01-01 16:18:00 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:685)
2013-01-01 16:18:00 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-01 16:18:00 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
2013-01-01 16:18:00 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-01 16:18:00 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-01 16:18:00 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-01-01 16:18:00 [INFO] [STDERR]     at ahm.a(SourceFile:200)
2013-01-01 16:18:00 [INFO] [STDERR]     at ahm.a(SourceFile:180)
2013-01-01 16:18:00 [INFO] [STDERR]     at ahm.a(SourceFile:132)
2013-01-01 16:18:00 [INFO] [STDERR]     at ahm.b(SourceFile:120)
2013-01-01 16:18:00 [INFO] [STDERR]     at ahm.a(SourceFile:88)
2013-01-01 16:18:00 [INFO] [STDERR]     at ahm.a(SourceFile:59)
2013-01-01 16:18:00 [INFO] [STDERR]     at ahm.a(SourceFile:35)
2013-01-01 16:18:00 [INFO] [STDERR]     at yc.a(World.java:3839)
2013-01-01 16:18:00 [INFO] [STDERR]     at mi.i(SourceFile:148)
2013-01-01 16:18:00 [INFO] [STDERR]     at mi.bn(SourceFile:57)
2013-01-01 16:18:00 [INFO] [STDERR]     at drzhark.mocreatures.MoCEntityMob.bn(MoCEntityMob.java:418)
2013-01-01 16:18:00 [INFO] [STDERR]     at drzhark.mocreatures.MoCEntityWerewolf.bn(MoCEntityWerewolf.java:517)
2013-01-01 16:18:00 [INFO] [STDERR]     at md.c(EntityLiving.java:1787)
2013-01-01 16:18:00 [INFO] [STDERR]     at qj.c(SourceFile:26)
2013-01-01 16:18:00 [INFO] [STDERR]     at drzhark.mocreatures.MoCEntityMob.c(MoCEntityMob.java:233)
2013-01-01 16:18:00 [INFO] [STDERR]     at drzhark.mocreatures.MoCEntityWerewolf.c(MoCEntityWerewolf.java:401)
2013-01-01 16:18:00 [INFO] [STDERR]     at md.j_(EntityLiving.java:843)
2013-01-01 16:18:00 [INFO] [STDERR]     at qj.j_(SourceFile:31)
2013-01-01 16:18:00 [INFO] [STDERR]     at yc.a(World.java:2295)
2013-01-01 16:18:00 [INFO] [STDERR]     at in.a(WorldServer.java:645)
2013-01-01 16:18:00 [INFO] [STDERR]     at yc.g(World.java:2257)
2013-01-01 16:18:00 [INFO] [STDERR]     at yc.h(World.java:2103)
2013-01-01 16:18:00 [INFO] [STDERR]     at in.h(WorldServer.java:514)
2013-01-01 16:18:00 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
2013-01-01 16:18:00 [INFO] [STDERR]     ... 4 more
2013-01-01 16:18:00 [SEVERE] [Minecraft] Encountered an unexpected exception t
t: Ticking entity
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:685)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at ahm.a(SourceFile:200)
        at ahm.a(SourceFile:180)
        at ahm.a(SourceFile:132)
        at ahm.b(SourceFile:120)
        at ahm.a(SourceFile:88)
        at ahm.a(SourceFile:59)
        at ahm.a(SourceFile:35)
        at yc.a(World.java:3839)
        at mi.i(SourceFile:148)
        at mi.bn(SourceFile:57)
        at drzhark.mocreatures.MoCEntityMob.bn(MoCEntityMob.java:418)
        at drzhark.mocreatures.MoCEntityWerewolf.bn(MoCEntityWerewolf.java:517)
        at md.c(EntityLiving.java:1787)
        at qj.c(SourceFile:26)
        at drzhark.mocreatures.MoCEntityMob.c(MoCEntityMob.java:233)
        at drzhark.mocreatures.MoCEntityWerewolf.c(MoCEntityWerewolf.java:401)
        at md.j_(EntityLiving.java:843)
        at qj.j_(SourceFile:31)
        at yc.a(World.java:2295)
        at in.a(WorldServer.java:645)
        at yc.g(World.java:2257)
        at yc.h(World.java:2103)
        at in.h(WorldServer.java:514)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
        ... 4 more
2013-01-01 16:18:00 [SEVERE] [Minecraft] This crash report has been saved to: /home/wolftein/Server02/./crash-reports/crash-2013-01-01_16.18.00-server.txt

**Comment by Wolftein** [comment]
Also i have another Error.

2013-01-01 16:36:27 [SEVERE] [BukkitForge] Could not pass event GMUserEvent to Towny v0.82.0.0
org.bukkit.event.EventException

> ```
>   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
>   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
>   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:480)
>   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
>   at org.anjocaido.groupmanager.events.GMUserEvent$1.run(GMUserEvent.java:82)
>   at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
>   at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:345)
>   at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:23)
>   at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
>   at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
>   at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
>   at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
>   at fy.run(SourceFile:849)
> ```
> 
> Caused by: java.lang.NullPointerException
>       at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldData(WorldsHolder.java:437)
>       at com.palmergames.bukkit.towny.permissions.GroupManagerSource.getPlayerPermissionStringNode(Unknown Source)
>       at com.palmergames.bukkit.towny.permissions.GroupManagerSource$GMCustomEventListener.onGMUserEvent(Unknown Source)
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>       at java.lang.reflect.Method.invoke(Method.java:601)
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
>       ... 13 more

**Comment by Wolftein** [comment]
GMUserEvent is caused by GroupManager plugin i replaced with bPermission and everything is working fine, but i cannot use Towny permissions with a non op user with both permissions plugins, keep saying: Command Disabled, using permissions.

**Comment by keepcalm** [comment]
Weird... I'll look, it's probably because of the way I'm checking permissions.

**Comment by ghost** [comment]
Yeah same thing is happening for me when i op myself i can create towns and use all the plugin. Once i switch over to default group cant do diddly squat :(. Is this issue fixed or am i just not giving the default group the right perms?

**Comment by SpoonsJTD** [comment]
Closing as dupe - permissions issue
