### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by shakey2** [keepcalm/BukkitForge#82]
After updating from 26 to 33 I start getting this error when attempting to connect:

2013-01-01 23:02:37 [INFO] [Minecraft] Disconnecting shakey2 [/127.0.0.1:1426]: Internal server error
2013-01-01 23:02:37 [SEVERE] [ForgeModLoader] Error handling login related packet - connection from shakey2 [/127.0.0.1:1426] refused
java.lang.IllegalArgumentException: Unknown entity: thaumcraft.common.entities.golems.EntityGolemStraw
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:219)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.getBukkitEntity(BukkitEventFactory.java:102)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callCreatureSpawnEvent(BukkitEventFactory.java:272)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onEntityJoinWorld(ForgeEventHandler.java:141)
    at net.minecraftforge.event.ASMEventHandler_103_ForgeEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at yc.a(World.java:3755)
    at zz.c(Chunk.java:1084)
    at im.c(ChunkProviderServer.java:150)
    at il.<init>(PlayerInstance.java:35)
    at ik.a(SourceFile:172)
    at ik.a(SourceFile:203)
    at gm.a(ServerConfigurationManager.java:163)
    at gm.c(ServerConfigurationManager.java:206)
    at gm.a(ServerConfigurationManager.java:123)
    at it.completeConnection(NetLoginHandler.java:195)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:153)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
    at it.d(NetLoginHandler.java:179)
    at it.c(NetLoginHandler.java:72)
    at hu.a(ServerListenThread.java:56)
    at ht.b(SourceFile:29)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
2013-01-01 23:02:37 [WARNING] [Minecraft] Failed to handle packet for shakey2 [/127.0.0.1:1426]: java.lang.IllegalArgumentException: Unknown entity: thaumcraft.common.entities.golems.EntityGolemStraw
java.lang.IllegalArgumentException: Unknown entity: thaumcraft.common.entities.golems.EntityGolemStraw
    at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:219)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.getBukkitEntity(BukkitEventFactory.java:102)
    at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callCreatureSpawnEvent(BukkitEventFactory.java:272)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onEntityJoinWorld(ForgeEventHandler.java:141)
    at net.minecraftforge.event.ASMEventHandler_103_ForgeEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at yc.a(World.java:3755)
    at zz.c(Chunk.java:1084)
    at im.c(ChunkProviderServer.java:150)
    at il.<init>(PlayerInstance.java:35)
    at ik.a(SourceFile:172)
    at ik.a(SourceFile:203)
    at gm.a(ServerConfigurationManager.java:163)
    at gm.c(ServerConfigurationManager.java:206)
    at gm.a(ServerConfigurationManager.java:123)
    at it.completeConnection(NetLoginHandler.java:195)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:153)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
    at it.d(NetLoginHandler.java:179)
    at it.c(NetLoginHandler.java:72)
    at hu.a(ServerListenThread.java:56)
    at ht.b(SourceFile:29)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

**Comment by keepcalm** [comment]
I thought I fixed this... grr

**Comment by shakey2** [comment]
Man you are fast!
