### ISSUE TITLE
Kick on interacting with an object

### ISSUE THREAD

**Issue by Adubbz** [keepcalm/BukkitForge#83]
When attempting to interact with an object (for example, opening a door) it kicks you with 'internal error' and spits this error out in the console

2013-01-02 16:18:23 [SEVERE] [ForgeModLoader] A critical server error occured ha
ndling a packet, kicking 309
java.lang.NullPointerException
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteracti
on(ForgeEventHandler.java:239)
        at net.minecraftforge.event.ASMEventHandler_127_ForgeEventHandler_onPlay
erInteraction_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:
35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEven
tFactory.java:28)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:578)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:454)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
2013-01-02 16:18:23 [WARNING] [Minecraft] Failed to handle packet for Adubbz/25.
254.155.103: java.lang.NullPointerException
java.lang.NullPointerException
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteracti
on(ForgeEventHandler.java:239)
        at net.minecraftforge.event.ASMEventHandler_127_ForgeEventHandler_onPlay
erInteraction_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:
35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEven
tFactory.java:28)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:578)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:454)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)

**Comment by Adubbz** [comment]
My bad, careless Adubbz :S

**Comment by keepcalm** [comment]
Try updating to the most recent build?

**Comment by Adubbz** [comment]
The version i'm using is Build 34, previously i was using the 'jenkins is down' build and this wasn't happening

**Comment by keepcalm** [comment]
Try build 35 - it's building now, jenkins will show you the progress

**Comment by Adubbz** [comment]
Unfortunately, still pretty much the same issue (with the exception of minor differences) (With build 38)

2013-01-02 18:06:42 [SEVERE] [ForgeModLoader] A critical server error occured ha
ndling a packet, kicking 306
java.lang.NullPointerException
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteracti
on(ForgeEventHandler.java:235)
        at net.minecraftforge.event.ASMEventHandler_129_ForgeEventHandler_onPlay
erInteraction_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:
35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEven
tFactory.java:28)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:578)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:454)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
2013-01-02 18:06:42 [WARNING] [Minecraft] Failed to handle packet for Adubbz/25.
254.155.103: java.lang.NullPointerException
java.lang.NullPointerException
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteracti
on(ForgeEventHandler.java:235)
        at net.minecraftforge.event.ASMEventHandler_129_ForgeEventHandler_onPlay
erInteraction_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:
35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEven
tFactory.java:28)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:578)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:454)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)

**Comment by Adubbz** [comment]
Fixed now, thanks keepcalm =)
