### ISSUE TITLE
Crash when using water buckets

### ISSUE THREAD

**Issue by Manawyrm** [keepcalm/BukkitForge#85]
Every-time I use a water bucket, this exception occures...

2013-01-02 09:13:44 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kic
king 357
java.lang.NullPointerException
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.fillBukkit(ForgeEventHandler.java:296
)
        at net.minecraftforge.event.ASMEventHandler_51_ForgeEventHandler_fillBukkit_FillBucketEvent.
invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at td.a(ItemBucket.java:48)
        at ur.a(SourceFile:98)
        at ir.a(ItemInWorldManager.java:348)
        at iv.a(NetServerHandler.java:555)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
2013-01-02 09:13:44 [WARNING] [Minecraft] Failed to handle packet for tobi31061/89.182.84.86: java.lang.NullPointerException
java.lang.NullPointerException
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.fillBukkit(ForgeEventHandler.java:296
)
        at net.minecraftforge.event.ASMEventHandler_51_ForgeEventHandler_fillBukkit_FillBucketEvent.
invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at td.a(ItemBucket.java:48)
        at ur.a(SourceFile:98)
        at ir.a(ItemInWorldManager.java:348)
        at iv.a(NetServerHandler.java:555)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)

**Comment by keepcalm** [comment]
what's the rest of this line:
at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.fillBukkit(ForgeEventHandler.java:29?

**Comment by Manawyrm** [comment]
I updated the text...

**Comment by xKillerbees** [comment]
Having the same issue with any right click on blocks. If I right click with a pick or tool, I'm fine. if I do it with my fists, I crash. 

http://pastebin.com/gNxi0xNA
