### ISSUE TITLE
Modifyworld Issue

### ISSUE THREAD

**Issue by Adubbz** [keepcalm/BukkitForge#87]
After updating to the latest build it seems there is now an issue with modifyworld (part of the PEX plugin bundle) preventing item drops from being picked up. I'm using build 40

2013-01-02 20:48:25 [SEVERE] [BukkitForge] Could not pass event PlayerInteractEv
ent to Modifyworld v1.19.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:486)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:470)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(For
geEventHandler.java:353)
        at net.minecraftforge.event.ASMEventHandler_128_ForgeEventHandler_intera
ctEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:
35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEven
tFactory.java:28)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:578)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:454)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
        at ru.tehkode.modifyworld.ModifyworldListener.getMaterialPermission(Modi
fyworldListener.java:94)
        at ru.tehkode.modifyworld.ModifyworldListener.getMaterialPermission(Modi
fyworldListener.java:98)
        at ru.tehkode.modifyworld.ModifyworldListener.getBlockPermission(Modifyw
orldListener.java:102)
        at ru.tehkode.modifyworld.ModifyworldListener.getObjectPermission(Modify
worldListener.java:171)
        at ru.tehkode.modifyworld.ModifyworldListener.assemblePermission(Modifyw
orldListener.java:152)
        at ru.tehkode.modifyworld.ModifyworldListener.permissionDenied(Modifywor
ldListener.java:128)
        at ru.tehkode.modifyworld.handlers.PlayerListener.onPlayerInteract(Playe
rListener.java:290)
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        ... 20 more

**Comment by lisim** [comment]
I do not think it is Modifyworld simply as while testing GP i removed ModifyWolrd and still we were unable to pickup items

**Comment by Adubbz** [comment]
When i removed it it worked fine, however it is a pain not having it :/

**Comment by keepcalm** [comment]
I think my next step will be to go and see what MCPC does to make bukkit support mods.

**Comment by Adubbz** [comment]
Seems to be fixed now, thanks!

**Comment by Adubbz** [comment]
And i retract that statement, it WAS working originally but then it randomly stopped again. Bah!

**Comment by keepcalm** [comment]
It seems to be working for me...

**Comment by Adubbz** [comment]
Same issue as essentials, you have to be opped otherwise it won't work (even if you do have perms) Looks like i am gonna have to take your suggestion and use groupmanager, for now at least

**Comment by Adubbz** [comment]
On second thought, maybe not. Groupmanager is horrible in my opinion and i can't get it to cooperate :S Ah well, i'm sure you'll have it fixed quickly

**Comment by keepcalm** [comment]
Try bPermissions? (GroupManager isn't that bad is it?)

**Comment by Adubbz** [comment]
I suppose, my hate for group manager is that it is world specific (unless you manually add the world to the plugins main config to share perms with another one) as well as the fact it is uncooperative with prefixes etc (for me at least). Is the issue with pex not something that can be fixed on your side?

**Comment by Adubbz** [comment]
Joining groupmanager: bPermissions! Being absolutely useless and not enforcing any permissions, refusing to use mchat for chat formatting (I actually have an error for that) and just being useless.

2013-01-04 20:52:29 [SEVERE] [BukkitForge] Could not pass event AsyncPlayerChatE
vent to mChatSuite v1.4.5-R0.12-b300jnks
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:486)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:470)
        at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callEvent(Buk
kitEventFactory.java:119)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.serverChat(ForgeE
ventHandler.java:458)
        at net.minecraftforge.event.ASMEventHandler_146_ForgeEventHandler_server
Chat_ServerChatEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:
35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at iv.a(NetServerHandler.java:744)
        at cu.a(SourceFile:44)
        at cg.i(TcpConnection.java:347)
        at cg.c(TcpConnection.java:544)
        at ch.run(SourceFile:93)
Caused by: java.lang.NoClassDefFoundError: de/bananaco/bpermissions/api/util/Cal
culableType
        at com.miraclem4n.mchat.api.Reader.getbPermInfo(Reader.java:333)
        at com.miraclem4n.mchat.api.Reader.getRawInfo(Reader.java:59)
        at com.miraclem4n.mchat.api.Reader.getRawPrefix(Reader.java:72)
        at com.miraclem4n.mchat.api.Parser.parseMessage(Parser.java:55)
        at com.miraclem4n.mchat.api.Parser.parseChatMessage(Parser.java:354)
        at com.miraclem4n.mchat.events.ChatListener.onPlayerChat(ChatListener.ja
va:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        ... 13 more

EDIT: After looking, i think this is actually an error on bPermission's part. I think it has a new API that stuff needs updating to

**Comment by SpoonsJTD** [comment]
Closed as dupe - permission check seems to be failing
