### ISSUE TITLE
Another crash after startup

### ISSUE THREAD

**Issue by rbrian** [keepcalm/BukkitForge#9]
doesn't seem to happen until i log in and walk around a bit

---- Minecraft Crash Report ----
// Don't do that.

Time: 12/10/12 4:58 AM
Description: Exception ticking world

java.lang.NoSuchMethodError: in.w()Ljava/lang/String;
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.getWorld(BukkitServer.java:650)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java:47)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkUnloadEvent.<init>(ChunkUnloadEvent.java:15)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkUnloadEvent(ForgeEventHandler.java:222)
    at net.minecraftforge.event.ASMEventHandler_17_ForgeEventHandler_chunkUnloadEvent_Unload.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at zs.d(Chunk.java:1088)
    at im.b(ChunkProviderServer.java:311)
    at in.b(WorldServer.java:124)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:662)
    at ho.r(DedicatedServer.java:252)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
    at fy.run(SourceFile:856)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.getWorld(BukkitServer.java:650)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitChunk.getWorld(BukkitChunk.java:47)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkUnloadEvent.<init>(ChunkUnloadEvent.java:15)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.chunkUnloadEvent(ForgeEventHandler.java:222)
    at net.minecraftforge.event.ASMEventHandler_17_ForgeEventHandler_chunkUnloadEvent_Unload.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at zs.d(Chunk.java:1088)
    at im.b(ChunkProviderServer.java:311)
    at in.b(WorldServer.java:124)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [iq['blindahl'/248, l='world', x=238.29, y=64.00, z=224.70]]
    Chunk stats: ServerChunkCache: 625 Drop: 21
    Level seed: -1376911406613561018
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (245,64,214), Chunk: (at 5,4,6 in 15,13; contains blocks 240,0,208 to 255,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 4433 game time, 4433 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 26070 (now: false), thunder time: 84875 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:662)
    at ho.r(DedicatedServer.java:252)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
    at fy.run(SourceFile:856)

-- System Details --
Details:
    Minecraft Version: 1.4.5
    Operating System: Linux (amd64) version 2.6.32
    Java Version: 1.7.0_03, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1396908008 bytes (1332 MB) / 1543503872 bytes (1472 MB) up to 1543503872 bytes (1472 MB)
    JVM Flags: 2 total; -Xms1536M -Xmx1536M
    AABB Pool Size: 2567 (143752 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v7.23 FML v4.5.17.479 Minecraft Forge 6.4.1.426 4 mods loaded, 4 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Bukkit4Vanilla [Bukkit For Vanilla](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 548 (30688 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 20; [iq['blindahl'/248, l='world', x=238.29, y=64.00, z=224.70]]
    Is Modded: Definitely; Server brand changed to 'forge,fml'
    Type: Dedicated Server (map_server.txt)

**Comment by keepcalm** [comment]
Already fixed :D
