### ISSUE TITLE
EssentialsSpawn /spawn does NPE

### ISSUE THREAD

**Issue by Manawyrm** [keepcalm/BukkitForge#90]
When using /spawn without a set spawn point you get 
Error: null.

After setting the spawn with /setspawn you can successfully use /spawn.

**Comment by xKillerbees** [comment]
I did a /setspawn and it still gave me the null.

**Comment by Manawyrm** [comment]
Works just fine for me..

I got a stacktrace from /spawn...

```
2013-01-02 16:29:42 [WARNING] [BukkitForge] Fehler beim Teleportieren eines neuen Spielers (error while teleporting a new player)
java.lang.NullPointerException
        at com.earth2me.essentials.Util.isBlockDamaging(Util.java:434)
        at com.earth2me.essentials.Util.isBlockUnsafe(Util.java:409)
        at com.earth2me.essentials.Util.getSafeDestination(Util.java:361)
        at com.earth2me.essentials.Teleport.now(Teleport.java:234)
        at com.earth2me.essentials.Teleport.now(Teleport.java:218)
        at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$NewPlayerTeleport.run(EssentialsSpawnPlayerListener.java:153)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:345)
        at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:23)
        at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
        at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:588)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
```

**Comment by Manawyrm** [comment]
Hello xKillerbees,

please try to delete all configuration folders from essentials. 
I couldn't reproduce the bug in my debug environment.

After I deleted the configs from Essentials in my main installation it works just nicely...

**Comment by Manawyrm** [comment]
Aha.

The problem was caused by defective configuration files created by essentials under an old version of BukkitForge!
Recreating them with an modern version (with the world compare fix) solved the problem here!

So long,
Tobias
