### ISSUE TITLE
ShowCaseStandAlone

### ISSUE THREAD

**Issue by Thornas88** [keepcalm/BukkitForge#92]
2013-01-02 22:41:23 [SEVERE] [BukkitForge] Error occurred while enabling ShowCaseStandalone v1.49 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/inventory/CraftItemStack
    at com.kellerkindt.scs.ShowCaseStandalone.convertListStringToMaterial(ShowCaseStandalone.java:647)
    at com.kellerkindt.scs.ShowCaseStandalone.loadSCSConfig(ShowCaseStandalone.java:564)
    at com.kellerkindt.scs.ShowCaseStandalone.onEnable(ShowCaseStandalone.java:169)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:882)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:866)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:252)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:45)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.inventory.CraftItemStack
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more

**Comment by Manawyrm** [comment]
"CB 1.3.2-R1.0"

Is there a newer version I couldn't find?

**Comment by Thornas88** [comment]
ähm 1.4.2 0.2 ist the newest http://dev.bukkit.org/server-mods/scs/

**Comment by unrivaledneo** [comment]
U ever get it to work?
