### ISSUE TITLE
Error With Buildcraft

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#93]
2013-01-02 20:25:37 [INFO] [STDERR] t: Ticking tile entity
2013-01-02 20:25:37 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:685)
2013-01-02 20:25:37 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-02 20:25:37 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
2013-01-02 20:25:37 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-02 20:25:37 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-02 20:25:37 [INFO] [STDERR] Caused by: java.lang.ClassCastException: dan200.turtle.shared.TurtlePlayer cannot be cast to iq
2013-01-02 20:25:37 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.fillBukkit(ForgeEventHandler.java:319)
2013-01-02 20:25:37 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_65_ForgeEventHandler_fillBukkit_FillBucketEvent.invoke($
2013-01-02 20:25:37 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-01-02 20:25:37 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-01-02 20:25:37 [INFO] [STDERR]     at td.a(ItemBucket.java:48)
2013-01-02 20:25:37 [INFO] [STDERR]     at dan200.turtle.shared.TileEntityTurtle.useStack(TileEntityTurtle.java:1903)
2013-01-02 20:25:37 [INFO] [STDERR]     at dan200.turtle.shared.TileEntityTurtle.place(TileEntityTurtle.java:1569)
2013-01-02 20:25:37 [INFO] [STDERR]     at dan200.turtle.shared.TileEntityTurtle.updateCommands(TileEntityTurtle.java:2596)
2013-01-02 20:25:37 [INFO] [STDERR]     at dan200.turtle.shared.TileEntityTurtle.g(TileEntityTurtle.java:2373)
2013-01-02 20:25:37 [INFO] [STDERR]     at yc.h(World.java:2155)
2013-01-02 20:25:37 [INFO] [STDERR]     at in.h(WorldServer.java:514)
2013-01-02 20:25:37 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
2013-01-02 20:25:37 [INFO] [STDERR]     ... 4 more
2013-01-02 20:25:37 [SEVERE] [Minecraft] Encountered an unexpected exception t
t: Ticking tile entity
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:685)
        at ho.r(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.ClassCastException: dan200.turtle.shared.TurtlePlayer cannot be cast to iq
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.fillBukkit(ForgeEventHandler.java:319)
        at net.minecraftforge.event.ASMEventHandler_65_ForgeEventHandler_fillBukkit_FillBucketEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at td.a(ItemBucket.java:48)
        at dan200.turtle.shared.TileEntityTurtle.useStack(TileEntityTurtle.java:1903)
        at dan200.turtle.shared.TileEntityTurtle.place(TileEntityTurtle.java:1569)
        at dan200.turtle.shared.TileEntityTurtle.updateCommands(TileEntityTurtle.java:2596)
        at dan200.turtle.shared.TileEntityTurtle.g(TileEntityTurtle.java:2373)
        at yc.h(World.java:2155)
        at in.h(WorldServer.java:514)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
        ... 4 more

**Comment by keepcalm** [comment]
Dan200 uses players... That should be easily fixed though.
