### ISSUE TITLE
43 Crash on Load

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#96]
Server won't boot up now. 

2013-01-03 03:12:21 [INFO] [STDERR] java.lang.ArrayIndexOutOfBoundsException: 4062
2013-01-03 03:12:21 [INFO] [STDERR]     at org.bukkit.Material.addMaterial(Material.java:942)
2013-01-03 03:12:21 [INFO] [STDERR]     at org.bukkit.Material.addMaterial(Material.java:933)
2013-01-03 03:12:21 [INFO] [STDERR]     at keepcalm.mods.bukkit.BukkitHelpers.addMaterial(BukkitHelpers.java:17)
2013-01-03 03:12:21 [INFO] [STDERR]     at up.<init>(Item.java)
2013-01-03 03:12:21 [INFO] [STDERR]     at buildcraft.core.ItemBuildCraft.<init>(ItemBuildCraft.java:19)
2013-01-03 03:12:21 [INFO] [STDERR]     at buildcraft.core.ItemWrench.<init>(ItemWrench.java:10)
2013-01-03 03:12:21 [INFO] [STDERR]     at buildcraft.BuildCraftCore.loadConfiguration(BuildCraftCore.java:211)
2013-01-03 03:12:21 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-03 03:12:21 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2013-01-03 03:12:21 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-01-03 03:12:21 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Method.java:601)
2013-01-03 03:12:21 [INFO] [STDERR]     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:478)
2013-01-03 03:12:21 [INFO] [STDERR]     at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
2013-01-03 03:12:21 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-01-03 03:12:21 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Method.java:601)
2013-01-03 03:12:21 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2013-01-03 03:12:21 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-01-03 03:12:21 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2013-01-03 03:12:21 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2013-01-03 03:12:21 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2013-01-03 03:12:21 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
2013-01-03 03:12:21 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-01-03 03:12:21 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2013-01-03 03:12:21 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2013-01-03 03:12:21 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Method.java:601)
2013-01-03 03:12:21 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2013-01-03 03:12:21 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-01-03 03:12:21 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2013-01-03 03:12:21 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2013-01-03 03:12:21 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:268)
2013-01-03 03:12:21 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
2013-01-03 03:12:21 [INFO] [STDERR]     at cpw.mods.fml.common.Loader.loadMods(Loader.java:485)
2013-01-03 03:12:21 [INFO] [STDERR]     at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
2013-01-03 03:12:21 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:345)
2013-01-03 03:12:21 [INFO] [STDERR]     at ho.c(DedicatedServer.java:64)
2013-01-03 03:12:21 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
2013-01-03 03:12:21 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-03 03:12:21 [SEVERE] [Minecraft] Encountered an unexpected exception ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException: 4062
    at org.bukkit.Material.addMaterial(Material.java:942)
    at org.bukkit.Material.addMaterial(Material.java:933)
    at keepcalm.mods.bukkit.BukkitHelpers.addMaterial(BukkitHelpers.java:17)
    at up.<init>(Item.java)
    at buildcraft.core.ItemBuildCraft.<init>(ItemBuildCraft.java:19)
    at buildcraft.core.ItemWrench.<init>(ItemWrench.java:10)
    at buildcraft.BuildCraftCore.loadConfiguration(BuildCraftCore.java:211)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:478)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:485)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:345)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
2013-01-03 03:12:21 [SEVERE] [Minecraft] This crash report has been saved to: /home/minecraft/multicraft/servers/server4/./crash-reports/crash-2013-01-03_03.12.21-server.txt

**Comment by keepcalm** [comment]
I forgot to change the size of an array - it's a quick fix.

**Comment by xKillerbees** [comment]
Alright, looking forward to build 44.
