### ISSUE TITLE
[ComputerCraft] (Turtles)

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#98]
Caused by: java.lang.NullPointerException

> ```
>   at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.getName(BukkitPlayer.java:117)
>   at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.hashCode(BukkitPlayer.java:747)
>   at java.util.WeakHashMap.hash(WeakHashMap.java:364)
>   at java.util.WeakHashMap.remove(WeakHashMap.java:665)
>   at org.bukkit.plugin.SimplePluginManager.unsubscribeFromDefaultPerms(SimplePluginManager.java:679)
>   at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:172)
>   at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:149)
>   at org.bukkit.permissions.PermissibleBase.<init>(PermissibleBase.java:29)
>   at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java:51)
>   at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:107)
>   at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitPlayer.<init>(BukkitPlayer.java:112)
>   at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.fillBukkit(ForgeEventHandler.java:353)
>   at net.minecraftforge.event.ASMEventHandler_73_ForgeEventHandler_fillBukkit_FillBucketEvent.invoke(.dynamic)
>   at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
>   at net.minecraftforge.event.EventBus.post(EventBus.java:103)
>   at td.a(ItemBucket.java:48)
>   at dan200.turtle.shared.TileEntityTurtle.useStack(TileEntityTurtle.java:1903)
>   at dan200.turtle.shared.TileEntityTurtle.place(TileEntityTurtle.java:1569)
>   at dan200.turtle.shared.TileEntityTurtle.updateCommands(TileEntityTurtle.java:2596)
>   at dan200.turtle.shared.TileEntityTurtle.g(TileEntityTurtle.java:2373)
>   at yc.h(World.java:2155)
>   at in.h(WorldServer.java:514)
>   at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
>   ... 4 more
> ```

**Comment by Wolftein** [comment]
And this is another Error

2013-01-03 11:16:27 [INFO] [STDERR] t: Ticking tile entity
2013-01-03 11:16:27 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:685)
2013-01-03 11:16:27 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-03 11:16:27 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
2013-01-03 11:16:27 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
2013-01-03 11:16:27 [INFO] [STDERR]     at fy.run(SourceFile:849)
2013-01-03 11:16:27 [INFO] [STDERR] Caused by: java.lang.ClassCastException: dan200.turtle.shared.TurtlePlayer cannot be cast to$
2013-01-03 11:16:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventoryPlayer.<init>(BukkitInventory$
2013-01-03 11:16:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntityHuman.<init>(BukkitEntityHuman.java$
2013-01-03 11:16:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.entity.BukkitEntity.getEntity(BukkitEntity.java:104)
2013-01-03 11:16:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.getBukkitEntity(BukkitEventFa$
2013-01-03 11:16:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.bukkitAPI.event.BukkitEventFactory.callEntityDamageEvent(BukkitE$
2013-01-03 11:16:27 [INFO] [STDERR]     at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onLivingDamage(ForgeEventHandler.$
2013-01-03 11:16:27 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_69_ForgeEventHandler_onLivingDamage_LivingHu$
2013-01-03 11:16:27 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-01-03 11:16:27 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-01-03 11:16:27 [INFO] [STDERR]     at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:334)
2013-01-03 11:16:27 [INFO] [STDERR]     at qx.d(EntityPlayer.java:1137)
2013-01-03 11:16:27 [INFO] [STDERR]     at iq.d(iq.java:242)
2013-01-03 11:16:27 [INFO] [STDERR]     at md.a(EntityLiving.java:1045)
2013-01-03 11:16:27 [INFO] [STDERR]     at qx.a(EntityPlayer.java:1014)
2013-01-03 11:16:27 [INFO] [STDERR]     at iq.localAttackEntityFrom(iq.java:151)
2013-01-03 11:16:27 [INFO] [STDERR]     at iq.a(iq.java:123)
2013-01-03 11:16:27 [INFO] [STDERR]     at dan200.turtle.shared.TileEntityTurtle.useStack(TileEntityTurtle.java:1884)
2013-01-03 11:16:27 [INFO] [STDERR]     at dan200.turtle.shared.TileEntityTurtle.attackWithItemStack(TileEntityTurtle.java:488)
2013-01-03 11:16:27 [INFO] [STDERR]     at dan200.turtle.shared.TurtleTool.attack(TurtleTool.java:127)
2013-01-03 11:16:27 [INFO] [STDERR]     at dan200.turtle.shared.TurtleTool.useTool(TurtleTool.java:112)
2013-01-03 11:16:27 [INFO] [STDERR]     at dan200.turtle.shared.TileEntityTurtle.useTool(TileEntityTurtle.java:1547)
2013-01-03 11:16:27 [INFO] [STDERR]     at dan200.turtle.shared.TileEntityTurtle.attack(TileEntityTurtle.java:1540)
2013-01-03 11:16:27 [INFO] [STDERR]     at dan200.turtle.shared.TileEntityTurtle.updateCommands(TileEntityTurtle.java:2551)
2013-01-03 11:16:27 [INFO] [STDERR]     at dan200.turtle.shared.TileEntityTurtle.g(TileEntityTurtle.java:2373)
2013-01-03 11:16:27 [INFO] [STDERR]     at yc.h(World.java:2155)
2013-01-03 11:16:27 [INFO] [STDERR]     at in.h(WorldServer.java:514)
2013-01-03 11:16:27 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:679)
2013-01-03 11:16:27 [INFO] [STDERR]     ... 4 more

**Comment by Wolftein** [comment]
Any progress on this? i cannot use any new build because of this :(

**Comment by keepcalm** [comment]
Yes, I'll fix it in a few hours.

**Comment by SpoonsJTD** [comment]
Ticking entity was fixed by keepcalm many versions ago. Should be fixed.
